### ISSUE TITLE
Configure Nx for Packages

### ISSUE THREAD

**Issue by ObliviousHarmony** [woothemes/woocommerce#31072]
### Overview

Now that we've merged https://github.com/woocommerce/woocommerce/pull/30977 and integrated PNPM, it's time to fully utilize [Nx](https://nx.dev/) in order to better support managing projects within the monorepo. This tool will allow us to run executors and generators for the monorepo, support incremental builds, and execute commands on packages affected by changes.

The goal of this initial issue is just to get everything working in the fastest way possible. The lack of infrastructure is wreaking a bit of havoc on the workflows of others, so we can iterate after it's working!

### Tasks

- [x] Add `project.json` files to all current Js packages. ([Relevant Documentation](https://nx.dev/l/r/core-concepts/configuration))
- [x] Add executors for `build`, `lint`, `test`, and `e2e` for the packages where appropriate. For now, let's just run commands through NPM for them, and we can look at alternatives later.
- [ ] ~~Use `nx-composer` plugin to support having the Core plugin as a package.~~
- [x] Add `project.json` file for Core plugin and make sure dependencies are connected to relevant packages in both PHP and Composer correctly.

### Acceptance Criteria

- Use [Nx's dependency graph](https://nx.dev/l/a/cli/dep-graph) and verify that everything is connected appropriately.
- Make sure all of the commands execute the way that they're supposed to.
- Test incremental builds too!
