### ISSUE TITLE
Task List: Add Products Task - Layout Experiment

### ISSUE THREAD

**Issue by verofasulo** [woothemes/woocommerce#32144]
**User story:**
As a new merchant
I want to start with a pre-filled product
So I can easily understand what are the most important fields according to the type of product that I want to sell.

**Description:** 
We reviewed the Add products page and built upon the Start with a template idea that performed well in the [previous testing](https://github.com/woocommerce/woocommerce-admin/issues/5296). 

We'd like to try out two different layouts: 

1. **Card layout**: is based on showing multiple cards in a grid.

![Card Layout](https://user-images.githubusercontent.com/98944206/156599140-5fcbdf97-430c-4dc7-80f6-15bf5174b331.gif)

2. **Stack layout**: the product types are vertically stacked. 

![Stack Layout](https://user-images.githubusercontent.com/98944206/156599341-f2b9d0eb-374a-446f-9d30-dcd8a25f052f.gif)

**Design overview:**
cJQeyyhx9PraQrY3YAtCGM-fi-1133%3A131992

**Acceptance criteria:**

- [ ] This page is visible to users that just started their business or skipped the Profiler. If they declared to sell somewhere else, they're addressed to a different screen ([Import products](https://github.com/woocommerce/woocommerce-admin/issues/8407)).
- [ ] The visible product types depend on what the user declared during the signup (step 3 - Product types - What type of products will be listed?). The other ones are collapsed. 
The following are all the possible configurations:

> Selected (signup): Physical products
> Surfaced (add product page): Physical product, Variable product, Grouped product

> Selected (signup): Physical products, Subscriptions
> Surfaced (add product page): Physical product, Subscription product

> Selected (signup): Physical products, Downloads
> Surfaced (add product page): Physical product, Digital product

> Selected (signup): Physical products, Downloads, Subscriptions
> Surfaced (add product page): Physical product, Digital product, Subscription product

> Selected: Downloads
> Surfaced: Digital product

> Selected: Downloads, Subscriptions
> Surfaced: Digital product, Subscription product

> Selected: Subscriptions
> Surfaced: Subscription product

- [ ] Includes the Load sample products feature that allows users to preview what their store might look like. 
- [ ] Includes new icons and new copy.
- [ ] Includes a 1.5 px `Gutenberg-blue` border when components are hovered (instead of grey background).

**Event tracking:** 
To be assessed by the team - some things I'd like to measure:

- Task completion rate
- Task completion time on average (the amount of time it takes a user to select an option and move to the next step).
- % of users that clicks on suggested product types
- % of users that clicks on view more product types
- % of users that clicks on start black VS start with a template
- % of users that follows the suggested pathway (import products or start with a template) VS follow the secondary one
- List of the most clicked product types

**Comment by mattsherman** [comment]
@verofasulo It is unclear to me where this screen should be... is it a replacement of the "Add Products" task on the home screen, or is it an interstitial that is shown when the user clicks "Add New" on the sidebar (which is what the mockup seems to show)?

> This page is visible to users that just started their business or skipped the Profiler

How do we know that they "just started their business"?

> The visible product types depend on what the user declared during the signup (step 3 - Product types - What type of products will be listed?). The other ones are collapsed.

What should be visible if they skipped step 3 of the Profiler?

> Includes the Load sample products feature that allows users to preview what their store might look like.

What is this "Load sample products" feature?

/cc @pmcpinto

**Comment by verofasulo** [comment]
@mattsherman 

> It is unclear to me where this screen should be

I attach a brief video to show you where it is in the flow. When the user clicks on the Add or import products task in the task list, they see this page before being addressed to the product page. 

![Screen Capture on 2022-03-24 at 09-46-24 (1)](https://user-images.githubusercontent.com/98944206/159878080-eb0287d5-7daf-49b5-9f9e-b38a5f734bf1.gif)

> How do we know that they "just started their business"?

When a user declares "I don't have any products yet" in the step "Tell us about your business" - Screen shot attached.

<img width="1728" alt="image" src="https://user-images.githubusercontent.com/98944206/159879273-d7704a91-b245-4c4b-a851-823cd4dcf31f.png">

> What should be visible if they skipped step 3 of the Profiler?

In this case, we default to the first option as the majority of our users sell physical products:

Selected (signup): Physical products
Surfaced (add product page): Physical product, Variable product, Grouped product

> What is this "Load sample products" feature?

The “Load sample products” feature allows to upload sample products to give users a preview of what their store might look like - I attach a brief video to show the flow.

![Sample products](https://user-images.githubusercontent.com/98944206/159880019-1bad8a5d-41a6-4b78-a167-f7ca9e3e9644.gif)

**Comment by mattsherman** [comment]
> The “Load sample products” feature allows to upload sample products to give users a preview of what their store might look like - I attach a brief video to show the flow.

This is distinct enough and complex enough that we should split it out into its own followup story. The other changes in this story have value on their own without that, so we shouldn't tie them together.

**Comment by verofasulo** [comment]
> This is distinct enough and complex enough that we should split it out into its own followup story.

Hey @mattsherman , good point! I created another issue related to sample products here: https://github.com/woocommerce/woocommerce/issues/32412

**Comment by chihsuan** [comment]
@verofasulo Thanks for creating this issue! I've looked over the requirements. Overall looks good! 👍 

I just split this into smaller tasks and have a few questions:

> % of users that clicks on start black VS start with a template

I guess you mean "`start blank`"?

> We'd like to try out two different layouts:

So we need to create an A/B test for them, right?

> Task completion time on average (the amount of time it takes a user to select an option and move to the next step).

Does this include import CSV steps for import product?

**Comment by chihsuan** [comment]
> We'd like to try out two different layouts:

@verofasulo So we need to create an A/B test for them, right?

**Comment by verofasulo** [comment]
@chihsuan thanks for going through this!

> I guess you mean "start blank"?

Yes, exactly! My bad, typo mistake 😄

> So we need to create an A/B test for them, right?

Yes, We'd like to run an A/B test to assess which layout works better for our users. 

> Does this include import CSV steps for import product?

No, we're not going to test that flow this time.

**Comment by pmcpinto** [comment]
> So we need to create an A/B test for them, right?
> Yes, We'd like to run an A/B test to assess which layout works better for our users.

@chihsuan it would be great to have an estimate of the effort required to build one version vs the two versions. We can start by testing just one version, and then test the 2nd version depending on the results. 

Test the two versions at the same time
Control vs V1
Control vs V2

Or sequence them
Control vs V1
and then
V1 vs V2 (if the results of the first experiment are positive)

**Comment by ilyasfoo** [comment]
@pmcpinto Testing two versions at the same time could be faster to iterate. What do you think of country-based segmentation similar to what we did in the previous experiment? 

If it's agreeable, perhaps you can let us know what group of countries should experience which variant.

**Comment by pmcpinto** [comment]
👍 We can use the same countries used in the previous a/b test
