### ISSUE TITLE
Task List: Add Products Task - Import products

### ISSUE THREAD

**Issue by verofasulo** [woothemes/woocommerce#32143]
**User story:**
As a new merchant with an existing product catalog
I want to be able to see the import options highlighted
So I can quickly import my products. 

**Description:** 
We reviewed the Add products page to organize the options according to the user profile. If users declared they're already selling somewhere else, they're addressed to the "Import products" page that makes more prominent options such as "Import from CSV" and "Import from Cart2Cart". All the other options are collapsed, yet still reachable by users.  

![Import Page](https://user-images.githubusercontent.com/98944206/156612070-1d5560dd-4e4e-494b-add7-2d14769efb70.gif)

![image](https://user-images.githubusercontent.com/98944206/156612274-28692672-dfd2-4f2a-88a6-0b7910d492b5.png)

**Design overview:**
cJQeyyhx9PraQrY3YAtCGM-fi-1133%3A131992

**Acceptance criteria:**

- [ ] This page is visible to users that declared to run a business and sell products somewhere else.
- [ ] Includes new icons and new copy.
- [ ] Includes a 1.5 px Gutenberg-blue border when components are hovered (instead of grey background). 
- [ ] Collapse all the other options that are not focused on importing products.

**Event tracking:**
- https://github.com/woocommerce/woocommerce/issues/32633

**Comment by mattsherman** [comment]
@verofasulo Should the style of the collapsed options match the layout of the active treatment in #32144? Or, should it always be a "stack layout"? And, I see the "stack layout" styling in this mockup looks slightly different than shown in #32144... I assume they should be the same?

/cc @pmcpinto

**Comment by verofasulo** [comment]
> Should the style of the collapsed options match the layout of the active treatment in https://github.com/woocommerce/woocommerce/issues/32144?

@mattsherman They are slightly different as I want to convey a different visual hierarchy: on the add products page they are the main focus, conversely here they are just a secondary option.

**Comment by mattsherman** [comment]
> > Should the style of the collapsed options match the layout of the active treatment in #32144?
> 
> @mattsherman They are slightly different as I want to convey a different visual hierarchy: on the add products page they are the main focus, conversely here they are just a secondary option.

Makes sense.

Though, I would say that since they are collapsed by default, they already have a different visual hierarchy and I question whether having a slightly different style is worth the slight increase in maintenance/complexity/etc.

**Comment by verofasulo** [comment]
That's a good point to keep into consideration.

To assess if it's worth it or not, I put together the differences between the two components:

<img width="1065" alt="image" src="https://user-images.githubusercontent.com/98944206/160150414-408c3222-fbaa-4eb7-8767-2bbbb4c6bbe9.png">

- Icon size and color
- Headline weight (semibold vs. regular)
- Body size (body vs. small body)
- Box height

And these would be the whole page:

Using the same component
<img width="1463" alt="image" src="https://user-images.githubusercontent.com/98944206/160150672-fe624528-1f91-4b9b-90ca-bfb18eb61271.png">

Differentiating components
<img width="1521" alt="image" src="https://user-images.githubusercontent.com/98944206/160150853-96ab5725-b799-4d16-9008-e8d1bf8ee393.png">

Personally, I think the first version is a bit unbalanced and once the user expands the panel, there's not enough visual hierarchy between the blocks. But of course, it depends on how much the maintenance effort is and if we think it's valuable or not. 

Looking forward to hear your thoughts @mattsherman

**Comment by verofasulo** [comment]
After testing the design ([user research recap](https://woostartp2.wordpress.com/2022/03/25/add-and-import-products-user-testing-recap/) if you'd like to know more), we decided to tweak the Cart2Cart copy a bit to make this feature clearer to our users.
 
@mattsherman  Please implement the following copy:

![image](https://user-images.githubusercontent.com/98944206/160845304-f84795dc-aab1-45af-b661-85313f8b2876.png)

The link addresses users to the same external Cart2Cart page as before but adding the Learn more link gives them more confidence that they are not starting the flow, only collecting information and exploring the option. 

**Figma link**:
cJQeyyhx9PraQrY3YAtCGM-fi-836%3A101683

**Comment by mattsherman** [comment]
> Personally, I think the first version is a bit unbalanced and once the user expands the panel, there's not enough visual hierarchy between the blocks. But of course, it depends on how much the maintenance effort is and if we think it's valuable or not.
> 
> Looking forward to hear your thoughts @mattsherman

Looking at both options, I think that using the same component results in an overall design that feels more coherent. The "differentiating components" design feels like a mix of two styles. I hold that a clear hierarchy is established by:

* positioning lower on the screen, collapsed by default
* smaller blocks, compared to the large import options at the top of the page

So, I'd personally go with using the same component simply from a design perspective. From a maintenance perspective, I think the savings is minimal... we could implement the two different styles without too much complexity.

**Comment by adrianduffell** [comment]
> The link addresses users to the same external Cart2Cart page as before but adding the Learn more link gives them more confidence that they are not starting the flow, only collecting information and exploring the option.


@verofasulo For the Cart2Cart option, would the whole button link to the [external Cart2Cart page](https://woocommerce.com/products/cart2cart/?utm_medium=product)?

**Comment by adrianduffell** [comment]
<del>@verofasulo Also, does this change remove the"Start with a template" option?</del>

<img width="747" alt="Screen Shot 2022-04-19 at 10 17 36 pm" src="https://user-images.githubusercontent.com/9312929/164025023-c5debe0c-d0cb-4977-8ee4-e40fe60c3e2c.png">

It looks like we would now start each of the product types "from scratch". Does that mean pre-filling the correct product type on the New Product screen, but leaving everything else blank?

**Comment by adrianduffell** [comment]
> Also, does this change remove the"Start with a template" option?

Oh I get it, this is the import screen and it didn't previously have the "Start with a template option".

**Comment by verofasulo** [comment]
> For the Cart2Cart option, would the whole button link to the [external Cart2Cart page](https://woocommerce.com/products/cart2cart/?utm_medium=product)?

Yes, exactly. Thanks, Adrian

> Oh I get it, this is the import screen and it didn't previously have the "Start with a template option". 

Yes 😄 The idea is to organize the “add product” options according to the user profile - so if the user declared to sell already somewhere else, we display this page with a focus on the import options (still, there's the possibility to start with a template but it's collapsed in the accordion).

**Comment by moon0326** [comment]
@verofasulo ✋ 

>  If users declared they're already selling somewhere else

So we have four different options for "selling elsewhere". 
![Screen Shot 2022-04-22 at 2 41 42 PM](https://user-images.githubusercontent.com/4723145/164799843-548d43f6-ebf8-45d7-8123-ea67dbb7c9f5.jpg)

Should we also consider `Yes, in person at physical stores and/or events` as "selling elsewhere" for this issue?

**Comment by verofasulo** [comment]
That's a great question @moon0326 - My assumption is that also physical stores rely on their own database/file/any form of data storage to manage their product catalog. So yes, I would consider `physical stores and/or events` as "selling elsewhere" for this issue.

**Comment by moon0326** [comment]
Hi @verofasulo 

It's very minor, but I noticed a tiny inconsistency while working on the issue.

https://github.com/woocommerce/woocommerce/issues/32634 shows `View more product types` link aligned to the left, but this issue shows `or add your products from scratch` link at the center.

Is this intended?

**Comment by moon0326** [comment]
Hi @verofasulo 

I have one more question :)

The icon has the following note on the Figma design.

```
/* Core / Light Gray / 900 */
background: #A2AAB2
```

Is this a variable from core? I wasn't able to locate it.
![Screen Shot 2022-04-28 at 9 30 21 PM](https://user-images.githubusercontent.com/4723145/165885472-c052cf85-9afa-414f-be4a-ef2c4225b4fd.jpg)

**Comment by verofasulo** [comment]
> https://github.com/woocommerce/woocommerce/issues/32634 shows View more product types link aligned to the left, but this issue shows or add your products from scratch link at the center.

Thanks for spotting it @moon0326 ! The correct version is the one with the accordion aligned at the centre, both for the import and add products pages :)

**Comment by verofasulo** [comment]
> Is this a variable from core? I wasn't able to locate it.

That's a great question - I used the Gridicons set that is the one used by the mobile team and I thought there was consistency in terms of color palette but it seems it's not. I just updated the designs using `Gutenberg/Gray 500` :)

**Comment by moon0326** [comment]
>  Thanks for spotting it @moon0326 ! The correct version is the one with the accordion aligned at the centre, both for the import and add products pages :)

Thank you!

@chihsuan We might need to update https://github.com/woocommerce/woocommerce/pull/32801 in this case.
