### ISSUE TITLE
Setup experiment: new task list layout (version 2)

### ISSUE THREAD

**Issue by jarekmorawski** [woothemes/woocommerce#32164]
**Description:**
In this experiment we want to see if splitting tasks into goals/sections will have an impact on the completion rate.

<img width="545" alt="image" src="https://user-images.githubusercontent.com/79307566/155321668-d21f1fb5-871a-4076-99e1-98cb9b0ffb52.png">

Design overview:
* pbIJXs-1ew-p2-p2
* G9vi4e286yjdzyIdg8hBb1-fi-737%3A97358

Acceptance Criteria:

- [ ]  Visible only to new stores in the US
- [ ] Uses the new header with the progress bar ( progress bar is added in woocommerce/woocommerce#32165 )
- [ ] Tasks are split across multiple sections
- [ ] Each section has its own title, description, and illustration
- [ ] Merchant can only open 1 section at a time (if there's one open, it'd collapse)
- [ ] When merchant completes the last task in the section, we automatically collapse it and expand the next one
- [ ] Collapsed sections follow the style of the Orders/Reviews/Stock section in the Home screen
- [ ] 'Cover the basics' section includes 1 extra task ('You created [store_name') that's not interactive
- [ ] Collapsed sections have a number badge indicating the number of incomplete tasks
- [ ] Each task has unique name and description
- [ ] Completed tasks have names with summarized changes (G9vi4e286yjdzyIdg8hBb1-fi-942%3A114217)
- [ ] Completed tasks have a green checkmark icon
- [ ] Complete and incomplete tasks have new inner padding and margins: 24 (left), 16 (top), 24 (right), 16 (bottom)
- [ ] In the 2-column layout, the design behaves like the current task list
- [ ] Task list should still be hidden or viewable through the dropdown help menu

Sections (see figma for section copy and the completed copy of each task):
- Cover the basics
     - You created <store name> (always shows as completed)
     - You added store details
     - Create or upload your first products ( replacing the 'Add my products' task)
          - Add products to sell and build your catalog.
     - Add a way to get paid ( replacing the 'set up payments' task )
          - Let your customers pay the way they like.
- Get ready to sell
     - Select how to ship your products ( replacing 'Set up Shipping' task)
          - Set delivery costs and enable extra features, like shipping label printing.
     - Get taxes out of your mind ( replacing 'Set up tax' task)
          - Have sales tax calculated automatically, or add the rates manually.
- Customize & expand
     - Make your store stand out with unique design ( replacing 'Personalize my store' task?)
          - Upload your logo to adapt the store to your brand's personality. 
     - Grow your business with marketing tools ( replacing 'Set up marketing tools' task)
          - Promote your store in other sales channels, like email, Google, and Facebook.

**Event tracking:**
- Expand/collapse of a section?
- Complete section?
- All the tasks should keep the same tracks as before? (see woocommerce/woocommerce#32150 for events)

**Comment by louwie17** [comment]
@jarekmorawski under the **Cover the basics** section does the **You created <store name>** always show up as completed, or is there a case when it shows as uncompleted?

**Comment by louwie17** [comment]
In terms of technicals:
- Task list design will require a full make over for this one, we would want to create a completely separate stand alone task list component that follows this design.
- We don't allow for grouping of tasks very well, the easiest would be to add a task type to the [task class](https://github.com/woocommerce/woocommerce-admin/blob/main/src/Features/OnboardingTasks/Task.php#L77-L82) and group them in our newly created task list component.
     - We will also have to manage the section title and logo somewhere (maybe as part of the TaskList class as `additional_info` or something like that?)
- We can make use of the `Panel` and `PanelBody` [components from gutenberg](https://github.com/WordPress/gutenberg/tree/trunk/packages/components/src/panel#expand-and-collapse) for the sections, this is what we also use in the [orders/reviews activity panels ](https://github.com/woocommerce/woocommerce-admin/blob/main/client/homescreen/activity-panel/index.js#L88)

**Comment by jarekmorawski** [comment]
> under the Cover the basics section does the You created always show up as completed, or is there a case when it shows as uncompleted?

Yes, it will always be completed and inactive. It is checked off by the mere fact that you're seeing the list (which means you've created a store).

> Task list design will require a full make over for this one, we would want to create a completely separate stand alone task list component that follows this design.

@pmcpinto, just bringing this to your attention. I think the sections make a lot of sense and given our recent conversations about exploring other visual directions for the task list, I think this initiative is worth the effort.

> We can make use of the Panel and PanelBody [components from gutenberg](https://github.com/WordPress/gutenberg/tree/trunk/packages/components/src/panel#expand-and-collapse) for the sections, this is what we also use in the [orders/reviews activity panels](https://github.com/woocommerce/woocommerce-admin/blob/main/client/homescreen/activity-panel/index.js#L88)

That was exactly my intention behind this design. Please note that compared to the current panels, I increased the spacing between them and fixed visual errors (mostly effects on hover and a bizarre jump in padding when you expand a panel).

**Comment by pmcpinto** [comment]
> @pmcpinto, just bringing this to your attention. I think the sections make a lot of sense and given our recent conversations about exploring other visual directions for the task list, I think this initiative is worth the effort.

Thanks for the heads up.

@louwie17 out of curiosity, do you think that there's a way to implement the approach we want to test without rebuilding the task list from scratch? We don't know if it will perform better than the current version, so it would be interesting to explore if we can accomplish something faster/with less effort, even if it requires some adjustments to the design proposed by Jarek.

**Comment by louwie17** [comment]
> @louwie17 out of curiosity, do you think that there's a way to implement the approach we want to test without rebuilding the task list from scratch? We don't know if it will perform better than the current version, so it would be interesting to explore if we can accomplish something faster/with less effort, even if it requires some adjustments to the design proposed by Jarek.

Rebuilding from scratch might of been an over exaggeration, it's mostly the UI part that needs to be re-done, but most of the underlying logic can stay the same. We should also be able to re-use the individual task list item. So the re-building will mostly be for the different sections and managing those.
I am not sure what we could adjust on the design, I think it would mostly be related with animations of the sections to keep them as close to what the `wordpress/components` library already does for us.

**Comment by pmcpinto** [comment]
Gotcha. Thanks for the clarification

**Comment by louwie17** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Mothra-60df2bf941ae44000ebbda7c/issues/woocommerce/woocommerce-admin/8352?planning-poker) with ZenHub @jacob-sewell @joelclimbsthings @octaedro

**Comment by octaedro** [comment]
Hey @jarekmorawski,
I have a couple of questions related to the extended task list (`Things to do next`). In the design, I couldn't see the setup task list (`Get ready to start selling`) and the extended one together. Currently, we can see them at the same time, will that behavior change?
Will the extended task list have any changes?

**Comment by jarekmorawski** [comment]
> Currently, we can see them at the same time, will that behavior change?

That's a good question. My intention was to only show `Things to do next` when you complete the task list (which is why in the designs its only present along with the congratulatory card), but that could have consequences for our partnerships and less essential flows. 🤔 @pmcpinto, do you have any thoughts? To me, we should only suggest other steps when others are done to avoid overwhelming people. If there's something important in `Things to do next,` perhaps it should be part of the main task list?

> Will the extended task list have any changes?

Nope, except for updated inner paddings to match tasks in the new layout. Design- and code-wise, they're one and the same element.

**Comment by pmcpinto** [comment]
For the experiment, I think it's better to keep the `Things to do next` list in the experience. We can reassess this if the treatment version is declared as winner.

**Comment by louwie17** [comment]
@jarekmorawski @pmcpinto another question in regards to this, the payment task is currently under the `Cover the basics` section. When a user selects WooCommerce Payments in the onboarding wizard and the WooCommerce Payments specific task shows up, should this one also be displayed in the `Cover the basics` section?

In this case I am assuming it will replace the payment task, similar to how the current logic works.

**Comment by jarekmorawski** [comment]
> When a user selects WooCommerce Payments in the onboarding wizard and the WooCommerce Payments specific task shows up, should this one also be displayed in the Cover the basics section?

That's correct.

> In this case I am assuming it will replace the payment task, similar to how the current logic works.

Yes, exactly. We're not changing the logic, just the visual treatment.

**Comment by mattsherman** [comment]
@louwie17 Is there anything outstanding with this issue, or can we close it?

**Comment by louwie17** [comment]
> @louwie17 Is there anything outstanding with this issue, or can we close it?

This should be good to close (I will close it).
