### ISSUE TITLE
Setup experiment: task chaining - popover

### ISSUE THREAD

**Issue by jarekmorawski** [woothemes/woocommerce#32162]
**User Story:**
As a new merchant
I want to know what I need to do to complete store setup
So I can do it quickly and without clicking through different menus

**Description:**
In attempt to help merchants stay in the flow while setting up their store and boost the number of people who complete more than a few tasks, we'd introduce additional guidance at the end of each task. We'd suggest next step the moment the last one is finished and make the task list available from any screen inside WooCommerce.

![screenshot-www figma com-2022 02 25-13_48_25](https://user-images.githubusercontent.com/1314156/155754683-89680fc0-b759-4d7a-ae81-986c07584b85.png)

**Design overview:**
* pbIJXs-1ew-p2
* G9vi4e286yjdzyIdg8hBb1-fi-123%3A14927

**Acceptance Criteria:**

_Popover_

- [ ] When merchant completes a task, after a 1 s delay we show a popover message with some guidance
- [ ] The popover uses the same styles/component as the help spotlight message in NUX
- [ ] The copy inside the message is unique for each task
- [ ] The number of steps in the copy is linked to the Home screen
- [ ] The message can be dismissed without triggering any additional action (X dismisses the message)
    - QUESTION: does message reappear when a new task is completed?
    - Answer: Yes, dismissing only for the current task, reappearing when they complete another.
    - QUESTION: if they refresh page before dismissing message, does it reappear?
    - Answer: No stickiness, have to click the button in order to see it again.
- [ ] Clicking the CTA button in the popover would take merchants straight to the next task's internal flow and skip the Home screen entirely
- [ ] The popover could be powered by the Tour Kit (p58i-bHf). If possible, we'd introduce this library to wc-admin as we'll likely use the spotlights on multiple occasions in the near future
- [ ] If needed, we can decouple the next step popover message from the side panel and complete the latter in the next cycle

**Event tracking:** to be assessed by the team

**Tasks**

- [ ] Determine how to let client know when a task was completed, if a page refresh occurs
    - Keep a record of last completed task, or
    - Keep a timestamp on each completed task
- [ ] If we had a general "modal API", we could use that to see if something should be shown
    - keep track of modals by slug

**Comment by mattsherman** [comment]
Split into two issues... this one is for the popover. woocommerce/woocommerce#32152 is for the side panel

**Comment by octaedro** [comment]
Hi @jarekmorawski,
I have a few questions related to this issue:

>  The popover could be powered by the Tour Kit (p58i-bHf). If possible, we'd introduce this library to wc-admin as we'll likely use the spotlights on multiple occasions in the near future

I couldn't make the link (`p58i-bHf`) work, is it possible to get a link to the library?

This would be a pretty similar popover to what we did [here](https://github.com/woocommerce/woocommerce-admin/pull/5826), is there a reason to discard the [WP Popover](https://developer.wordpress.org/block-editor/reference-guides/components/popover/)?

**Comment by octaedro** [comment]
The events that I think should be tracked are:
- When the popover is shown.
- When the popover is closed by pressing the `X`.
- When the user presses the total amount of tasks to do.
- When the user presses the CTA button.

**Comment by jarekmorawski** [comment]
Hi @octaedro! 👋 

> I couldn't make the link (p58i-bHf) work, is it possible to get a link to the library?

Here's the [public repo](https://github.com/Automattic/wp-calypso/tree/trunk/packages/tour-kit).

> This would be a pretty similar popover to what we did https://github.com/woocommerce/woocommerce-admin/pull/5826, is there a reason to discard the [WP Popover](https://developer.wordpress.org/block-editor/reference-guides/components/popover/)?

I don't know the full details, but it's possible that the existing popover component will co-exist with Tour Kit (which the new library builds off of, I think) and all future onboarding-related interactions in Gutenberg will use it from now on. By adding it to core, we future-proof the code.

It could be, however, that Tour Kit is not ready to use in production just yet. In that case, it's alright to use the same component as in the help tooltip (the intention is to keep these messages consistent so if we use Tour Kit, ideally we'd use it for the help button, too).

Would you mind taking a look at the Tour Kit repo and assessing the state it's in?

**Comment by jacob-sewell** [comment]
Per meeting discussion: if a user navigates to the WooCommerce Home screen any active task chaining popover will be silently dismissed.

(We were discussing this in the context of interfaces that redirect you to Home once you use them, but presumably this would be the desired behavior if the user manually navigates Home as well.)

@jarekmorawski @pmcpinto @verofasulo @louwie17 @octaedro feel free to clarify this point if I'm misrepresenting it.

**Comment by louwie17** [comment]
For a little bit of extra context, we might be able to re-use the current logic of the 'Finish setup' panel, and only render the popup then: https://github.com/woocommerce/woocommerce-admin/blob/main/client/activity-panel/activity-panel.js#L234-L264

Also here is our current `HighlightTooltip` that we can use for this: https://github.com/woocommerce/woocommerce-admin/blob/main/client/activity-panel/highlight-tooltip/index.js
Here is the example of usage: https://github.com/woocommerce/woocommerce-admin/blob/main/client/activity-panel/activity-panel.js#L389-L403

**Comment by louwie17** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Mothra-60df2bf941ae44000ebbda7c/issues/woocommerce/woocommerce-admin/8354?planning-poker) with ZenHub @jacob-sewell @joelclimbsthings @octaedro

**Comment by louwie17** [comment]
@jarekmorawski @pmcpinto a follow up question that came up during our sprint kick off today, was if this pop up should automatically be dismissed if a user leave's the specific page without interacting with the pop up? Meaning that it won't hang around across different pages.

**Comment by louwie17** [comment]
Ooh and an additional question, if the action button should always point to the next (unfinished) inline task, or always to the unfinished task at the top of the list. This would only matter if a user did tasks out of order.

**Comment by jarekmorawski** [comment]
> was if this pop up should automatically be dismissed if a user leave's the specific page without interacting with the pop up?

No, I think it should persist on the screen until dismissed.

> if the action button should always point to the next (unfinished) inline task, or always to the unfinished task at the top of the list.

It should point to the first unfinished task at the top of the list. 👍

**Comment by jarekmorawski** [comment]
Hi y'all! As discussed during the last product call, to limit the scope of work and validate the idea before committing to it, we'll start with a simpler version of the popover. Much like the original version, it'll appear 150ms after user completes a task and point to the new `Finish setup` button in the top bar. It will only appear once.

<img width="723" alt="image" src="https://user-images.githubusercontent.com/79307566/164518096-36fd2d40-d975-4134-9465-87e7d045e4d3.png">

Here's the popover's copy:

> 👏  Well done! What’s next?
Click here to open the store setup guide and see the next steps.
Got it [Secondary button]

Let me know if you have any questions!

**Comment by pmcpinto** [comment]
@louwie17 is it possible to have an estimate of the effort required to implement this new exploration shared by Jarek?

**Comment by louwie17** [comment]
> @louwie17 is it possible to have an estimate of the effort required to implement this new exploration shared by Jarek?

I will check with every one in Slack and get back to you with the effort, at first glance this should decrease the amount of effort quite a bit.

**Comment by louwie17** [comment]
@pmcpinto @jarekmorawski follow up after chatting with the team about this:

The design changes of this definitely make this issue a bit easier to do. **But** the biggest time consumer is the underlying code to manage the showing and dismissing of the popup after task completion. We have some of that logic in place, but in several different area's of our app and some of it will have to be re-factored to be more generic.

Meaning that as part of the issue we might want to spent some time working on a dismissal system that can easily handle this situation and also others surrounding task list progress and completion.
We could create a separate issue for this and point that issue. Then re-point this with the other issue in mind.

If you prefer to get this issue in earlier, we could alter the `show` logic to be a little simpler. Maybe similar to what we use for the reminder task bar? - having it pop up if you are not on the home screen after the user has finished at-least 2 tasks for example.
We be happy to chat more about this, async or setting up a meeting.

**Comment by jarekmorawski** [comment]
Thanks for the detailed overview of the issues at hand, @louwie17. It seems like we need to make a decision.

> We have some of that logic in place, but in several different area's of our app and some of it will have to be re-factored to be more generic.

Frankly, I think we'd need that logic anyway. If not for this particular element, we'll likely use it to trigger a different interaction at some point in the future. The more scaffolding like this we have, the easier it will be to run experiments within key parts of the setup experience.

I think it's worth the extra time investment, but I can see how this may not be the best time to do it. In the meantime, we could do it how you proposed. Note that it'll then be a different kind of experiment: we'd point to a specific part in the UI, rather than guide and suggest the next steps. We've got to be aware that the experiment may not have the impact we count for.

What do you think, @pmcpinto?

**Comment by pmcpinto** [comment]
@louwie17 thanks for the additional context.

> We have some of that logic in place, but in several different area's of our app and some of it will have to be re-factored to be more generic.

Is there a specific setup task where we could test the popover without rebuilding the code to manage the show/dismiss behavior post-task completion?

**Comment by louwie17** [comment]
> Is there a specific setup task where we could test the popover without rebuilding the code to manage the show/dismiss behavior post-task completion?

Yeah, if we wanted we could make use of the current notices code that we show when creating the first product for example or adding the first tax rate, there is also one for after updating the homepage.
Assuming this popup would replace the notice, it should be relatively minimal to make use of the popup in that code.

This shouldn't add any extra bloat given we can re-use the popup once we implement the dismissal framework.

**Comment by pmcpinto** [comment]
Interesting. We could start by showing the popover just when the user creates the first product, nudging him to move to the next task (payments).
this would allow us to test the effectiveness of this approach without having to rebuild the underlying logic. @jarekmorawski what do you think?

**Comment by mattsherman** [comment]
I've removed this from Cycle 24 and removed the final estimate, as both will need to be reconsidered once the "simpler version"'s details are ironed out.

**Comment by mattsherman** [comment]
> We could start by showing the popover just when the user creates the first product, nudging him to move to the next task (payments).
this would allow us to test the effectiveness of this approach without having to rebuild the underlying logic. @jarekmorawski what do you think?

@pmcpinto @jarekmorawski Do we still want to proceed with this? Should we wait until we have related side panel changes in and have seen how it performs? https://github.com/woocommerce/woocommerce/issues/32152

**Comment by pmcpinto** [comment]
I think it makes sense to wait and see the impact of the side panel changes. Do you agree?

Is it possible to release #32152 with 6.6?

**Comment by joelclimbsthings** [comment]
> Is it possible to release https://github.com/woocommerce/woocommerce/issues/32152 with 6.6?

@pmcpinto I have [a PR](https://github.com/woocommerce/woocommerce/pull/33124) up for this now, but unfortunately it missed the code freeze yesterday. My suspicion is that it will be difficult to get this 🍒 picked into 6.6 at this point.
