### ISSUE TITLE
Setup experiment: new task list layout (version 1)

### ISSUE THREAD

**Issue by jarekmorawski** [woothemes/woocommerce#32165]
**Description:**
To increase the number of people completing more than 3 tasks, we want to try out two new list layouts. This experiment will be run side-by-side with the other as part of an A/B test and uses the most recent layout as a foundation. I've updated the illustrations to reflect the new design language and added a progressive header to helps merchants track their progress (described in a separate task).

<img width="707" alt="image" src="https://user-images.githubusercontent.com/79307566/155320157-abe7ab4c-d405-4d3f-88be-b18aa9c77d50.png">

**Design overview:**
* pbIJXs-1ew-p2
* G9vi4e286yjdzyIdg8hBb1-fi-736%3A92987

**Acceptance Criteria:**

- [ ] Visible only to new stores in the US
- [ ] Uses the unchanged layout & mechanics of the recently run task progression experiment
- [ ] Uses the new header with the progress bar
- [ ] Includes updated illustrations for each task ( updating the labels of completed tasks to be in the past tense now - see screenshot)
- [ ]  Task list should still be hidden or viewable through the dropdown help menu

**Event tracking:**

See woocommerce/woocommerce#32150 for events, there should be no need for additional events for this issue.

**Comment by louwie17** [comment]
@jarekmorawski I assume the progress bar will also span across the two columns if that view is enabled, in the same way that the current experimental task list is spanning across both columns?
<img width="1214" alt="Screen Shot 2022-02-24 at 1 29 07 PM" src="https://user-images.githubusercontent.com/2240960/155576218-2a22c0cb-4bcb-4364-8fbe-faf898cc4e65.png">

**Comment by louwie17** [comment]
One thing to note about running two of these experiments side by side, is that we would probably wanted to run a multivariate experiment ( in this case two treatments, with the control being our standard task list ). This way we can still disable the experiment mid-way and return to our default set up versus showing one of the treatment options.
This is possible, but does seem to be in early alpha stage:
<img width="709" alt="Screen Shot 2022-02-24 at 1 41 06 PM" src="https://user-images.githubusercontent.com/2240960/155578073-60ca8035-edf4-4ae9-b239-110ae393e803.png">

Unless this task list will be the default one anyway given how the current experiment will play out.

**Comment by louwie17** [comment]
In terms of technical's:
- The progress bar has to be created from scratch as we don't already have one (this should be relatively straight forward), could add a config option in the task list for this?
- We currently don't allow for alternate task titles, this would have to be added to our [Task class](https://github.com/woocommerce/woocommerce-admin/blob/main/src/Features/OnboardingTasks/Task.php#L77-L82), making this configurable so it can be turned on/off (depending on the task list).
- Make sure the multivariate experiment works well, we most likely want to handle this on the back-end versus currently in our front-end to avoid many different conditions spread through the app (moved this into a separate issue - woocommerce/woocommerce#32150)

**Comment by jarekmorawski** [comment]
> I assume the progress bar will also span across the two columns if that view is enabled, in the same way that the current experimental task list is spanning across both columns?

No. The 2-column layout did not perform as well as the single column one so I'm thinking we could change it a little. In horizontal layout, the task list could be displayed in the left column (much like the control version) and the new header would replace the existing one. What do you think?

<img width="1440" alt="Home" src="https://user-images.githubusercontent.com/79307566/155599456-4a1ffbec-e97b-4c31-b3d9-3279410a56e8.png">

**Comment by louwie17** [comment]
> No. The 2-column layout did not perform as well as the single column one so I'm thinking we could change it a little. In horizontal layout, the task list could be displayed in the left column (much like the control version) and the new header would replace the existing one. What do you think?

Thanks for the clarification @jarekmorawski, that sounds good with me.

I do notice in your screenshot above the Orders/Stock/Reviews panels are listed in the right column is that something also being changed as part of this? usually we don't show them until the task list is hidden and in the left column.

**Comment by jarekmorawski** [comment]
> I do notice in your screenshot above the Orders/Stock/Reviews panels are listed in the right column is that something also being changed as part of this? usually we don't show them until the task list is hidden and in the left column.

No, it's just an omission on my part. Thanks for pointing it out! I've fixed the screenshot.

**Comment by louwie17** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Mothra-60df2bf941ae44000ebbda7c/issues/woocommerce/woocommerce-admin/8350?planning-poker) with ZenHub @joelclimbsthings @jacob-sewell @octaedro

**Comment by louwie17** [comment]
@jarekmorawski I have a couple small questions that came up as I was working on this:
- The wireframe doesn't include the `Personalize my store` task, will that one indeed not be included?
- For the `Get more sales` task I don't have a completed title, currently I put `You added marketing tools`, let me know if you prefer something else?

**Comment by jarekmorawski** [comment]
> will that one indeed not be included?

No, it should be there. I couldn't find it in Elizabeth's file and didn't know how it was implemented, but I've updated the design file now: G9vi4e286yjdzyIdg8hBb1-fi-1241%3A123187

> For the Get more sales task I don't have a completed title, currently I put You added marketing tools, let me know if you prefer something else?

Sounds good! Since the button says `Add sales channels`, the completed task could read `You added sales channels`.

**Comment by mattsherman** [comment]
Closing this issue as we have followup issues to track remaining work.
