### ISSUE TITLE
Task List: Add Products Task - Load sample products feature

### ISSUE THREAD

**Issue by verofasulo** [woothemes/woocommerce#32412]
**User story:**
As a new merchant who has no products yet
I want to start with some sample products
So I can easily preview what my store will look like.

**Description:**
While redesigning the [add product page](https://github.com/woocommerce/woocommerce/issues/32144), we'd like to introduce and test this new feature along with the product templates. We think it might be useful for beginners that don't have a product catalog ready yet.

![Load sample products](https://user-images.githubusercontent.com/98944206/160785697-12223522-e01e-4fed-af98-ea02364d427d.gif)

**Design overview:**
cJQeyyhx9PraQrY3YAtCGM-fi-1133%3A138411

**Acceptance criteria:**

- [ ] This feature is included in the add product page alongside with the product templates
- [ ] 9 sample products are loaded
- [ ] Product images based on the industry the user selected. If it's not possible to follow this approach and diversify content, I would use clothing and accessories images for everyone.
- [ ] In addition to images, upload fake data such as price, description, categories etc. to make it perceived like a real product page.

**Event tracking:**
To be assessed by the team

**Comment by jonathansadowski** [comment]
Hi @verofasulo. Please be sure when creating tasks for your team to add the appropriate focus/plugin/status/type labels, otherwise the issue ends up in our triage queue. Thanks!

**Comment by verofasulo** [comment]
Hey @jonathansadowski , thanks for pointing it out and sorry for the additional work 🙏

**Comment by jonathansadowski** [comment]
No worries. It's a new process for us, so we're still nailing it down.

**Comment by adrianduffell** [comment]
@verofasulo Do you have any sample products in mind? The [sample.csv](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/sample-data/sample_products.csv) file included with WooCommerce adds the following products. However is this too focused on clothing/accessories? 

![image](https://user-images.githubusercontent.com/9312929/164028181-92636552-7e75-40ab-ba20-a2f6912fbf17.png)

We could also make some new fake products. Perhaps we could source images from [openverse](https://wordpress.org/openverse/) 🤔

**Comment by verofasulo** [comment]
@adrianduffell that's a great point.

> We could also make some new fake products. Perhaps we could source images from [openverse](https://wordpress.org/openverse/) 🤔

Yes, I think we could use some more realistic product images as the purpose is to give the user an idea of what the store might look like after adding products. Do we already have some sample images or just the ones in the screenshot above?

> However is this too focused on clothing/accessories?

I was thinking to focus on this industry as it's the most popular one. Maybe in the future, we can differentiate sample images based on the industry selected by the user in the profiler?

**Comment by chihsuan** [comment]
> Do we already have some sample images or just the ones in the screenshot above?

@verofasulo We only have ones in the screenshot above now. 

> Maybe in the future, we can differentiate sample images based on the industry selected by the user in the profiler?

Yeah, that sounds great! 😄

**Comment by adrianduffell** [comment]
I've extracted the sourcing of new sample clothing/accessories products into an issues here https://github.com/woocommerce/woocommerce/issues/32859
