### ISSUE TITLE
Standardize Nx Executors

### ISSUE THREAD

**Issue by ObliviousHarmony** [woothemes/woocommerce#32435]
In pursuit of making our repository easier to work with, we should lean into using Nx as consistently as possible. We should not be using `pnpm run` scripts if at all possible, and instead, rely on more general solutions. One of the guiding principles of this epic is to deeply utilize `Nx` plugins. These will be better for utilizing the features available to us, such as build environments, and all kinds of fun things like that.

- [x] https://github.com/woocommerce/woocommerce/issues/32551
- [x] https://github.com/woocommerce/woocommerce/issues/32552
- [x] https://github.com/woocommerce/woocommerce/issues/32553
- [x] https://github.com/woocommerce/woocommerce/issues/32554
- [x] https://github.com/woocommerce/woocommerce/issues/32555
- [x] https://github.com/woocommerce/woocommerce/issues/32556

Please note that _all_ of these changes will need to be clearly and proactively communicated. They are breaking changes to existing workflows, and while the outcome will be better, that is still something to keep in mind.

**Comment by ObliviousHarmony** [comment]
We should review some of our `composer` commands. A standard workflow right now is that after pulling, you would want to run `pnpm install` to get the latest dependencies. I can imagine that the same would be generally true of Composer dependencies, so maybe we need a `postinstall` script in the root `package.json` that runs a composer installation against every project in the monorepo? I'm not sure `composer-` commands need to exist, since dependency management should still be done using it.

**Comment by ObliviousHarmony** [comment]
This issue has been closed in favor of a transition to Turborepo.
