### ISSUE TITLE
Store location: Task list

### ISSUE THREAD

**Issue by verofasulo** [woothemes/woocommerce#32587]
**Description:**
Collecting the store location right at the beginning of the new user experience is critical, as payments, shipping, and taxes recommendations are tailored according to the store country. About 25% of new users skip the store profiler. Among them, less than 2% add the store location during the first 3 days of activity through settings or the shipping/tax tasks.

When the user clicks on “Store details” in the task list, we send them back to the first step of the Profiler and force them to go through each step before being back to the home page. 
To streamline the flow, we think it would be smoother to address users to Settings > General and let them add the store location details from there.

![Store location - Settings flow](https://user-images.githubusercontent.com/98944206/162934877-b09c2a4b-4b50-45f4-a44c-4d5c3300a790.gif)

 **Design overview:**
cJQeyyhx9PraQrY3YAtCGM-fi-888%3A123713

**Acceptance Criteria:**

- [x] Address users to Settings > General after they clicked on the "Store details" task in the task list. https://github.com/woocommerce/woocommerce/pull/33671#pullrequestreview-1027976691
- [x] Add a spotlight to guide users in Settings and point out where they can add the store details.
- [ ] Add event tracking so that we can evaluate whether the spotlight encourages users to fill out the store location details

**Comment by verofasulo** [comment]
Following up on the [new spotlight component initiative](https://ghidorahp2.wordpress.com/2022/04/13/shared-in-app-spotlight-component/), please implement the new spotlight that’s part of a larger design element used for help and guidance.

![image](https://user-images.githubusercontent.com/98944206/164718124-db8fe38a-cecb-4ed1-be7d-870140de8b82.png)

**Comment by moon0326** [comment]
Nice addition @verofasulo  👍 

I have questions.

1. Do we always send users to the `Settings -> General` tab or do we have a condition? I'm guessing that we send users to the `Settings -> General` when the user skipped the `Store details` after they were redirected to it during the installation process, but I wasn't sure.
2. How do users access `Store details` tasks again?

**Comment by verofasulo** [comment]
Hey @moon0326, thanks for starting working on it 🙌

 > Do we always send users to the Settings -> General tab or do we have a condition?

Yes, we always send users to Settings > General - both if the task is not completed (users skipped the profiler) and if it's marked as done (and users click on that again).

> How do users access Store details tasks again?

By clicking on the "Store details" task 🙂

**Comment by moon0326** [comment]
> Hey @moon0326, thanks for starting working on it 🙌
> 
> > Do we always send users to the Settings -> General tab or do we have a condition?
> 
> Yes, we always send users to Settings > General - both if the task is not completed (users skipped the profiler) and if it's marked as done (and users click on that again).
> 
> > How do users access Store details tasks again?
> 
> By clicking on the "Store details" task 🙂

I think I might be missing something 🤔 

How do users access Industry, Product Types, and Business Details again?

**Comment by verofasulo** [comment]
> How do users access Industry, Product Types, and Business Details again?

Is it something users usually do? My assumption is that no one would go back to fill this data as they don't have any impact on setting up their store (apart from store location). They are mostly data that we use to profile them, but once skipped the profiler, there's no reason for our users to spend time selecting industry or type of products. But if we have any data that demonstrates the opposite, I'm happy to re-discuss the designs 😄

**Comment by moon0326** [comment]
> > How do users access Industry, Product Types, and Business Details again?
> 
> Is it something users usually do? My assumption is that no one would go back to fill this data as they don't have any impact on setting up their store (apart from store location). They are mostly data that we use to profile them, but once skipped the profiler, there's no reason for our users to spend time selecting industry or type of products. But if we have any data that demonstrates the opposite, I'm happy to re-discuss the designs 😄

That sounds reasonable 👍

**Comment by chihsuan** [comment]
@verofasulo How do we determine whether the store details task is completed or not? In the current design, we mark it as completed when a user completes the last step in OBW.

**Comment by verofasulo** [comment]
> How do we determine whether the store details task is completed or not? In the current design, we mark it as completed when a user completes the last step in OBW.

I think the task should be marked as completed once the user added the store location by filling out the address/ city / country fields in Settings.

**Comment by chihsuan** [comment]
> > How do we determine whether the store details task is completed or not? In the current design, we mark it as completed when a user completes the last step in OBW.
> 
> I think the task should be marked as completed once the user added the store location by filling out the address/ city / country fields in Settings.

Thanks, sounds good! 🙌

**Comment by rjchow** [comment]
Reopening because we still need to add tracks

**Comment by verofasulo** [comment]
Following @manospsyx's [suggestion](https://hostedwoo.wordpress.com/2022/09/07/skip-the-onboarding-profiler-in-the-ecommerce-plan/#comment-216), could we update the copy in the tooltip to make it more clear to click on the "Save" button?

![image](https://user-images.githubusercontent.com/98944206/190656405-2384c9e4-91b0-4980-a2c9-46a66d93103e.png)

**Copy:**
Add your store location details to help us configure shipping, taxes, currency and more in a fully automated way. Once done, click on the “Save’ button at the end of the form.
