### ISSUE TITLE
Task List: Add Products Task - Add products

### ISSUE THREAD

**Issue by chihsuan** [woothemes/woocommerce#32634]
**Description:** 
We reviewed the Add products page and built upon the Start with a template idea that performed well in the [previous testing](https://github.com/woocommerce/woocommerce-admin/issues/5296). 

We'd like to try out two different layouts: 

1. **Card layout**: is based on showing multiple cards in a grid.

![Card Layout](https://user-images.githubusercontent.com/98944206/156599140-5fcbdf97-430c-4dc7-80f6-15bf5174b331.gif)

2. **Stack layout**: the product types are vertically stacked. 

![Stack Layout](https://user-images.githubusercontent.com/98944206/156599341-f2b9d0eb-374a-446f-9d30-dcd8a25f052f.gif)

**Design overview:**

- cJQeyyhx9PraQrY3YAtCGM-fi-364%3A42405
- cJQeyyhx9PraQrY3YAtCGM-fi

**Acceptance criteria:**

- [x] This page is visible to users that just started their business or skipped the Profiler. If they declared to sell somewhere else, they're addressed to a different screen ([Import products](https://github.com/woocommerce/woocommerce-admin/issues/8407)). (https://github.com/woocommerce/woocommerce/pull/32789)
- [ ] The visible product types depend on what the user declared during the signup (step 3 - Product types - What type of products will be listed?). The other ones are collapsed. 
The following are all the possible configurations:

> Selected (signup): Physical products
> Surfaced (add product page): Physical product, Variable product, Grouped product

> Selected (signup): Physical products, Subscriptions
> Surfaced (add product page): Physical product, Subscription product

> Selected (signup): Physical products, Downloads
> Surfaced (add product page): Physical product, Digital product

> Selected (signup): Physical products, Downloads, Subscriptions
> Surfaced (add product page): Physical product, Digital product, Subscription product

> Selected: Downloads
> Surfaced: Digital product

> Selected: Downloads, Subscriptions
> Surfaced: Digital product, Subscription product

> Selected: Subscriptions
> Surfaced: Subscription product

- [ ] Includes new icons and new copy.
- [ ] Includes a 1.5 px `Gutenberg-blue` border when components are hovered (instead of grey background).
- [ ] Provide a toggle flag to display card or stack layout for  layout experiment 

**Event tracking:**
- https://github.com/woocommerce/woocommerce/issues/32633

**Comment by adrianduffell** [comment]
It looks like this would need to add two new templates:

* Grouped product
* External product

**Comment by chihsuan** [comment]
>  The visible product types depend on what the user declared during the signup (step 3 - Product types - What type of products will be listed?). The other ones are collapsed.

@verofasulo Just wanted to confirm what should we display if a user skips the onboarding wizard?

**Comment by verofasulo** [comment]
> Just wanted to confirm what should we display if a user skips the onboarding wizard?

@chihsuan please go with the first option: Physical product, Variable product, Grouped product.

Thank you :)
