### ISSUE TITLE
[WC 6.5 beta1] Completed task list items are not marked as completed when "Pinterest for WooCommerce" and "WooCommerce Payments" were installed and activated

### ISSUE THREAD

**Issue by rodelgc** [woothemes/woocommerce#32702]
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

In the onboarding wizard, when you choose to install "Pinterest for WooCommerce" and "WooCommerce Payments", the "Store details" task list item will not be marked as completed even though you did. This happens across all other items that you've already completed.
<img width="705" alt="Screen Shot 2022-04-20 at 9 32 03 PM" src="https://user-images.githubusercontent.com/4509348/164242075-af291941-0d80-46b7-b794-1a6b7c53528a.png">

Link to internal discussion: pb22l9-1cO-p2#comment-1202

### Expected behavior

Completed tasks are marked as completed.

### Actual behavior

Completed tasks were not marked as completed.

### Steps to reproduce

1. Install WooCommerce 6.5 (currently in beta)
2. Complete the onboarding wizard. Make sure to install WC Pay and Pinterest as suggested in the "Business Details" step.
3. Notice that the "Store details" task isn't marked as completed.
4. Try to complete the other tasks like "Add my products". Notice that they too will not appear as completed.

### WordPress Environment

WC 6.5 beta1

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**Comment by pmcpinto** [comment]
@becdetat which team should fix this?

**Comment by 12csw1** [comment]
Should this issue be labeled as priority: high?

We are doing research about “Issue Priority Prediction". We have developed a tool to automatically label the priority of an issue. The basic idea is to employ Bert model to encode the textual and code descriptions of the issue, and incorporate the issue’s attributes in the model, then apply multi-task learning to facilitate other information boosting the prediction performance. 
 We have conducted experiments on four GitHub projects with 21700 issues, and results show that [79 accuracy]() can be achieved.

Our tool shows that this issue has a very large possibility to be labeled as priority: high 
Could you please tell us whether it should be labeled as priority: high?
And if you have any comments or suggestions with this tool, could you please tell us? 
Thank you so much.

**Comment by 12csw1** [comment]
Should this issue be labeled as priority: high?

We are doing research about “Issue Priority Prediction". We have developed a tool to automatically label the priority of an issue. The basic idea is to employ Bert model to encode the textual and code descriptions of the issue, and incorporate the issue’s attributes in the model, then apply multi-task learning to facilitate other information boosting the prediction performance.
We have conducted experiments on four GitHub projects with 21700 issues, and results show that 79 accuracy can be achieved.

Our tool shows that this issue has a very large possibility to be labeled as priority: high
Could you please tell us whether it should be labeled as priority: high?
And if you have any comments or suggestions with this tool, could you please tell us?
Thank you so much.

**Comment by becdetat** [comment]
@pmcpinto Ghidorah should handle this. @adrianduffell can you get someone to take a look?

@12csw1 I think this should be high priority, it looks like it could be a regression (bad) but it's in a high value area regardless.

**Comment by adrianduffell** [comment]
This is being fixed in PR #32704. It's related to the latest tasklist experiment.
