### ISSUE TITLE
[WC 6.5 beta1] Some copy and header images in task list experiment 1 are different from design

### ISSUE THREAD

**Issue by louwie17** [woothemes/woocommerce#32802]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

In the new task list experiment the copy and images for some of the tasks are slightly different. This was missed when initially updating the new task list design.
There is some more context in this thread: p1650896716380659/1650522879.606939-slack-C01CMSA1VHS

It be nice to get this cherry picked into 6.5, but it doesn't break any changes, it could have a slight affect on the experiment results.

See wireframe of Treatment 1 here: G9vi4e286yjdzyIdg8hBb1-fi-735%3A83647
**Note**
Don't include the header for the Store Details task, this is done as part of https://github.com/woocommerce/woocommerce/issues/32760 

### Expected behavior

- Copy and header illustrations should match that of the wireframes (note: some tasks might not require any updates)

Design:  G9vi4e286yjdzyIdg8hBb1-fi-735%3A83647

### Steps to reproduce

1. Install the latest of `trunk`
2. Enable usage tracking through finishing the onboarding wizard
3. Visit Tools > WCA Test Helper > Experiments and enable woocommerce_tasklist_setup_experiment_1_2022_04
4. Visit the home screen and step through the task list finishing each task, notice how the header and copy for each task is unique, but slightly different from that in the designs (linked above).

### WordPress Environment

WooCommerce 6.5 Beta 1

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.
