### ISSUE TITLE
Task list: Set up marketing tools

### ISSUE THREAD

**Issue by verofasulo** [woothemes/woocommerce#32924]
**Description**

About 44% of users who visit the marketing task install one of the extensions or click “Manage” to proceed and finish the setup. Establishing an online marketing strategy/presence is a key element of almost any successful business. So why are we not seeing 60-70% of users showing the intent to install or complete the setup of the extensions we suggest? 

One hypothesis is that we can improve at providing more context about the importance of setting up marketing channels to acquire the first users and improve the current flows to make the experience smoother.

**Improve the "Set up marketing tools" page**

We’d like to test three variants and measure the impact. The only difference between the three variants is the header. All the other sections are common. 

**1. V1: Content-based**

Hypothesis to be tested: users want to have more context about the importance of setting up marketing tools by briefly going through the most valuable points. 

![image](https://user-images.githubusercontent.com/98944206/167366631-281b12ec-7926-4ef4-8bdb-fa2bb70b7fae.png)

**2. V2: Visual-based**

Hypothesis to be tested: users want to have more context still not being overwhelmed with too much content. A clear headline and a more descriptive subheadline are sufficient to reach the purpose. 

![image](https://user-images.githubusercontent.com/98944206/167366698-cfc880f1-16ee-4a31-bfaa-fb795190d0b7.png)

**3. V3: Hybrid V1+V2**

Hypothesis to be tested: users want to be informed and read the important information in a compact form along with nice visual assets. 

![image](https://user-images.githubusercontent.com/98944206/167366765-2e578705-ea1b-403a-b42b-2b2d821b8cb5.png)

**Design overview**
cJQeyyhx9PraQrY3YAtCGM-fi-1426%3A153376

**Acceptance criteria**

- [ ] When the user clicks on the marketing task on the home page, they get directed to the marketing page. 
- [ ] Use the following styles and labels for the CTAs:

![image](https://user-images.githubusercontent.com/98944206/167369992-03961bda-782e-492c-bb2f-b8c3f61f22b2.png)

- [ ] When the user clicks on the link "reviewing this checklist", they get directed to the Google Merchant page: https://support.google.com/merchants/answer/6363310
- [ ] When the user clicks on "Explore more marketing tools", they get directed to WooCommerce > Extensions with the marketing pill active (to filter only marketing extensions)
- [ ] Implement and test the three different headers (content-based, visual-based, and hybrid) vs. the control group (current design).
- [ ] When the extension is installed and set up, move it to the bottom of the section and add a feedback label in place of the description. Please refer to the following design (Google Listings and Ads installed and set up):

![image](https://user-images.githubusercontent.com/98944206/167373697-2b5153c9-809f-41b5-acde-192b0a6e81e1.png)

**Event tracking**

To be assessed by the team

**Comment by masteradhoc** [comment]
@verofasulo why is there currently no way of skipping this page? not every shop needs one of the proposed marketing tools.

**Comment by verofasulo** [comment]
Hey @masteradhoc 

> why is there currently no way of skipping this page? not every shop needs one of the proposed marketing tools.

It's actually something we designed and ready to be implemented: https://github.com/woocommerce/woocommerce/issues/34077

**Comment by timmy5685** [comment]
Hi @verofasulo - The specific onboarding task surface named in the issue no longer exists in the same form on trunk.

If there are any remaining problems, they should be re-filed against the current marketing task flow instead.

Thanks!
