### ISSUE TITLE
Task list: Set up marketing tools - Optimizing flows

### ISSUE THREAD

**Issue by verofasulo** [woothemes/woocommerce#32921]
**Description**

About 44% of users who visit the marketing task install one of the extensions or click “Manage” to proceed and finish the setup. Establishing an online marketing strategy/presence is a key element of almost any successful business. So why are we not seeing 60-70% of users showing the intent to install or complete the setup of the extensions we suggest? 

One hypothesis is that we can improve at providing more context about the importance of setting up marketing channels to acquire the first users and improve the current flows to make the experience smoother.

**Improve the current flows**

**1. Installing an extension**

Current design: when the user clicks on “Get started” to install a new extension on the “Set up marketing tools” page, they get directed back to the home page with the feedback “Plugin successfully activated” in the snackbar. To start setting up the extension, they have to click again on the marketing task and keep going with the flow. 

![image](https://user-images.githubusercontent.com/98944206/167365689-e03832a3-2ada-43fe-8e65-04c640f8c2d2.png)

Proposed design: when the user clicks on “Get started” to install a new extension on the “Set up marketing tools” page, the extension is installed and they get directed to the setup flow.

![image](https://user-images.githubusercontent.com/98944206/167365635-401ba564-5afd-42b4-b279-97799f53cd6a.png)

**2. Logic behind marking the task as completed**

Current design: when the user clicks on “Get started” to install a new extension on the “Set up marketing tools” page and gets directed back to the home page, the task is marked as done.

Proposed design: the task is marked as done once the user sets up one marketing tool. Please refer to the flow charts above.

**3. Google Listings & Ads**

Current design: Google Listings and Ads follows a particular flow. When the user clicks on the cta to start the setup, they are directed to Marketing > Google Listings and Ads. 

Proposed design: users are not directed to Marketing > Google Listings and Ads, but directly to the setup flow. Please refer to the flow charts above.

**Design overview**
cJQeyyhx9PraQrY3YAtCGM-fi-1426%3A153376

**Acceptance criteria**

- [ ] When the user clicks on “Get started” to install a new extension on the “Set up marketing tools” page, the extension is installed and they get directed to the extension setup flow.
- [ ] The task is marked as done once the user sets up one marketing tool.
- [ ] When the user wants to set up Google Listings and Ads, They are not directed to Marketing > Google Listings and Ads, but directly to the setup flow.

**Event tracking**

To be assessed by the team

**Comment by timmy5685** [comment]
Hi @verofasulo - closing this out as won't-fix as the referenced onboarding flow was replaced.
