### ISSUE TITLE
Order refund items might delete meta data from original line item

### ISSUE THREAD

**Issue by mpskovvang** [woothemes/woocommerce#33545]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Added order item meta data might get lost when refunding the item. It seems the new refunded item copies the original meta data (inclusive meta ID).

Therefore, adding the same meta key on the refunded item will delete the meta key from the original item.

### Expected behavior

The meta data should be kept on the original/copied order item.

The refunded item should copy the meta data without the `meta_id` value.

### Actual behavior

The meta data is deleted from the original order item when the same meta key is added to the refunded item with uniqueness.

### Steps to reproduce

1. Add meta data to new order items:
```PHP
add_action('woocommerce_new_order_item', function ($item_id, $item) {
    $item->add_meta_data('foo', 'bar', true); // or update_meta_data
    $item->save_meta_data();
}, 10, 2);
```

2. Create a new order from admin

3. Add a product

4. Set order status to `Completed` and save.

5. Notice the `foo` meta data at the order line. The meta is attached with the `order_item_id` of the line in DB.

6. Refund the item

7. The `foo` meta data is deleted from the original item and saved to the refunded item. Verify in DB.

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://friluft.dk.local
Site address (URL): https://friluft.dk.local
WC Version: 6.6.1
REST API Version: ✔ 6.6.1
WC Blocks Version: ✔ 7.6.2
Action Scheduler Version: ✔ 3.4.0
Log Directory Writable: ✔
WP Version: ❌ 5.9.1 - Der findes en nyere version af WordPress (6.0)
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: da_DK
External object cache: ✔

### Server Environment ###

Server Info: Apache/2.4.53 (Debian)
PHP Version: 8.0.18
PHP Post Max Size: 64 MB
PHP Time Limit: 600
PHP Max Input Vars: 1000
cURL Version: 7.74.0
OpenSSL/1.1.1n

SUHOSIN Installed: –
MySQL Version: 5.7.25
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 6.1.1
WC Database Prefix: wp_
Total databasestørrelse: 23.01MB
Database datastørrelse: 19.71MB
Database indexstørrelse: 3.30MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.14MB + Index: 0.16MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.06MB + Index: 0.13MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_aioseo_cache: Data: 0.09MB + Index: 0.03MB + Engine InnoDB
wp_aioseo_notifications: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_aioseo_posts: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_aioseo_terms: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.09MB + Index: 0.09MB + Engine InnoDB
wp_iconic_was_fees: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_iconic_woo_linked_variations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_litespeed_url: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_litespeed_url_file: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_mailchimp_carts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailchimp_jobs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 4.02MB + Index: 0.13MB + Engine InnoDB
wp_postmeta: Data: 8.14MB + Index: 0.73MB + Engine InnoDB
wp_posts: Data: 4.16MB + Index: 0.16MB + Engine InnoDB
wp_termmeta: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.03MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_gpf_render_cache: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_se_queue: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_se_settings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_bis_activity: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_bis_notifications: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_woocommerce_bis_notificationsmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_gpf_google_taxonomy: Data: 1.52MB + Index: 0.00MB + Engine InnoDB
wp_yoast_indexable: Data: 0.19MB + Index: 0.22MB + Engine InnoDB
wp_yoast_indexable_hierarchy: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yoast_primary_term: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_yoast_seo_links: Data: 0.02MB + Index: 0.03MB + Engine InnoDB

### Post Type Counts ###

acf-field: 25
acf-field-group: 2
attachment: 71
cpt_iconic_wlv: 2
nav_menu_item: 26
oembed_cache: 13
page: 12
post: 4
postman_sent_mail: 250
product: 14
product_variation: 21
revision: 70
shop_coupon: 2
shop_order: 93
shop_order_refund: 17
size-guide: 1
wp_global_styles: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ❌Fejlmeddelelser skal ikke vises til besøgende.

### Active Plugins (12) ###

WooCommerce Linked Variations by Iconic: af Iconic  – 1.3.0
Advanced Custom Fields PRO: af Delicious Brains – 5.12
EAN betalings-gateway til WooCommerce: af Plugins.dk – 1.0.8
LiteSpeed Cache: af LiteSpeed Technologies – 4.5.0.1
Permalink Manager Pro: af Maciej Bis – 2.2.9.9
Post SMTP: af Yehuda Hassine – 2.0.23
WooCommerce Back In Stock Notifications: af WooCommerce – 1.3.1
Pixel Manager for WooCommerce: af SweetCode – 1.17.7
WooCommerce: af Automattic – 6.6.1
Yoast SEO: af Team Yoast – 18.3
WP Redis: af Pantheon
Josh Koenig
Matthew Boynes
Daniel Bachhuber
Alley Interactive – 1.1.4

Yoast SEO: WooCommerce: af Team Yoast – 13.9

### Inactive Plugins (9) ###

All in One SEO Pro: af All in One SEO Team – 4.1.8
Klaviyo: af Klaviyo
Inc. – 3.0.1

Loco Translate: af Tim Whitlock – 2.5.8
MonsterInsights - eCommerce Addon: af MonsterInsights Team – 7.3.9
MonsterInsights Pro: af MonsterInsights – 7.14.0
Partner-ads Woocommerce tracking and feed: af Partner-ads – 1.16.0
Query Monitor: af John Blackbourn – 3.8.2
WooCommerce PensoPay: af PensoPay – 6.2.2
WooCommerce Profitmetrics: af Profitmetrics – 2.20

### Dropin Plugins (2) ###

advanced-cache.php: advanced-cache.php
object-cache.php: object-cache.php

### Settings ###

API Enabled: –
Force SSL: –
Currency: DKK (kr)
Currency Position: right_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-filtered (exclude-from-filtered)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: –

### WC Pages ###

Shop basisside: #6 - /shop/
Kurv: #7 - /cart/
Checkout: #8 - /checkout/
Min konto: #9 - /my-account/
Vilkår og betingelser: #296 - /handelsbetingelser/

### Theme ###

Name: Nordlys
Version: 1.1.67
Author URL: https://www.katoni.dk/
Child Theme: ❌ – Hvis du redigerer WooCommerce i et hovedtema
som du ikke selv har udviklet
anbefaler vi
at du anvender et undertema (child theme). Se: Hvordan du opretter et undertema

WooCommerce Support: ✔

### Templates ###

Overrides: nordlys/woocommerce/archive-product.php
nordlys/woocommerce/emails/customer-note.php
nordlys/woocommerce/emails/plain/customer-note.php
nordlys/woocommerce/global/wrapper-end.php version - er udgået. Kerneversionen er 3.3.0
nordlys/woocommerce/global/wrapper-start.php version - er udgået. Kerneversionen er 3.3.0
nordlys/woocommerce/loop/pagination.php
nordlys/woocommerce/single-product/meta.php
nordlys/woocommerce/single-product/price.php
nordlys/woocommerce/single-product/product-image.php version - er udgået. Kerneversionen er 3.5.1

Outdated Templates: ❌
					
					
						Lær hvordan man opdaterer

### Back In Stock ###

Database Version: 1.3.1
Loopback Test: ❌ Loopback test failed.

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
experimental-products-task
experimental-import-products-task
experimental-fashion-sample-products
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
wc-pay-promotion
wc-pay-welcome-page
wc-pay-subscriptions-page

Disabled Features: minified-js
settings

Daily Cron: ✔ Next scheduled: 2022-06-21 18:28:03 +00:00
Options: ✔
Notes: 81
Onboarding: completed

### Action Scheduler ###

Gennemført: 85
Oldest: 2022-03-18 18:57:05 +0000
Newest: 2022-06-21 08:02:59 +0000

Mislykket: 1
Oldest: 2022-02-27 14:51:39 +0000
Newest: 2022-02-27 14:51:39 +0000

Igangværende: 67
Oldest: -0001-11-30 00:00:00 +0000
Newest: 2022-06-28 08:02:58 +0000

### Status report information ###

Generated at: 2022-06-21 19:25:48 +00:00
`

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by vedanshujain** [comment]
Thanks for the report, marking this as `bug`. Also adding a `low-priority` label as compared to other high priority bugs already opened in the repo.

**Comment by flakas** [comment]
Hi @mpskovvang - thanks for the report.

I know this has been open for a very long time, and I appreciate your patience. We're currently going through some older WooCommerce issues, identifying what still needs fixing, and tidying up what's already fixed or out of scope.

I've taken a look and marked this ready for the engineering team to pick up.

What I'm seeing: The refund creation path still instantiates refunded line items from the original item object, and order-item cloning still preserves meta IDs. That leaves the issue's described risk intact: copied refund item meta can carry original meta identifiers into the refunded item path.
