### ISSUE TITLE
Proposed A/B Test: Task list improvements

### ISSUE THREAD

**Issue by verofasulo** [woothemes/woocommerce#34077]
Test the effectiveness of the following design changes to improve the onboarding experience.

### 1st improvement

**Assumption**
The current approach is very good at highlighting the items on top of the list but it lacks connection with the tasks at the bottom.

**Design proposal** 
Move the tasks already performed at the bottom so that the header can be contextual to the item highlighted. The task featured in the header is always the first item in the list (apart from the use case where the user clicks on another task on purpose).

**Expected results**
Increase conversion rate for those tasks that are not listed at the first 3 positions. 

### 2nd improvement

**Assumption**
Not all the tasks are meaningful to all the users. They want to have the possibility to dismiss the ones that don’t match their needs.

**Design proposal** 
Add the "Skip" button in the header to allow users to remove items that don’t match their needs.
When at least one step is skipped, add the “Restore skipped steps” option in the kebab menu.

**Expected results**
Some tasks will be skipped. Track user’s behavior and gather learning.

![image](https://user-images.githubusercontent.com/98944206/181262226-c6760e20-a941-458e-8536-2063b9078cc4.png)

![image](https://user-images.githubusercontent.com/98944206/181262297-97e71fc0-ef59-4273-86fd-30852fe542c0.png)

**Design overview**
cJQeyyhx9PraQrY3YAtCGM-fi-3132%3A328591

**Acceptance criteria**

- [ ] Remove numbers from incomplete tasks and use an empty circle with border in `gutenberg-gray-400 `
- [ ] When a task is completed, move it down to the bottom of the task list
- [ ] Add the "Skip" button in the header
- [ ] When at least one step is skipped, add the “Restore skipped steps” option in the kebab menu.

**Comment by verofasulo** [comment]
cc @SamratBiswas1

**Comment by SamratBiswas1** [comment]
I would A/B test the following way:
- 2 variants : 1st variant with 1st improvement and 2nd variant with 1st and 2nd improvement
- Metric : 3 task completion rate in Wk 1. Keep it simple.

**Comment by verofasulo** [comment]
> Metric : 3 task completion rate in Wk 1. Keep it simple.

In addition, I'd like to track:

- % of skipped tasks and which ones
- Task click on control and variant - For each task. Would like to see if there's any difference in clicking on tasks that are now at the bottom of the list.
