### ISSUE TITLE
[Inventory] Quantity tracking

### ISSUE THREAD

**Issue by jarekmorawski** [woothemes/woocommerce#34387]
**User story**

As a merchant,
I want to control my product inventory
So that I can keep up with the demand

As a merchant,
I want to manage my inventory
So that my customers won’t purchase products that I don’t have at hand

**Design**
5sAIeTRd9Yp7nSCT33BAWz-fi-6498%3A284871

**Acceptance criteria**

- [ ] When enabled, users see the `Current quantity` and `Email me when the quantity reaches` fields.
- [ ] The toggle is enabled by default if the `Enable stock management` checkbox in `WooCommerce > Settings > Products > Inventory` is checked.
- [ ] The tooltip reads: `Enter how many items you can sell to customers. We’ll automatically reduce this number after each purchase. Check out the **Advanced** section below for more options.`
- [ ] The `Current quantity` field only accepts numbers (no character limit).
- [ ] The `Current quantity` field displays number field controls on hover (arrow up and arrow down).
- [ ] The `Email me when quantity reaches` field only accepts numbers (no character limit). By default, it uses the store value (it’s placed in the placeholder).
- [ ] When the user types anything into the `Email me when quantity reaches` field, we override the store value and use the new value instead.
- [ ] The help text under the `Email me when quantity reaches` field redirects to `WooCommerce > Settings > Products > Inventory`. The link opens in a new tab.
