### ISSUE TITLE
[Epic]: Shipping Product management MVP 1.0

### ISSUE THREAD

**Issue by AnnaMag** [woothemes/woocommerce#34749]
- [x] https://github.com/woocommerce/woocommerce/issues/34328

- [x] https://github.com/woocommerce/woocommerce/issues/34329

- [x] https://github.com/woocommerce/woocommerce/issues/34657

- [x] https://github.com/woocommerce/woocommerce/issues/35036

- [x] https://github.com/woocommerce/woocommerce/issues/35037
