### ISSUE TITLE
[Epic] Images Product management MVP 1.0

### ISSUE THREAD

**Issue by AnnaMag** [woothemes/woocommerce#34759]
- [x] https://github.com/woocommerce/mothra-private/issues/39
- [ ] https://github.com/woocommerce/mothra-private/issues/40
- [ ] https://github.com/woocommerce/mothra-private/issues/41
