### ISSUE TITLE
User meta select field without class is breaking in admin-panel

### ISSUE THREAD

**Issue by sudipto-shakhari** [woothemes/woocommerce#34779]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

I have created extra fields on customer billing information. If I create a select field without any class in the field parameters, it throws a notice in the user edit panel. It throws a notice stating that:  "Undeifned index: class in /wp-content/woocommerce/includes/class-wc-admin-profile.php on line 179". 
https://prnt.sc/wdoduiCmrJkc

### Expected behavior

The class should be checked before assigning the class and if no class is found then the class should not be given on the class parameters.
https://prnt.sc/PI5wZjGOslLW

### Actual behavior

When the select type field is printed then the class is not validated, for that reason, when I create select options using the filter `woocommerce_customer_meta_fields`, it breaks the user edit page in the admin. 

### Steps to reproduce

1. Fire the filter to create the customer meta fields :

![image](https://user-images.githubusercontent.com/937723/193300272-0bcf2569-b66d-4b22-bea5-4722c6842d35.png)

2. Filter callback functions:

![image](https://user-images.githubusercontent.com/937723/193300370-7812f76d-33dc-43da-b4e7-995f31056917.png)

3. Add the select field and return the fields:

![image](https://user-images.githubusercontent.com/937723/193300442-6ba2638f-a40c-499e-bb2a-a9967a5be19c.png)

4. When checking the fields on the user edit options notice given:

![image](https://user-images.githubusercontent.com/937723/193300493-fd6ce382-1495-4a51-9bd8-050bcfc092bf.png)

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): http://vrbn-api.test
Site address (URL): http://vrbn-api.test
WC Version: 6.9.3
REST API Version: ✔ 6.9.3
WC Blocks Version: ✔ 8.3.2
Action Scheduler Version: ✔ 3.4.0
Log Directory Writable: ✔
WP Version: 6.0.2
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.23.1
PHP Version: 7.4.30
PHP Post Max Size: 512 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.84.0
(SecureTransport) OpenSSL/1.1.1q

SUHOSIN Installed: –
MySQL Version: 8.0.30
Max Upload Size: 512 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 6.9.3
WC Database Prefix: wp_
Total Database Size: 5.16MB
Database Data Size: 3.47MB
Database Index Size: 1.69MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.09MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 2.05MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 0.25MB + Index: 0.14MB + Engine InnoDB
wp_posts: Data: 0.08MB + Index: 0.06MB + Engine InnoDB
wp_serial_numbers: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_serial_numbers_activations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wpml_mails: Data: 0.02MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

attachment: 74
page: 7
post: 3
product: 55
product_variation: 4
revision: 1
shop_order: 3
wp_global_styles: 1

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (6) ###

JSON Basic Authentication: by WordPress API Team – 0.1
User Switching: by John Blackbourn & contributors – 1.7.0
Vrbn API: by Selise – 1.0.0
WooCommerce Stripe Gateway: by WooCommerce – 6.7.0
WooCommerce: by Automattic – 6.9.3
WP Mail Logging: by Wysija – 1.10.4

### Inactive Plugins (6) ###

Ever Accounting: by everaccounting – 1.1.2
Payment Plugins for Stripe WooCommerce: by Payment Plugins
support@paymentplugins.com – 3.3.26

WC Min Max Quantities: by pluginever – 1.1.1
weDevs Academy: by Tareq Hasan – 1.0
WooCommerce PayPal Payments: by WooCommerce – 1.9.3
WooCommerce Serial Numbers: by pluginever – 1.2.10

### Settings ###

API Enabled: –
Force SSL: –
Currency: BDT (৳ )
Currency Position: right
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: assets (assets)
building (building)
bundle (bundle)
external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔

### WC Pages ###

Shop base: #6 - /shop/
Cart: #7 - /cart/
Checkout: #8 - /checkout/
My account: #9 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: vrbn eshop
Version: 1.0.0
Author URL: https://selise.ch
Child Theme: ✔
Parent Theme Name: vrbn
Parent Theme Version: 1.0.0
Parent Theme Author URL: https://selise.ch
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
experimental-products-task
experimental-import-products-task
experimental-fashion-sample-products
experimental-product-tour
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
settings

Daily Cron: ✔ Next scheduled: 2022-09-23 10:11:36 +00:00
Options: ✔
Notes: 53
Onboarding: completed

### Action Scheduler ###

Complete: 157
Oldest: 2022-09-04 06:35:35 +0000
Newest: 2022-09-22 10:13:00 +0000

Pending: 2
Oldest: 2022-09-23 10:00:22 +0000
Newest: 2022-09-23 10:00:22 +0000

### Status report information ###

Generated at: 2022-09-22 11:06:52 +00:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by Konamiman** [comment]
Hi @sudipto-shakhari, thanks for your report. We've been able to reproduce the issue so I'll label this as a bug.
