### ISSUE TITLE
[COT] TypeError exception (PHP >= 8.0) for object meta-values

### ISSUE THREAD

**Issue by DavidAnderson684** [woothemes/woocommerce#34913]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

If any meta value that is going to be printed in the "Custom Fields" section of an order screen (/wp-admin/admin.php?page=wc-orders&id=(ID)&action=edit) is not a string, then a TypeError exception (and crash, being uncaught) will occur because the variable is passed to `htmlspecialchars()` as-is, without having been turned back to a string.

N.B. https://woocommerce.github.io/code-reference/classes/WC-Data.html#method_update_meta_data shows that it is valid to store non-strings as meta-values.

### Actual behavior

```
PHP Fatal error:  Uncaught TypeError: htmlspecialchars(): Argument #1 ($string) must be of type string, stdClass given in wp-includes/formatting.php:4604
Stack trace:
#0 wp-includes/formatting.php(4604): htmlspecialchars()
#1 wp-admin/includes/template.php(643): esc_textarea()
#2 wp-admin/includes/template.php(600): _list_meta_row()
#3 wp-content/plugins/woocommerce/src/Internal/Admin/Orders/MetaBoxes/CustomMetaBox.php(74): list_meta()
#4 wp-content/plugins/woocommerce/src/Internal/Admin/Orders/MetaBoxes/CustomMetaBox.php(60): Automattic\WooCommerce\Internal\Admin\Orders\MetaBoxes\CustomMetaBox->render_custom_meta_form()
#5 wp-content/plugins/woocommerce/src/Internal/Admin/Orders/Edit.php(172): Automattic\WooCommerce\Internal\Admin\Orders\MetaBoxes\CustomMetaBox->output()
#6 wp-admin/includes/template.php(1402): Automattic\WooCommerce\Internal\Admin\Orders\Edit->render_custom_meta_box()
#7 wp-content/plugins/woocommerce/src/Internal/Admin/Orders/Edit.php(251): do_meta_boxes()
#8 wp-content/plugins/woocommerce/src/Internal/Admin/Orders/Edit.php(180): Automattic\WooCommerce\Internal\Admin\Orders\Edit->render_meta_boxes()
#9 wp-content/plugins/woocommerce/src/Internal/Admin/Orders/PageController.php(163): Automattic\WooCommerce\Internal\Admin\Orders\Edit->display()
#10 wp-includes/class-wp-hook.php(307): Automattic\WooCommerce\Internal\Admin\Orders\PageController->output()
#11 wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters()
#12 wp-includes/plugin.php(476): WP_Hook->do_action()
#13 wp-admin/admin.php(259): do_action()
#14 {main}
  thrown in wp-includes/formatting.php on line 4604
```

### Steps to reproduce

In this example, order ID 1234 is an existing order.

```
# php80 -a
> require 'wp-load.php';
> $order = wc_get_order(1234); // Some existing order
> $thing = new stdClass;
> $thing->value = 'anything';
> $order->update_meta_data('any_key', $thing);
> $order->save();
> exit;
```

Then visit the order page - /wp-admin/admin.php?page=wc-orders&id=1234&action=edit

### WordPress Environment

WC: 7.0.0-hpos.dev.4
WP: 6.0.2
PHP: 8.0.23

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.
