### ISSUE TITLE
[Epic][Downloads] File upload

### ISSUE THREAD

**Issue by jarekmorawski** [woothemes/woocommerce#35141]
**Job story**

- When I put my digital product or service on sale on my website,
- I want to upload the source files
- So the customers can easily access them after purchase

**Design**

AkVNGImLgSqCObTQ3idVn7-fi-7001_308054

**Acceptance criteria**

- [x] The Downloads form section is shown after the Images section under the General tab. The section tooltip reads: `Add any files you'd like to make available for the customer to download after purchasing, such as instructions or warranty info.` 
- [x] When there are no files, we show an empty state with a copy that reads: `Supported file types: PNG, JPG, PDF, PPT, DOC, MP3, MP4, and more. View all.` "View all" links to: `https://codex.wordpress.org/Uploading_Files`.
- [x] The user can click anywhere on the empty to open the system file picker.
- [x] The user can click the Add new button to open a dropdown with available options.
- [x] Upload -> Opens the system file picker
- [x] Media library -> Opens the WordPress media library
- [x] Insert from URL -> Opens a 2nd-level input field where the user can paste the link. Clicking the arrow button or pressing Enter will automatically upload the file from the source.
- [x] The user can select multiple files to upload (both in the system file picker and the Library modal).
- [x] If a file can’t be upload, we show a snackbar message in the bottom left corner of the screen. If the file type isn't accepted, we show a message that reads: `Sorry, [file name] is not supported.`. In any other case, we show a message that reads: `We couldn't upload [file name]. Please try.`
