### ISSUE TITLE
[Epic] Variations list behavior

### ISSUE THREAD

**Issue by pmcpinto** [woothemes/woocommerce#35660]
**Description:** users can easily access one or more variations through a simple and intuitive list.

**Issues**

* [x] https://github.com/woocommerce/woocommerce/issues/35788
* [x] https://github.com/woocommerce/woocommerce/issues/35790
* [x] https://github.com/woocommerce/woocommerce/issues/35789
* [x] https://github.com/woocommerce/woocommerce/issues/35791
* [x] https://github.com/woocommerce/woocommerce/issues/35792

**Acceptance criteria:**

- [x] The list should include a row for each variation, displaying the variation options, price, inventory (if enabled): AkVNGImLgSqCObTQ3idVn7-fi-1639_214803
- [x] The list should include pagination, a checkbox to select one or more variations, option-base filters, and quick actions. All the details are in the variations list anatomy frame: AkVNGImLgSqCObTQ3idVn7-fi-1639_220087
- [x] The card has a fixed height, so it doesn’t jump when we don’t have enough items to fill the space.
- [x] Each variation has a visibility indicator that should work as the "enabled" option in the current experience: AkVNGImLgSqCObTQ3idVn7-fi-1639_220087
- [ ] ~~Quantity status indicator: green when >=10, yellow when <5, red when 2, 1 or 0: AkVNGImLgSqCObTQ3idVn7-fi-1639_217612~~
- [x] We show the pagination when the number of variations exceeds 5: AkVNGImLgSqCObTQ3idVn7-fi-1639_220087
- [x] Users can filter the list by one or multiple variations and several options: AkVNGImLgSqCObTQ3idVn7-fi-1640_207898
- [x] Clicking the checkbox in the intermediate state selects all. Clicking it again clears the selection: AkVNGImLgSqCObTQ3idVn7-fi-1640_208858
- [x] We disable the ‘Select all’ button when all variations are selected: AkVNGImLgSqCObTQ3idVn7-fi-1640_214140

The quick actions acceptance criteria will be included in a separate issue.

**Event tracking:**
We should track all the user actions

**Comment by pmcpinto** [comment]
Acceptance criteria reviewed and updated with the latest designs.

The Issues section should be updated by the team

**Comment by jarekmorawski** [comment]
I know we've already done a lot of work on variations in the original new form. I compared that and the new one to see if we could reuse some code. Most of the experience is the same. Here are the key differences.

**Changes**

- The tab name is `Variations` instead of `Options`
- There's an additional text in the empty screen when there are no options or variations
- New illustrations for empty and error states
- `Options` are now called `Variation options`
- There are some minor copy and styling differences in the Add variation options modal
- For attributes that are already used, we show a tooltip instead of a popover
- Variation list pagination row looks different
- We no longer have the turn visibility on/off button in the variations list
- We no longer have drag-to-reorder action on the variations list
- Stock indications look different
- We no longer disable pricing, inventory, and shipping fields for a parent product
- The notice we show in these tabs has different styling based on #38443


**New stuff**

- Local attributes no longer have the ( i ) icon. Instead, they have the filters icon
- We also show the visibility icons in the variations and options lists
- We no longer have the individual variation editing screen (yet). Instead, we have quick actions and contextual editing options hidden in a kebab menu
- We added search and confirmation button for the opened filters
- The default value settings in the edit option modal is now a checkbox, not a dropdown

**Comment by AnnaMag** [comment]
TO-DO: turn AC into issues and update the list included in the body of the issue.

**Comment by mdperez86** [comment]
@pmcpinto @AnnaMag this is very confusing `Quantity status indicator: green when >=10, yellow when <5, red when 2, 1 or 0`

Should the following example be the right one?
`stock` < 5 then `red`
`stock` >= 5 and < 10 then `yellow`
`stock` >= 10 then `green`

And this is what we currently have implemented already
`stock` < 3 then `red`
`stock` >= 3 and < 10 then `yellow`
`stock` >= 10 then `green`

**Comment by AnnaMag** [comment]
@mdperez86 this was raised before [in the legacy issue](https://github.com/woocommerce/woocommerce/issues/35791#issuecomment-1332677823) and corrected as: 

Acceptance criteria:
The indicator should be green when the inventory is >= 10
The indicator should be yellow when the inventory is < 10 and > 2
The indicator should be red when the inventory is <= 2

**Comment by AnnaMag** [comment]
@pmcpinto 
given:

>And this is what we currently have implemented already
> stock < 3 then red
>stock >= 3 and < 10 then yellow
>stock >= 10 then green

should we consider leaving it as-is?

**Comment by pmcpinto** [comment]
We leave it as is, considering that the difference is minimal. We can revisit this once Jarek is back from AFK. Thanks
