### ISSUE TITLE
[Epic] Individual variations flow

### ISSUE THREAD

**Issue by pmcpinto** [woothemes/woocommerce#35661]
**Description:** users can easily manage each variation through a fully-fledged view for individual product variations.

**Issues**

* [x] [Add single product variation screen#35786](https://github.com/woocommerce/woocommerce/issues/35786)
* [x] [Add edit button to variations list items#35787](https://github.com/woocommerce/woocommerce/issues/35787)
* [x] [Add single product variation General section #35987](https://github.com/woocommerce/woocommerce/issues/35987)
* [x] [Add single product variation sections #35988](https://github.com/woocommerce/woocommerce/issues/35988)
* [x] [Product variations should inherit parent product properties #35989](https://github.com/woocommerce/woocommerce/issues/35989)
* [x] [Add product variation attributes to product header #35990](https://github.com/woocommerce/woocommerce/issues/35990)
* [x] [Add product variation navigation component #35991](https://github.com/woocommerce/woocommerce/issues/35991)
* [x] [Product variations should prompt for unsaved changes #35992](https://github.com/woocommerce/woocommerce/issues/35992)

**Acceptance criteria:**

- [ ] When the user clicks to edit an individual variation in the variations list, he'll be redirected to a view where he can edit the general, pricing, inventory, and shipping sections of the variation: BaoQ3PGPnhAiJCsJtxgej3-fi-102%3A10092&t=Jsh233onKmJpJYtN-0
- [ ] Each tab should include the following:
General: description, images, visibility
Pricing: regular price, sale price, scheduled sale, tax class
Inventory: SKU, manage stock, stock quantity, low stock threshold email, stock status, out of stock options, sold individually (the same options we have for the parent product)
Shipping: weight, dimensions, shipping class
Extensibility: variations support all extensions and features from the main product form.
- [ ] Each variation inherits data added in the main/master product. For example, if it has a description, users will see it added to each variation. They can edit it independently from the main/master product. Variations would also inherit images, but to keep the footprint low, we'd import them from the parent product instead of making copies.
- [ ] The name of the currently edited variation is added as the 3rd-level breadcrumb in the top bar: BaoQ3PGPnhAiJCsJtxgej3-fi-102%3A10092&t=Jsh233onKmJpJYtN-0
- [ ] We'll add a new element to the bottom of the page to allow users to easily navigate between variations. ‘Return to main product’ takes the user back to the main product editing UI. The arrows let them switch back and forth between variations (we always ask about unsaved changes while switching): BaoQ3PGPnhAiJCsJtxgej3-fi-102%3A10092&t=Jsh233onKmJpJYtN-0
- [ ] We should prompt the user to save changes when he tries to move away from the individual variation: BaoQ3PGPnhAiJCsJtxgej3-fi-102%3A18466&t=Jsh233onKmJpJYtN-0
- [ ] The preview button opens the regular product preview (with the variations added).

**Event tracking:**
TBD

**Comment by joshuatf** [comment]
@pmcpinto @jarekmorawski I've broken down most of these into smaller issues, but had a few quick questions/comments:

**Extensibility** - As we previously touched on, I think we should spend more time diving into how we want to handle extensibility before tackling here.

**Shipping** - The designs include a toggle ‘This variation requires shipping or pickup’ and “Shipping fee” radio control.  Since these don’t yet exist on the parent, is it okay to hold off on these for now or are they important for the variation work?

**Tax class** - Same question with regards to tax class.  This does not yet exist on the parent product.

<img width="342" alt="Screen Shot 2022-12-14 at 3 01 34 PM" src="https://user-images.githubusercontent.com/10561050/207734483-3bba3ea7-a91c-446f-8125-4319c2ce0df3.png">
<img width="363" alt="Screen Shot 2022-12-14 at 3 01 14 PM" src="https://user-images.githubusercontent.com/10561050/207734488-54937869-6159-4698-9248-94e7d41d9b04.png">

**Comment by jarekmorawski** [comment]
> As we previously touched on, I think we should spend more time diving into how we want to handle extensibility before tackling here.

Yes, it's worthy of a separate issue. We want to support extensibility in product variations in the same way as the "main" product. It is rather limited in the current interface.

> The designs include a toggle ‘This variation requires shipping or pickup’ and “Shipping fee” radio control. Since these don’t yet exist on the parent, is it okay to hold off on these for now or are they important for the variation work?

> Tax class - Same question with regards to tax class. This does not yet exist on the parent product.

No, we'll only support physical products at launch, so it's okay to come back to this once we introduce virtual and downloadable product types into the "main" product form.

cc @pmcpinto for confirmation.

**Comment by pmcpinto** [comment]
@joshuatf how long do you think it will take to implement these shipping and tax options on the parent product?

**Comment by pmcpinto** [comment]
@joshuatf here's the issue regarding the Tax options: #36164

**Comment by joshuatf** [comment]
Thanks, @pmcpinto!  Added an estimate on that issue.  Should be an easy addition.
