### ISSUE TITLE
EPIC: Quick actions flow

### ISSUE THREAD

**Issue by pmcpinto** [woothemes/woocommerce#35670]
**Description:** users can easily update any detail of one or more variations through the quick edit actions.

**Acceptance criteria:**
- [x] Introduce a quick actions dropdown in the variations list: AkVNGImLgSqCObTQ3idVn7-fi-1641_213260
- [x] This dropdown should include all the quick actions available in the current experience, organized by buckets: 
Pricing: AkVNGImLgSqCObTQ3idVn7-fi-1641_214278
Inventory: AkVNGImLgSqCObTQ3idVn7-fi-1641_215506
Shipping: AkVNGImLgSqCObTQ3idVn7-fi-1641_216594
Downloads (to be implemented when downloads are supported):AkVNGImLgSqCObTQ3idVn7-fi-1641_217634
- [x] After selecting one of the quick actions, users see a modal to add/update the value. We replicate the current behavior for all quick update features: AkVNGImLgSqCObTQ3idVn7-fi-1641_218670
- [x] After the update, we show a snackbar informing users that the variations were updated: AkVNGImLgSqCObTQ3idVn7-fi-1641_218705

**Event tracking:**
We should track all the quick actions behavior, including the modal to add/update values

**Comment by pmcpinto** [comment]
Acceptance criteria reviewed and updated with the new designs
