### ISSUE TITLE
 Multichannel Marketing Backend MVP: Changes to the core library

### ISSUE THREAD

**Issue by nima-karimi** [woothemes/woocommerce#35956]
**Prerequisites (mark completed items with an [x]):**
- [x] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [x] My issue is not a security issue, support request, bug report, enhancement, or feature request (Please use the link above if it is).

**Issue Description:**

This issue is part of the epic https://github.com/woocommerce/woocommerce/issues/34548.

As part of the multichannel marketing feature, we implemented a light framework/library in the core that other marketing extensions can use and give us access to their data through a unified method. This library was implemented in PR https://github.com/woocommerce/woocommerce/pull/35099 and is currently merged to the feature branch for MCM Backend ([feature/34548-multichannel-marketing-backend](https://github.com/woocommerce/woocommerce/tree/feature/34548-multichannel-marketing-backend))

After some discussion with @ecgan, I realized there should be a distinction between "marketing channels" and "marketing extensions". We also decided to keep the library open for third parties instead of limiting it to a predetermined list of extensions returned by the recommendations API (`GET https://woocommerce.com/wp-json/wccom/marketing-tab/1.2/recommendations.json`). More details in pe2C5g-zO-p2.

**Tasks**

- [ ] Remove the validation check before registering marketing channels, allowing any extension to register as a marketing channel.
- [ ] Fetch the "marketing extensions" list from the recommendations API and return them separately from the marketing channels. Note that the marketing extension properties like name and description should also come from the API; this includes their "manage" or "getting started" URL.
- [ ] Change the name of method `MarketingChannelInterface::get_error_no` to `get_error_count` (referrene: pe2C5g-zb-p2)
