### ISSUE TITLE
[Epic] Product Management extensibility add initial SlotFill support

### ISSUE THREAD

**Issue by louwie17** [woothemes/woocommerce#35952]
**Description:** 
Plugins can extend the new Product Management screen by the use of Slot fills.
This Epic will be part of phase 1, which will primarily focus on laying the ground work and setting it up for the Product Details section.

**Issues**
*to be created
* [ ] Create a WooFormFieldItem wrapper for Slot fills (#36014)
* [ ] Create a WooFormSectionItem wrapper for Slot fills (#36015)
* [ ] Replace product details section fields with Slot fill (#36016)
* [ ] Add WooFormSectionItem slot and add product details section using this slot (#36018)
* [ ] Clean up product details fields (name, category, feature, summary, description field) and move to `@woocommerce/components` package

**Acceptance criteria:**
- [ ] Product details fields name, category, etc... should be added using a SlotFill
- [ ] Plugins have the ability to add fields to the product details section by use of `WooFormFieldItem`
- [ ] Product details section should be added by the use of `WooFormSectionItem`
- [ ] name, category, feature, summary, description fields should be accessible through a JS package. 

**Event tracking:**
TBD

**Comment by pmcpinto** [comment]
@louwie17 should we close this issue?

**Comment by louwie17** [comment]
> @louwie17 should we close this issue?

Yup, this one is also not relevant anymore in relation to the architecture switch we did.
