### ISSUE TITLE
[Epic] Product Management extensibility add PHP config

### ISSUE THREAD

**Issue by louwie17** [woothemes/woocommerce#35953]
**Description:** 
Plugins can extend the new Product Management screen through PHP, by the use of a config driven JSON schema.
This Epic will be part of phase 1, which will primarily focus on laying the ground work and setting it up for adding fields only.

**Issues**
*to be created
* [ ] Create PHP helper function for adding new fields (#36019)
* [ ] Create new API endpoint for retrieving new fields (#36021)
* [ ] Create Data store for retrieving form fields (#36073)
* [ ] Create key/value function/store for basic field types (#36074 )
* [ ] Add component to automatically add SlotFills for fields coming from PHP config. (#36075)

**Acceptance criteria:**
- [ ] Should expose a PHP helper function to add new fields to product details section.
- [ ] Should be able to add fields of type text, checkbox, number, radio.
- [ ] Added fields should show up in Product Details section.

**Event tracking:**
TBD

**Comment by pmcpinto** [comment]
@louwie17 should we close this issue?

**Comment by louwie17** [comment]
> @louwie17 should we close this issue?

Yes, this is not relevant anymore, thanks!
