### ISSUE TITLE
[Epic] Improve Gutenberg support in the new product form

### ISSUE THREAD

**Issue by jarekmorawski** [woothemes/woocommerce#36123]
We want to support more blocks in the summary and description fields in the new product form and improve the user experience so that the editor is easier to use and more powerful. We'll use P2's comment system as a vehicle to get there.

**Issues**

_TBD_

**Designs**

`nUovpfiFdBnjDq1nl8PlbG-fi-547%3A21705`

<img width="760" alt="image" src="https://user-images.githubusercontent.com/79307566/208849252-0c5e5ed0-e398-45d5-8132-b4100fc70b8e.png">

**Acceptance criteria**

- [ ] The summary and description fields allow users to add and manipulate content using blocks.
- [ ] We use the same experience as P2, including the maximized view with the sidebar and full-size block insert panel.
- [ ] When the field is not in focus, the editor controls are visible but faded (`gutenberg-400`). `nUovpfiFdBnjDq1nl8PlbG-fi-547%3A21706&t=UFfhCgqMhovDOIq9-4`
- [ ] The default field size for the summary and description is respectively 160 and 280 px (including the editor toolbar, which is 48 px). `nUovpfiFdBnjDq1nl8PlbG-fi-547%3A21706&t=UFfhCgqMhovDOIq9-4`
- [ ] Users can resize the fields by dragging a handle in the bottom right corner. There's no limit for its minimum and maximum height. `nUovpfiFdBnjDq1nl8PlbG-fi-547%3A27673&t=UFfhCgqMhovDOIq9-4`
- [ ] The editor top toolbar includes the inserter, undo/redo, summary, full screen, and more buttons. `nUovpfiFdBnjDq1nl8PlbG-fi-547%3A22888&t=UFfhCgqMhovDOIq9-4`
- [ ] Users can insert blocks using the inserter or by pressing / on the keyboard. `nUovpfiFdBnjDq1nl8PlbG-fi-547%3A25290&t=UFfhCgqMhovDOIq9-4`
- [ ] The more menu includes a link to the full screen view, code editor, and tools (copy/clear all). `nUovpfiFdBnjDq1nl8PlbG-fi-547%3A26481&t=UFfhCgqMhovDOIq9-4`
- [ ] While editing a block, the toolbar appears contextually. It cannot be fixed at the top of the field (it's one feature from P2 that we won't support at the moment).
- [ ] There're are no limitations regarding support blocks and block types.
- [ ] There's no sidebar (cog/drawer icon in the top right corner) in the in-form view. It is only available in the full screen view.
- [ ] Users can enter the full screen view by clicking the maximize icon in the editor toolbar. It's an extension of the in-form editor, so it'd be nice add a scaling effect or another similar transition.
- [ ] Users can also use the keyboard shortcut `⇧⌥⌘F` to enter the full screen view when the field is active. They keyboard should not work when the field is not in focus.
- [ ] The title of the full screen view modal is `Edit description` or `Edit summary`.
- [ ] The icon for entering and leaving the full screen view are called `Expand` and `Collapse`. They are part of P2's design system.
- [ ] We remember all changes user made in the in-form view and let them smoothly continue editing the description in the full experience. For example, if they just added an image block in the in-form view and haven't uploaded an image, they'll be able to do it in the full screen view.
- [ ] The sidebar is open by default when the user enters the full screen view. `nUovpfiFdBnjDq1nl8PlbG-fi- 547%3A41625&t=UFfhCgqMhovDOIq9-4`
- [ ] The sidebar only includes the `Block` tab. There's no `Page` tab. `nUovpfiFdBnjDq1nl8PlbG-fi- 547%3A41625&t=UFfhCgqMhovDOIq9-4`
- [ ] In the full screen view, the inserter is full size and supports both blocks and patterns. `nUovpfiFdBnjDq1nl8PlbG-fi-547%3A43444&t=UFfhCgqMhovDOIq9-4`
- [ ] Users can exit the full screen view by clicking the Collapse button in the corner. It uses the same animation or transition that we added for switching from the in-form view to full screen.
- [ ] If needed, we show a spinner when the users switch between viewing modes.
- [ ] In addition to the above, the full screen view is a proper Gutenberg experience and should support all its features.

**Comment by mdperez86** [comment]
We have two ways we can follow to implement this: 

1. Using [isolated-block-editor](https://github.com/Automattic/isolated-block-editor) which already implement must of the features we need but it has some experimental features and its not as flexible as the second option.
2. Using [block-editor](https://github.com/WordPress/gutenberg/tree/trunk/packages/block-editor) which is more flexible but it might required more implementation from our hands.

Both ways are viable to implement with the warning of outdated dependencies that we have currently. We should consider implement a contained editor that we can reuse for the summary, description and any other field that required the enhanced block experience, then apply those chances to each field in the product form (which means drop the current implementation to be replaced with the new one per field).

We can parallelize the work here by dividing those ACs in 2 groups: not fullscreen and fullscreen. And the min common ACs should be implemented first so we can unblock the resting dependant ACs and can be parallelized correctly.

There is a high uncertainty level and some risks, but this epic can be done in a week and half aprox by two engineers. More engineers might not reduce the time because of dependencies between the issues.
