### ISSUE TITLE
New users: onboard/offboard flows

### ISSUE THREAD

**Issue by pmcpinto** [woothemes/woocommerce#36161]
**Description:** we plan to start rolling out the beta version of the new experience to a small % of new users to validate that we're moving in the right direction:
- Ship, learn and iterate is better than refining in a vacuum.
- Focus on users who can have a moment of delight with the new experience.
- Validate utility: does the new experience solve the main pain points? Does the new experience lead to unexpected behavior or consequences? 
We want to target WC 7.9 (code freeze: June 19th)

**Acceptance criteria:**
- [ ] When a new user selects the "Physical product" option in the "Add products" task, we enable the new experience for 50% of new users. This issue with the A/B test setup is [here](https://github.com/woocommerce/mothra-private/issues/76).
- [ ] The rest of the users should get the current experience.

**Acceptance criteria done by other issues:**
- [ ] When the new user enters the new experience for the first time, we should show him a spotlight: lj4AUMJnpMtUe7XqyvOONq-fi-1335_125302  - https://github.com/woocommerce/woocommerce/issues/38516
- [ ] If the user closes the modal or selects the "not now" option, we display a bar at the bottom that will allow him to share feedback or disable the new experience. The bar should be displayed permanently unless it's closed by the user.
- [ ] If the user selects "View highlights", we enable the feature tour with 4 steps. The tour is based on the existing onboarding component in the post and site editor. lj4AUMJnpMtUe7XqyvOONq-fi-1335_125248 - https://github.com/woocommerce/woocommerce/issues/38516
- [ ] The "Tell me more" button in the 4th step should open a new tab with a link to a wc.com page with more info about the new experience: https://woocommerce.com/product-form-beta - https://github.com/woocommerce/woocommerce/issues/38518
- [ ] We should show the bottom bar after the user completes or closes the spotlight tour. The bar should be displayed permanently unless it's closed by the user. - https://github.com/woocommerce/woocommerce/issues/38520
- [ ] The bar is also shown to all users after they publish a product or on their next visit to the new product editing UX. - https://github.com/woocommerce/woocommerce/issues/38519
- [ ] In the bottom bar, if the user selects "share feedback," we should enable the regular CES. We should introduce a new field to the CES, allowing the user to enter his email address (do you need a separate issue for this change?). In WooExpress, the email field should be replaced by a checkbox that says `I want to participate in further discussion and future user research`. If not checked, the user's email address isn't shared with the rest of the feedback. - https://github.com/woocommerce/woocommerce/issues/38519 and https://github.com/woocommerce/woocommerce/issues/38521
- [ ] In the bottom bar, if the user selects "turn it off", we should show a new survey before redirecting the user to the current experience: lj4AUMJnpMtUe7XqyvOONq-fi-1334_116373. This survey should also be displayed when the user selects the "use the classic editor" option at the topbar. - https://github.com/woocommerce/woocommerce/issues/38519
- [ ] In the more menu in the top right corner, the `About the form` option re-opens the feature tour. https://github.com/woocommerce/woocommerce/issues/38522

**Event tracking:**
We should track all the interactions included in the flow.

**Comment by octaedro** [comment]
Hey @pmcpinto, 

> we should show a new survey before redirecting the user to the current experience: lj4AUMJnpMtUe7XqyvOONq-fi-501%3A6362&t=npEAXmnjXwQbZ97A-0

I see in the survey (and other CES) designs that there is an `?` icon next to the title. Is that icon a tooltip? //cc @jarekmorawski 

<img width="822" alt="Screenshot 2023-01-06 at 15 34 03" src="https://user-images.githubusercontent.com/1314156/211076647-8058123d-3d0e-411b-83e0-081fb72fce45.png">

**Comment by jarekmorawski** [comment]
No, it's just a decoration in the header, but feel free to skip it. It's a remnant of an older modal component design.

**Comment by pmcpinto** [comment]
> The "Tell me more" button in the 4th step should open a new tab with a link to a wc.com page with more info about the new experience (link and content TBD) - https://github.com/woocommerce/woocommerce/issues/38518

Issue description updated with the final link

**Comment by pmcpinto** [comment]
@louwie17 just to confirm that we can close this issue. Thanks
