### ISSUE TITLE
Options creation flow

### ISSUE THREAD

**Issue by pmcpinto** [woothemes/woocommerce#36286]
**Description:** this epic is a follow-up of the changes introduced in #35659

**Acceptance criteria:**

- [x] Create a new tab called "Variations" after the "Shipping tab.
- [x] If an existing product has 0 local or global attributes with "Used for variations" enabled, display the Variations empty state with the "Add variation options" CTA: AkVNGImLgSqCObTQ3idVn7-fi-1637_204904
- [x] If an existing product has at least 1 local or global attribute with "Used for variations" enabled, display the Options section with a list including the available attributes + values. This section will behave exactly as the Attributes section: AkVNGImLgSqCObTQ3idVn7-fi-1641_226803
- [x] If the user clicks "Add variation options", we'll open the "Add variation options" modal, and the entire flow reuses the attributes creation flow: AkVNGImLgSqCObTQ3idVn7-fi-1637_205314
- [x] The option dropdown field immediately focuses on the first 10 options (product/local attributes with ‘Used for variations’ enabled).
- [x] Each product option should be saved as a global attribute used for variations. By default, all attributes are created globally. We inform the user about this in the add attributes modal.
- [x] Each product option can be edited through a modal, where it will be possible to change the option name, add/remove values, define a default value, and define if it should be displayed to customers (local vs global): [AkVNGImLgSqCObTQ3idVn7-fi-1639_216872](https://href.li/?https://www.figma.com/file/AkVNGImLgSqCObTQ3idVn7/?node-id=1639-216872)
- [x] The first variation in each option is selected by default on the product page. Users can remove it by deselecting the `Set default value` box in the option edit modal (in the current experience, we don't have a default value selected, which causes some quirky behaviors). When the box isn't checked for all variations, no variation will be selected when the user enters the page.
- [x] Global attributes with the `Use as filter` box unchecked are marked with a small filter icon. It is displayed in the Attributes and Variation options lists. When the user hovers over the icon, they will see a tooltip explaining that a local attribute will not be used for filtering, etc.
- [x] In Attributes, those with the `Use as filter` box unchecked are marked with a small filter icon displayed in the list. When the user hovers over the icon, they will see a tooltip.
- [x] In Attributes, those with the `Show in product details` box unchecked are marked with a small eye icon displayed in the list. When the user hovers over the icon, they will see a tooltip.
- [x] Users can create several global attributes with the same name. We’d generate a unique slug for each based on its name. For example, the slugs for Color and Color would be ‘color’ and ‘color-2’.
- [x] Users need to go to the Attributes screen, to edit the attribute advanced details such as slug or archive.
- [x] When at least one option is created, we should automatically create variations from all options. The product should be transformed into a variable product.
- [x] The variations should be displayed in a Variations section. We show a spinner while the variations are being generated: AkVNGImLgSqCObTQ3idVn7-fi-1637_206790
- [x] When the variations are created show an overlay in the Pricing, Inventory, and Shipping tabs of the parent product. AkVNGImLgSqCObTQ3idVn7-fi-2780-278432&t=WyEjPQcmmsYnF3DJ-4
- [x] When the user hovers over one of the disabled tabs, we show a tooltip reading: Manage individual variation details in the Variations tab. 
- [x] The variation list should be updated if the user adds or removes values. For example, if the user adds a new value to a "Size" option, we should auto-create all the new variations based on the new size value.
- [x] If an attribute is added in one section, it can’t be selected in another. Users have to remove it from one section and add it to another. We would detect when an attribute was already added somewhere else and let users move it from one section to another.
- [x] In the Add variation options modal, when users add a global attribute to Attributes, we automatically add its first value. When they add it to Variation options, we add all of its values.
- [x] Users can select global attributes in both places. If they create new values, they’re added to the attribute but not selected in its assigned products.
- [x] Each option should have the box 'Show in product details' unchecked by default.
- [ ] Attributes and Variation options can be sorted separately. Variation options are, by default, hidden from the product description. If the user enables the visibility toggle, Variation options will be displayed below regular attributes.
- [ ] Changing the options order will be reflected at the top of the page and in the product description.
- [ ] If a product has 7 attributes: 2 variation options and 5 regular attributes, they can move n2 above n1, but not n7 above n2. They are managed in separate lists, even though they’re displayed in the same area in the product description.
- [x]  When users switch from the new experience back to the classic one, attributes from both sections will be displayed in a single list. We’ll respect the sorting order and place regular attributes below attributes used for variations. Users will be able to move them up and down however they want.

**Event tracking:**
All user interactions should be tracked

**Comment by pmcpinto** [comment]
@joshuatf I created this new epic. Let me know if you have any questions. It would be helpful to have a sense of the effort required to implement each item.

cc @jarekmorawski pls confirm if there's anything missing. 

Thanks

**Comment by AnnaMag** [comment]
We keep it open as it is UI- agnostic and the principles will apply to the new designs.

**Comment by pmcpinto** [comment]
Acceptance criteria reviewed and updated with the latest designs

**Comment by mdperez86** [comment]
> If an attribute is added in one section, it can’t be selected in another. Users have to remove it from one section and add it to another. We would detect when an attribute was already added somewhere else and let users move it from one section to another.

@pmcpinto @jarekmorawski could you explain this a little more? What does section means in this context? Could you provide and example of this please?
cc: @louwie17 @AnnaMag

**Comment by mdperez86** [comment]
> When users add a global attribute to Attributes, we automatically add its first value. When they add it to Options, we add all of its values.

@pmcpinto @jarekmorawski Where we automatically add its first value? Where we add all of its values?
cc: @louwie17 @AnnaMag

**Comment by jarekmorawski** [comment]
> If an attribute is added in one section, it can’t be selected in another. Users have to remove it from one section and add it to another. We would detect when an attribute was already added somewhere else and let users move it from one section to another.

Say you've got an attribute called `Fabric`. It has a few values, like `Cotton` and `Linen`. When you go to `Organization > Attributes`, you'll see it in the list in the `Add attributes` modal. If you add it there, navigate to the `Variations` tab, and click `Add variation options`, you will not see `Fabric` in the `Attributes` dropdown field.

Similarly, if you add it in `Variations` first, you won't see it in the dropdown field in the `Add attributes` modal in `Organization > Attributes`. Do you think this helps?

> Where we automatically add its first value? Where we add all of its values?

In the `Add variation options` modal, there are two columns: `Attributes` and `Values`. When the user selects a global attribute in the first column (e.g., `Fabric` or `Color`), we automatically select and add all values in the right column. For instance, when the user selects `Fabric`, we automatically add the `Cotton` and `Linen` values. I'll update the ACs.

<img width="670" alt="image" src="https://github.com/woocommerce/woocommerce/assets/79307566/e3d1513d-a067-4d60-8afc-d5cde8c432aa">

**Comment by louwie17** [comment]
Closing this as the bulk of the work has been done and we already have a follow up issue for the drag and drop/re-ordering work.
