### ISSUE TITLE
[Epic] TreeControl component

### ISSUE THREAD

**Issue by mattsherman** [woothemes/woocommerce#36590]
## Issues/PRs

- [x] https://github.com/woocommerce/woocommerce/pull/36432
- [x] https://github.com/woocommerce/woocommerce/pull/36517
- [x] https://github.com/woocommerce/woocommerce/pull/36434
- [x] https://github.com/woocommerce/woocommerce/pull/36476
- [x] https://github.com/woocommerce/woocommerce/pull/36435
- [x] https://github.com/woocommerce/woocommerce/pull/36480
- [x] https://github.com/woocommerce/woocommerce/pull/36459

**Comment by pmcpinto** [comment]
I'm closing this issue as all the PRs were merged
