### ISSUE TITLE
[Epic] Package organization

### ISSUE THREAD

**Issue by mattsherman** [woothemes/woocommerce#36756]
Issues:

- [x] https://github.com/woocommerce/mothra-private/issues/79
- [x] https://github.com/woocommerce/woocommerce/issues/36719
- [x] https://github.com/woocommerce/woocommerce/issues/36723
- [x] https://github.com/woocommerce/woocommerce/issues/36721
- [x] https://github.com/woocommerce/woocommerce/issues/37247
- [x] https://github.com/woocommerce/woocommerce/issues/36720
- [x] https://github.com/woocommerce/woocommerce/issues/36722
- [x] https://github.com/woocommerce/woocommerce/issues/36724
- [x] https://github.com/woocommerce/woocommerce/issues/36725
- [x] https://github.com/woocommerce/woocommerce/issues/36726
- [x] https://github.com/woocommerce/woocommerce/issues/36727
- [x] https://github.com/woocommerce/woocommerce/issues/36728
- [x] https://github.com/woocommerce/woocommerce/issues/36729
