### ISSUE TITLE
[GlobalStep] [WP 6.2 Beta] For WP 6.2 Beta, User navigates to blank page upon clicking "Add (Paid Product Type) to my store" option from Task list on "Woocommerce > Home" page.

### ISSUE THREAD

**Issue by gglobalstep** [woothemes/woocommerce#36793]
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

For WP 6.2 Beta, User navigates to blank page upon clicking "Add (Paid Product Type) to my store" option from Task list on "Woocommerce > Home" page.

### Expected behavior

All content should be display after clicking on "Add (Paid Product Type) to my store" option from Task list on "Woocommerce > Home" page.

### Actual behavior

For WP 6.2 Beta, User navigates to blank page upon clicking "Add (Paid Product Type) to my store" option from Task list on "Woocommerce > Home" page.

### Steps to reproduce

1. Create any test site using Jurassic Ninja.
2. Install and activate all the required plugins.
3. Install and activate Woocommerce.
4. Start with OBW.
5. Go to Product Types step.
6. Select any Paid Product Type and Click Continue.
7. Complete OBW.
8. Go to "Woocommerce > Home" page
9. Click on "Add (Paid Product Type) to my store" option from Task list.
10. Observe that for WP 6.2 Beta, user is navigated to a Blank page.

### Screenshot:

![#36793](https://user-images.githubusercontent.com/41110392/217538195-2f9abb33-c599-4ce9-bed0-73bae859f363.gif)

### WordPress Environment

Woocommerce Version: WooCommerce 7.4 RC 1
WordPress version: 6.2 Beta 1

PC:
Windows 10, MacOS Ventura 13.0.1
Chrome(Version 109.0.5414.120)
Firefox(Version 109.0.1)
Safari (Version 16.2)

<details>
`
### WordPress Environment ###

WC Version: 7.4.0
REST API Version: ✔ 7.4.0
WC Blocks Version: ✔ 9.4.3
Action Scheduler Version: ✔ 3.5.4
Log Directory Writable: ✔
WP Version: 6.2-beta1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.55 (Unix) OpenSSL/1.0.2g
PHP Version: 7.4.33
PHP Post Max Size: 1 GB
PHP Time Limit: 30
PHP Max Input Vars: 5000
cURL Version: 7.47.0
OpenSSL/1.0.2g

SUHOSIN Installed: –
MySQL Version: 5.7.33-0ubuntu0.16.04.1-log
Max Upload Size: 512 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.4.0
WC Database Prefix: wp_
Total Database Size: 9.18MB
Database Data Size: 7.44MB
Database Index Size: 1.74MB
wp_woocommerce_sessions: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.09MB + Index: 0.09MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.06MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.08MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 4.47MB + Index: 0.08MB + Engine InnoDB
wp_postmeta: Data: 0.23MB + Index: 0.19MB + Engine InnoDB
wp_posts: Data: 0.14MB + Index: 0.06MB + Engine InnoDB
wp_snippets: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wpml_mails: Data: 1.52MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

attachment: 33
page: 11
post: 3
product: 24
product_variation: 11
revision: 8
shop_coupon: 3
shop_order: 32
shop_order_refund: 1
wp_global_styles: 1
wp_template_part: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (7) ###

Query Monitor: by John Blackbourn – 3.11.1
Code Snippets: by Code Snippets Pro – 3.2.2
Companion Plugin: by Osk – 1.29
WooCommerce Payments: by Automattic – 5.4.0
WooCommerce: by Automattic – 7.4.0-rc.1
WordPress Beta Tester: by Peter Westwood
Andy Fragen – 3.2.7

WP Mail Logging: by SendLayer – 1.10.5

### Inactive Plugins (4) ###

Akismet Anti-Spam: by Automattic – 5.0.2
Hello Dolly: by Matt Mullenweg – 1.7.2
Jetpack: by Automattic – 11.8
Pinterest for WooCommerce: by WooCommerce – 1.2.11

### Dropin Plugins (1) ###

db.php: Query Monitor Database Class (Drop-in)

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔
Enforce Approved Product Download Directories: ✔
Order datastore: WC_Order_Data_Store_CPT

### WC Pages ###

Shop base: #7 - /shop/
Cart: #109 - /cart-block/
Checkout: #111 - /checkout-block/
My account: #10 - /my-account/
Terms and conditions: #9 - /checkout/

### Theme ###

Name: Storefront
Version: 4.2.0
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Subscriptions ###

WCS_DEBUG: ✔ No
Subscriptions Mode: ✔ Live
Subscriptions Live URL: https://relative-gibbon.jurassic.ninja
Subscriptions-core Library Version: 5.3.1
Subscription Statuses: –
WooCommerce Account Connected: ✔ Yes
Active Product Key: ❌ No

### Store Setup ###

Country / State: United States (US) — California

### Payment Gateway Support ###

WooCommerce Payments: products
refunds
multiple_subscriptions
subscription_cancellation
subscription_payment_method_change_admin
subscription_payment_method_change_customer
subscription_payment_method_change
subscription_reactivation
subscription_suspension
subscriptions
gateway_scheduled_payments
tokenization
add_payment_method

Cash on delivery: products

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
multichannel-marketing
mobile-app-banner
navigation
new-product-management-experience
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
product-variation-management
settings

Daily Cron: ✔ Next scheduled: 2023-02-09 06:40:05 +00:00
Options: ✔
Notes: 28
Onboarding: completed

### WooCommerce Payments ###

Version: 5.4.0
Connected to WPCOM: Yes
Blog ID: 215396702
Account ID: acct_1MZAhyC5kOOOwU20

### Action Scheduler ###

Canceled: 1
Oldest: 2023-02-08 11:15:29 +0000
Newest: 2023-02-08 11:15:29 +0000

Complete: 149
Oldest: 2023-02-08 06:41:18 +0000
Newest: 2023-02-08 11:53:01 +0000

Failed: 8
Oldest: 2023-02-08 06:42:18 +0000
Newest: 2023-02-08 13:01:22 +0000

Pending: 3
Oldest: 2023-02-08 14:01:22 +0000
Newest: 2023-02-09 07:54:03 +0000

### Status report information ###

Generated at: 2023-02-08 13:02:13 +00:00
`
</details>

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by chihsuan** [comment]
Closed by https://github.com/woocommerce/woocommerce/pull/36887
