### ISSUE TITLE
Spike: Block based product editor

### ISSUE THREAD

**Issue by joshuatf** [woothemes/woocommerce#36865]
We're considering shifting the new product editing experience to a blocks-based editor.  Before committing to this, we need to validate its feasibility, extensibility, performance, and highlight any other potential issues we might run into.

This spike will involve diving into blocks to learn how they work and how they can fit into the product editing experience.

**Issues**

* [ ] [Blocks performance in product editing experience#36861](https://github.com/woocommerce/woocommerce/issues/36861)
* [ ] [Blocks extensibility in the new product editing experience#36862](https://github.com/woocommerce/woocommerce/issues/36862)
* [ ] [Blocks saving in the new product editing experience#36863](https://github.com/woocommerce/woocommerce/issues/36863)
* [ ] [Converting existing product components to blocks#36864](https://github.com/woocommerce/woocommerce/issues/36864)
