### ISSUE TITLE
[Epic] Better attribute management

### ISSUE THREAD

**Issue by jarekmorawski** [woothemes/woocommerce#37099]
We want to improve the attribute management flows in the Product data module to provide guidance and explain the benefits of using attributes. Our goal is to boost the usability and discoverability of this feature.

<img width="467" alt="image" src="https://user-images.githubusercontent.com/79307566/223396058-89e45c1e-69c5-4b1b-a220-e4c2e212a954.png">

**Designs:**
`zs56kcy53K7GoGhgyjcQ2R-fi-210%3A30923`

**Acceptance criteria:**

- [ ] There's a new empty state shown when no attributes (global or local) are added to the product. There's an icon and copy that reads `Add descriptive pieces of information that customers can use to search for this product on your store, such as “Material” or “Brand”.` The arrow points to the "Add new" button.
- [ ] The existing attribute dropdown is displayed but disabled if there are no global attributes. If there are, the user can click and select an attribute. When selected, the attribute is added immediately (no second confirmation click is needed).
- [ ] The dropdown's default placeholder text is "Add existing". It only contains existing global attributes and nothing else.
- [ ] "Add new" is no longer part of the dropdown. It is now a separate button that can be clicked at any moment.
- [x] The name and value/s fields are required in the add attribute form. Until they’re filled, the `Save attributes` button is disabled.
- [ ] When the user hovers over the disabled `Save attributes` button, we show a tooltip that reads: `Make sure you enter the name and values for each attribute.`
- [x] The validation works for all currently edited attribute forms. If the user clicks the "Add new" button multiple times and only fills out the required fields for one attribute, the button will remain disabled.
- [ ] The default placeholder text in the new attribute form header is `New attribute`.
- [ ] Item controls (Remove, Reorder, Expand/Collapse) are always visible. They are rearranged so that the expand/collapse arrow is on the right edge.
- [ ] We change the name of the button used to create new values in existing attributes from “Add new” to “Create value”. It opens a browser dialog window just like it does now.
- [x] The `Used for variations` box is checked by default for all added attributes for variable products.
- [ ] When the user attempts to remove an attribute with the Used for variations box checked, we show a browser dialog window with an updated copy: `If you remove this attribute, customers will no longer be able to purchase some variations of this product.`

**Tracks events:**

- [ ] The attributes tab link (from any other tab or part of the product form).
- [ ] The new "Add new" button in the empty state.
- [ ] The new "Add new" button when there's at least one attribute/form added.
- [ ] The new "Add existing" dropdown in the empty state.
- [ ] The new "Add existing" dropdown when there's at least one attribute/form added.
- [ ] The "Save attributes" buttons.

cc @pmcpinto

**Comment by pmcpinto** [comment]
For the engineering team: it would be great to have feedback on the feasibility of each AC item before we move forward with the implementation.

> There's a new empty state shown when no attributes (global or local) are added to the product.

Should we have a link to the documentation? Similar to variations. 

> The dropdown's default placeholder text is "Add existing". It only contains existing global attributes and nothing else.

What if an extension adds dropdown options?

**Comment by jarekmorawski** [comment]
> Should we have a link to the documentation? Similar to variations.

It shouldn't be needed. I checked it out, and it doesn't add more to what the new empty state copy already says. I'd keep it simple and not drive people away from the flow.

> What if an extension adds dropdown options?

I'm not aware of such an extension. Is this part of the UI extendable? The dropdown should only include attributes, so if there are any plugin-added options, they could show up as buttons.

**Comment by pmcpinto** [comment]
> It shouldn't be needed. I checked it out, and it doesn't add more to what the new empty state copy already says. I'd keep it simple and not drive people away from the flow.

👍 

> Is this part of the UI extendable? 

Anything can be extended 😄

**Comment by octaedro** [comment]
Hi @pmcpinto,
The ACs look feasible without requiring significant effort, and we will examine them further during our next grooming session.

I noticed that a couple of ACs had already been done. For the remaining items, I have split them into 7 separate issues: 
- https://github.com/woocommerce/woocommerce/issues/37151
- https://github.com/woocommerce/woocommerce/issues/37157
- https://github.com/woocommerce/woocommerce/issues/37158
- https://github.com/woocommerce/woocommerce/issues/37159
- https://github.com/woocommerce/woocommerce/issues/37160
- https://github.com/woocommerce/woocommerce/issues/37162
- https://github.com/woocommerce/woocommerce/issues/37163

**Comment by toktor** [comment]
Leaving this comment here, in case anyone else stumbles upon it. I can see that this is intended behavior, though I am not sure why.

Just went down the rabbit hole of debugging why our attributes aren't showing up anymore on the product page.

We show attributes for simple products and only show them if they are not used for variations.

This changes default behavior not only for variable products but also for simple products.

For simple products, if I add attribute it will have "used for variation" field hidden and checked. No visible change for admin, but different behavior.

Two ways to work around: 
1. Change product to variable, to show "used for variation" field and uncheck. Change product back to simple.
2. use "woocommerce_attribute_default_is_variation" filter.

**Comment by jarekmorawski** [comment]
Hi @toktor! Thanks for sharing your thoughts. I confirm that this change should not affect simple products. I'm happy to add some context behind this decision if you'd like. Apart from the issues with simple products on your website, is there anything else you need clarification on this change?

@octaedro @nathanss Would you mind looking into this again? It seems that we apply the new default for all product types, while it should only affect variable types. Could activating the new filter for non-variable products help solve the issue?

**Comment by nathanss** [comment]
Hi @jarekmorawski, I can confirm that the default value for the checkbox is checked in scenarios where the field is hidden. Shall we invert that behavior? 

> Could activating the new filter for non-variable products help solve the issue?

That is unclear to me. But I think it's confusing that the default value is 'checked'. Maybe we can fix the issue in a simpler way?

**Comment by jarekmorawski** [comment]
> I can confirm that the default value for the checkbox is checked in scenarios where the field is hidden. Shall we invert that behavior?

Yes, please. The box should only be checked for variable product types. If it's not visible and controllable by the user, it should be unchecked. Thank you!
