### ISSUE TITLE
[Epic] Better variations discoverability

### ISSUE THREAD

**Issue by jarekmorawski** [woothemes/woocommerce#37100]
We want to improve the discoverability of variations in the Product data module to help people create them—from creating attributes to generating variations. Our goal is to boost the usability and discoverability of this feature.

<img width="488" alt="image" src="https://user-images.githubusercontent.com/79307566/223403057-a51aa181-75da-441c-b889-76a3d3c9c6be.png">

**Designs:**
`zs56kcy53K7GoGhgyjcQ2R-fi-210%3A30924`

**Acceptance criteria:**

- [ ] There's a new empty state in the `Variations` tab shown when no attributes (global or local) with the `Used for variations` box are added to the product. There's an icon and copy that reads `Add some attributes in the Attributes tab to generate variations. Make sure to check the Used for variations box. Learn more`. The word `Attributes` is linked to the attributes part. The link `Learn more` takes people to https://woocommerce.com/document/variable-product/.
- [ ] There's another empty state when the attributes with the Used for variations box are added, but the variations are not generated yet. There's an icon and copy that reads `No variations yet. Generate them from all added attributes or add a new variation manually.` The arrow points to the new "Generate variations" button.
- [ ] "Create variations from all attributes" is no longer part of the dropdown. It is now a separate button labeled `Generate variations`. Clicking it generates the variations from all attributes with the `Used for variations` box checked.
- [ ] "Add variations" is no longer part of the dropdown. It is now a separate button labeled `Add manually`. Clicking it adds a new variation form (the same as it does now).
- [ ] The dropdown is displayed in neither empty state. It is only shown when there is at least 1 variation created. The label now reads `Bulk actions`.
- [ ] When the user switches from another product type to the variable product type for the first time, we show a spotlight that points to the attributes tab. The spotlight reads `Start by adding attributes. Add attributes like size and color for customers to choose from on the product page. We will use them to generate product variations.`. It is only shown once for each user. The `Got it` and the `X` buttons dismiss it.

**Tracks events:**

- [ ] The variations tab link (from any other tab or part of the product form).
- [ ] The "Attributes" link in the new empty state (when no attributes are added).
- [ ] The "Learn more" link in the new empty state (when no attributes are added).
- [ ] The "Generate variations" button in the second new empty state (when attributes are added, but the variations have not been generated yet).
- [ ] The "Add manually" button in the second new empty state (when attributes are added, but the variations have not been generated yet).
- [ ] The "Bulk actions" dropdown.
- [ ] (If possible) Each action selected in the "Bulk actions" dropdown.

cc @pmcpinto

**Comment by pmcpinto** [comment]
For the engineering team: it would be great to have feedback on the feasibility of each AC item before we move forward with the implementation.

> The dropdown is displayed in neither empty state. It is only shown when there is at least 1 variation created. The label now reads Bulk actions.

We need to clarify what should happen if an extension adds an option to the dropdown. Should we show the dropdown?

**Comment by jarekmorawski** [comment]
> We need to clarify what should happen if an extension adds an option to the dropdown. Should we show the dropdown?

I'd say no. Except for the two we're turning into separate buttons, all actions in the dropdown are bulk actions. If an extension adds its item there, it will likely affect all variations. We'd have to be really smart about picking items that show up before the variations are added, and that isn't possible without some advanced conditional logic.

I'd remove the dropdown from the empty state to keep things simple.

**Comment by octaedro** [comment]
Hi @pmcpinto 

> For the engineering team: it would be great to have feedback on the feasibility of each AC item before we move forward with the implementation.

At first glance, I don't see anything too difficult to do. We will have a grooming session next week, and we will estimate all the AC.

Based on the ACs, I created the following issues:
- https://github.com/woocommerce/woocommerce/issues/37139
- https://github.com/woocommerce/woocommerce/issues/37147
- https://github.com/woocommerce/woocommerce/issues/37148
- https://github.com/woocommerce/woocommerce/issues/37149
- https://github.com/woocommerce/woocommerce/issues/37150

**Comment by octaedro** [comment]
Hey @jarekmorawski,

> I'd say no. Except for the two we're turning into separate buttons, all actions in the dropdown are bulk actions. If an extension adds its item there, it will likely affect all variations. We'd have to be really smart about picking items that show up before the variations are added, and that isn't possible without some advanced conditional logic.
I'd remove the dropdown from the empty state to keep things simple.

Just to confirm, if an extension adds an option to the dropdown, we will remove all our options from the dropdown and show only the ones added by the extension, right?

**Comment by jarekmorawski** [comment]
> Just to confirm, if an extension adds an option to the dropdown, we will remove all our options from the dropdown and show only the ones added by the extension, right?

No, they should always be shown together. However, we shouldn't show the dropdown at all—whether it contains any third-party added options or not—in the variations empty state. There, the user should only see the `Generate variations` and `Add manually` buttons, and the icon and the empty state body text.
