### ISSUE TITLE
[Epic] Improve the layout of the inventory fields

### ISSUE THREAD

**Issue by jarekmorawski** [woothemes/woocommerce#37102]
We want to improve the usability and copy in the inventory tab in the Product data module. Our goal is to clarify how we communicate certain features and create a connection between the product-level and global settings.

<img width="776" alt="image" src="https://user-images.githubusercontent.com/79307566/223411394-2711e007-1fb8-4ae8-9dcc-34a89287aef7.png">

**Designs:**
`zs56kcy53K7GoGhgyjcQ2R-fi-210%3A30925`

**Acceptance criteria:**

- [ ] The `Manage stock?` section header title now reads `Stock management`.
- [ ] If stock management is disabled in `WooCommerce > Settings > Products > Inventory`, we show a message in the `Stock management section`. It reads `Disabled in store settings`. The `store settings` part links to `WooCommerce > Settings > Products > Inventory`.
- [ ] The "Stock status" field is now displayed as a collection of radio buttons instead of a dropdown. However, if for any reason the number of items inside exceeds three, it should be displayed as a dropdown again.
- [ ] If stock management is enabled in store settings, we show a toggle with a tweaked label: `Track stock quantity for this product` (previously “Manage stock level (quantity)”).
- [ ] When stock tracking is enabled for the first time, we default to quantity=1 (now we default to 0, which creates lots of issues).
- [ ] The "Allow backorders?" is now displayed as a collection of radio buttons instead of a dropdown.
- [ ] For variable products, we show an additional message at the top of the form. It reads `Settings below apply to all variations without manual stock management enabled. Learn more`. The `Learn more` part links to https://woocommerce.com/document/variable-product/.

**Tracks events:**

- [ ] The store settings link displayed when store-wide inventory tracking is disabled.
- [ ] The "Track stock quantity for this product" toggle.
- [ ] The "Learn more" link in the message displayed at the top of the form (for variable products).

cc @pmcpinto

**Comment by pmcpinto** [comment]
For the engineering team: it would be great to have feedback on the feasibility of each AC item before we move forward with the implementation.

**Comment by octaedro** [comment]
Hey @pmcpinto,
The ACs look like easy goals with a big impact, so I think that we should move forward with the implementation.

To tackle the changes required here, I created the following issues:
- https://github.com/woocommerce/woocommerce/issues/37113
- https://github.com/woocommerce/woocommerce/issues/37115
- https://github.com/woocommerce/woocommerce/issues/37116
- https://github.com/woocommerce/woocommerce/issues/37117
- https://github.com/woocommerce/woocommerce/issues/37118
- https://github.com/woocommerce/woocommerce/issues/37119
- https://github.com/woocommerce/woocommerce/issues/37136
