### ISSUE TITLE
Remove use of interpolateComponents and use createInterpolateElement instead

### ISSUE THREAD

**Issue by louwie17** [woothemes/woocommerce#37312]
**Prerequisites (mark completed items with an [x]):**
- [x] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [x] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

**Issue Description:**

We have several use case of `interpolateComponents` coming from `@automattic/interpolate-components`. While there is a similar function as part of `@wordpress/element` called `createInterpolateElement` that does something very similar.

We should replace our use of `interpolateComponents` with the wp.element version, once removed we should be able to remove the `@automattic/interpolate-components` dependency as well 🎉 

Remove use cases in (there are around 54 different files across these packages/plugins that make use of it):

```[tasklist]
### Tasks
- [ ] `@woocommerce/components`
    - [x] `advanced-filters`: https://github.com/woocommerce/woocommerce/pull/37967
    - [ ] `search/autocompleters`
- [x] `@woocommerce/product-editor`
- [x] `@woocommerce/onboarding` ( https://github.com/woocommerce/woocommerce/pull/38423 )
- [ ] `woocommerce/admin/client`
```

**Acceptance criteria**

- [ ] Use `createInterpolateElement` instead of `interpolateComponents`
- [ ] Removed `@automattic/interpolate-components` dependency once all items have been updated.

**Comment by pmcpinto** [comment]
This one's really more of an internal process or repo task than a product bug, so I've routed it over to the relevant engineering team to pick up.
