### ISSUE TITLE
Milestone + Community PR investigation

### ISSUE THREAD

**Issue by psealock** [woothemes/woocommerce#37325]
**Prerequisites (mark completed items with an [x]):**
- [x] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [x] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

**Issue Description:**

Once the 7.6.0 Code Freeze action has run (today, March 20th) create community PRs from your fork to investigate the following:

- [ ] Does the Cherry Pick Tool action run when the milestone is applied **before** merge
- [ ] Does the Cherry Pick Tool action run when the milestone is applied **after** merge

If either of these two processes incur a failure, address it as part of this issue.

**Comment by samueljseay** [comment]
I don't know about 7.6.0 but I saw cherry pick not work when milestone was applied **after merge** when working on 8.0.1

cc @jonathansadowski

**Comment by rrennick** [comment]
@jonathansadowski Closing this one. Feel free to re-open if this still needs investigation.
