### ISSUE TITLE
[Epic] Variations tab enhancements v2

### ISSUE THREAD

**Issue by jarekmorawski** [woothemes/woocommerce#37836]
I've reviewed the changes implemented in 7.7 and came up with a few minor improvements we can make to streamline the experience further. 

**Acceptance criteria**

- [x] We no longer check if any global attributes exist in the store. The empty state is always shown when the number of variations is 0. (Issue [#38120](https://github.com/woocommerce/woocommerce/issues/38120))
  - [x] We use the new empty states introduced as part of #37411.
- [ ] The line separating the buttons from the rest of the empty state is removed.
- [ ] We automatically preselect the first value as the default form value for each variation attribute. For example, if `Color` has Blue, Red, and Green, Blue will be the default value.
- [x] Once the variations are created, the button for generating variations from attributes changes from `Generate variations` to `Regenerate variations`. (Issue [#38080](https://github.com/woocommerce/woocommerce/issues/38080))
- [ ] The button has a tooltip that says `Recreate variations from all added attributes` on hover.
- [x] #38095
- [ ] We use the browser dialog instead of the custom modal to add price to variations that miss it (from the notice above the variations list).

**Comment by octaedro** [comment]
Hey @jarekmorawski,
I have a question related to the first two points.

> We no longer check if any global attributes exist in the store. The empty state is always shown when the number of variations is 0.

and

> We use the new empty states introduced as part of https://github.com/woocommerce/woocommerce/pull/37411.

Just to confirm, we will always show this empty state:

![Screenshot 2023-05-04 at 13 21 57](https://user-images.githubusercontent.com/1314156/236266609-3a94660a-81ea-45c9-b862-6df58f1ed7b1.png)

And we won't show this form anymore, right?
![Screenshot 2023-05-04 at 13 29 04](https://user-images.githubusercontent.com/1314156/236266741-32042038-dda1-407d-8412-e80e06c330af.png)

**Comment by jarekmorawski** [comment]
That's correct!

**Comment by pmcpinto** [comment]
I'm going to close this one, as design is exploring some improvements targeting the current variation management experience.
