### ISSUE TITLE
[Epic] Attributes tab enhancements v2

### ISSUE THREAD

**Issue by jarekmorawski** [woothemes/woocommerce#37839]
I've reviewed the changes implemented in 7.7 and came up with a few minor improvements we can make to streamline the experience further.

**Design**

`zs56kcy53K7GoGhgyjcQ2R-fi-365-39439&t=IlDQFEuvZsBvigFP-4`

<img width="799" alt="image" src="https://user-images.githubusercontent.com/79307566/233087332-2f8d3e08-d939-4375-8945-a703ba7daa39.png">

**Acceptance criteria**

- [x] #38104
- [ ] We automatically select all values when the user adds an existing attribute.
- [ ] When adding an existing attribute, the placeholder text in the Value/s field reads `Select values` (currently, it's `Select terms`).
- [ ] When the `Used for variations` box is unchecked, the placeholder text in the `Value/s` field reads `Enter some descriptive text. Use “|” to separate different values.`
- [ ] The notice in the empty state is dismissible. Once hidden, it does not re-appear.

**Comment by jimjasson** [comment]
Hey @jarekmorawski, 

I took a look at some of your designs for the Attributes tab and compared them to what has been implemented so far. I noticed that when adding a new attribute, a double-boarder shows up on the sides of the Attribute box: 

 
![Markup on 2023-06-19 at 16:31:13](https://github.com/woocommerce/woocommerce/assets/25955483/ee0c951b-baf0-4788-a0cd-29072654093f)

This border doesn't exist in the designs you shared, so I was wondering if you could add the removal of these borders as a task for this Epic.

From my investigation, I found that this border is coming from the `.postbox` class: 

![Markup on 2023-06-19 at 16:33:59](https://github.com/woocommerce/woocommerce/assets/25955483/6f6b2f2a-0312-408a-9219-57e00f9c3fa8)

My proposal is to override this rule specifically for the `.woocommerce_attribute.wc-metabox.postbox` class and set the boarder rule to `0px` -- by doing so, the only border that will show up will be the border-bottom, which is coming from the rule that targets the `.wc-metaboxes-wrapper .wc-metaboxes` element. 

The only thing that would be missing then is a top border for the first element, which can be added as a bottom border to the  `toolbar` element that precedes the attributes. 

The `toolbar` element normally adds a bottom border: https://github.com/woocommerce/woocommerce/blob/1ae97495de85237e45ade80ad51716c0c51d20a0/plugins/woocommerce/client/legacy/css/admin.scss#LL5539C1-L5544C3, which isn't added in this case because the `#variable_product_options_inner` element exists in the page. This rule needs to be rewritten so that bottom borders are added to the `toolbar` element in the Attributes tab.
