### ISSUE TITLE
[Epic] Inventory tab enhancements v2

### ISSUE THREAD

**Issue by jarekmorawski** [woothemes/woocommerce#37835]
I've reviewed the changes implemented in 7.7 and came up with a few minor improvements we can make to streamline the experience further.

**Design**

`zs56kcy53K7GoGhgyjcQ2R-fi-342-39509&t=IlDQFEuvZsBvigFP-4`

<img width="984" alt="image" src="https://user-images.githubusercontent.com/79307566/233076945-fbede0ec-fcec-43e4-be05-0eade06bc3c3.png">

**Acceptance criteria**

- [ ] For variable products, the notice shown at the top has subtler styling (per the design).
- [ ] The notice is shown below the SKU field, but above the Stock management checkbox. There's a thin line that separates the two.
- [ ] The spacing between the radio buttons under Allow backorders is 2 px.
- [ ] The help icon is removed.
