### ISSUE TITLE
[Enhancement]: Implement promises in meta-boxes-product-variation.js

### ISSUE THREAD

**Issue by octaedro** [woothemes/woocommerce#37909]
## Description

It would be beneficial to use `Promises` in [meta-boxes-product-variation.js](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/client/legacy/js/admin/meta-boxes-product-variation.js) to improve user experience.

The way that the async calls are being used could be improved, resulting in a couple of buggy behaviors.

Incorporating promises to the methods that use `$.ajax`, `$.get` and `$.post` will enhance the user experience since we can decouple a lot of code.

Currently, we're using only [one "promise"](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/client/legacy/js/admin/meta-boxes-product-variation.js#L749) in this file.

## Acceptance criteria

- [ ] `wc_meta_boxes_product_variations_ajax.save_changes()` returns a Promise that is resolved when the variations have been saved
    - [ ] `wc_meta_boxes_product_variations_ajax.check_for_changes()` is updated to handle `save_changes()` Promise
    - [ ] `wc_meta_boxes_product_variations_ajax.save_variations()` is updated to handle `save_changes()` Promise
    - [ ] `wc_meta_boxes_product_variations_ajax.save_on_submit()` is updated to handle `save_changes()` Promise
- [ ]  `wc_meta_boxes_product_variations_ajax.add_varation()` returns a Promise that is resolved when the variation has been added
    - [ ] `wc_meta_boxes_product_variations_ajax.add_varation_manually()` is updated to handle `add_variation()` Promise
 - [ ] `wc_meta_boxes_product_variations_ajax.link_all_variations()` returns a Promise that is resolved when the variations have been linked
     - [ ] `wc_meta_boxes_product_variations_ajax.generate_variations()` is updated to handle `link_all_variations()` Promise
 - [ ] TBD

## Implementation details

TBD
