### ISSUE TITLE
[MVP QA #1] General tab: Attributes

### ISSUE THREAD

**Issue by jarekmorawski** [woothemes/woocommerce#38206]
Hi there! I reviewed the latest build of the product editing experience and made some notes about changes we can make. In this issue, I outline improvements to the `General` tab.

**Acceptance criteria**
- [x] Add attributes: when the user adds a new value to an existing global attribute, we show a new `Create attribute` modal on top of the “Add attributes” modal. This shouldn’t happen, and we should let users add new values without any friction (generate the slug based on the name and leave the description empty). - https://github.com/woocommerce/woocommerce/issues/39223
- [ ] Add attributes: ifor local attributes, users should be able to just type a value and move on to the next field (we’d automatically add it as a value).
- [ ] Add attributes: users should be able to create a value by pressing a comma (this will likely require a separate issue as I am not sure our select control supports this)
- [x] List: the last list item shouldn’t have the bottom border. https://github.com/woocommerce/woocommerce/issues/39224
- [x] List: the color of the delete button should be Gutenberg-700, not Gutenberg-900. https://github.com/woocommerce/woocommerce/issues/39224
- [x] List: the button should say “Edit”, not “edit”. https://github.com/woocommerce/woocommerce/issues/39224
- [x] List: the right padding on the list item should be 0px, not 24px. https://github.com/woocommerce/woocommerce/issues/39224
- [ ] Edit attributes: the field labels use a different style from all other fields. Also, the help icon should be Gutenberg-600 and aligned vertically to the checkbox label.
- [ ] Add/edit attributes: let’s change the placeholder texts in all attribute fields. Attribute: `e.g. Season or Skin type`, Values: `e.g., Spring/Summer or Dry skin`.

cc @pmcpinto

**Comment by pmcpinto** [comment]
AC ordered by priority

**Comment by jarekmorawski** [comment]
I received the ACs and I think they're worthwhile improvements to the UX.

**Comment by mattsherman** [comment]
Remaining unchecked AC need separate issues created for them.

**Comment by mattsherman** [comment]
Could we move to the core [`FormTokenField`](https://wordpress.github.io/gutenberg/?path=/docs/components-formtokenfield--docs) for the attribute value field?

**Comment by mattsherman** [comment]
We should decide whether to move to core components for these fields before making changes, and verify what behavior we want.

@j111q Can you please review the Add Attributes modal and see if we can move to core components to provide functionality and consistency with the rest of WP?

**Comment by j111q** [comment]
The four unchecked ACs above are still valid IMO, and agree that the [FormTokenField](https://wordpress.github.io/gutenberg/?path=/docs/components-formtokenfield--docs) looks like it would provide the functionality we're looking for! 👀

**Comment by pmcpinto** [comment]
I'm going to close this for now, as it refers to the new editor.
