### ISSUE TITLE
Select Control (Epic): Refactor and consolidate logic

### ISSUE THREAD

**Issue by joshuatf** [woothemes/woocommerce#38226]
## Problem

This issue will act as an epic to house other issues around the `__experimentalSelectControl` and `__experimentalSelectTreeControl` components.  There are two main issues we're facing with these components:

1. We are duplicating a heavy amount of logic between these two components and should consolidate the efforts to reduce maintenance going forward.
2. Downshift's API has been more limiting than we anticipated and we need to apply workarounds to create our blur/focus/selection logic.

## Solution

We should strive to share as much code as possible between these components and break this into meaningful chunks that are reusable.

We can do this with a combination of hooks and pre-made components that handle the default render.  If we are careful to decouple the render from the selection logic, we can make these components much more composable reducing limitations moving forward.

This may look something like this:

```js
const {
	isOpen,
	selected,
	select,
	remove,
	comboBoxProps,
	getItemProps,
	menuProps,
} = useDropdown(
	items: [ ... ]
	initialSelected: [],
	multiple: true,
);
return <>
	<ComboBox { ...comboBoxProps }>
		<Menu { ...menuProps } />
		<SelectedItems items={ selected } />
	</ComboBox>
</>
```

## Issues

```[tasklist]
### Tasks
- [ ] #38364
- [ ] Add a draft title or issue reference here
- [ ] Create dropdown hook to house selected item status and item props
- [ ] Create remove method in dropdown hook and connect to the selected item tags
- [ ] Create menu open status in dropdown hook and respective event handlers for blur/focus
- [ ] Create combobox props in dropdown hook
- [ ] Create menu props in dropdown hook
- [ ] #35851
- [ ] Create highlighted item status and keyboard handlers for highlighting items
- [ ] Create keyboard handlers for focusing tags and remove buttons
- [ ] https://github.com/woocommerce/woocommerce/issues/38229
- [ ] https://github.com/woocommerce/woocommerce/issues/38231
- [ ] https://github.com/woocommerce/woocommerce/issues/38227
- [ ] https://github.com/woocommerce/woocommerce/issues/38232
```

**Comment by joshuatf** [comment]
Closing this epic in favor of the `FormTokenField` component from GB in https://github.com/woocommerce/woocommerce/issues/45295.

I've left the child issues open and left references to the above issue where related.
