### ISSUE TITLE
Collect feedback + tracking

### ISSUE THREAD

**Issue by tommyshellberg** [woothemes/woocommerce#38411]
Add Feedback mechanism:

- [x] A simple Thumbs-Up/Thumbs-Down icon?

Add Tracks events for the following:

- [x] Every time a user clicks the "Make it for me" button.
- [x] When a user clicks on a feedback feature (good/bad).
- [x] When a description is successfully generated.
- [ ] When a description fails to generate.

We'll also want to figure out what data to send since things like blog_id won't automatically be sent as part of the Tracks event.

**Comment by tommyshellberg** [comment]
Completed.
