### ISSUE TITLE
Product Block Editor: (Epic) Description editor add fixed block toolbar header

### ISSUE THREAD

**Issue by louwie17** [woothemes/woocommerce#38422]
**Description**

The edit description modal currently doesn't contain the fixed block toolbar that allows you to add new blocks.
We should add this to the description edit modal.
The toolbar should support adding a new block with the left side pop out and viewing the full list of blocks.

It should also include the undo/redo buttons if that is easy to add, given we are using a custom provider for this, this may work out of the box.

**Issues**

* [x] [Product Block Editor: Add modal editor toolbar and block appender#38486](https://github.com/woocommerce/woocommerce/issues/38486)
* [x] [Product Block Editor: Add interaction mode button to modal editor toolbar#38487](https://github.com/woocommerce/woocommerce/issues/38487)
* [x] [Product Block Editor: Add undo/redo buttons to the modal editor toolbar#38488](https://github.com/woocommerce/woocommerce/issues/38488)
* [x] [Product Block Editor: Add the list view component and button to the modal editor#38489](https://github.com/woocommerce/woocommerce/issues/38489)

**Designs**

![Image](https://user-images.githubusercontent.com/2240960/240592321-bcc127cf-2275-48f8-82ae-ba376b55a3c2.png)

AkVNGImLgSqCObTQ3idVn7-fi-305_38548

**Acceptance criteria**

- [ ] The fixed block toolbar should be present in the description edit modal, show the `Toggle block inserter`, `Tools`, `Undo`, `Redo`, and `Document overview` buttons.

**Comment by joshuatf** [comment]
@jarekmorawski just confirming that we want to add the list view/document outline (right-most button in the above toolbar).  We'll need to add that component as well for the button to work.

**Comment by joshuatf** [comment]
cc @jarekmorawski just checking to see if you saw the above.

**Comment by jarekmorawski** [comment]
I thought I saw a ping about this, but I couldn't find it later. 🙈 I don't think we need the outline for the i1. We can add it later based on user feedback.

**Comment by tomxygen** [comment]
Hi @jarekmorawski @joshuatf 
Here is the first user feedback.
I’ve been trying to use the new product editor experience with Gutenberg in product description but unfortunately it’s very complicated to use it without that toolbar.
The “+” button is very important to see the list of all the available blocks, so that I don’t have to remember all their names.
And the hamburger menu to show all the blocks and their hierarchy inside the page is vital to be able to select for example the columns block and apply customizations.

What I’ve been doing ultimately to create graphical product descriptions is to create a new page, create the product description, copy all the blocks and paste them into the product description.

**Comment by jarekmorawski** [comment]
Thanks for sharing your thoughts, @tomxygen. You raise a good point; the list view can be life-saving for complex layouts that use groups and columns. Let's go ahead and add it, then, @joshuatf. As for the plus button, we'll definitely have it. 👍 We're still working on the description editor. The end goal is to have full functionality of the post editor.

**Comment by tomxygen** [comment]
Oh wow, that was swift ahaha! Thanks @jarekmorawski 

Also, I do have another question regarding product description and the block editor.
I’m not talking for myself here, because I really do enjoy using the block editor for any kind of product description, even basic text.
However, I do understand that there may be many merchants that don’t really need the complexity of the block editor for writing plain text product description.
Do you have any plans to tackle this specific scenario? 
Maybe just show a text field for basic product descriptions and then a button that says something like “edit in the block editor” or something like that for visual and complex descriptions?
