### ISSUE TITLE
[Epic] Product Editor: More menu item in description editor modal

### ISSUE THREAD

**Issue by louwie17** [woothemes/woocommerce#39024]
Let's add the missing buttons to the description editing modal's header.
This issue focuses only on adding the more button to the description editor modal, with some of the basic options that are easy to add. We can do a follow up for any of the more complicated options.

**Design**

AkVNGImLgSqCObTQ3idVn7-fi-1005_134542 

<img width="594" alt="Screenshot 2023-07-10 at 16 40 46" src="https://github.com/woocommerce/woocommerce/assets/2098816/26e5b576-6451-4dc7-b6f2-fbd920bf00b4">

**Child issues**

- [ ] Top Toolbar
- [ ] Spotlight Mode
- [ ] Visual editor and Code editor
- [x] https://github.com/woocommerce/woocommerce/issues/39131
- [x] https://github.com/woocommerce/woocommerce/issues/39183
- [x] https://github.com/woocommerce/woocommerce/issues/39181

**Acceptance criteria**

- [ ] There's a more button in the header. It contains the same options as the post editor*

*not all options will be added in this issue, only the ones that are simple (should be mentioned in the PR description )

**Comment by pmcpinto** [comment]
I'm going to close this one. It refers to the new editor that will be removed.
