### ISSUE TITLE
still variation data on variable product under post meta table.

### ISSUE THREAD

**Issue by sumitsinghwp** [woothemes/woocommerce#39378]
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

the issue is I am creating custom code based on all variation product listings and getting variation names & values from databases post meta field under the variation product ID, even though I have removed the attribute from the Attribute tab. 

https://github.com/woocommerce/woocommerce/assets/23701579/ef0b0cf5-f6ca-43ba-af0d-acb6a829d725

For more information, you can see the mentioned video.

### Expected behavior

When i removed the attribute then it should be removed from all variation post meta entry.

### Actual behavior

When I removed the attribute then it should be not removed from all variations post meta entry.

### Steps to reproduce

You can creating a variation product and see issue with mentioned quick shared recorded video.

https://github.com/woocommerce/woocommerce/assets/23701579/1759b655-8636-4cb0-a7b7-86483598dc2d

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://hz2pvs9n6g-staging.onrocket.site
Site address (URL): https://hz2pvs9n6g-staging.onrocket.site
WC Version: 7.8.2
REST API Version: ✔ 7.8.2
WC Blocks Version: ✔ 10.2.4
Action Scheduler Version: ✔ 3.6.1
Log Directory Writable: ✔
WP Version: ❌ 6.1.3 - There is a newer version of WordPress available (6.2.2)
WP Multisite: –
WP Memory Limit: 1 GB
WP Debug Mode: –
WP Cron: ✔
Language: en_GB
External object cache: ✔

### Server Environment ###

Server Info: Apache
PHP Version: 7.4.33
PHP Post Max Size: 100 MB
PHP Time Limit: 600
PHP Max Input Vars: 100000
cURL Version: 7.87.0
OpenSSL/1.1.1p

SUHOSIN Installed: –
MySQL Version: 8.0.34
Max Upload Size: 100 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 6.6.1
WC Database Prefix: wp_
Total Database Size: 612.68MB
Database Data Size: 474.51MB
Database Index Size: 138.17MB
wp_woocommerce_sessions: Data: 93.63MB + Index: 5.50MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.14MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 1.52MB + Index: 1.97MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
FileVersions: Data: 1.52MB + Index: 1.72MB + Engine InnoDB
auth_group: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
auth_group_permissions: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
auth_permission: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
auth_user: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
auth_user_groups: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
auth_user_user_permissions: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
diamondProducts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
django_admin_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
django_content_type: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
django_migrations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
django_session: Data: 0.31MB + Index: 0.02MB + Engine InnoDB
websr_constant_settings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
websr_cron_info: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
websr_currency_settings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
websr_diamondData: Data: 29.56MB + Index: 0.00MB + Engine InnoDB
websr_diamond_default_info: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
websr_diamond_feed_credentials: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
websr_diamond_import_log: Data: 21.55MB + Index: 2.52MB + Engine InnoDB
websr_idex_settings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
websr_login_logs_details: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
websr_marginal_markup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
websr_markup_settings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
websr_price_markup_details: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
websr_sold_diamond_details: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
websr_supplier_details: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
websr_user_api_details: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 1.06MB + Index: 0.95MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.34MB + Index: 0.33MB + Engine InnoDB
wp_adtribes_my_conversions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_berocket_termmeta: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_booking: Data: 0.11MB + Index: 0.00MB + Engine InnoDB
wp_bookingdates: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_braapf_product_stock_status_parent: Data: 0.28MB + Index: 0.13MB + Engine InnoDB
wp_braapf_product_variation_attributes: Data: 0.14MB + Index: 0.42MB + Engine InnoDB
wp_braapf_term_taxonomy_hierarchical: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_braapf_variable_attributes: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_ce4wp_abandoned_checkout: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_cli_cookie_scan: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_cli_cookie_scan_categories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_cli_cookie_scan_cookies: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_cli_cookie_scan_url: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_cli_scripts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.44MB + Index: 0.41MB + Engine InnoDB
wp_css_js_manager: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_cwv_criticalfiles: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_cwv_criticalrules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_cwv_scriptrules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_db7_forms: Data: 1.52MB + Index: 0.00MB + Engine InnoDB
wp_ff_scheduled_actions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_fluentform_draft_submissions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_fluentform_entry_details: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_fluentform_form_analytics: Data: 3.52MB + Index: 0.00MB + Engine InnoDB
wp_fluentform_form_meta: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_fluentform_forms: Data: 0.09MB + Index: 0.00MB + Engine InnoDB
wp_fluentform_logs: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_fluentform_order_items: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_fluentform_submission_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_fluentform_submissions: Data: 0.08MB + Index: 0.00MB + Engine InnoDB
wp_fluentform_subscriptions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_fluentform_transactions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_fsmpt_email_logs: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_ig_actions: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_ig_blocked_emails: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_ig_campaigns: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_ig_contact_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_ig_contactmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_ig_contacts: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_ig_contacts_ips: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_ig_custom_fields: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_ig_forms: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_ig_links: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_ig_lists: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_ig_lists_contacts: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_ig_mailing_queue: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_ig_queue: Data: 0.02MB + Index: 0.13MB + Engine InnoDB
wp_ig_sending_queue: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_ig_temp_import: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_ig_unsubscribe_feedback: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_ig_workflows: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_ig_workflows_queue: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_litespeed_avatar: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_litespeed_crawler: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_litespeed_crawler_blacklist: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_litespeed_cssjs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_litespeed_img_optm: Data: 8.52MB + Index: 4.03MB + Engine InnoDB
wp_litespeed_img_optming: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_litespeed_url: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_litespeed_url_file: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_mailchimp_carts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailchimp_jobs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mgmlp_folders: Data: 0.17MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 9.45MB + Index: 0.27MB + Engine InnoDB
wp_pmxe_exports: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_pmxe_google_cats: Data: 0.39MB + Index: 0.00MB + Engine InnoDB
wp_pmxe_posts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_pmxe_templates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_files: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_hash: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_history: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_images: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_imports: Data: 0.44MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_posts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_templates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_postmeta: Data: 186.66MB + Index: 27.11MB + Engine InnoDB
wp_posts: Data: 51.52MB + Index: 7.06MB + Engine InnoDB
wp_prli_clicks: Data: 0.02MB + Index: 0.19MB + Engine InnoDB
wp_prli_link_metas: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_prli_links: Data: 0.02MB + Index: 0.17MB + Engine InnoDB
wp_rank_math_404_logs: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_rank_math_analytics_ga: Data: 1.52MB + Index: 1.52MB + Engine InnoDB
wp_rank_math_analytics_gsc: Data: 11.02MB + Index: 24.61MB + Engine InnoDB
wp_rank_math_analytics_inspections: Data: 2.52MB + Index: 0.78MB + Engine InnoDB
wp_rank_math_analytics_keyword_manager: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_rank_math_analytics_objects: Data: 1.52MB + Index: 0.48MB + Engine InnoDB
wp_rank_math_internal_links: Data: 0.11MB + Index: 0.05MB + Engine InnoDB
wp_rank_math_internal_meta: Data: 0.28MB + Index: 0.00MB + Engine InnoDB
wp_redirection_404: Data: 0.08MB + Index: 0.05MB + Engine InnoDB
wp_redirection_groups: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_redirection_items: Data: 0.11MB + Index: 0.13MB + Engine InnoDB
wp_redirection_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_smush_dir_images: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 1.52MB + Index: 1.52MB + Engine InnoDB
wp_term_taxonomy: Data: 0.08MB + Index: 0.09MB + Engine InnoDB
wp_termmeta: Data: 2.52MB + Index: 0.19MB + Engine InnoDB
wp_terms: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_tinvwl_analytics: Data: 0.25MB + Index: 0.14MB + Engine InnoDB
wp_tinvwl_items: Data: 0.17MB + Index: 0.00MB + Engine InnoDB
wp_tinvwl_lists: Data: 0.08MB + Index: 0.00MB + Engine InnoDB
wp_tm_taskmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_tm_tasks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_tps_setting: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_user_registration_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_usermeta: Data: 1.52MB + Index: 3.03MB + Engine InnoDB
wp_users: Data: 0.09MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.09MB + Index: 0.06MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.11MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.11MB + Index: 0.08MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.08MB + Index: 0.09MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.28MB + Index: 0.28MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 1.52MB + Index: 1.20MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wpf_filters: Data: 0.25MB + Index: 0.00MB + Engine InnoDB
wp_wpf_meta_data: Data: 19.55MB + Index: 37.58MB + Engine InnoDB
wp_wpf_meta_keys: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wpf_meta_values: Data: 2.52MB + Index: 3.03MB + Engine InnoDB
wp_wpf_meta_values_bk: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wpf_modules: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wpf_modules_type: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpf_usage_stat: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wpfm_backup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpgb_cards: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wpgb_facets: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wpgb_grids: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wpgb_index: Data: 0.17MB + Index: 0.28MB + Engine InnoDB
wp_wpmailsmtp_debug_events: Data: 0.09MB + Index: 0.00MB + Engine InnoDB
wp_wpmailsmtp_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wt_iew_action_history: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_wt_iew_cron: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wt_iew_ftp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wt_iew_mapping_template: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_yoast_indexable: Data: 8.52MB + Index: 7.05MB + Engine InnoDB
wp_yoast_indexable_hierarchy: Data: 0.17MB + Index: 0.30MB + Engine InnoDB
wp_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yoast_primary_term: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_yoast_seo_links: Data: 1.52MB + Index: 0.42MB + Engine InnoDB

### Post Type Counts ###

acf-field: 74
acf-field-group: 5
attachment: 19457
br_filters_group: 19
br_product_filter: 35
ct_template: 78
custom_css: 3
es_template: 2
fusion_element: 82
fusion_tb_layout: 1
fusion_tb_section: 6
mc4wp-form: 1
mgmlp_media_folder: 35
nav_menu_item: 59
oembed_cache: 60
page: 93
popup: 2
popup_theme: 8
post: 56
product: 5955
product_categories: 88
product_variation: 725
rank_math_schema: 1
revision: 1833
shop_order: 622
slide: 29
user_registration: 1
viwec_template: 14
wp_block: 242
wp_global_styles: 2
wpcf7_contact_form: 8
wpgmapembed: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (52) ###

ManageWP - Worker: by GoDaddy – 4.9.17
Advanced Scripts: by Clean Plugins – 2.4.1
WooCommerce added to cart popup (Ajax): by XootiX – 1.7
Advanced Custom Fields PRO: by WP Engine – 6.1.7
Advanced Product Fields for WooCommerce: by StudioWombat – 1.6.3
Automatic.css: by Kevin Geary
Matteo Greco – 1.3.2

CookieYes | GDPR Cookie Consent: by CookieYes – 3.1.1
Category Builder Products List and Filter Functionality: by Group6 Interactive – 1.0.0
Custom Post Type UI: by WebDevStudios – 1.13.7
Date and Time Picker by Input WP: by Input WP – 2.2
GTM4WP: by Thomas Geiger – 1.16.2
Email Template Customizer for WooCommerce: by VillaTheme – 1.2.0
File Manager Advanced: by modalweb – 5.1
FluentSMTP: by FluentSMTP & WPManageNinja Team – 2.2.5
Fluent Forms: by Contact Form - WPManageNinja LLC – 5.0.6
Fluent Forms Pro Add On Pack: by Fluent Forms – 5.0.3
FlyingPress: by  – 4.6.1
Guest Order Tracking for WooCommerce: by Algoritmika Ltd – 2.1.2
Ingle & Rhode Woocommerce Templates: by Group6 Interactive – 1.0.0
Layout Grid: by Automattic – 1.8.4
MC4WP: Mailchimp for WordPress: by ibericode – 4.9.6
Object Cache Pro: by Rhubarb Group – 1.18.2
Oxy Toolbox: by Gagan S Goraya
Sridhar Katakam – 1.5.9

OxyExtras: by OxyExtras – 1.4.3
Oxygen Elements for WooCommerce: by Soflyy – 2.0
Oxygen: by Soflyy – 4.6.2
Perfmatters: by forgemedia – 2.1.3
Permalink Manager Pro: by Maciej Bis – 2.4.1.2
Redirection: by John Godley – 5.3.10
Search Regex: by John Godley – 3.0.6
Rank Math SEO PRO: by Rank Math – 3.0.40
Rank Math SEO: by Rank Math – 1.0.119.1
Simple Cloudflare Turnstile: by Elliot Sowersby
RelyWP – 1.22.1

SVG Support: by Benbodhi – 2.5.5
Temporary Login Without Password: by StoreApps – 1.8.2
TI WooCommerce Wishlist: by TemplateInvaders – 2.7.2
TPS Bespoke Ring: by Transpacific software – 1.0
TPS Jewellery: by Transpacific software – 1.0
TPS Ringbuilder: by Transpacific software – 1.0
TPS Ready To Wear: by Transpacific software – 1.0
User Registration: by WPEverest – 3.0.2.1
Premmerce Permalink Manager for WooCommerce: by Premmerce – 2.3.8
Product Feed PRO for WooCommerce: by AdTribes.io – 12.7.8
Product Filter by WBW: by WBW – 2.3.9
Additional Variation Images Gallery for WooCommerce: by Emran Ahmed – 1.3.13
Variation Swatches for WooCommerce: by Emran Ahmed – 1.1.19
WooCommerce AJAX Products Filter: by BeRocket – 3.1.4.4
WooCommerce Stripe Gateway: by WooCommerce – 7.4.1
WooCommerce Google Analytics Integration: by WooCommerce – 1.8.3
WooCommerce: by Automattic – 7.8.2 (update to version 7.9.0 is available)
TPS Loose diamond: by Transpacific software PVT LTD – 1.0.0
WPC Show Single Variations for WooCommerce: by WPClever – 2.3.2

### Inactive Plugins (5) ###

Contact Form 7: by Takayuki Miyoshi – 5.7.7
Contact Form CFDB7: by Arshid – 1.2.6.6
GP Premium: by Tom Usborne – 2.1.1
HandL UTM Grabber: by Haktan Suren – 2.7.26
WP Mail SMTP: by WP Mail SMTP – 3.8.0

### Dropin Plugins (2) ###

advanced-cache.php: advanced-cache.php
object-cache.php: Object Cache Pro (Drop-in)

### Must Use Plugins (2) ###

CDN Cache Plugin: by  – 1.1.3
ManageWP - Worker Loader: by GoDaddy – 1.0.0

### Settings ###

API Enabled: –
Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: –
HPOS feature screen enabled: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### WC Pages ###

Shop base: #6 - /shop
Basket: ❌ Page does not contain the [woocommerce_cart] shortcode or the woocommerce/cart block.
Checkout: #8 - /checkout
My account: #9 - /my-account
Terms and conditions: #6766 - /delivery-and-returns

### Theme ###

Name: GeneratePress Child
Version: 0.1
Author URL: https://tomusborne.com
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build
personally we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: /home/hz2pqbn/public_html/hz2pvs9n6g-staging.onrocket.site/wp-content/plugins/woo-variation-gallery/templates/product-images.php version 3.5.1 is out of date. The core version is 7.8.0
/home/hz2pqbn/public_html/hz2pvs9n6g-staging.onrocket.site/wp-content/plugins/woo-variation-gallery/templates/product-thumbnails.php

Outdated Templates: ❌
					
					
						Learn how to update

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: core-profiler
minified-js
new-product-management-experience
product-variation-management
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2023-07-25 07:07:10 +01:00
Options: ✔
Notes: 18
Onboarding: completed

### TI WooCommerce Wishlist Templates ###

Overrides: –

### Action Scheduler ###

Canceled: 43
Oldest: 2023-06-27 05:26:05 +0100
Newest: 2023-07-19 05:15:52 +0100

Complete: 190
Oldest: 2023-06-27 05:24:23 +0100
Newest: 2023-07-24 08:58:00 +0100

Failed: 11
Oldest: 2023-03-22 07:45:32 +0000
Newest: 2023-07-17 06:36:32 +0100

Pending: 3
Oldest: 2023-07-24 11:04:50 +0100
Newest: 2023-07-30 07:10:06 +0100

### Status report information ###

Generated at: 2023-07-24 09:03:05 +01:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by rrennick** [comment]
Hi @sumitsinghwp , Thanks for creating the issue. It looks like this is another facet of #32533. As a result I'll close this as a duplicate.
