### ISSUE TITLE
[Epic]: Increasing E2E test coverage to the block editor

### ISSUE THREAD

**Issue by octaedro** [woothemes/woocommerce#39407]
We will add E2E test coverage to the new block editor. 

## Tests to add

```[tasklist]
### Tasks
- [ ] #39417
- [ ] #39442
- [ ] #39411
- [ ] #39412
- [ ] #39413
- [ ] #39414
- [ ] #39415
- [ ] #39416
```

- [x] Menu - Can turn off the new product form https://github.com/woocommerce/woocommerce/issues/39417.
- [x] Menu - Can enable the new product form https://github.com/woocommerce/woocommerce/issues/39442.
- [x] Can create and edit a product https://github.com/woocommerce/woocommerce/issues/39411.
- [x] Organization tab - Can create categories, child categories, and unselect categories. Can add, edit and delete multiple attributes. Can `Enable product reviews` https://github.com/woocommerce/woocommerce/issues/39412.
- [ ] Pricing tab - Can set `Sale price`, add `Schedule sale` and modify the option `Charge sales tax on` and the `Advanced` settings https://github.com/woocommerce/woocommerce/issues/39413.
- [ ] Inventory tab - Can modify the SKU, the `Stock status` option, and the advanced settings https://github.com/woocommerce/woocommerce/issues/39414.
- [ ] Shipping tab - Can modify the `Shipping class` option and set product dimensions https://github.com/woocommerce/woocommerce/issues/39415.
- [ ] Variations tab - Is `Variations` tab content visible https://github.com/woocommerce/woocommerce/issues/39416.

**Comment by pmcpinto** [comment]
I'm going to close this one. It refers to the new editor that will be removed.
