### ISSUE TITLE
HPOS sync did not include all order meta

### ISSUE THREAD

**Issue by tomektomczuk** [woothemes/woocommerce#40288]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

I have synced my previous order to the new HPOS feature. 

After that, I checked some of my previous orders just to realize that not all of the data were synced.

I have attached a print screen for the same order on both tables 

<img width="375" alt="Screenshot 2023-09-19 at 22 35 41" src="https://github.com/woocommerce/woocommerce/assets/40096666/1e84f5c3-261b-46b3-b7f1-a86a797d21b4">
<img width="699" alt="Screenshot 2023-09-19 at 22 34 13" src="https://github.com/woocommerce/woocommerce/assets/40096666/a4ec5548-6981-452e-903b-f592e89a3683">
<img width="717" alt="Screenshot 2023-09-19 at 22 30 06" src="https://github.com/woocommerce/woocommerce/assets/40096666/89357e29-fbf6-4bb1-81d6-f870e3eef2c5">
<img width="785" alt="Screenshot 2023-09-19 at 22 31 02" src="https://github.com/woocommerce/woocommerce/assets/40096666/05eca7e5-8f58-42e1-bbe5-59ec4b1bb882">

### Expected behavior

wc_orders_meta table should contain all of custom meta that are on a woocommerce_order_itemmeta table

### Actual behavior

old order did not fully sync with HPOS tables

### Steps to reproduce

you would have to create some orders without HPOS. The order should have a custom meta added through 
wc_add_order_item_meta() through woocommerce_new_order_item hook action. then sync your old order to get new HPOS (woocommerce -> advance settings -> features)

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): http://uh.local
Site address (URL): http://uh.local
WC Version: 8.1.1
REST API Version: ✔ 8.1.1
WC Blocks Version: ✔ 10.9.3
Action Scheduler Version: ✔ 3.6.2
Log Directory Writable: ✔
WP Version: 6.3.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.16.0
PHP Version: 8.2.10
PHP Post Max Size: 1,000 MB
PHP Time Limit: 1200
PHP Max Input Vars: 4000
cURL Version: 8.1.2
(SecureTransport) LibreSSL/3.3.6

SUHOSIN Installed: –
MySQL Version: 8.0.16
Max Upload Size: 300 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.1.1
WC Database Prefix: wp_
Total Database Size: 294.96MB
Database Data Size: 232.55MB
Database Index Size: 62.41MB
wp_woocommerce_sessions: Data: 0.33MB + Index: 0.02MB + Engine MyISAM
wp_woocommerce_api_keys: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_order_items: Data: 0.18MB + Index: 0.07MB + Engine MyISAM
wp_woocommerce_order_itemmeta: Data: 2.17MB + Index: 1.61MB + Engine MyISAM
wp_woocommerce_tax_rates: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_ac_segments: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_actionscheduler_actions: Data: 2.77MB + Index: 1.55MB + Engine MyISAM
wp_actionscheduler_claims: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_actionscheduler_groups: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_actionscheduler_logs: Data: 1.95MB + Index: 1.47MB + Engine MyISAM
wp_admin_columns: Data: 0.01MB + Index: 0.00MB + Engine MyISAM
wp_commentmeta: Data: 0.02MB + Index: 0.02MB + Engine MyISAM
wp_comments: Data: 1.35MB + Index: 0.63MB + Engine MyISAM
wp_defender_audit_log: Data: 3.52MB + Index: 2.91MB + Engine InnoDB
wp_defender_email_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_defender_lockout: Data: 0.47MB + Index: 0.64MB + Engine InnoDB
wp_defender_lockout_log: Data: 0.06MB + Index: 0.06MB + Engine InnoDB
wp_defender_quarantine: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_defender_scan: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_defender_scan_item: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gf_addon_feed: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_gf_addon_payment_callback: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_gf_addon_payment_transaction: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_gf_draft_submissions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_gf_entry: Data: 0.03MB + Index: 0.01MB + Engine MyISAM
wp_gf_entry_meta: Data: 0.12MB + Index: 0.08MB + Engine MyISAM
wp_gf_entry_notes: Data: 0.02MB + Index: 0.01MB + Engine MyISAM
wp_gf_form: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_gf_form_meta: Data: 0.25MB + Index: 0.00MB + Engine MyISAM
wp_gf_form_revisions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_gf_form_view: Data: 0.07MB + Index: 0.03MB + Engine MyISAM
wp_gf_rest_api_keys: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_gspc_form_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_hustle_entries: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_hustle_entries_meta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_hustle_modules: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_hustle_modules_meta: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_hustle_tracking: Data: 0.60MB + Index: 0.61MB + Engine MyISAM
wp_icl_background_task: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_icl_content_status: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_icl_core_status: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_icl_flags: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_icl_languages: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_icl_languages_translations: Data: 0.11MB + Index: 0.12MB + Engine MyISAM
wp_icl_locale_map: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_icl_message_status: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_icl_mo_files_domains: Data: 0.09MB + Index: 0.02MB + Engine InnoDB
wp_icl_node: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_icl_reminders: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_icl_string_batches: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_icl_string_packages: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_icl_string_positions: Data: 0.02MB + Index: 0.01MB + Engine MyISAM
wp_icl_string_status: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_icl_string_translations: Data: 3.49MB + Index: 1.72MB + Engine MyISAM
wp_icl_strings: Data: 2.79MB + Index: 2.35MB + Engine MyISAM
wp_icl_translate: Data: 2.36MB + Index: 0.04MB + Engine MyISAM
wp_icl_translate_job: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_icl_translation_batches: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_icl_translation_downloads: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_icl_translation_status: Data: 1.86MB + Index: 0.65MB + Engine MyISAM
wp_icl_translations: Data: 1.87MB + Index: 3.56MB + Engine MyISAM
wp_jet_post_types: Data: 0.01MB + Index: 0.00MB + Engine MyISAM
wp_jet_smart_filters_indexer: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_jet_taxonomies: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_levcharity_confirmations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_levcharity_ecards_queue: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_levcharity_emails: Data: 0.11MB + Index: 0.00MB + Engine InnoDB
wp_levcharity_emails_queue: Data: 10.52MB + Index: 0.00MB + Engine InnoDB
wp_links: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_options: Data: 6.31MB + Index: 0.09MB + Engine MyISAM
wp_pmxe_exports: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_pmxe_google_cats: Data: 0.26MB + Index: 0.05MB + Engine MyISAM
wp_pmxe_posts: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_pmxe_templates: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_pmxi_files: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_pmxi_hash: Data: 0.12MB + Index: 0.08MB + Engine MyISAM
wp_pmxi_history: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_pmxi_images: Data: 0.76MB + Index: 0.07MB + Engine MyISAM
wp_pmxi_imports: Data: 0.07MB + Index: 0.00MB + Engine MyISAM
wp_pmxi_posts: Data: 0.05MB + Index: 0.02MB + Engine MyISAM
wp_pmxi_templates: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_postmeta: Data: 109.31MB + Index: 11.59MB + Engine MyISAM
wp_posts: Data: 23.37MB + Index: 3.72MB + Engine MyISAM
wp_rank_math_404_logs: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_rank_math_internal_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_rank_math_internal_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_rank_math_redirections: Data: 0.11MB + Index: 0.02MB + Engine InnoDB
wp_rank_math_redirections_cache: Data: 0.30MB + Index: 0.13MB + Engine InnoDB
wp_salesforce_actions: Data: 0.09MB + Index: 0.00MB + Engine InnoDB
wp_sgs_log_events: Data: 45.58MB + Index: 16.59MB + Engine InnoDB
wp_sgs_log_visitors: Data: 0.38MB + Index: 0.41MB + Engine InnoDB
wp_smush_dir_images: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_term_relationships: Data: 0.62MB + Index: 1.19MB + Engine MyISAM
wp_term_taxonomy: Data: 0.20MB + Index: 0.19MB + Engine MyISAM
wp_termmeta: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_terms: Data: 0.19MB + Index: 0.27MB + Engine MyISAM
wp_uh_cad_transaction_ids: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_uh_eur_transaction_ids: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_uh_usd_transaction_ids: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_usermeta: Data: 0.33MB + Index: 0.18MB + Engine MyISAM
wp_users: Data: 0.02MB + Index: 0.02MB + Engine MyISAM
wp_wc_admin_note_actions: Data: 0.03MB + Index: 0.01MB + Engine MyISAM
wp_wc_admin_notes: Data: 0.05MB + Index: 0.00MB + Engine MyISAM
wp_wc_category_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_customer_lookup: Data: 0.10MB + Index: 0.09MB + Engine MyISAM
wp_wc_download_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_order_addresses: Data: 0.41MB + Index: 0.78MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_order_operational_data: Data: 0.39MB + Index: 0.23MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.24MB + Index: 0.21MB + Engine MyISAM
wp_wc_order_stats: Data: 0.19MB + Index: 0.13MB + Engine MyISAM
wp_wc_order_tax_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_orders: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_wc_orders_meta: Data: 0.14MB + Index: 0.22MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wc_product_meta_lookup: Data: 0.01MB + Index: 0.03MB + Engine MyISAM
wp_wc_rate_limits: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_reserved_stock: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_tax_rate_classes: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wc_webhooks: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wp_phpmyadmin_extension__errors_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wpfm_backup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wpie_template: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpmailsmtp_debug_events: Data: 0.13MB + Index: 0.00MB + Engine InnoDB
wp_wpmailsmtp_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpml_mails: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpr_rocket_cache: Data: 2.52MB + Index: 3.22MB + Engine InnoDB
wp_wpr_rucss_used_css: Data: 2.52MB + Index: 4.08MB + Engine InnoDB
wp_wrc_caches: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wrc_relations: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wt_iew_action_history: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wt_iew_mapping_template: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_yoast_indexable: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_yoast_indexable_hierarchy: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yoast_primary_term: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_yoast_seo_links: Data: 0.02MB + Index: 0.03MB + Engine InnoDB

### Post Type Counts ###

acf-field: 15
advance-event-form: 15
attachment: 30602
charity-donation: 16
ecard: 18
event: 1
event-form: 1
flickr_gallery: 1
gala-form: 1
groovy_menu_preset: 1
jet-engine: 19
jet-menu: 23
jet-smart-filters: 1
job: 10
jobs: 17
movies: 2
nav_menu_item: 87
oembed_cache: 20
page: 79
patterns: 24
podcast: 1
post: 2
press: 118
product: 261
product_variation: 1543
program: 16
revision: 65
shop_order: 2561
shop_order_refund: 1
shop_subscription: 7
stories: 1422
team: 56
wporg_product: 1
wp_block: 26
wp_global_styles: 4
wp_navigation: 30
wp_template: 10
wp_template_part: 10

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (46) ###

Gravity Forms: by Gravity Forms – 2.7.13
WPML Multilingual CMS: by OnTheGoSystems – 4.6.5
Accordion Gutenberg Block: by the LeverageIT team – 1.1.0
Add To Cart Levit Button: by the LeverageIT team – 1.0.0
All-in-One WP Migration Unlimited Extension: by ServMask – 2.53
All-in-One WP Migration: by ServMask – 7.78
Checkout Field Editor and Manager for WooCommerce: by Acowebs – 2.2.15
Countdown Gutenberg Block: by the LeverageIT team – 1.1.0
Crocoblock Wizard: by Crocoblock – 1.1.0
Gallery Gutenberg Block: by the LeverageIT team – 1.1.0
Google Map Gutenberg Block: by the LeverageIT team – 1.0.4
Gravity Forms Advanced Post Creation Add-On: by Gravity Forms – 1.4.0
GS Product Configurator: by Gravity Wiz – 1.0-beta-1.5
Gutenberg Additional Settings: by the LeverageIT team – 1.4.7
Hustle Pro: by WPMU DEV – 4.8.1
The Icon Block: by Nick Diego – 1.6.0
JetEngine: by Crocoblock – 3.2.5
JetMenu: by Crocoblock – 2.4.0
JetSmartFilters: by Crocoblock – 3.2.1
LevCharity Campaigns: by the LeverageIT team – 1.0.0
LevCharity Donation Equipment: by the LeverageIT team – 1.0.0
LevCharity E-Cards: by the LeverageIT team – 1.0.0
LevCharity Emails: by the LeverageIT team – 1.0.0
LevCharity Events: by the LeverageIT team – 1.0.0
LevCharity Gateways: by the LeverageIT team – 1.0.0
LevCharity Gravity Form Product: by the LeverageIT team – 1.0.0
LevCharity Offline: by the LeverageIT team – 1.0.0
LevCharity P2P Campaigns: by the LeverageIT team – 1.0.0
LevCharity: by the LeverageIT team – 1.0.0
Levit Flickr Albums List: by the LeverageIT team – 1.0.0
Query Link Wrapper Gutenberg Block: by the LeverageIT team – 1.0.4
Query List Gutenberg Block: by the LeverageIT team – 1.1.1
Safe SVG: by 10up – 2.2.0
Swiper Gutenberg Block: by the LeverageIT team – 1.2.2
Tabs Gutenberg Block: by the LeverageIT team – 1.2.1
WooCommerce Payment Gateway - SUMIT: by OfficeGuy Ltd. – 3.2.0
WooCommerce Subscriptions: by WooCommerce – 5.3.1
WooCommerce: by Automattic – 8.1.1
WP Crontrol: by John Blackbourn & crontributors – 1.15.3
Defender Pro: by WPMU DEV – 4.1.0
WP Mail Logging: by WP Mail Logging Team – 1.12.0
WP REST Cache: by Acato – 2023.2.1
Smush Pro: by WPMU DEV – 3.14.2
WPML Media: by OnTheGoSystems – 2.7.3
WPML String Translation: by OnTheGoSystems – 3.2.7
WPMU DEV Dashboard: by WPMU DEV – 4.11.21

### Inactive Plugins (7) ###

Duplicate Page: by mndpsingh287 – 4.5.3
LevCharity Matching Campaigns: by the LeverageIT team – 1.0.0
LevCharity P2P Teams: by the LeverageIT team – 1.0.0
Toolset Types: by OnTheGoSystems – 3.4.20
User Switching: by John Blackbourn & contributors – 1.7.0
WooCommerce Gravity Forms Product Add-Ons: by Element Stark – 3.5.1
WooCommerce Multilingual & Multicurrency: by OnTheGoSystems – 5.2.0

### Must Use Plugins (1) ###

WP REST Cache - Must-Use Plugin: by Richard Korthuis - Acato – 2021.3.0

### Settings ###

API Enabled: –
Force SSL: –
Currency: ILS (₪)
Currency Position: left_space
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: campaign (campaign)
digital-ads (digital-ads)
donation (donation)
e-card (e-card)
ecard (ecard)
equipment (equipment)
event (event)
external (external)
fundraising (programs)
fundraising (general)
fundraising (fundraising)
gravity-form (gravity-form)
grouped (grouped)
p2p-campaign (p2p-campaign)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature screen enabled: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: ✔

### WC Pages ###

Shop base: #238 - /shop/
Cart: #239 - /cart/
Checkout: #240 - /checkout/
My account: #241 - /my-account/
Terms and conditions: #249 - /terms-conditions/

### Theme ###

Name: United Hatzalah
Version: 1.0.0
Author URL: https://leverage.it
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: united-hatzalah/woocommerce/cart/cart-totals.php
united-hatzalah/woocommerce/cart/cart.php
united-hatzalah/woocommerce/checkout/form-checkout.php
united-hatzalah/woocommerce/checkout/form-coupon.php
united-hatzalah/woocommerce/checkout/payment.php version 7.8.0 is out of date. The core version is 8.1.0
united-hatzalah/woocommerce/checkout/thankyou.php version 3.7.0 is out of date. The core version is 8.1.0
/Volumes/LaCie - 4TB - Twelve/websites/Local Sites/uh/app/public/wp-content/plugins/woocommerce/packages/woocommerce-blocks/templates/notices/error.php
/Volumes/LaCie - 4TB - Twelve/websites/Local Sites/uh/app/public/wp-content/plugins/woocommerce/packages/woocommerce-blocks/templates/notices/notice.php
/Volumes/LaCie - 4TB - Twelve/websites/Local Sites/uh/app/public/wp-content/plugins/woocommerce/packages/woocommerce-blocks/templates/notices/success.php

Outdated Templates: ❌
					
					
						Learn how to update

### Subscriptions ###

WCS_DEBUG: ✔ No
Subscriptions Mode: ❌ Staging
Subscriptions Live URL: http://uh.local
Subscriptions-core Library Version: 6.1.0
Subscription Statuses: wc-active: 7
WooCommerce Account Connected: ❌ No
Report Cache Enabled: ✔ Yes
Cache Update Failures: ✔ 0 failure

### Store Setup ###

Country / State: Israel

### Subscriptions by Payment Gateway ###

LevIT Authorize.Net Gateway: wc-active: 6
SUMIT: wc-active: 1

### Payment Gateway Support ###

SUMIT: products
refunds
add_payment_method
tokenization
subscriptions
subscription_cancellation
subscription_suspension
subscription_reactivation
subscription_amount_changes
subscription_date_changes
subscription_payment_method_change
subscription_payment_method_change_customer
subscription_payment_method_change_admin
multiple_subscriptions

LevIT Stripe Gateway: products
subscriptions
subscription_cancellation
subscription_suspension
subscription_reactivation
subscription_amount_changes
subscription_date_changes
subscription_payment_method_change
subscription_payment_method_change_customer
subscription_payment_method_change_admin
multiple_subscriptions

LevIT Authorize.Net Gateway: products
subscriptions
subscription_cancellation
subscription_suspension
subscription_reactivation
subscription_amount_changes
subscription_date_changes
subscription_payment_method_change
subscription_payment_method_change_customer
subscription_payment_method_change_admin
multiple_subscriptions

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: customize-store
minified-js
new-product-management-experience
product-variation-management
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2023-09-20 16:15:11 +03:00
Options: ✔
Notes: 134
Onboarding: completed

### Action Scheduler ###

Canceled: 3
Oldest: 2023-09-04 09:06:14 +0000
Newest: -0001-11-30 00:00:00 +0000

Complete: 10,672
Oldest: 2023-08-20 02:24:03 +0000
Newest: 2023-09-19 20:39:39 +0000

Failed: 55
Oldest: 2023-02-15 17:39:00 +0000
Newest: 2023-09-18 10:53:24 +0000

Pending: 16
Oldest: 2023-09-19 20:41:10 +0000
Newest: 2024-06-30 19:33:32 +0000

### Status report information ###

Generated at: 2023-09-19 23:41:33 +03:00
`

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by barryhughes** [comment]
Hi @tomektomczuk,

> wc_orders_meta table should contain all of custom meta that are on a woocommerce_order_itemmeta table

This is not actually the case. HPOS does not replace the `order_itemmeta` table: that will continue to be used, just as it is when the CPT data-store is enabled.

I see you encountered a problem, judging by the screenshot you shared, but I cannot replicate it. If for instance I add item meta data like `_display_name` to an order item, it successfully renders in the HPOS-powered order editor. I also tried:

- Disabling sync and switching back to WordPress posts storage.
- Creating a new order with some line items.
- Adding order item meta data to one of those items, ie: `wc_add_order_item_meta( 17720, '_display_name', 'Test #40288' );`.
- Re-enabling sync (compatibility mode) then, once ready, re-enabled HPOS.
- Refreshed the order editor and confirmed the association between order and order item meta was still intact:

<div align="center"><img width="600" alt="Screenshot 2023-09-19 at 14 52 57" src="https://github.com/woocommerce/woocommerce/assets/3594411/4f4ddd05-ff13-4495-a4c3-ddffd4e853f7"></div>

Is there anything else we'd need to do to see the problem?

**Comment by tomektomczuk** [comment]
Hi @barryhughes thank you for your quick reply. If HPOS does not sync data from `order_itemmeta` I would have to JOIN two more tables (`woocommerce_order_items, woocommerce_order_itemmeta`) just to get these metas. Is that the correct behaviour? Also seeing your above example, where is your `_display_name` meta stored with HPOS enabled?

**Comment by barryhughes** [comment]
Hi!

> Also seeing your above example, where is your `_display_name` meta stored with HPOS enabled?

In `woocommerce_order_itemmeta`, just as it is when the CPT data-store is running.

> If HPOS does not sync data from order_itemmeta I would have to JOIN two more tables

If you want to do things from some custom code, in a single query, yes that's probably the best way (though you could probably also use sub-queries).
