### ISSUE TITLE
[Epic] Single variation view

### ISSUE THREAD

**Issue by jarekmorawski** [woothemes/woocommerce#40304]
We're ready to build a simple view for managing individual variation information in the new product editing experience. This issue contains the designs and acceptance criteria for the whole experience.

**Design**

AkVNGImLgSqCObTQ3idVn7-fi-7819_442831

<img width="730" alt="image" src="https://github.com/woocommerce/woocommerce/assets/79307566/cdcd23b4-be19-4a72-809c-24e148581840">

**Acceptance criteria**

- [x] We add an `Edit` button to each row in the variations table. It's displayed between the ... button on the right and the visibility option on the left. AkVNGImLgSqCObTQ3idVn7-fi-1639_220087
- [x] Clicking the `Edit` button takes the user to a new page that contains the single variation settings. We fade the main form a bit and show a spinner if needed.
- [x] The title in the header is the combination's name, e.g., `White, Small, Cotton`. On the left side of the name, we show the `group` icon in Gutenberg-600. On the right side, we show the variation's ID (same font, but regular weight. Color: Gutenberg-700).
- [x] The header mostly works the same as the one in the main product form. On the left, there's a button that says: `Main product`. On hover, it changes color to primary and shows a tooltip that reads: `Return to the main product`. AkVNGImLgSqCObTQ3idVn7-fi-7819_444061
- [x] We display a variation switching bar at the bottom of the page. It's fixed and remains in place when the user scrolls.
   - [x] The bar has a subtle shadow and a 1px top border (Gutenberg-100) on the scroll. When the user scrolls to the bottom of the page, we remove the shadow and the border. AkVNGImLgSqCObTQ3idVn7-fi-7819_444061
   - [x] The left button links to the previous variation. If there isn't one, we don't show anything. On hover, it changes color to primary and displays a tooltip that reads: `Edit previous variation`. If there are unsaved changes, we show the browser confirmation dialog.
   - [x] The right button links to the next variation. If there isn't one, we don't show anything. On hover, it changes color to primary and displays a tooltip that reads: `Edit next variation`. If there are unsaved changes, we show the browser confirmation dialog.
   - [x] If a variation doesn't have an image, we show a placeholder. AkVNGImLgSqCObTQ3idVn7-fi-7819_444685
   - [x] We don't show the bar if there are no previous or next variations to show.
- [x] The page is split into four tabs: General, Pricing, Inventory, and Shipping (SEO's out of scope for now).
- [ ] General AkVNGImLgSqCObTQ3idVn7-fi-7819_442811
   - [x] The `Note` field uses the same component as `Summary` in the main form. It's what we call `Description` in the current UX.
   - [x] The `Note` field has a placeholder that reads: `Enter an optional note displayed on the product page when customers select this variation.`
   - [x] When the “Hide in product catalog” is off by default. When it is on, we set the variation's status to `Disabled` and show the crossed eye icon next to the variations table in the main form. When it is off, we don't show anything in the variations table.
   - [x] In the `Images` section, we use the same component as the main form. The user can upload images from their device or choose from the Media Library.
   - [ ] **Nice to have:** the user can add multiple images to a single variation. Rearranging and replacing images works the same as in the main form.
   - [ ] **Nice to have:** We display an image thumbnail in the header once the image is added. AkVNGImLgSqCObTQ3idVn7-fi-7819_520036
   - [x] In the Download section, everything works the same as described in https://github.com/woocommerce/woocommerce/issues/35144.
- [x] Pricing AkVNGImLgSqCObTQ3idVn7-fi-7819_442751
   - [x] Everything works the same as in the main form.
   - [x] We remove the advanced section and bring out the tax class radio buttons.
   - [x] The tax class is automatically set to the same as the parent. The user can change it to something else.
- [x] Inventory AkVNGImLgSqCObTQ3idVn7-fi-7819_442771
   - [x] Everything works the same as in the main form.
   - [x] We remove the advanced section.
- [x] Shipping AkVNGImLgSqCObTQ3idVn7-fi-7819_442791
   - [x] Everything works the same as in the main form.
   - [x] We add a new toggle on top. If enabled, the fields below are accessible. If disabled, the fields are locked (same as in the main form) and the variation gets the `Virtual` trait.
- [x] We display a notice at the top of each page.
   - [x] If dismissed, it disappears from all tabs at once.
   - [x] If dismissed, it doesn’t appear on any other variation in this product. It reappears on other products, though.
   - [x] Clicking the link takes the user to the main product. If there are unsaved changes, we show the browser confirmation dialog.
- [ ] Clicking the kebab menu next to the `Update` button opens the same menu as in the main product form, but we add `Delete variation` in the first position. AkVNGImLgSqCObTQ3idVn7-fi-7819_442851
   - [x] Choosing it launches the delete confirmation modal. If the currently viewed variation is deleted, we automatically move on to the next one and show a snackbar message that reads: `[Variation name] deleted.`
   - [ ] Nice to have: the snackbar has a `Undo` button. Clicking it restores the previously deleted variation.
- [x] If a variation doesn’t have a price, we immediately trigger the validation error. It will also show up in the pre-publish modal. AkVNGImLgSqCObTQ3idVn7-fi-7819_518850

**Comment by octaedro** [comment]
Hi @jarekmorawski,
Great work with the designs! They look great!

I have one question regarding the variation switching bar at the bottom of the page. When that bar is visible, we should hide the feedback bar at the bottom if it wasn't hidden before, right?

![Screenshot 2023-10-03 at 08 39 41](https://github.com/woocommerce/woocommerce/assets/1314156/9498751b-54b7-4b55-a94d-0380d2116488)

**Comment by jarekmorawski** [comment]
That's correct! The feedback bar isn't visible in the single variation details view.

**Comment by louwie17** [comment]
Closing this as only a couple of "nice to haves" are left, we can create follow up issues for those if the need re-surfaces.
