### ISSUE TITLE
[Epic] Update the "Add to store" button

### ISSUE THREAD

**Issue by jarekmorawski** [woothemes/woocommerce#40374]
The "Publish" button is arguably the most important button in the whole product form. Let's upgrade it a bit to offer more flexibility and add the last few missing features.

**Design**
Link to Figma: AkVNGImLgSqCObTQ3idVn7-fi-3359%3A33948 

<img width="684" alt="image" src="https://github.com/woocommerce/woocommerce/assets/65582817/f8392cae-a1c6-406f-b311-c510ac12b339">

```[tasklist]
### Tasks
- [ ] https://github.com/woocommerce/woocommerce/issues/43062
- [ ] https://github.com/woocommerce/woocommerce/issues/40376
- [ ] https://github.com/woocommerce/woocommerce/issues/43047
```

**Comment by mattsherman** [comment]
Marking this as blocked until we finalize the design.

**Comment by j111q** [comment]
@mattsherman , I've updated the description, Figma link, and screenshot in the main issue above. ☝️  I didn't update the tasks since they're tied to existing issues,  so do please update that according to the tweaked design. 🙏 Thank you!

**Comment by pmcpinto** [comment]
@j111q thanks for updating the mockups. I reviewed the changes with the team today. They look great.

There was just one comment regarding the "move to bin" copy. It should be "move to trash". Can you update the mockups?

**Comment by j111q** [comment]
Thanks for the review @pmcpinto! Is there a reason we're using `move to trash`? I used `move to bin` to align with Core WordPress.

**Comment by jarekmorawski** [comment]
WooCommerce's product list (as for Posts and Pages on my test site) uses `Trash` in the UI.

<img width="164" alt="image" src="https://github.com/woocommerce/woocommerce/assets/79307566/effbc519-4ed9-4bce-a665-4f37ed04470c">

**Comment by pmcpinto** [comment]
> WooCommerce's product list (as for Posts and Pages on my test site) uses Trash in the UI.

Correct. I'm also seeing the Trash terminology in other WP flows:

<img width="728" alt="Captura de ecrã 2024-01-04, às 10 31 37" src="https://github.com/woocommerce/woocommerce/assets/3380168/32bbba61-e604-4894-99d8-5ae2d1ab0f4c">
<img width="328" alt="Captura de ecrã 2024-01-04, às 10 30 43" src="https://github.com/woocommerce/woocommerce/assets/3380168/e7b3b653-3287-4184-b155-01641573186c">

@j111q I think this is a localization detail. Because I'm using english (US) as the site language, and probably you're using english (UK) :)

**Comment by louwie17** [comment]
Yes, when I switch my localization to english ( UK ) I see `Move to bin` as well.
From a code perspective they seem to use `Move to trash` -> https://github.com/search?q=repo%3AWordPress%2Fwordpress-develop+%22Move+to+trash%22&type=code
& https://github.com/search?q=repo%3AWordPress%2Fgutenberg%20%22Move%20to%20trash%22&type=code

**Comment by j111q** [comment]
Oh, how fascinating 😆 I would never have guessed it was a localisation (or should I say, **localization** thing ;)) Okay let's use `Move to trash` then. I've updated all the copy in Figma and tweaked the screenshots.

**Comment by pmcpinto** [comment]
@mdperez86 can we close this issue or do you want to test the latest changes first?

**Comment by mdperez86** [comment]
> @mdperez86 can we close this issue or do you want to test the latest changes first?

I think it is ok to close it as it is. If you do agree.
