### ISSUE TITLE
[Epic] Pre-publish modal

### ISSUE THREAD

**Issue by jarekmorawski** [woothemes/woocommerce#40371]
Let's add a few more missing features and come up with a way to handle errors across different tabs in the new product editing experience. As discussed on multiple occasions elsewhere, we'll go with a customized version of the post editor's pre-publish modal. We'll add a new section with errors that the user can view and interact with before publishing a product in their store.

**Design (temporary link)**
AkVNGImLgSqCObTQ3idVn7-fi-3359_344908

<img width="877" alt="image" src="https://github.com/woocommerce/woocommerce/assets/79307566/b033fa19-e938-491d-aeb9-174c3b1c79fa">

**Acceptance criteria**

- [ ] Visibility and scheduling
   - [ ] When the user clicks `Publish` in the top right corner, a panel slides out from the right edge of the screen. It looks and works exactly like the pre-publish modal in the post/site editor.
   - [ ] The `Visibility` section contains the same options as the one in the Organization tab. They look and work the same, e.g., when the Require a password box is checked, the user can enter the password directly in the panel. The section and the block in the Organization tab are fully synced.
   - [ ] The title `Visibility: Public` changes to `Visibility: Hidden` if `Hide in product catalog` or `Hide from search results` as checked (there’s also a badge in the title bar)
   - [ ] The `Add: xxx` section works exactly as in the post/site editor. When expanded, the user can select the time and date. If no custom time and date is selected, the section says `Add: Immediately`. If the user adds a custom time and date, it says: `Add: [date] [time]`, just like in the post/site editor.
   - [ ] When the user selects a future time and date, the top button's label changes from `Add` to `Schedule`.
   - [ ] The `Always show pre-publish checks` disables the pre-publish modal and publishes the product immediately when the user clicks `Publish`. The only exception is when the form contains errors that the user must take action on.
- [ ] Error handling
   - [ ] The section title includes the total number of identified issues. If there's just one issue, the title says: `1 issue found`. If there are more, it says: `X issues found`.
   - [ ] When the pre-publish modal is open, the `Add` button is disabled until all issues are resolved.
   - [ ] We list validation messages for all affected fields the same as they're displayed below them.
   - [ ] User can click on each message or use the arrows in the corner to go between affected fields and solve them one by one.
   - [ ] If there are no more next or previous errors, the arrow button is disabled and changes color to Gutenberg-400.
   - [ ] When an error is solved, it immediately disappears from the list.
   - [ ] If the` Always show pre-publish checks` box was unchecked before, we don't show it at the bottom of the panel (the panel is only shown because of the errors).

```[tasklist]
### Tasks
- [ ] #40376
- [ ] #43047
- [ ] #43046
- [ ] https://github.com/woocommerce/woocommerce/issues/43703
- [ ] https://github.com/woocommerce/woocommerce/issues/43704
- [ ] https://github.com/woocommerce/woocommerce/issues/43705
- [ ] https://github.com/woocommerce/woocommerce/issues/43706
- [ ] https://github.com/woocommerce/woocommerce/issues/43707
```

**Out of the scope**

These issues are not going to be covered as part of this Epic for now.

```[tasklist]
### Tasks
- [ ] https://github.com/woocommerce/woocommerce/issues/43708
- [ ] https://github.com/woocommerce/woocommerce/issues/43709
```

**Comment by louwie17** [comment]
Closing this as the validation will be tackled as part of this issue: https://github.com/woocommerce/woocommerce/issues/46788
