### ISSUE TITLE
Logging: Improvements to the file logger and UI

### ISSUE THREAD

**Issue by coreymckrill** [woothemes/woocommerce#40644]
One of the reasons we were [considering](https://github.com/woocommerce/woocommerce/issues/40525) making the database logging handler the default logger is that the UI for it is much better than the file logger. The log entries are all presented in a table format, where you can filter, sort, and search them. Severity levels are shown in colorized labels, so it's easy to pick out the ones that are most important.

While the database logger will continue to be available, it turns out that making it the default isn't feasible, so this issue is to explore and scope out improvements to the file logger UI so that it has a similar feature set that helps to streamline troubleshooting for merchants and Happiness Engineers.

### Core improvements

- [x] Replace the file-chooser dropdown with a separate, list table-style file browser screen. This would allow for filtering, sorting, and selective exporting/deleting of _log files_. #40915
- [x] When viewing a single log file, do some parsing and HTML wrapping on the back end before rendering, such that the raw log file can be visually enhanced and more interactive. Examples could be adding line numbers (like when viewing code files in GitHub), colorizing the severity label, allowing for jumping to a specific line as in the aforementioned search function improvement, adding a "copy to clipboard" button, and hiding subsequent lines of a multi-line log entry in a `<details>`element. #41143
- [x] Add a search function that does a string search within the current, possibly filtered set of log files. This would introduce a "search results" view in a list table-style format, with each row being a matched line from a log file. Clicking a result would take you to the view of that log file, directly to that particular line. #41257

### Other ideas

- [ ] Allow flagging or bookmarking of individual log file lines.
- [ ] Allow preserving of particular log files so they don't get auto-deleted by the normal policy.

### Open questions

* Does the current practice of using the `source` argument of a log entry as the prefix for a log file (and thus, entries with different `source` values are stored in separate files) still make sense?
    * What if, instead of allowing `source` to be an arbitrary value, it was auto-populated with the name/slug of the plugin from which the log entry originated?

This will probably end up becoming an epic that branches off into separate, smaller issues.

**Comment by coreymckrill** [comment]
The three core items for this issue are now complete. The other ones are not priorities, and we can work up separate issues for them if they get prioritized in the future. As such, I'm marking this one as complete!
