### ISSUE TITLE
Improvements to HPOS migration/verification

### ISSUE THREAD

**Issue by jorgeatorres** [woothemes/woocommerce#40702]
```[tasklist]
### Sync
- [ ] https://github.com/woocommerce/woocommerce/issues/37721
- [ ] https://github.com/woocommerce/woocommerce/issues/40506
- [ ] https://github.com/woocommerce/woocommerce/issues/41348
- [ ] https://github.com/woocommerce/woocommerce/issues/41907
- [ ] https://github.com/woocommerce/woocommerce/issues/42746
```

```[tasklist]
### CLI
- [ ] #36194
- [ ] #33348
- [ ] #41248
- [ ] https://github.com/woocommerce/woocommerce/issues/41908
- [ ] https://github.com/woocommerce/woocommerce/issues/41909
- [ ] https://github.com/woocommerce/woocommerce/issues/41910
```

```[tasklist]
### Verification
- [ ] https://github.com/woocommerce/woocommerce/issues/41912
- [ ] https://github.com/woocommerce/woocommerce/issues/41911
```

**Comment by jorgeatorres** [comment]
Closing now. The remaining issues can be (and are being) looked into, but we no longer need this epic to track progress as most of the work has been completed.
