### ISSUE TITLE
Cleanup CPT database records after HPOS migration is complete and sync is disabled

### ISSUE THREAD

**Issue by jorgeatorres** [woothemes/woocommerce#40714]
After a successful HPOS migration, disabling sync should allow cleaning up old records from the postmeta table.

We should make use of the verification improvements detailed in #40702 in order to double check we haven't missed any data before proceeding with the removal.

```[tasklist]
### Tasks
- [ ] https://github.com/woocommerce/woocommerce/issues/41914
- [ ] https://github.com/woocommerce/woocommerce/issues/41915
- [ ] https://github.com/woocommerce/woocommerce/issues/41916
```

**Comment by Babylon1999** [comment]
Hello @jorgeatorres!

Will this change also remove the "sync orders" notice that allows merchants to switch back to the post table after migration?

<img width="2620" alt="image" src="https://github.com/woocommerce/woocommerce/assets/67080558/707fa70b-f746-4073-82b9-3894a56ed33b">


For reference: https://wordpress.org/support/topic/wc-hpos-issue/

**Comment by jorgeatorres** [comment]
Hi @Babylon1999!

No, we have no plans to remove the sync orders option. Currently, the cleanup is planned as a new setting that you'd have to toggle on for it to kick in.
The cleanup option won't be available while sync is active as those are two opposite operations, but you'll be free to enable one or the other.

**Comment by Babylon1999** [comment]
>  The cleanup option won't be available while sync is active as those are two opposite operations, but you'll be free to enable one or the other.

Thank you for clarifying!

Just to clarify, the sync notice in the screenshot is only relevant if you're trying to switch back to the posts table, correct?

Do you think it would be helpful for the notice to explicitly mention this? The current notice might give an impression that these orders need to be synced, when if fact they don't.

**Comment by Babylon1999** [comment]
Ticket: https://wordpress.org/support/topic/wc-hpos-issue/

<img src="https://d.pr/i/xpAMkl+" alt="">
Link to image: https://d.pr/i/xpAMkl

**Comment by jorgeatorres** [comment]
@Babylon1999: I see what you mean now. Yes, the notice is only relevant if you intend to switch datastores (by first enabling compatibility mode to sync things). That's unrelated to the cleanup work we're doing here, but I do think it'd be good to make the message more clear. I'll submit another issue to track that.

**Comment by Babylon1999** [comment]
>  I'll submit another issue to track that.

Thank you!

**Comment by dawn2duskpt** [comment]
Hello.

I've turned on "Enable compatibility mode (synchronizes orders to the posts table)." in order to change from legacy to HPOS. Nevertheless the setting after changing to HPOS mode and saving settings fails to be turned on and continues to work in legacy mode. 


How can I debug this issue? No incompatible plugins are turned on. I've uploaded latest WooCommerce template pages to our theme. 

thanks,
Best,
Tiago

**Comment by petergerard** [comment]
Is there a recommended way to do clear out the legacy data manually while we wait for the official update? Our site has become very slow due to our high volume of orders and thus a multi-gig postmeta table. We switched to HPOS last month but hasn’t made a big enough impact.

**Comment by jorgeatorres** [comment]
@petergerard: In 8.5.0 we released a WP CLI command that you can use for this purpose: `wp hpos cleanup`. We're still ironing out a few wrinkles (see https://github.com/woocommerce/woocommerce/pull/43727) but if you want to give it a go, you can do that now, provided you're confident things are running ok with HPOS [*].

[*] Unless you wait until 8.6.0 for an updated version of this tool, you might have to run the tool with the `--force` flag, which bypasses some sanity checks during the cleanup process.

**Comment by mondalaci** [comment]
Just tried out `wp wc hpos cleanup all`, and the reduction of `wp_postmeta` records is amazing, but the process has failed:

```
HPOS cleanup  95 % [================================================================================================================================================================================================================================>          ] 179:42 / 182:28
Fatal error: Uncaught Error: Call to a member function get_data_store() on bool in /home/laci/projects/ultimatehackingkeyboard.com/wordpress/wp-content/plugins/woocommerce/src/Internal/DataStores/Orders/LegacyDataHandler.php:181
Stack trace:
#0 /home/laci/projects/ultimatehackingkeyboard.com/wordpress/wp-content/plugins/woocommerce/src/Internal/DataStores/Orders/LegacyDataHandler.php(148): Automattic\WooCommerce\Internal\DataStores\Orders\LegacyDataHandler->is_order_newer_than_post(false)
#1 /home/laci/projects/ultimatehackingkeyboard.com/wordpress/wp-content/plugins/woocommerce/src/Database/Migrations/CustomOrderTable/CLIRunner.php(933): Automattic\WooCommerce\Internal\DataStores\Orders\LegacyDataHandler->cleanup_post_data(5979, false)
#2 [internal function]: Automattic\WooCommerce\DataBase\Migrations\CustomOrderTable\CLIRunner->cleanup_post_data(Array, Array)
#3 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Dispatcher/CommandFactory.php(100): call_user_func(Array, Array, Array)
#4 [internal function]: WP_CLI\Dispatcher\CommandFactory::WP_CLI\Dispatcher\{closure}(Array, Array)
#5 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Dispatcher/Subcommand.php(488): call_user_func(Object(Closure), Array, Array)
#6 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(436): WP_CLI\Dispatcher\Subcommand->invoke(Array, Array, Array)
#7 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(459): WP_CLI\Runner->run_command(Array, Array)
#8 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1284): WP_CLI\Runner->run_command_and_exit()
#9 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Bootstrap/LaunchRunner.php(28): WP_CLI\Runner->start()
#10 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/bootstrap.php(83): WP_CLI\Bootstrap\LaunchRunner->process(Object(WP_CLI\Bootstrap\BootstrapState))
#11 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/wp-cli.php(32): WP_CLI\bootstrap()
#12 phar:///usr/local/bin/wp/php/boot-phar.php(20): include('...')
#13 /usr/local/bin/wp(4): include('...')
#14 {main}
  thrown in /home/laci/projects/ultimatehackingkeyboard.com/wordpress/wp-content/plugins/woocommerce/src/Internal/DataStores/Orders/LegacyDataHandler.php on line 181
```

Any ideas what to do?

**Comment by wessiack** [comment]
use the --force flat 
wc hpos cleanup all --force
worked for me - don't know if this is safe, just tested it on our integration environment

**Comment by jorgeatorres** [comment]
> Any ideas what to do?

Hey @mondalaci! This is a known issue and we have already merged a fix for it (https://github.com/woocommerce/woocommerce/pull/43727) but hasn't been publicly released yet. If you feel comfortable with your site running HPOS only, you could use the `--force` flag when running the command ([as @wessiack suggested](https://github.com/woocommerce/woocommerce/issues/40714#issuecomment-1908582588)), but this comes at the price of disabling a few sanity checks before data is removed.

**Comment by mondalaci** [comment]
Thanks for the quick update! I'll patiently wait for the next release just to be safe. Keep up the great work!

**Comment by jorgeatorres** [comment]
Now that #43293 has been merged, this can be considered complete.

**Comment by rsbst23** [comment]
I ran the cleanup tool through the CLI and I agree, the reduction in wp_postmeta was great! I did notice that there are still a bunch of records in the wp_posts table with the post_type of shop_order_placehold. Is it safe for me to delete these records manually? And/Or can you add them to the cleanup tool?

**Comment by nicomollet** [comment]
> I ran the cleanup tool through the CLI and I agree, the reduction in wp_postmeta was great! I did notice that there are still a bunch of records in the wp_posts table with the post_type of shop_order_placehold. Is it safe for me to delete these records manually? And/Or can you add them to the cleanup tool?

I searched for this info too but it looks like `shop_order_placehold` posts are needed for backfill compatibility.
With it, WC is able to recreate all the posts/postmeta data the old way.
And at the moment, Woo even prevents deletion of `shop_order_placehold` posts (of course you can still do it with an SQL query).

Woo team will probably integrate a feature to remove this CPT too in the future, but it would break the ability to backfill order posts.

**Comment by freeaanzee** [comment]
Small warning for people with a mild form of OCD considering to delete those placeholders via SQL: this will make all order notes invisible, because they rely on the default _wp_comments_ table, even after switching to HPOS.

If you delete the `shop_order_placehold` rows the `wc_get_order_notes()` helper function (which uses `get_comments()` under the hood) returns zero results. The orphaned comments are still there in the database, but because of some JOIN statement with _wp_posts_ the WP_Comment_Query class doesn't return them.

Been there, done that, but not in production 😉.
