### ISSUE TITLE
[Epic] Template API: Enhancements, Cycle 41

### ISSUE THREAD

**Issue by mattsherman** [woothemes/woocommerce#40929]
## Description

The Block Template API will be enhanced with a number of additions aimed at improving the developer experience, focused on:

- Providing troubleshooting tools (inspector and logging)
- Reducing the need for custom blocks (conditional disabling)

Introductory dev blog posts and investigations into future areas of improvement will also be conducted.

## Issues

- [x] https://github.com/woocommerce/woocommerce/issues/40690 (estimate: 1)
- [x] https://github.com/woocommerce/woocommerce/issues/40912 (estimate: 1)
- [x] https://github.com/woocommerce/woocommerce/issues/40920 (estimate: 2)
- [x] https://github.com/woocommerce/woocommerce/issues/40182 (estimate: 1)
- [ ] https://github.com/woocommerce/woocommerce/issues/40921 (estimate: 3)
- [x] https://github.com/woocommerce/woocommerce/issues/40914 (estimate: 3)
- [ ] https://github.com/woocommerce/woocommerce/issues/40922 (estimate: 2)

**Comment by mattsherman** [comment]
Closing this epic, as most of it has been completed and the remainder will be handled in future epics/cycles.
