### ISSUE TITLE
[Woo AI Assistant] - Code Refactor and initial PoC merge into feature branch

### ISSUE THREAD

**Issue by tommyshellberg** [woothemes/woocommerce#41751]
```[tasklist]
### Tasks
- [x] Develop reusable hooks and components, and migrate as many of them as possible to the @woocommerce/ai package.
- [x] Improve and refactor the existing proof-of-concept code for the WooCommerce Assistant. Ensure code quality, maintainability, scalability and security.
- [x] Add client-side unit tests w/ React testing library.
```

**Comment by tommyshellberg** [comment]
Initial PR is here:

https://github.com/woocommerce/woocommerce/pull/41673

**Comment by tommyshellberg** [comment]
PR merged into a feature branch.
