### ISSUE TITLE
[Woo AI Assistant] - Logging and Events Tracking

### ISSUE THREAD

**Issue by tommyshellberg** [woothemes/woocommerce#41756]
Establish a robust logging system using Logstash. 
Track and log the following to StatsD to facilitate monitoring and improve service quality:

- [x] Task Failures. - Tracks: `rest_api_error`.
- [x] General Failures. - Tracks: `send_message_error` and Grafana.
- [x] Response generation times (seconds). Grafana.
- [x] Network/API errors. Grafana.
- [x] Costs - via Grafana as "Woo AI Assistant"

**Comment by tommyshellberg** [comment]
Diff here: D132377-code

**Comment by tommyshellberg** [comment]
Costs are automatically logged and are visible via Grafana as "Woo AI Assistant".
