### ISSUE TITLE
Add tracking to Command Palette opening and search

### ISSUE THREAD

**Issue by Aljullu** [woothemes/woocommerce#41837]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

In https://github.com/woocommerce/woocommerce/pull/41605 we added tracking when using a WooCommerce command in the Command Palette. In order to get a better understanding of this data, we would also like to track (1) when the command palette is open and (2) what merchants search in the command palette.

### Expected behavior

-

### Actual behavior

-

### Steps to reproduce

0. To test tracking, open the browser console (<kbd>F12</kbd>) and run `localStorage.setItem( 'debug', 'wc-admin:*' );`.
1. Go to the post editor (Posts > Add New).
2. Press <kbd>Ctrl</kbd>+<kbd>K</kbd> to open the Command Palette.
3. An event should be triggered when the Command Palette was opened.
4. Type a search term in the Command Palette. Ie, `products`.
5. An event should be triggered with the search term.

Note: tracking events are recorded in the devtools console (<kbd>F12</kbd>) in the form of `wc-admin:tracks recordevent woocommerce_command_palette_search ...`.

### WordPress Environment

-

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.
