### ISSUE TITLE
External/Affiliate products - introduce a new ExPlat experiment in 8.5

### ISSUE THREAD

**Issue by louwie17** [woothemes/woocommerce#41931]
**Description:** as we prepare the release of the External/Affiliate flows, we keep the incremental approach and introduce a new experiment in 8.5 to release the feature to a small subset of users. 

**Acceptance criteria:**

```[tasklist]
### Tasks
- [x] Replicate the experiment running in 8.3. The only difference is that new users who select the digital product option should also be exposed to the experiment. In sum, we should expose users who select one of the following options in the "Add products" task: Physical product, Variable product, and Digital product.
- [x] Create the experiment P2. (feel free to ping me to review the draft)
- [x] Create the experiment in Abacus.
- [x] Add the segment to the WPCOM core.
- [x] Take into account that the experiment will be released a few days before in the Atomic weekly release.
```

**Comment by louwie17** [comment]
Closing this, as it has been released as part of the grouped experiment.
