### ISSUE TITLE
Add regression tests to Jetpack shopper tracking

### ISSUE THREAD

**Issue by senadir** [woothemes/woocommerce#42007]
We recently introduced shopper [tracking in Jetpack](https://github.com/Automattic/jetpack/tree/8834b8a942977725d5a4d5baac6c75a946f12a2e/projects/plugins/jetpack/modules/woocommerce-analytics/classes), this tracking will inform many product decisions. It recently regressed and reported wrong values when parts of our core implementation changed, it's vital this event flow is stable and consistent.

This issue can be split into 3, 5, or 9 parts. Those are the things we need to track:

1. Track existing core events: 

- [ ] `woocommerceanalytics_product_view` → Gets called when viewing a product page
- [ ] `woocommerceanalytics_product_checkout` → Gets called when visiting the checkout page
- [ ] `woocommerceanalytics_product_purchase` → Gets called after placing an order

2. Track page view events:

- [ ] `woocommerceanalytics_cart_view` → Gets called when viewing the cart page
- [ ] `woocommerceanalytics_checkout_view` → Gets called when viewing the checkout page
- [ ] `woocommerceanalytics_order_confirmation_view` → Gets called when viewing the order confirmation page  

For those 2 groups, tracking needs to be done in the following matrix

|  | Block Theme | Regular Theme |
| ------------- | ------------- | ------------- |
| **Cart/Checkout Blocks**  | [ ]  | [ ]  |
| **Cart/Checkout shortcode**  | [ ] | [ ]  |

3. Track my accounts events:

- [ ] `woocommerceanalytics_my_account_page_view` → Gets called when viewing the My Account page 
- [ ] `woocommerceanalytics_my_account_order_action_click` → Gets called when clicking the view order button
- [ ] `woocommerceanalytics_my_account_order_number_click` → Gets called when clicking the order number link
- [ ] `woocommerceanalytics_my_account_address_click` → Gets called when clicking the edit address link
- [ ] `woocommerceanalytics_my_account_address_save` → Gets called when saving the address
- [ ] `woocommerceanalytics_my_account_details_save` → Gets called when saving the account details
- [ ] `woocommerceanalytics_my_account_payment_add` → Gets called when adding a payment method
- [ ] `woocommerceanalytics_my_account_payment_save` → Gets called when saving a payment method
- [ ] `woocommerceanalytics_my_account_payment_delete` → Gets called when deleting a payment method

For sack of completeness, I added all my account events, but if they prove to be too complex to fire, then it's okay to skip them, if's fine if we're to ensure some of those events are firing (page view mostly) and that values are consistent.

Tests should contain a predefined result from the event depending on the environment, and the event should return that value for it to pass.

It doesn't matter if this is done via E2E or Unit testing. It has to be automated and uses WordPress.

**Comment by pmcpinto** [comment]
@senadir, do you think the team should work on this before moving the package? Reference: pfeIvj-6N-p2

**Comment by pmcpinto** [comment]
cc @senadir in case you missed https://github.com/woocommerce/woocommerce/issues/42007#issuecomment-2043253213. Thanks

**Comment by senadir** [comment]
Sorry I missed the comment.

Working on this would be easier once we move the code, as it stands right now, it's a bit tricky to test code that relies on Jetpack connection.

However, it depends if we want to keep the jetpack connection after we move or not. In both regards, this can be reconsidered once we start the moving process.

**Comment by pmcpinto** [comment]
Thanks for the clarification. I'll move to cycle 4 until we have more news about the package transition.

**Comment by adimoldovan** [comment]
@senadir @pmcpinto Is this issue still relevant?

The package `@woocommerce/admin-e2e-tests` was deprecated and removed, but if these tests are still needed they should still be added wherever is best (unit, e2e-pw).

I'll remove the `package: @woocommerce/admin-e2e-tests` label for now.

**Comment by pierorocca** [comment]
@senadir please triage.

**Comment by senadir** [comment]
fine to close
