### ISSUE TITLE
Store Customization MVP (Phase 4)

### ISSUE THREAD

**Issue by nefeline** [woothemes/woocommerce#42103]
Following up on the work made on the three previous phases of this project on https://github.com/woocommerce/woocommerce-blocks/issues/10087, https://github.com/woocommerce/woocommerce-blocks/issues/10568 and https://github.com/woocommerce/woocommerce-blocks/issues/11086, the goal of phase four of this project is to prepare the CYS experience for the launch in the core of WooCommerce (on self-hosted) and fine-tune AI content generation and images management on WooExpress. 

## Release the CYS experience on core

The scope of the project is still being defined, but at a minimum, we should ensure that:

- 🔴  All patterns have their default placeholder images replaced with equivalents from Pixhere/Openverse by following the designs provided by @verofasulo
- 🔴  All patterns have their content updated based on new copy (TBD)
- 🔴  Update the onboarding flow, excluding all references to AI (as soon as we have the designs ready). We will have to reach out to Guidorah to coordinate those changes, as the codebase for the onboarding is on the core.
- 🟡 Ensure the Products Collection block displays placeholder content for products when none have been created in the store yet. This feature should be developed to allow extensibility so AI can individually change each of the placeholder images for this block at the pattern level on WooExpress.
- 🟢 Explore the usage of the PTK API to allow for sourcing entire patterns over the wire and facilitate sharing patterns between WP.com and Woo. If viable, start implementing the solution.

All tasks marked in red are considered blockers for the release. The tasks in yellow are important but not blockers; tasks marked with the green dot are a low priority for this phase and will be pushed to the next one if there's no time available.

## AI fine-tuning

In addition to releasing the CYS experience on core, this phase of the project also aims to fine-tune AI content generation and images management on WooExpress.
```[tasklist]
### Tasks
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/11780
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/11875
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/11873
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/11845
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/11829
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/11828
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/11831
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/11832
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/11847
- [ ] https://github.com/woocommerce/woocommerce/issues/41623
- [ ] https://github.com/woocommerce/woocommerce/issues/41619
- [ ] https://github.com/woocommerce/woocommerce/issues/41620
- [ ] https://github.com/woocommerce/woocommerce/issues/41635
- [ ] https://github.com/woocommerce/woocommerce/issues/41637
- [ ] https://github.com/woocommerce/woocommerce/issues/41697
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/12067
- [ ] https://github.com/woocommerce/woocommerce/issues/42698
- [ ] https://github.com/woocommerce/woocommerce/issues/42906
- [ ] https://github.com/woocommerce/woocommerce/issues/42901
- [ ] https://github.com/woocommerce/woocommerce/issues/42905
- [ ] https://github.com/woocommerce/woocommerce/issues/42939
- [ ] https://github.com/woocommerce/woocommerce/issues/42940
- [ ] https://github.com/woocommerce/woocommerce/issues/42941
- [ ] https://github.com/woocommerce/woocommerce/issues/42948
- [ ] https://github.com/woocommerce/woocommerce/issues/42994
```

**Comment by Marc-pi** [comment]
@nefeline 

< for the launch in the core of WooCommerce (on self-hosted)

You mean woo express / WordPress.com ?

**Comment by nefeline** [comment]
> You mean woo express / WordPress.com ?

Hi @Marc-pi ! No, I mean the core of WooCommerce: we are launching the Customize Your Store experience for all users.

**Comment by Marc-pi** [comment]
@nefeline good news ! thx. keep it up ! :-)

**Comment by nefeline** [comment]
This phase of the Store Customization MVP project is complete. For more details regarding the new onboarding flow on core, please refer to: https://github.com/woocommerce/woocommerce/issues/43623
