### ISSUE TITLE
Product Collection: Add telemetry

### ISSUE THREAD

**Issue by kmanijak** [woothemes/woocommerce#42117]
### Background

Add some events to Product Collection block so we have better knowledge on collections and filters usage.

Ref: pdnLyh-5jB-p2

```[tasklist]
### Tasks
- [ ] https://github.com/woocommerce/woocommerce/issues/45186
- [ ] https://github.com/woocommerce/woocommerce/issues/45187
- [ ] https://github.com/woocommerce/woocommerce/issues/45189
- [ ] https://github.com/woocommerce/woocommerce/issues/45188
- [ ] https://github.com/woocommerce/woocommerce/issues/42301
```

**Comment by manospsyx** [comment]
Worth keeping in mind that if we introduce conversion/revenue analytics later on, we'll want to make the performance (conversions, revenue) filterable by:

- product, 
- collection type, and perhaps by
- template; and
- individual block

Since "usage" and "impact" will become queryable for/by merchants, it will become straightforward for us to collect accurate usage data for product improvement purposes.

**Comment by kmanijak** [comment]
Closing as done
