### ISSUE TITLE
Product Collection: Soft-deprecate existing product list blocks based on AbstractProductGrid with Collections

### ISSUE THREAD

**Issue by kmanijak** [woothemes/woocommerce#42162]
### Background

With the Collections, they can start replacing other blocks based on AbstractProductGrid block.

### Requirements

1. "Old" blocks are hidden from inserter so
2. "New" collections are enabled in the inserter and each collection includes the keyword referencing to "old" block allowing for easy discovery.
3. Replace the blocks in the patterns or other blocks that may use it.
4. "Old" blocks ARE NOT removed from the codebase! They have to be preserved so they work in existing stores that rely on them!

- Make sure all the existing tests are passing
- Update customer documentation
- Write announcement post

```[tasklist]
### Tasks
- [x] Best Selling Products -> Top Sellers collection
- [x] Top Rated Products -> Top Rated Products collection
- [x] Newest Products -> New Arrivals collection
- [x] On Sale Products -> On Sale Products collection
- [x] Hand-picked Products -> Hand-picked Products collection
- [x] Upsells -> Upsells collection
- [x] Cross-Sells -> Cross-Sells collection
- [x] ??? -> Featured products
```

Note: this issue doesn't require a lot of active work (each step is easy and repetitive) but still it can be stretched over time as there may be longer breaks between each task to complete.

**Comment by manospsyx** [comment]
Wondering if it's possible to take a gradual approach like this:


1) JIT-migrate old blocks

- Keep old block references in post content.
- When a post/page/template is edited, replace the old block with its Product Collection equivalent using a pre-determined mapping (and perhaps notify the user!).
- When the content is saved, save the JIT-migrated block as a product collection block.

2) Sunset old blocks

- Continue to surface old blocks in the inserter for at least a while.
- If no issues are reported with the JIT migration approach, sunset the old blocks permanently.

**Comment by imanish003** [comment]
**Note:** Before soft-deprecating product list blocks, we need to verify if existing plugins are compatible with the new experience. Are there any extensibility points that won't be available?

It's possible that some existing product list blocks have extensibility points that Collections may not support. Therefore, we need to verify this and make a decision based on the findings.

CC: @kmanijak
