### ISSUE TITLE
Frontend Filters Improvements

### ISSUE THREAD

**Issue by roykho** [woothemes/woocommerce#42255]
<details>
<summary>Cycle 5 - August 14th – October 6th</summary>

## Cycle 5 - August 14th – October 6th

The goal of this project is to improve the performance of all filters that effects the products blocks. We need to take in account for large stores with many products.

```[tasklist]
### Make the filters contextual (relative to the products shown in the product grid) but keep the solution performant for large stores.
- [x] https://github.com/woocommerce/woocommerce-blocks/issues/10985
- [x] https://github.com/woocommerce/woocommerce-blocks/issues/10569
- [x] https://github.com/woocommerce/woocommerce-blocks/issues/10570
- [x] https://github.com/woocommerce/woocommerce-blocks/issues/10572
- [x] https://github.com/woocommerce/woocommerce-blocks/issues/10573
```

```[tasklist]
### Potentially optimize filters to avoid any re-rendering.
- [x] https://github.com/woocommerce/woocommerce-blocks/issues/10577
- [x] https://github.com/woocommerce/woocommerce-blocks/issues/10578
- [x] https://github.com/woocommerce/woocommerce-blocks/issues/10579
- [x] https://github.com/woocommerce/woocommerce-blocks/issues/10580
```

```[tasklist]
### Explore how the Interactivity API can be utilized for any related improvements.
- [ ] https://github.com/woocommerce/woocommerce/issues/42229
- [x] https://github.com/woocommerce/woocommerce-blocks/issues/10813
- [x] https://github.com/woocommerce/woocommerce-blocks/issues/10811
- [x] https://github.com/woocommerce/woocommerce-blocks/issues/10812
```

```[tasklist]
### Convert/Add e2e tests to Playwright
- [ ] https://github.com/woocommerce/woocommerce/issues/42254
- [ ] https://github.com/woocommerce/woocommerce/issues/42253
- [ ] https://github.com/woocommerce/woocommerce/issues/42252
```

```[tasklist]
### Create new collection filters block
- [x] https://github.com/woocommerce/woocommerce-blocks/issues/10711
- [x] https://github.com/woocommerce/woocommerce-blocks/issues/10984
```

</details>

<details>
<summary>Cycle 6 - October 9th – December 1st</summary>

## Cycle 6 - October 9th – December 1st

In the next phase of the project, we divide our work into two parts: Research and Implementation.

### Research

Continue working and finish the in progress research from last cycle, as well as start thinking about the migration strategy to see if if affect the implementation direction.

```[tasklist]
- [ ] woocommerce/woocommerce#42178
- [ ] woocommerce/woocommerce#42177
- [ ] woocommerce/woocommerce#42176
```

```[tasklist]
### Implementation
- [x] https://github.com/woocommerce/woocommerce-blocks/issues/10985
- [ ] https://github.com/woocommerce/woocommerce/issues/42109
- [x] woocommerce/woocommerce-blocks#11610 
- [x] https://github.com/woocommerce/woocommerce-blocks/issues/10813
- [ ] woocommerce/woocommerce#42179
- [ ] https://github.com/woocommerce/woocommerce/issues/42229
- [x] https://github.com/woocommerce/woocommerce-blocks/issues/10811
- [x] https://github.com/woocommerce/woocommerce-blocks/issues/10812
```

```[tasklist]
### Follow up bug fixes
- [ ] woocommerce/woocommerce#42053
- [ ] woocommerce/woocommerce#42052
```
</details>

## Current cycle - December 4th - present

```[tasklist]
### Required for launch
- [ ] https://github.com/woocommerce/woocommerce/issues/42179
- [ ] https://github.com/woocommerce/woocommerce/issues/42229
- [ ] https://github.com/woocommerce/woocommerce/issues/42109
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/11620
- [ ] https://github.com/woocommerce/woocommerce/issues/42168
- [ ] https://github.com/woocommerce/woocommerce/issues/42176
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/11610
- [ ] https://github.com/woocommerce/woocommerce/issues/42160
- [ ] https://github.com/woocommerce/woocommerce/issues/42055
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/11460
- [ ] https://github.com/woocommerce/woocommerce/issues/42056
- [ ] https://github.com/woocommerce/woocommerce/issues/42975
- [ ] https://github.com/woocommerce/woocommerce/issues/42976
- [ ] https://github.com/woocommerce/woocommerce/issues/43154
- [ ] https://github.com/woocommerce/woocommerce/issues/43167
- [ ] https://github.com/woocommerce/woocommerce/issues/43544
- [ ] https://github.com/woocommerce/woocommerce/issues/43493
- [ ] https://github.com/woocommerce/woocommerce/issues/43545
- [ ] https://github.com/woocommerce/woocommerce/issues/43732
- [ ] https://github.com/woocommerce/woocommerce/issues/43234
```

```[tasklist]
### 3rd Product Review Feedback
- [ ] https://github.com/woocommerce/woocommerce/issues/44748
- [ ] https://github.com/woocommerce/woocommerce/issues/44750
- [ ] https://github.com/woocommerce/woocommerce/issues/44751
- [ ] https://github.com/woocommerce/woocommerce/issues/44752
- [ ] https://github.com/woocommerce/woocommerce/issues/44753
- [ ] https://github.com/woocommerce/woocommerce/issues/44755
- [ ] https://github.com/woocommerce/woocommerce/issues/44756
- [ ] https://github.com/woocommerce/woocommerce/issues/44758
- [ ] https://github.com/woocommerce/woocommerce/issues/44759
```
```[tasklist]
### Bug fixes and refinements
- [ ] https://github.com/woocommerce/woocommerce/issues/45228
- [ ] https://github.com/woocommerce/woocommerce/issues/45315
- [ ] https://github.com/woocommerce/woocommerce/issues/42053
- [ ] https://github.com/woocommerce/woocommerce/issues/42052
- [ ] https://github.com/woocommerce/woocommerce/issues/43156
- [ ] https://github.com/woocommerce/woocommerce/issues/43155
- [ ] https://github.com/woocommerce/woocommerce/issues/43158
- [ ] https://github.com/woocommerce/woocommerce/issues/43170
- [ ] https://github.com/woocommerce/woocommerce/issues/43171
- [ ] https://github.com/woocommerce/woocommerce/issues/43205
- [ ] https://github.com/woocommerce/woocommerce/issues/43210
- [ ] https://github.com/woocommerce/woocommerce/issues/42121
- [ ] https://github.com/woocommerce/woocommerce/issues/44061
- [ ] https://github.com/woocommerce/woocommerce/issues/44630
- [ ] https://github.com/woocommerce/woocommerce/issues/44684
- [ ] https://github.com/woocommerce/woocommerce/issues/45300
- [ ] https://github.com/woocommerce/woocommerce/issues/45491
- [ ] https://github.com/woocommerce/woocommerce/issues/45361
- [ ] https://github.com/woocommerce/woocommerce/issues/44686
```

```[tasklist]
### QA
- [ ] https://github.com/woocommerce/woocommerce/issues/43029
- [ ] https://github.com/woocommerce/woocommerce/issues/43391
- [ ] https://github.com/woocommerce/woocommerce/issues/42170
- [ ] https://github.com/woocommerce/woocommerce/issues/42171
- [ ] https://github.com/woocommerce/woocommerce/issues/42252
- [ ] https://github.com/woocommerce/woocommerce/issues/42253
- [ ] https://github.com/woocommerce/woocommerce/issues/42254
```

```[tasklist]
## Next cycles
- [ ] https://github.com/woocommerce/woocommerce/issues/42178
- [ ] https://github.com/woocommerce/woocommerce/issues/42073
- [ ] https://github.com/woocommerce/woocommerce/issues/42169
- [ ] https://github.com/woocommerce/woocommerce/issues/42175
- [ ] https://github.com/woocommerce/woocommerce/issues/44683
- [ ] https://github.com/woocommerce/woocommerce/issues/45100
- [ ] https://github.com/woocommerce/woocommerce/issues/45370
- [ ] https://github.com/woocommerce/woocommerce/issues/45372
- [ ] https://github.com/woocommerce/woocommerce/issues/45507
```

**Comment by Marc-pi** [comment]
@dinhtungdu / @roykho i found finaly the EPIC issue about filters :-)
One question : what's your performance target in term of max nr of products ?
do you plan to manage indexes to speed up things, or other improvements to well manage the larger shops (here i'm running 80-100K products with Woo).

**Comment by dinhtungdu** [comment]
@Marc-pi We haven't look at the performance yet so I can't give you any insights/information on that matter right now. I will raise this to our team to discuss.

Personally, for the size of the store you're running, I will use specialized solution like Elasticsearch to improve the performance.

**Comment by Marc-pi** [comment]
@dinhtungdu for now we make use of wpgridbuilder, and it's mostly 80-100K hidden behing grouped products (approx 25K grouped products), for which we've build our own templates / plugin to manage the missing features. 
(as you know, the grouped product FSE template is not available yet into WCBlocks, it uses the single product template only where there are encapsulated templates to manage the display of child product elements). 
keep it up, i see you're moving quite fast on those new filters with interactive API.
glad to see. 
NB : when released, would be nice to indicate the perf target so people will be aware of the limitations / usage scope

**Comment by roykho** [comment]
Closing as this is superseded by https://github.com/woocommerce/woocommerce/issues/46142
