### ISSUE TITLE
Add Tracker events to the Mini Cart block

### ISSUE THREAD

**Issue by ralucaStan** [woothemes/woocommerce#42317]
**Description**: Currently, there is no tracking done at the Mini Cart block level.
When we track, we rely on a flow that looks like: Product Page > Cart page > Checkout page.
Some websites skip the Cart page by using the Mini Cart block. They use the Proceed to Checkout button from there. We should leverage the woocommerce-analytics module. This will need to be implemented in the Jetpack repo. More info about prior art here: pb0Spc-ou-p2#comment-701

**Acceptance criteria:**

- [ ] Create a new event that should be fired when the shopper views the mini-cart:
Event name: woocommerceanalytics_mini_cart_view
Event properties: `mini_cart_contains_block` (if the mini cart is powered by blocks), `pp`, `pq`, `pt`, `r3d`, `ui`, `url`, `woo_version`, `device`, `products_count` (number of products included in the cart), `order_value` (the order value/total)

- [ ] Create a new event that should be fired when the shopper clicks "view my cart":
Event name: woocommerceanalytics_mini_cart_view_cart_click
Event properties: `mini_cart_contains_block` (if the mini cart is powered by blocks), `pp`, `pq`, `pt`, `r3d`, `ui`, `url`, `woo_version`, `device`,  `products_count` (number of products included in the cart), `order_value` (the order value/total)

- [ ] Create a new event that should be fired when the shopper clicks "checkout":
Event name: woocommerceanalytics_mini_cart_checkout_click
Event properties: `mini_cart_contains_block` (if the mini cart is powered by blocks), `pp`, `pq`, `pt`, `r3d`, `ui`, `url`, `woo_version`, `device`,  `products_count` (number of products included in the cart), `order_value` (the order value/total)

- [ ] Create a new event that should be fired when the shopper closes the mini-cart:
Event name: woocommerceanalytics_mini_cart_close_click
Event properties: `mini_cart_contains_block` (if the mini cart is powered by blocks), `pp`, `pq`, `pt`, `r3d`, `ui`, `url`, `woo_version`, `device`,  `products_count` (number of products included in the cart), `order_value` (the order value/total)

- [ ] Create a new event that should be fired when the shopper clicks "remove item":
Event name: woocommerceanalytics_mini_cart_remove_item_click
Event properties: `mini_cart_contains_block` (if the mini cart is powered by blocks), `pp`, `pq`, `pt`, `r3d`, `ui`, `url`, `woo_version`, `device`,  `products_count` (number of products included in the cart), `order_value` (the order value/total)

- [ ] Create a new event that should be fired when the shopper clicks to update stock:
Event name: woocommerceanalytics_mini_cart_update_stock_click
Event properties: `mini_cart_contains_block` (if the mini cart is powered by blocks), `pp`, `pq`, `pt`, `r3d`, `ui`, `url`, `woo_version`, `device`,  `products_count` (number of products included in the cart), `order_value` (the order value/total)

**Comment by pmcpinto** [comment]
@ralucaStan the issue description was updated with the acceptance criteria

**Comment by ralucaStan** [comment]
Adding @Aljullu for awarness

**Comment by tomxygen** [comment]
Hi @ralucaStan 
is this tracking event used by WooCommerce to assess how merchants use WooCommerce, or is it available for merchants to understand what shoppers are doing in the store (just like Google Analytics)?

**Comment by pmcpinto** [comment]
Hi Tommaso, it's the former. But it will also give us the option to help merchants make better decisions to improve shopper conversion in the future.

**Comment by tomxygen** [comment]
Ok thanks!
However, as I said in multiple occasions, I would love to see an improved analytics in WooCommerce > Analytics, that shows how many active carts and checkouts there are.
It is especially important nowadays, since advertising platforms struggle to reliably track the shoppers actions due to Apple's privacy limitations and many competing platforms have some sort of implementation.
I've already[ created an issue](https://github.com/woocommerce/woocommerce/issues/38508) a couple of months ago but unfortunately I haven't received any feedback yet.

**Comment by senadir** [comment]
@ralucaStan @pmcpinto it's not clear if this was in Rubik's project and I missed it, or if this is meant for Kirigami/Origami to work on?

**Comment by ralucaStan** [comment]
Hey Nadir, it was not in Rubik's project.

**Comment by samrat-biswas-git** [comment]
Hi @ralucaStan - thanks for reporting this, and for the detail you gave.

I know this has been open for a very long time, and I appreciate your patience. We're currently going through some older WooCommerce issues, identifying what still needs fixing, and tidying up what's already fixed or out of scope.

It looks like this has already been fixed, or it's no longer happening on trunk.

Here's what I found: The issue body itself says the tracker work needs implementation in Jetpack; I found no WooCommerce-core PR or local code path that would make this a trunk issue for this repo.

I'm going to close this one. If you're still facing this issue on a current version, please reply with steps to reproduce and we'll happily take another look.
