### ISSUE TITLE
Product Gallery Block

### ISSUE THREAD

**Issue by thealexandrelara** [woothemes/woocommerce#42335]
# Description

For the past few months, we have been working on https://github.com/woocommerce/woocommerce-blocks/issues/8054. During the development process, we introduced a new block called the Product Image Gallery block, which enables the display of product images on the Single Product page.

In the initial iteration, we essentially incorporated the existing functionality of the Product Image in the Classic Single Product template. This allowed merchants to add product images to the page and position them according to their preferences.

This epic covers a work to enhance the Product Image Gallery block by introducing new functionalities and customization options for thumbnails, next/previous buttons, pager, and more in a new block named Product Gallery.

# Phases

The tasks required to complete the Product Gallery block are divided into various phases. It's important to note that the tasks in one phase can overlap with those in the following phases. Additionally, new phases may be introduced to address any missing tasks or to incorporate new functionalities/behaviors into the block.

## Phase 1: Foundation

The main goal is to complete the foundation work of the block. The Product Gallery block has several inner blocks that must be integrated to provide the block's functionality.  In this initial phase, the goal is to incorporate only the block markups without implementing any actual interactions or functionality.. Additionally, each block has its own unique set of settings that empower merchants to personalize their stores, and these settings must also be included.

```[tasklist]
### Tasks
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/9907
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/9925
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/9900
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/9943
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/9901
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/9902
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/9903
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/9904
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/9905
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/9898
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/9897
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/9896
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/9946
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/9899
- [ ] woocommerce/woocommerce-blocks#10836
- [ ] woocommerce/woocommerce-blocks#10838
```

## Phase 2: Add interactivity 

Introduce interactivity to the block and its inner components by utilizing the Interactivity API and Behaviors API. Additionally, we want to include E2E tests for the block and its inner blocks.

```[tasklist]
### Tasks
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/10760
- [ ] https://github.com/woocommerce/woocommerce-blocks/pull/10782
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/10629
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/10630
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/10631
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/9941
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/9942
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/10751
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/9899
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/10783
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/11028
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/10750
```

## Phase 3: Enhancements and Fixes for the block

We've made significant progress with the Foundation blocks and the integration with the Interactivity API. All current open issues will be addressed in this phase since our main goal is to complete all the remaining tasks to make the block usable and stable.

```[tasklist]
### Tasks
- [ ] https://github.com/woocommerce/woocommerce/issues/43826
- [ ] https://github.com/woocommerce/woocommerce/issues/43762
- [ ] https://github.com/woocommerce/woocommerce/issues/43761
- [ ] https://github.com/woocommerce/woocommerce/issues/43759
- [ ] https://github.com/woocommerce/woocommerce/issues/43760
- [ ] https://github.com/woocommerce/woocommerce/issues/43796
- [ ] https://github.com/woocommerce/woocommerce/issues/43000
- [ ] https://github.com/woocommerce/woocommerce/issues/42043
- [ ] https://github.com/woocommerce/woocommerce/issues/42095
- [ ] https://github.com/woocommerce/woocommerce/issues/42061
- [ ] https://github.com/woocommerce/woocommerce/issues/43295
- [ ] https://github.com/woocommerce/woocommerce/issues/42219
- [ ] https://github.com/woocommerce/woocommerce/issues/42852
- [ ] https://github.com/woocommerce/woocommerce/issues/42060
- [ ] https://github.com/woocommerce/woocommerce/issues/42192
- [ ] https://github.com/woocommerce/woocommerce/issues/42217
- [ ] https://github.com/woocommerce/woocommerce/issues/42044
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/11988
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/11940
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/11699
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/11014
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/11882
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/11656
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/11311
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/11027
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/11717
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/11285
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/11291
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/11148
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/11504
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/11083
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/11100
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/11099
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/10632
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/10880
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/11284
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/11104
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/10870
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/9895
- [ ] https://github.com/woocommerce/woocommerce-blocks/pull/11559
- [ ] https://github.com/woocommerce/woocommerce-blocks/pull/11550
- [ ] https://github.com/woocommerce/woocommerce/issues/42792
- [ ] https://github.com/woocommerce/woocommerce/issues/43306
- [ ] https://github.com/woocommerce/woocommerce/issues/43304
```

**Comment by paaljoachim** [comment]
Sharing this related Gutenberg Tracking issue: Image Lightbox
https://github.com/WordPress/gutenberg/issues/51132

**Comment by roykho** [comment]
Closing this as the work in these phases are complete. A new cycle planning issue has been created here https://github.com/woocommerce/woocommerce/issues/52976
