### ISSUE TITLE
Remove `propTypes` definitions

### ISSUE THREAD

**Issue by nielslange** [woothemes/woocommerce#42364]
While the majority of files have been converted from JS to TS, we still have a few JS files that use `propTypes` definitions. In addition, we also have a few TSX files that use `propTypes` definitions.

## Steps to reproduce

1. Search for `propTypes` in your favourite IDE.
2. Exclude the following files/folders: 
```
build, node_modules, vendor, storybook, .xml, .json, reports
```

Running these steps, I can find 211 results in 36 files.

## Expected outcome

I suggest we eliminate all `propTypes` definitions and utilize TypeScript (TS/TSX) for type checking.

```[tasklist]
### To do
- [ ] woocommerce/woocommerce-blocks#9524
- [ ] woocommerce/woocommerce-blocks#9526
- [ ] woocommerce/woocommerce-blocks#9539
- [ ] woocommerce/woocommerce-blocks#9542
- [ ] woocommerce/woocommerce#42360
- [ ] woocommerce/woocommerce#42294
```

```[tasklist]
### Done
- [ ] woocommerce/woocommerce-blocks#9514
- [ ] woocommerce/woocommerce-blocks#9515
- [ ] woocommerce/woocommerce-blocks#9516
- [ ] woocommerce/woocommerce-blocks#9517
- [ ] woocommerce/woocommerce-blocks#9518
- [ ] woocommerce/woocommerce-blocks#9519
- [ ] woocommerce/woocommerce-blocks#9520
- [ ] woocommerce/woocommerce-blocks#9521
- [ ] woocommerce/woocommerce-blocks#9522
- [ ] woocommerce/woocommerce-blocks#9523
- [ ] woocommerce/woocommerce-blocks#9525
- [ ] woocommerce/woocommerce-blocks#9527
- [ ] woocommerce/woocommerce-blocks#9528
- [ ] woocommerce/woocommerce-blocks#9529
- [ ] woocommerce/woocommerce-blocks#9530
- [ ] woocommerce/woocommerce-blocks#9531
- [ ] woocommerce/woocommerce-blocks#9532
- [ ] woocommerce/woocommerce-blocks#9533
- [ ] woocommerce/woocommerce-blocks#9534
- [ ] woocommerce/woocommerce-blocks#9535
- [ ] woocommerce/woocommerce-blocks#9536
- [ ] woocommerce/woocommerce-blocks#9537
- [ ] woocommerce/woocommerce-blocks#9538
- [ ] woocommerce/woocommerce-blocks#9540
- [ ] woocommerce/woocommerce-blocks#9541
- [ ] woocommerce/woocommerce-blocks#9544
- [ ] woocommerce/woocommerce-blocks#9545
- [ ] woocommerce/woocommerce-blocks#9546
- [ ] woocommerce/woocommerce-blocks#9547
- [ ] woocommerce/woocommerce-blocks#9548
```

**Comment by hritikchaudhary** [comment]
Hi @nielslange I'd like to work on this... it'll be my first issue for woocommerce-blocks.. I'm setting it up on my local
if I understand this correctly we have to:
1. Convert JS files to TS/TSX, excluding the mentioned files..
2. Remove propTypes definitions

That's all right?

**Comment by nielslange** [comment]
Hello @hritikchaudhary 👋 Thanks for showing interest in working on this issue! Any help is much appreciated.

 Given that it touches numerous files, I think it might be better to split this issue into individual issues. That way, it's easier to implement the individual issues. Let me quickly convert this issue into an epic and create the necessary individual issues.
 
> Convert JS files to TS/TSX, excluding the mentioned files..

If a *.js file is using a `propTypes` definition, that file should be renamed to *.ts respectively *.tsx, depending on its nature.

> Remove propTypes definitions

The `propTypes` definition within the individual file should be replaced with the corresponding TS definitions. For example, let's have a look at https://github.com/woocommerce/woocommerce-blocks/blob/trunk/assets/js/blocks/product-search/block.js.

To remove the `propTypes` definitions, we'd have to introduce an interface, e.g. like this:
```tsx
interface ProductSearchBlockProps {
	attributes: {
		label: string;
		placeholder: string;
		formId: string;
		className: string;
		hasLabel: boolean;
		align: string;
	};
}
```
and then change 
```tsx
const ProductSearchBlock = ( {
	attributes: { label, placeholder, formId, className, hasLabel, align },
} ) => {

```
to
```tsx
const ProductSearchBlock = ( {
	attributes: { label, placeholder, formId, className, hasLabel, align },
}: ProductSearchBlockProps ) => {

```

Kindly note that I created the TS interface for demo purposes without looking too much into this case. I noticed that the label `good first issue` might be misplaced for this issue. Nevertheless, feel free to gap one of the individual issues to work on. I'll create them now.

**Comment by hritikchaudhary** [comment]
@nielslange  sure not a problem, will work on it.

**Comment by nielslange** [comment]
> @nielslange sure not a problem, will work on it.

@hritikchaudhary I just converted this issue into an epic and created all individual issues. You are welcome to pick one of the issues. I suggest starting with the smallest file. Some files are quite big. Converting them from *.js to *.tsx will, most likely, introduce many TypeScript errors. The smaller the file, in terms of lines of code, the less TypeScript errors will be introduced.

Thanks again for showing interest in working in this area, and please don't hesitate to ask if you have any questions. 🙌

**Comment by hritikchaudhary** [comment]
Thanks @nielslange

**Comment by hritikchaudhary** [comment]
Hi @nielslange, I have completed the setup of the development environment, had to install php@7.3 from shivammathur/php.
but there is an issue, when I generate zip using npm run package-plugin:dev and upload it to my local wordpress instance it gives me `The link you followed has expired.` and if i generate a production zip using npm run package-plugin it let me upload the plugin but i don't see any woocommerce block when i try to add blocks.
I also tried to directly pasting generated dev zip in wp-content/plugins but it was not visible under plugins.

Do you know how to resolve this? or where can I look to solve this? Cause i converted a block file and unit tests and linting is successful but is there any way from UI I can confirm the functionality of that file is intact..

Environment info:
Node: v16.15.0 
PHP: v7.3.33
Wordpress instance installed in docker
OS: MacOS Ventura (M1 silicon)
Thanks!

**Comment by nielslange** [comment]
@hritikchaudhary I suggest following the steps as described on [Getting Started](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/contributors/contributing/getting-started.md). 

As for the steps you described, I'm not sure what exactly you're trying to do. Here's how my local setup looks like:

- I'm using Laravel Valet for creating local development sites.
- My sites are located at `~/Sites`.
- My plugins are located as `~/Plugins`.
- My themes are located at `~/Themes`.
- My primary development site is `https://store.test/` which is located at `~/Sites/store`.
- The fork of the WooCommerce Blocks plugin is located at `~/Plugins/woocommerce-blocks`.
- That fork is symlinked into my primary site like this:
```sh
cd ~/Sites/store/wp-content/plugins
ln -s ~/Plugins/woocommerce-blocks
```

Apart from symlinking the WooCommerce Blocks plugin into your development site, you could also directly fork the plugin into the plugins folder of the site. 

That said, I suggest heading over to [Getting Started](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/contributors/contributing/getting-started.md), which explains how to start contributing to WooCommerce Blocks.

**Comment by hritikchaudhary** [comment]
Hi @nielslange 
Yes I followed the [Getting Started](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/contributors/contributing/getting-started.md) only.
One thing i missed was my repo was not located at ~/Plugins as I am using wordpress for docker, but now i have bind the repo to ~/plugins
<img width="372" alt="Screenshot 2023-05-22 at 1 28 15 PM" src="https://github.com/woocommerce/woocommerce-blocks/assets/33057454/80725fc1-841e-4e73-bbc4-ddbab270c65a">
 and I'm able to see WooCommerce Blocks, but still its not visible in panel nor the blocks are visible in blocks inserter, I've build the project already...
<img width="360" alt="image" src="https://github.com/woocommerce/woocommerce-blocks/assets/33057454/c02bc123-15a3-4cc9-9514-d3fc814c97ca">
Can I still go ahead with the changes, relying on unit test and build?

**Comment by nielslange** [comment]
> One thing i missed was my repo was not located at ~/Plugins as I am using wordpress for docker, but now i have bind the repo to ~/plugins

Keeping the fork of the WooCommerce Blocks repo in `~/Plugins` was just an example of what I am doing. The fork can live in any other direction. 

> and I'm able to see WooCommerce Blocks, but still its not visible in panel nor the blocks are visible in blocks inserter, I've build the project already...

On your screenshot, I see that the WooCommerce Blocks plugin is active, but the WooCommerce plugin is missing. WooCommerce Blocks can be seen as an add-on for WooCommerce. In WooCommerce Blocks, we migrate shortcodes to blocks. Every few weeks, we then merge WooCommerce Blocks into WooCommerce. However, without the WooCommerce plugin, you will not see the functionality of the WooCommerce Blocks plugin.

> Can I still go ahead with the changes, relying on unit test and build?

Sure, you can proceed with the changes. To do that, please select one of the tasks, as listed in the description of this epic.

**Comment by hritikchaudhary** [comment]
ohh! got it.
Thanks!

**Comment by hritikchaudhary** [comment]
Raised 1st PR woocommerce/woocommerce-blocks#9565 to fix woocommerce/woocommerce-blocks#9514 and woocommerce/woocommerce-blocks#9523

**Comment by hritikchaudhary** [comment]
woocommerce/woocommerce-blocks#9595 to fix woocommerce/woocommerce-blocks#9519

**Comment by hritikchaudhary** [comment]
woocommerce/woocommerce-blocks#9613 to fix woocommerce/woocommerce-blocks#9517 woocommerce/woocommerce-blocks#9545 woocommerce/woocommerce-blocks#9547 woocommerce/woocommerce-blocks#9548

**Comment by nielslange** [comment]
> woocommerce/woocommerce-blocks#9613 to fix woocommerce/woocommerce-blocks#9517 woocommerce/woocommerce-blocks#9545 woocommerce/woocommerce-blocks#9547 woocommerce/woocommerce-blocks#9548

Hi @hritikchaudhary, 

Thanks a lot for your effort on these issues, especially on woocommerce/woocommerce-blocks#9613. I've had a quick look at it and see that you've worked on four different sections:

- `assets/js/atomic/blocks/product-elements/add-to-cart/`
- `assets/js/base/components/product-list/`
- `assets/js/blocks/price-filter/`
- `assets/js/blocks/product-new/`

Your hard work is truly appreciated! You've applied changes to multiple sections, and that shows your dedication. 

However, just to share some thoughts for future work - it can be a bit easier to manage if we do smaller updates. For example, instead of one big update that includes changes to many sections, we can do smaller updates for each section.

Why is this a good idea? Let's imagine this scenario: we put all the changes together, but after a few weeks we discover a problem in one section. If we need to go back to the previous version, we'd have to undo all the changes, not just the ones that caused the problem. 

On the other hand, if we did separate updates for each section, we could just go back to the previous version of the section with the problem. The other sections wouldn't be affected.

I understand that this may seem like more work, and I'm sorry if it seems like I'm asking a lot. But it will make it easier to find and fix any issues in the future. Would it be possible to split woocommerce/woocommerce-blocks#9613 into separate updates for each section? If it's too much work, don't worry, we can keep it as is for now.

And for next time, if you could focus your updates on one specific section, that would be amazing! Hope this makes sense and thanks again for all your hard work. You're doing a fantastic job!

**Comment by hritikchaudhary** [comment]
Yes no worries I can split woocommerce/woocommerce-blocks#9613 into separate updates one for each issue.. it is not much work.
Thanks for the feedback!

**Comment by hritikchaudhary** [comment]
Done: 

1. woocommerce/woocommerce-blocks#9616 to fix woocommerce/woocommerce-blocks#9548
2. woocommerce/woocommerce-blocks#9615 to fix woocommerce/woocommerce-blocks#9547
3. woocommerce/woocommerce-blocks#9613 to fix woocommerce/woocommerce-blocks#9517

**Comment by hritikchaudhary** [comment]
- woocommerce/woocommerce-blocks#9623  to fix woocommerce/woocommerce-blocks#9520

**Comment by hritikchaudhary** [comment]
Hi @nielslange, I was going through reviews module assets/js/blocks/reviews we have 10 files in it but as only 3 files had proptypes on 3 issues are there, I think we should convert all of them to ts/tsx. If you agree can I fix these in one of the three issues we have or should i create new issues for each and add them to this epic?
Here is the list of files in that folder:

1. assets/js/blocks/reviews/attributes.js
2. assets/js/blocks/reviews/edit-utils.js
3. assets/js/blocks/reviews/editor-block.js
4. assets/js/blocks/reviews/editor-container-block.js - woocommerce/woocommerce-blocks#9526 
5. assets/js/blocks/reviews/example.js
6. assets/js/blocks/reviews/frontend-block.js - woocommerce/woocommerce-blocks#9525 
7. assets/js/blocks/reviews/frontend-container-block.js - woocommerce/woocommerce-blocks#9527 
8. assets/js/blocks/reviews/frontend.js
9. assets/js/blocks/reviews/save.js
10. assets/js/blocks/reviews/utils.js

**Comment by nielslange** [comment]
> Hi @nielslange, I was going through reviews module assets/js/blocks/reviews we have 10 files in it but as only 3 files had proptypes on 3 issues are there, I think we should convert all of them to ts/tsx. If you agree can I fix these in one of the three issues we have or should i create new issues for each and add them to this epic? Here is the list of files in that folder:

Thanks for double-checking. I'd say, converting all files to *.ts/*.tsx makes sense. Please go ahead and do that. The next days, I'll be travelling, so I might review your contributions a bit slower. Feel free to slow down a bit. 😀

**Comment by hritikchaudhary** [comment]
> Thanks for double-checking. I'd say, converting all files to _.ts/_.tsx makes sense. Please go ahead and do that. The next days, I'll be travelling, so I might review your contributions a bit slower. Feel free to slow down a bit. 😀

haha sure np..

**Comment by hritikchaudhary** [comment]
- woocommerce/woocommerce-blocks#9631 to fix woocommerce/woocommerce-blocks#9521
- woocommerce/woocommerce-blocks#9713 fixes woocommerce/woocommerce-blocks#9533

**Comment by hritikchaudhary** [comment]
- woocommerce/woocommerce-blocks#9614 to fix woocommerce/woocommerce-blocks#9545
- https://github.com/woocommerce/woocommerce-blocks/pull/9692 fixes woocommerce/woocommerce-blocks#9522 and woocommerce/woocommerce#42362
- woocommerce/woocommerce-blocks#9712 fixes woocommerce/woocommerce-blocks#9534 
- woocommerce/woocommerce-blocks#9755 fixes https://github.com/woocommerce/woocommerce-blocks/issues/9518
- woocommerce/woocommerce-blocks#9758 fixes https://github.com/woocommerce/woocommerce-blocks/issues/9515

**Comment by hritikchaudhary** [comment]
- woocommerce/woocommerce-blocks#9817 fixes woocommerce/woocommerce-blocks#9540 and woocommerce/woocommerce-blocks#9541
- https://github.com/woocommerce/woocommerce-blocks/pull/9838 fixes woocommerce/woocommerce-blocks#9528

**Comment by kkoteen** [comment]
Hi @nielslange - thanks for reporting this, and for the detail you gave.

I know this has been open for a very long time, and I appreciate your patience. We're currently going through some older WooCommerce issues, identifying what still needs fixing, and tidying up what's already fixed or out of scope.

It looks like this has already been fixed, or it's no longer happening on trunk.

Here's what I found: Current trunk no longer shows remaining `propTypes`/`PropTypes` definitions under `plugins/woocommerce/client/blocks` beyond historical release-note text. The epic appears to have been effectively completed or superseded by its child issues and merged follow-up work.

I'm going to close this one. If you're still facing this issue on a current version, please reply with steps to reproduce and we'll happily take another look.

Fix/changelog reference: client/blocks readme entries for multiple propTypes-removal PRs
