### ISSUE TITLE
Epic: Migrate E2E tests to Playwright project

### ISSUE THREAD

**Issue by gigitux** [woothemes/woocommerce#42413]
This is an epic to track all the Playwright migration related issues, see pdToLP-wu-p2

```[tasklist]
- [ ] woocommerce/woocommerce#42112
- [ ] woocommerce/woocommerce#42265
- [ ] woocommerce/woocommerce#42309
- [ ] woocommerce/woocommerce#42310
- [ ] woocommerce/woocommerce#42355
- [ ] woocommerce/woocommerce#42412
- [ ] woocommerce/woocommerce#42411
```

<details>
<summary>Closed tasks</summary>
<br>

```[tasklist]
- [ ] woocommerce/woocommerce-blocks#9002
- [ ] woocommerce/woocommerce-blocks#9203
- [ ] woocommerce/woocommerce-blocks#9261
- [ ] woocommerce/woocommerce-blocks#9632
- [ ] woocommerce/woocommerce-blocks#9646
- [ ] woocommerce/woocommerce-blocks#10037
- [ ] woocommerce/woocommerce-blocks#10135
```

<br>
</details>

<details>
<summary>Checkout tests</summary>
<br>

```[tasklist]
### Checkout tests
- [ ] woocommerce/woocommerce#42029
- [ ] woocommerce/woocommerce#42030
- [ ] woocommerce/woocommerce#42068
- [ ] woocommerce/woocommerce#42405
- [ ] woocommerce/woocommerce#42069
- [ ] woocommerce/woocommerce#42070
- [ ] woocommerce/woocommerce-blocks#9058
- [ ] woocommerce/woocommerce-blocks#11893
- [ ] woocommerce/woocommerce-blocks#11895
- [ ] woocommerce/woocommerce-blocks#11896
- [ ] woocommerce/woocommerce-blocks#11898
- [ ] woocommerce/woocommerce#43741
- [ ] woocommerce/woocommerce#44030
```

<br>
</details>

**Comment by ralucaStan** [comment]
I've added 2 new tickets for the Mini Cart under the Checkout tests section

**Comment by gigitux** [comment]
I'm going to close this issue given that it's outdated.
