### ISSUE TITLE
New Product Query Block

### ISSUE THREAD

**Issue by sunyatasattva** [woothemes/woocommerce#42616]
We are looking to create a new block, based (ideally or practically) on the Gutenberg Query Loop block whose goal is to replace all of our current product-displaying blocks. This new block should be flexible enough to reproduce all of the use-cases currently covered by existing blocks (e.g. showing all products, showing only new products, or products on sale, etc.), while also being filterable via dedicated filter blocks and compatible with FSE templates (i.e. it should replace the placeholders we currently use in archive templates).

This epic tracks the progress on producing a POC of this block, and not a final release. The POC should display all the above characteristics, albeit allowing for some cases not being fully covered. Specifically, we know the POC is going to have at least the following limitations:

1. Filter blocks will have to reload the page to interact with the block.
2. Multiple blocks with different queries won't be compatible with filter blocks.
3. We might have to rethink the hierarchy requirements of filter blocks in the long run.
4. Settings on the editor side won't be as user-friendly and could cause breakage of the block, due to difficulties in selecting or locking specific settings while extending a core block.

## Phases 1–2
- [x] woocommerce/woocommerce-blocks#6785 
- [x] woocommerce/woocommerce-blocks#6786
- [x] https://github.com/woocommerce/woocommerce-blocks/issues/6794
- [x] woocommerce/woocommerce-blocks#6788 
- [x] https://github.com/sunyatasattva/gutenberg/issues/1
- [x] woocommerce/woocommerce-blocks#6791
- [x] https://github.com/woocommerce/woocommerce-blocks/issues/6795
- [x] https://github.com/sunyatasattva/gutenberg/issues/2

### FSE

> **Note**
> FSE-related issues have been moved away from Phase 3 as of pdnLyh-2jZ-p2#comment-1685

### Product elements

- [x] woocommerce/woocommerce-blocks#7329
- [x] woocommerce/woocommerce-blocks#7330
- [x] woocommerce/woocommerce-blocks#7331
- [x] woocommerce/woocommerce-blocks#7332
- [x] woocommerce/woocommerce-blocks#7333
- [x] woocommerce/woocommerce-blocks#7334
- [x] woocommerce/woocommerce-blocks#7834 
- [x] woocommerce/woocommerce-blocks#7835

### Settings & Variations

- [x] woocommerce/woocommerce-blocks#7218
- [x] woocommerce/woocommerce-blocks#7322
- [x] woocommerce/woocommerce-blocks#7324
- [x] woocommerce/woocommerce-blocks#7326
- [x] woocommerce/woocommerce-blocks#7621
- [x] woocommerce/woocommerce-blocks#7327
- [x] woocommerce/woocommerce-blocks#7325
- [x] woocommerce/woocommerce-blocks#7217
- [x] woocommerce/woocommerce-blocks#7320
- [x] woocommerce/woocommerce-blocks#7321
- [x] woocommerce/woocommerce-blocks#7323

### Filters

- [x] woocommerce/woocommerce-blocks#7251
- [x] woocommerce/woocommerce-blocks#7186
- [x] woocommerce/woocommerce-blocks#7162
- [x] woocommerce/woocommerce-blocks#7631

### Patterns
- [x] woocommerce/woocommerce-blocks#7624

### Bugs and polishing

- [x] woocommerce/woocommerce-blocks#6969
- [x] woocommerce/woocommerce-blocks#7627
- [x] woocommerce/woocommerce-blocks#7629
- [x] woocommerce/woocommerce-blocks#7632
- [x] woocommerce/woocommerce-blocks#7933
- [x] woocommerce/woocommerce-blocks#7758
- [x] woocommerce/woocommerce-blocks#7921
- [x] woocommerce/woocommerce-blocks#7511 
- [x] woocommerce/woocommerce-blocks#7746 

### Related blocking issues

- [x] woocommerce/woocommerce-blocks#7604 

## Phase 4
 
- [x] woocommerce/woocommerce-blocks#7245
- [x] woocommerce/woocommerce-blocks#6790 
- [x]  woocommerce/woocommerce-blocks#8131

### Enhancements

- [ ] 🛑  woocommerce/woocommerce-blocks#8133
- [x] woocommerce/woocommerce-blocks#8135

### Product elements

- [ ]  🔄 woocommerce/woocommerce-blocks#7954
- [x] woocommerce/woocommerce-blocks#8085
- [x] woocommerce/woocommerce-blocks#8859 
- [x] woocommerce/woocommerce-blocks#8086
- [x] woocommerce/woocommerce-blocks#8087
- [ ] 🔨  woocommerce/woocommerce#42489
- [ ] 🔄 woocommerce/woocommerce-blocks#8151
- [x] woocommerce/woocommerce-blocks#8152 

### Bugs and polishing

- [x] woocommerce/woocommerce-blocks#8069
- [x] woocommerce/woocommerce-blocks#8084
- [ ] 🔄 woocommerce/woocommerce#42491
- [x] woocommerce/woocommerce-blocks#8147 
- [x] woocommerce/woocommerce-blocks#8041 
- [x] woocommerce/woocommerce-blocks#8249
- [x] woocommerce/woocommerce-blocks#8296
- [x] woocommerce/woocommerce-blocks#8530
- [x] woocommerce/woocommerce-blocks#8546
- [x] woocommerce/woocommerce-blocks#8765

### Product elements

- [ ] woocommerce/woocommerce#42504
- [x] woocommerce/woocommerce-blocks#8338 
- [x] woocommerce/woocommerce#42478

#### Only required with custom “Inherit from template” logic

- [x] woocommerce/woocommerce-blocks#6863

### Settings and Variations

- [ ] woocommerce/woocommerce#42539
- [ ] woocommerce/woocommerce#42538
- [ ] woocommerce/woocommerce#42537

### Bugs and polishing

- [x] woocommerce/woocommerce-blocks#7607
- [x] woocommerce/woocommerce#42572
- [ ] woocommerce/woocommerce#42540
- [ ] woocommerce/woocommerce#42535
- [ ] woocommerce/woocommerce#42536
- [ ] woocommerce/woocommerce#42534
- [ ] woocommerce/woocommerce-blocks#7886
- [ ] woocommerce/woocommerce#42516
- [x] woocommerce/woocommerce#42497
- [x] woocommerce/woocommerce-blocks#8213
- [x] woocommerce/woocommerce-blocks#7866

### Flaky tests

- [x] woocommerce/woocommerce#42508 
- [x] woocommerce/woocommerce#42507 
- [x] woocommerce/woocommerce#42503 
- [x] woocommerce/woocommerce#42502

### Product elements

- [x] woocommerce/woocommerce#42542
- [ ] woocommerce/woocommerce-blocks#7634
- [x] woocommerce/woocommerce-blocks#6949
- [ ] woocommerce/woocommerce#42425 

### Settings and Variations
- [x] woocommerce/woocommerce-blocks#6787 
- [x] woocommerce/woocommerce-blocks#7633

#### Only required with custom “Inherit from template” logic (issues closed and shall be reopened in case we follow work on custom “Inherit from template”)
- [x] woocommerce/woocommerce-blocks#7626
- [x] woocommerce/woocommerce-blocks#7608
- [x] woocommerce/woocommerce-blocks#7645
- [x] woocommerce/woocommerce-blocks#7630
- [x] woocommerce/woocommerce-blocks#7620

🔄 - In progress
🔨 - Ready to work
🛑 - Blocked

**Comment by Aljullu** [comment]
Should we close this issue considering that we are focusing our efforts on the Product Collection block, now? @sunyatasattva

**Comment by sunyatasattva** [comment]
Yep! For posterity, I suppose this is the latest related epic: https://github.com/woocommerce/woocommerce/issues/42161 ? Can you confirm @kmanijak ?

**Comment by imanish003** [comment]
Hi @sunyatasattva,

You're correct; we are currently focusing on Epic #42161. Prior to this, our main focus was Epic #42389. This Thursday, Karol and I will have a sync call to reorganize the GitHub board.
