### ISSUE TITLE
Linked products

### ISSUE THREAD

**Issue by j111q** [woothemes/woocommerce#42691]
**User story**

- As a merchant,
- I want to be able to recommend cross-sells and upsells for different products 
- So that I can help shoppers to discover more of what I sell and encourage them to purchase more items 

**Design**
AkVNGImLgSqCObTQ3idVn7-fi-12744%3A198156

**Acceptance criteria**

- [x] When the user selects `Linked products`, we show two sections, Upsells and Cross-sells. 
- [x] When the user clicks on the Question Mark icon next to either of the section titles, we show the relevant tooltip with help text and a link to learn more about linked products.
- [x] By default for new stores, both sections should be empty.
- [x]  When empty, the Upsell and Cross-sell sections each have an empty state -- an illustrated icon with some help text. 
- [x] The user is able to dismiss the empty state for both sections.
- [x] When the user clicks `Choose products for me`, we add five products using the Related Products functionality that currently exists. 
- [x] If the user don’t have tags / attributes etc added yet, then we choose 5 randomly selected products that are publicly published and in-stock.
- [x] If a store has less than 5 other products that are publicly published and in-stock, then we choose the maximum number of products they have.
- [x] If there are products already selected under Upsell / Cross-sell (regardless whether they are user-selected ones or auto-generated ones), they all get replaced with the new recommended suggestions.
- [ ] When the user clicks on the Search field, and the Search bar is empty, we show 5 random products in the dropdown. If they have less than 5 additional products, we show the maximum number they have. 
- [ ]  When the user types in the Search bar, we show up to 5 products with Product Names or Descriptions that match the user's input.
- [ ] The Search dropdown always excludes products that have already been selected below.
- [ ] When the user clicks on a product from the dropdown, the selected product appears in the list below and the search dropdown closes.
- [ ]  Clicking the product name will open it in the editing view in a new tab.
- [ ]  The product name column has a fixed width of 525 pixels. If the name or price extends beyond this width, we truncate the text.
- [x]  Clicking the arrow button will open the product's page in a new tab.
- [x] Clicking the X button will remove the product from the section.
- [x]  When the user removes all products, we show the empty state again.
- [x] When the product is a Grouped Product or an External/Affiliate Product, the Cross-sell section should be hidden. Only the Upsell section should appear.

```[tasklist]
### Tasks
- [ ] https://github.com/woocommerce/woocommerce/issues/42914
- [ ] https://github.com/woocommerce/woocommerce/issues/42915
- [ ] https://github.com/woocommerce/woocommerce/issues/42917
- [ ] https://github.com/woocommerce/woocommerce/issues/42922
- [ ] https://github.com/woocommerce/woocommerce/issues/42923
```

**Comment by pmcpinto** [comment]
@j111q  thanks for creating the issue for the Linked products flow 🙌 . I have a couple of comments regarding the acceptance criteria (AC).

>  When the user clicks Choose products for me, we add five products using the Related Products functionality that currently exists.
> If the user don’t have tags / attributes etc added yet, then we choose 5 randomly selected products that are publicly published and in-stock.
> If a store has less than 5 other products that are publicly published and in-stock, then we choose the maximum number of products they have.

As I mentioned in my P2 comment (peCask-z5-p2#comment-684), I'm not confident that we should include this in the first iteration, as it can negatively impact the shopping experience, as mentioned by Baymard.

Another aspect that needs to be added to the AC is how the Linked Products tab should behave when the product is external or grouped. In the classic experience, it's only possible to add upsells when the user is creating/editing an external or grouped product.

**Comment by j111q** [comment]
@pmcpinto Ah I see, I thought your feedback re: Baymard was referring to the default behaviour, so I removed the requirement of it appearing by default. So now it should only appear when the user has already decided they _want_ Upsells / Cross-sells. We are simply helping them populate the list quickly, which they can then edit. 

> Another aspect that needs to be added to the AC is how the Linked Products tab should behave when the product is external or grouped. In the classic experience, it's only possible to add upsells when the user is creating/editing an external or grouped product.

Oh yes. Added it to the AC! Thanks for the catch!

**Comment by pmcpinto** [comment]
> So now it should only appear when the user has already decided they want Upsells / Cross-sells. We are simply helping them populate the list quickly, which they can then edit.

👍 

>  If the user don’t have tags / attributes etc added yet, then we choose 5 randomly selected products that are publicly published and in-stock.

Btw, while there's no right number, I think we should start with 3 selected products. 5 may be too overwhelming in mobile views, considering that they'll be randomly selected. Also, the higher the number, the more likely we are to suggest irrelevant products.

**Comment by mdperez86** [comment]
Hey @j111q 
 > When the user removes all products, we show the empty state again.
 
What should happen if the user already dismissed the empty state?

> The user is able to dismiss the empty state for both sections.

What this means? The empty state is dismissed once and forever? Only for the specific user? Only for the specific editing product?

**Comment by retrofox** [comment]
> > The user is able to dismiss the empty state for both sections.
> 
> What this means? The empty state is dismissed once and forever? Only for the specific user? Only for the specific editing product?

If we decide to implement the functionality at the Product level, we should use product metadata to store the state permanently.
In this case, we need to remember that saving the product will require the user's action (save product).
Or saving the product in the background which may cause unexpected consequences.

**Comment by retrofox** [comment]
> > > The user is able to dismiss the empty state for both sections.
> > 
> > 
> > What this means? The empty state is dismissed once and forever? Only for the specific user? Only for the specific editing product?
> 
> If we decide to implement the functionality at the Product level, we should use product metadata to store the state permanently. In this case, we need to remember that saving the product will require the user's action (save product). Or saving the product in the background which may cause unexpected consequences.

For now, let's store the flag in the user's preferences. We can modify this later if necessary.

**Comment by retrofox** [comment]
> Btw, while there's no right number, I think we should start with 3 selected products. 5 may be too overwhelming in mobile views, considering that they'll be randomly selected. Also, the higher the number, the more likely we are to suggest irrelevant products.

https://github.com/woocommerce/woocommerce/issues/43697
