### ISSUE TITLE
Product Editor: Text area field

### ISSUE THREAD

**Issue by mattsherman** [woothemes/woocommerce#42736]
## Description

A `woocommerce/product-text-area-field` should be implemented, similar to `woocommerce/product-text-field`, but supporting multi-line text.

```[tasklist]
### Tasks
- [ ] https://github.com/woocommerce/woocommerce/issues/44164
- [ ] https://github.com/woocommerce/woocommerce/issues/44165
- [ ] https://github.com/woocommerce/woocommerce/issues/43128
- [ ] https://github.com/woocommerce/woocommerce/issues/44221
- [ ] https://github.com/woocommerce/woocommerce/pull/46089
- [x] Set `summary` block as obsolete
- [ ] https://github.com/woocommerce/woocommerce/issues/44182
- [x] Add a Readme.md file
- [ ] https://github.com/woocommerce/woocommerce/pull/44198
- [ ] https://github.com/woocommerce/woocommerce/issues/45555
```

## References

- Community request for textarea: https://woocommercecommunity.slack.com/archives/C064QAWNDS9/p1701981783261749

**Comment by NTShop** [comment]
Please allow this field to support HTML :)

**Comment by retrofox** [comment]
I guess these text-area fields could for the description and summary blocks

**Comment by mattsherman** [comment]
> I guess these text-area fields could for the description and summary blocks

Ideally we would use the same field for all of these, but from a practical standpoint I don't see a *need* for the description and summary blocks to be updated at this point in time to use this new field.

**Comment by retrofox** [comment]
> Please allow this field to support HTML :)

Hi @NTShop, this PR addresses the `plain` (HTML) mode. https://github.com/woocommerce/woocommerce/pull/44191

**Comment by retrofox** [comment]
> Address disabled property

Let's work upstream for this one for now. There is a `disableEditing` property that handles the requirement correctly—however, [it isn't available in the public API](https://github.com/WordPress/gutenberg/blob/48e0c7d5a280ef940869a019b97e456d1467e6cd/packages/block-editor/src/components/rich-text/index.js#L463-L472).

**Comment by mattsherman** [comment]
> > Address disabled property
> 
> Let's work upstream for this one for now. There is a `disableEditing` property that handles the requirement correctly—however, [it isn't available in the public API](https://github.com/WordPress/gutenberg/blob/48e0c7d5a280ef940869a019b97e456d1467e6cd/packages/block-editor/src/components/rich-text/index.js#L463-L472).

That makes sense.

**Comment by retrofox** [comment]
checking `Set `summary` block as obsolete`. It's going to be addressed here https://github.com/woocommerce/woocommerce/issues/45510

**Comment by retrofox** [comment]
> Add a Readme.md file

https://github.com/woocommerce/woocommerce/pull/45513
