### ISSUE TITLE
[Epic] Product Editor Extensibility, REST API, SlotFills, generic fields

### ISSUE THREAD

**Issue by mattsherman** [woothemes/woocommerce#42735]
```[tasklist]
### REST API issues
- [ ] https://github.com/woocommerce/woocommerce/issues/40618
- [ ] https://github.com/woocommerce/woocommerce/issues/40620
```

```[tasklist]
### Product editor slots issues
- [ ] https://github.com/woocommerce/woocommerce/issues/42737
- [ ] https://github.com/woocommerce/woocommerce/issues/42805
```

```[tasklist]
### Fields issues
- [ ] https://github.com/woocommerce/woocommerce/issues/42736
- [ ] https://github.com/woocommerce/woocommerce/issues/42825
- [ ] https://github.com/woocommerce/woocommerce/issues/41478
- [ ] https://github.com/woocommerce/woocommerce/issues/42883
- [ ] https://github.com/woocommerce/woocommerce/issues/42884
```

```[tasklist]
### Terminology cleanup
- [ ] https://github.com/woocommerce/woocommerce/issues/42885
```

**Comment by pmcpinto** [comment]
I'm going to close this one. It refers to the new editor that will be removed.
