### ISSUE TITLE
[EPIC] Woo Block Hooks API (Phase 1)

### ISSUE THREAD

**Issue by tjcafferkey** [woothemes/woocommerce#42745]
Since the release of the Block Hooks API, WooCommerce has identified several high value use cases for this. However the API is still in its infancy so cautious adoption will help validate the API and help identify potential gaps to further its development.

The below task list reflects Phase 1.

```[tasklist]
### Tasks
- [ ] https://github.com/woocommerce/woocommerce/issues/42752
- [ ] https://github.com/woocommerce/woocommerce/issues/42754
- [ ] https://github.com/woocommerce/woocommerce/issues/42755
- [ ] https://github.com/woocommerce/woocommerce/issues/42756
- [ ] https://github.com/woocommerce/woocommerce/issues/42757
- [ ] https://github.com/woocommerce/woocommerce/issues/43266
```
