### ISSUE TITLE
[Epic] Developer-only custom checkout fields

### ISSUE THREAD

**Issue by senadir** [woothemes/woocommerce#42769]
This is an epic that will track all issues in the Custom Fields for Checkout project.

```[tasklist]
### Must Have
- [ ] https://github.com/woocommerce/woocommerce/issues/42772
- [ ] https://github.com/woocommerce/woocommerce/issues/42771
- [ ] https://github.com/woocommerce/woocommerce/issues/42133
- [ ] https://github.com/woocommerce/woocommerce/issues/42134
- [ ] https://github.com/woocommerce/woocommerce/issues/43277
- [ ] https://github.com/woocommerce/woocommerce/issues/43043
- [ ] https://github.com/woocommerce/woocommerce/issues/42082
- [ ] https://github.com/woocommerce/woocommerce/issues/42081
- [ ] https://github.com/woocommerce/woocommerce/issues/42776
- [ ] https://github.com/woocommerce/woocommerce/issues/42777
- [ ] https://github.com/woocommerce/woocommerce/issues/42775
- [ ] https://github.com/woocommerce/woocommerce/issues/42779
- [ ] https://github.com/woocommerce/woocommerce/issues/42137
- [ ] https://github.com/woocommerce/woocommerce/issues/42136
- [ ] https://github.com/woocommerce/woocommerce/issues/42024
- [ ] https://github.com/woocommerce/woocommerce/issues/42025
- [ ] https://github.com/woocommerce/woocommerce/issues/42132
- [ ] https://github.com/woocommerce/woocommerce/issues/42131
- [ ] https://github.com/woocommerce/woocommerce/issues/42077
- [ ] https://github.com/woocommerce/woocommerce/issues/42135
- [ ] https://github.com/woocommerce/woocommerce/issues/42116
- [ ] https://github.com/woocommerce/woocommerce/issues/43525
- [ ] https://github.com/woocommerce/woocommerce/issues/44045
- [ ] https://github.com/woocommerce/woocommerce/issues/44495
- [ ] https://github.com/woocommerce/woocommerce/issues/45841
- [ ] https://github.com/woocommerce/woocommerce/issues/45496
- [ ] https://github.com/woocommerce/woocommerce/pull/45789
```

Issues here will be moved to either Nice to Have or Must Have.
```[tasklist]
### Need Product/Design input
- [ ] https://github.com/woocommerce/woocommerce/issues/42139
- [ ] https://github.com/woocommerce/woocommerce/issues/42125
- [ ] https://github.com/woocommerce/woocommerce/issues/42138
```

```[tasklist]
### Nice to Have
- [ ] https://github.com/woocommerce/woocommerce/issues/42778
- [ ] https://github.com/woocommerce/woocommerce/issues/42080
- [ ] https://github.com/woocommerce/woocommerce/issues/42773
- [ ] https://github.com/woocommerce/woocommerce/issues/42079
- [ ] https://github.com/woocommerce/woocommerce/issues/42774
- [ ] https://github.com/woocommerce/woocommerce/issues/42088
- [ ] https://github.com/woocommerce/woocommerce/issues/42127
- [ ] https://github.com/woocommerce/woocommerce/issues/42130
- [ ] https://github.com/woocommerce/woocommerce/issues/42129
- [ ] https://github.com/woocommerce/woocommerce/issues/42128
- [ ] https://github.com/woocommerce/woocommerce/issues/42126
- [ ] https://github.com/woocommerce/woocommerce/issues/43524
- [ ] https://github.com/woocommerce/woocommerce/issues/43657
- [ ] https://github.com/woocommerce/woocommerce/issues/43680
- [ ] https://github.com/woocommerce/woocommerce/issues/44019
- [ ] https://github.com/woocommerce/woocommerce/issues/45545
- [ ] https://github.com/woocommerce/woocommerce/issues/45938
- [ ] https://github.com/woocommerce/woocommerce/issues/45988
- [ ] https://github.com/woocommerce/woocommerce/issues/45989
- [ ] https://github.com/woocommerce/woocommerce/issues/50795
- [ ] https://github.com/woocommerce/woocommerce/issues/51255
```

**Comment by senadir** [comment]
The project has been split into 2 categories to see what we need to ship right now and what we can follow up with.

**Comment by ralucaStan** [comment]
I've renamed this to match the project thread title

**Comment by webdados** [comment]
Can you please add #45938 to this epic?

**Comment by senadir** [comment]
Done! thanks for the suggestion :D

**Comment by webdados** [comment]
New issues to add to this epic, please:
https://github.com/woocommerce/woocommerce/issues/45988
https://github.com/woocommerce/woocommerce/issues/45989

**Comment by webdados** [comment]
New issues to add to this epic, please:
#50795 
#51255

**Comment by ralucaStan** [comment]
I think we can close the epic for now and revisit it to extract pending items.
