### ISSUE TITLE
Manage empty state

### ISSUE THREAD

**Issue by mdperez86** [woothemes/woocommerce#42917]
**Prerequisites (mark completed items with an [x]):**
- [ ] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [ ] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

**ACs**

```[tasklist]
### Tasks
- [x] By default for new stores, both sections should be empty.
- [x] When empty, the Upsell and Cross-sell sections each have an empty state -- an illustrated icon with some help text. AkVNGImLgSqCObTQ3idVn7-fi-12744_189608, AkVNGImLgSqCObTQ3idVn7-fi-12744_189608
- [x] The user is able to dismiss the empty state for both sections. AkVNGImLgSqCObTQ3idVn7-fi-3295_303324
```
