### ISSUE TITLE
Manage `Choose products for me`

### ISSUE THREAD

**Issue by mdperez86** [woothemes/woocommerce#42922]
**Prerequisites (mark completed items with an [x]):**
- [ ] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [ ] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

**ACs**

```[tasklist]
### Tasks
- [x] When the user clicks Choose products for me, we add five products using the existing [Related Products](https://woo.com/document/related-products-up-sells-and-cross-sells/#section-3) functionality. AkVNGImLgSqCObTQ3idVn7-fi-12744_192579. Depends on #42849
- [x] If the user don’t have tags / attributes etc added yet, then we choose 5 randomly selected products that are publicly published and in-stock.
- [x] If a store has less than 5 other products that are publicly published and in-stock, then we choose the maximum number of products they have.
- [x] If there are products already selected under Upsell / Cross-sell (regardless whether they are user-selected ones or auto-generated ones), they all get replaced with the new recommended suggestions.
```

**Comment by mdperez86** [comment]
For Related Products logic, see what was implemented in https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/includes/class-wc-shortcodes.php#L695C3-L695C41
