### ISSUE TITLE
Linked product list

### ISSUE THREAD

**Issue by mdperez86** [woothemes/woocommerce#42923]
**Prerequisites (mark completed items with an [x]):**
- [ ] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [ ] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

**ACs**

```[tasklist]
### Tasks
- [x] When the user clicks on the Search field, and the Search field is empty, we show 5 random products in the dropdown. If they have less than 5 additional products, we show the maximum number they have. AkVNGImLgSqCObTQ3idVn7-fi-12744_192742
- [x] When the user types in the Search bar, we show up to 5 products with Product Names or Descriptions that match the user's input.
- [x] The Search dropdown always excludes products that have already been selected below.
- [x] When the user clicks on a product from the dropdown, the selected product appears in the list below and the search dropdown closes.
- [x] Clicking the product name will open it in the editing view in a new tab. AkVNGImLgSqCObTQ3idVn7-fi-12744_193642
- [x] The product name column has a fixed width of 525 pixels. If the name or price extends beyond this width, we truncate the text.
- [x] Clicking the arrow button will open the product's page in a new tab. AkVNGImLgSqCObTQ3idVn7-fi-12744_193642
- [x] Clicking the X button will remove the product from the section. AkVNGImLgSqCObTQ3idVn7-fi-12744_193642
- [x] When the user removes all products, we show the empty state again.
```
