### ISSUE TITLE
Product Collection M1: Implementation of contextual awareness for collections and filters

### ISSUE THREAD

**Issue by kmanijak** [woothemes/woocommerce#43037]
⚠️ **This is not a final scope. TBC**

**Issue Description:**

Both collections and filters will need to be aware of their context:

- Collections (pending design) may ask for user input depending on their placement, for example a Frequently Bought Together collection may require the user to search for and provide a product to generate recommendations in contexts where a product is not implied (e.g. pages, posts).
- Collection filters and options (e.g. “From current category”) will be conditionally surfaced depending on the editor context.

In some cases content may be inferred by a parent block. This goal of this project is to implement a provider for the following contexts, both on the editor side and on the store/frontend side:

- Single Product (product ID)
- Product Archive (product taxonomy)
- Order (list of order items / order details)
- Cart/Checkout (list of cart items and checkout/session data is available)
- Session (session data, e.g. user id — could be empty)

```[tasklist]
### Tasks
- [ ] https://github.com/woocommerce/woocommerce/issues/42167
- [ ] https://github.com/woocommerce/woocommerce/issues/42861
- [ ] https://github.com/woocommerce/woocommerce/issues/43694
- [ ] https://github.com/woocommerce/woocommerce/issues/44086
- [ ] https://github.com/woocommerce/woocommerce/issues/43991
- [ ] https://github.com/woocommerce/woocommerce/issues/44294
- [ ] https://github.com/woocommerce/woocommerce/pull/44636
```
