### ISSUE TITLE
Product Collection M1: Ship “core” set of Product Collection filters

### ISSUE THREAD

**Issue by kmanijak** [woothemes/woocommerce#43036]
**Issue Description:**

Merchants can customize core and extended collections by adding the following filters:
- ✅ Price (lt, gt)
- ✅ Creation date
- ✅ Keyword
- ✅ Featured status
- ✅ Product attributes 
- ✅ Custom Product taxonomies 
- ✅ Sale status (boolean)
- Stock status (✅ in, ❌ not in)
- Category (✅ in, ❌ not in)
- Products (✅ in, ❌ not in)
- Tag (✅ in, ❌ not in)

All core filters are available in all editor contexts. 

```[tasklist]
### Tasks
- [ ] https://github.com/woocommerce/woocommerce/issues/43370
- [ ] https://github.com/woocommerce/woocommerce/issues/43371
- [ ] https://github.com/woocommerce/woocommerce/issues/43372
- [ ] https://github.com/woocommerce/woocommerce/issues/43373
- [ ] https://github.com/woocommerce/woocommerce/issues/42049
- [ ] https://github.com/woocommerce/woocommerce/issues/43673
- [ ] https://github.com/woocommerce/woocommerce/issues/46850
```

**Comment by kmanijak** [comment]
Closing as done
