### ISSUE TITLE
Revisit how we set `WOOCOMMERCE_BLOCKS_PHASE` env variable

### ISSUE THREAD

**Issue by gigitux** [woothemes/woocommerce#43073]
**Prerequisites (mark completed items with an [x]):**
- [x] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [x] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

**Issue Description:**

The `WOOCOMMERCE_BLOCKS_PHASE` is a feature flag necessary to expose some features only for the feature plugin (now deprecated) or development.

Currently, the env variable `WOOCOMMERCE_BLOCKS_PHASE` is never set. This means that even for the product build, we expose features that should be available on the development build.  ([source code](https://github.com/woocommerce/woocommerce/blob/a9550d8894ea5de1f02fc954ff41db8eac487f73/plugins/woocommerce-blocks/bin/webpack-configs.js/#L126-L127))

This is the list of the current flag: https://github.com/woocommerce/woocommerce/blob/a9550d8894ea5de1f02fc954ff41db8eac487f73/plugins/woocommerce/src/Blocks/Domain/Services/FeatureGating.php/#L18-L21.

Looking at the `package.json` of the block-library project, we have to pass the env variable from the external: https://github.com/woocommerce/woocommerce/blob/a9550d8894ea5de1f02fc954ff41db8eac487f73/plugins/woocommerce-blocks/package.json/#L357-L367.

There are a few things to consider before implementing a robust solution:
- we should remove the `feature_plugin` flag and revisit all the features under the `feature_plugin` flag, and decide if we should promote to the core, if not, we have to "downgrade" them to "development".
- we have a similar issue for the variable `NODE_ENV`: https://github.com/woocommerce/woocommerce/blob/a9550d8894ea5de1f02fc954ff41db8eac487f73/plugins/woocommerce-blocks/bin/webpack-configs.js/#L127-L128

```[tasklist]
### Tasks
- [ ] https://github.com/woocommerce/woocommerce/issues/47692
- [ ] https://github.com/woocommerce/woocommerce/issues/47693
- [ ] https://github.com/woocommerce/woocommerce/issues/47694
- [ ] https://github.com/woocommerce/woocommerce/issues/47695
```

**Comment by gigitux** [comment]
Even if https://github.com/woocommerce/woocommerce/pull/43074 has been merged, we have to:
- find a better solution, this looks like a very raw approach.
- we should remove the feature_plugin flag and revisit all the features under the feature_plugin flag, and decide if we should promote to the core, if not, we have to "downgrade" them to "development".
- we have a similar issue for the `NODE_ENV` variable.
- add tests to ensure that the variable is set correctly.

**Comment by samueljseay** [comment]
@gigitux can you further explain the `NODE_ENV` issue? When I look at `NODE_ENV` usage it's just controlling webpack optimization in blocks afaict, which seems fine to me. Is there another problem with this approach?

EDIT: I think it might be referring to our `FeatureGating->is_development_environment()` and `is_production_environment()` methods.

**Comment by samueljseay** [comment]
I think what I really want to achieve here is some agreement on proposed steps to fix this because as I look through the code base there is not a lot of stuff to fix but it's piecemeal so we need a coordinated and agreed strategy to fix. Some of this will sound like what @gigitux has alluded to in his comment already.

My first thought is we should streamline what "environments" we have. In core WooCommerce (not including WC admin) I cannot find any consistently applied concept of development versus production. 
So I think we should forget the concept in PHP of development versus production. There are only a couple of times we do this with FeatureGating anyway. Let me list them:

1. A [fallback for whether we should cache or not](https://github.com/woocommerce/woocommerce/blob/f0b9be38cc8bab9799083b4c907d1d2b781f0b1f/plugins/woocommerce/src/Blocks/Assets/Api.php#L74) 

2. Determining if [block templates controller refactor](https://github.com/woocommerce/woocommerce/blob/f0b9be38cc8bab9799083b4c907d1d2b781f0b1f/plugins/woocommerce/src/Blocks/Domain/Services/FeatureGating.php#L164) is enabled

3. Determining if we should [do circular dep checking](https://github.com/woocommerce/woocommerce/blob/f0b9be38cc8bab9799083b4c907d1d2b781f0b1f/plugins/woocommerce/src/Blocks/Assets/Api.php#L250)

4. For [buildPhase of wcBlocksConfig](https://github.com/woocommerce/woocommerce/blob/f0b9be38cc8bab9799083b4c907d1d2b781f0b1f/plugins/woocommerce/src/Blocks/BlockTypes/AbstractBlock.php#L440)

I need some help determining what we should do with 1 and 2, for 3 I think we could rely on `WP_DEBUG`? for 4 it's quite solvable depending on how we treat registering experimental blocks as it's only used to determine block registration.

Once we refactor these 4 usages we can remove `FeatureGating`.

My next thought is that we need to decide how to treat experimental blocks. We have 2 options:

1. Demote them to development only
2. Find another way to mark them experimental

If we demote them to development only its a bit of a pain for testing. We do a production build of WC for live branches and playground, which I think still makes sense.

Could we consider using one umbrella setting in the experimental feature settings of core to encapsulate all experimental blocks? To be clear the settings code I'm talking about is this code: https://github.com/woocommerce/woocommerce/blob/f0b9be38cc8bab9799083b4c907d1d2b781f0b1f/plugins/woocommerce/src/Internal/Features/FeaturesController.php#L163 This already exposes a UI for setting/unsetting, it has tests etc.

We could also consider whether we can solve `2` via this approach too?

Here's a suggested tasklist:

- [ ] Refactor [caching logic](https://github.com/woocommerce/woocommerce/blob/f0b9be38cc8bab9799083b4c907d1d2b781f0b1f/plugins/woocommerce/src/Blocks/Assets/Api.php#L74) to remove use of `FeatureGating`
- [ ] Refactor [block templates controller refactor](https://github.com/woocommerce/woocommerce/blob/f0b9be38cc8bab9799083b4c907d1d2b781f0b1f/plugins/woocommerce/src/Blocks/Domain/Services/FeatureGating.php#L164) flag to use `FeaturesController` experimental features
- [ ] Refactor [circular dep checking](https://github.com/woocommerce/woocommerce/blob/f0b9be38cc8bab9799083b4c907d1d2b781f0b1f/plugins/woocommerce/src/Blocks/Assets/Api.php#L250) to use `WP_DEBUG`
- [ ] Put all experimental blocks behind `FeaturesController` experimental features
- [ ] Remove `FeatureGating`, all mentions of `blocks.ini`, WC_BLOCKS_PHASE, WC_BLOCKS_IS_FEATURE_PLUGIN

**Comment by samueljseay** [comment]
Follow up I did some more reading on background here and I missed the many usages of `isFeaturePluginBuild` https://github.com/woocommerce/woocommerce/blob/f0b9be38cc8bab9799083b4c907d1d2b781f0b1f/plugins/woocommerce-blocks/assets/js/settings/blocks/feature-flags.ts#L52

There has been much discussion about RFCs for better handling of experimental features, but I'd like to suggest one more addition to `FeaturesController` here to support "experimental block styling" or similar, since most usages focus on this. Because realistically we won't get to move on a new feature gating implementation in the near future.

- [ ] Add "Experimental block styling" option to `FeaturesController`
- [ ] Migrate all usages of `isFeaturePluginBuild` to new FeaturesController option.

**Comment by gigitux** [comment]
> can you further explain the `NODE_ENV` issue? When I look at `NODE_ENV` usage it's just controlling webpack optimization in blocks afaict, which seems fine to me. Is there another problem with this approach?

Thanks, @samueljseay, for checking it! I missed it, and I was convinced that `NODE_ENV` was an unset variable! 😅

I agree 💯 with all your points except for:

> Refactor [circular dep checking](https://github.com/woocommerce/woocommerce/blob/f0b9be38cc8bab9799083b4c907d1d2b781f0b1f/plugins/woocommerce/src/Blocks/Assets/Api.php#L250) to use WP_DEBUG

I'm unsure about this; `WP_DEBUG` differs from dev env. Even if the user sees the error, they cannot fix it. IMHO, we should keep this logic for dev builds.

> My next thought is that we need to decide how to treat experimental blocks. 

IMHO `FeaturesController` is a great fit for experimental blocks!

**Comment by samueljseay** [comment]
Thanks @gigitux i will have a think about how we can solve the circular deps issue. Appreciate the feedback!

**Comment by samueljseay** [comment]
I'm going to propose that for situations where we need to detect environment that we use `WC_ENVIRONMENT_TYPE`/ https://developer.wordpress.org/reference/functions/wp_get_environment_type/ which can be set in wp-config.php, this should allow us to get rid of the last of FeatureGating. FeatureGating has a check for test environment but its not used. I will create a task for this just for efficiency, but if we don't like it, the approach can still be changed.

cc @gigitux

**Comment by samueljseay** [comment]
Also just discovered that `is_block_templates_controller_refactor_enabled` is no longer used actually! So we can remove that usage, we will only need to check environment for the circular deps check.

**Comment by samueljseay** [comment]
@gigitux regarding:

> I'm going to propose that for situations where we need to detect environment that we use WC_ENVIRONMENT_TYPE/ https://developer.wordpress.org/reference/functions/wp_get_environment_type/ which can be set in wp-config.php

I don't remember if we discussed this, but what do you think about this approach to determining dev versus prod in PHP? It seems the blessed way in other codebases I've seen.

**Comment by gigitux** [comment]
> @gigitux regarding:
> 
> > I'm going to propose that for situations where we need to detect environment that we use WC_ENVIRONMENT_TYPE/ https://developer.wordpress.org/reference/functions/wp_get_environment_type/ which can be set in wp-config.php
> 
> I don't remember if we discussed this, but what do you think about this approach to determining dev versus prod in PHP? It seems the blessed way in other codebases I've seen.

I, too, can't remember if we discussed this already 😆


Can't we just use `wp_get_environment_type`? What is the benefit of adding an additional variable?

**Comment by samueljseay** [comment]
> Can't we just use wp_get_environment_type? What is the benefit of adding an additional variable?

@gigitux I'm confused... what variable? `WC_ENVIRONMENT_TYPE` ? that's what I'm suggesting :D `wp_get_environment_type` is set via `WC_ENVIRONMENT_TYPE` under the hood so you can control it via wp config.

**Comment by gigitux** [comment]
> > Can't we just use wp_get_environment_type? What is the benefit of adding an additional variable?
> 
> @gigitux I'm confused... what variable? `WC_ENVIRONMENT_TYPE` ? that's what I'm suggesting :D `wp_get_environment_type` is set via `WC_ENVIRONMENT_TYPE` under the hood so you can control it via wp config.

From what I understand, `wp_get_environment_type` relies on `WP_ENVIRONMENT_TYPE.` For me it makes sense use it! I'm not sure if you're proposing to add an additional variable: `WC_ENVIRONMENT_TYPE`. If yes, I'm not super convinced, but maybe I'm missing something.

**Comment by samueljseay** [comment]
> From what I understand, wp_get_environment_type relies on WP_ENVIRONMENT_TYPE.

Yes exactly, I'm not suggesting adding another variable :) 

Lets do it :D

**Comment by sunyatasattva** [comment]
Looks like all the tasks for this are done, can we close it? cc @gigitux @louwie17 @samueljseay

**Comment by gigitux** [comment]
Thanks for the ping! Yes!
