### ISSUE TITLE
Remove Variable product template from the product template list

### ISSUE THREAD

**Issue by mdperez86** [woothemes/woocommerce#43225]
**Prerequisites (mark completed items with an [x]):**
- [ ] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [ ] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

**Description**

Currently a variable product is shown in the list of supported product templates. The variable product should be treated as a standard product. 

**ACs**
```[tasklist]
### Tasks
- [x] Remove Variable product from the product template list.
- [x] If the product is variable and if it does not have a product template associated to it then the Standard product type should be highlighted by default.
- [x] The user should be redirected to the new product experience if the product was created in the classic experience and it has variable as type.
```
