### ISSUE TITLE
Remove associated product template when editing the product in the classic editor

### ISSUE THREAD

**Issue by mdperez86** [woothemes/woocommerce#43226]
**Prerequisites (mark completed items with an [x]):**
- [ ] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [ ] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

**Description**

If the user creates/edits a product in the new product experience the product could have a product template associated to it. If the is the case and if the user changes the product type in the classic editor and then redirect to the new editor the incorrect product template will be loaded and the user will se the wrong layout template.

**ACs**
```[tasklist]
### Tasks
- [ ] Remove the associated product template when editing a product in the classic editor.
```

**Comment by nathanss** [comment]
The PR https://github.com/woocommerce/woocommerce/pull/43384 will potentially fix this issue

**Comment by pmcpinto** [comment]
@mdperez86 is this still in review?

**Comment by mdperez86** [comment]
Solved in https://github.com/woocommerce/woocommerce/pull/43384
