### ISSUE TITLE
Redirect supported product types to the new experience based on the product template associated to it

### ISSUE THREAD

**Issue by mdperez86** [woothemes/woocommerce#43224]
**Prerequisites (mark completed items with an [x]):**
- [ ] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [ ] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

**Description**

When the product is created based on a selected product template, if the product template is not listed as part of the supported types then the user is redirected to the classic experience and it should not.

**ACs**
```[tasklist]
### Tasks
- [ ] Only redirect users to the classic experience (a) if the product does not has a product template, (b) if it has a product template but not a layout template.
```
