### ISSUE TITLE
Product Collection - Removing beta label

### ISSUE THREAD

**Issue by imanish003** [woothemes/woocommerce#43263]
This Epic contains all the tasks that must be completed before removing the beta label from the Product Collection block.
```[tasklist]
### Tasks
- [ ] https://github.com/woocommerce/woocommerce/issues/43393
- [ ] https://github.com/woocommerce/woocommerce/issues/42195
- [ ] https://github.com/woocommerce/woocommerce/issues/42284
- [ ] https://github.com/woocommerce/woocommerce/issues/42038
- [ ] https://github.com/woocommerce/woocommerce/issues/44394
- [ ] https://github.com/woocommerce/woocommerce/issues/44393
- [ ] https://github.com/woocommerce/woocommerce/pull/45135
- [ ] https://github.com/woocommerce/woocommerce/issues/44525
- [ ] https://github.com/woocommerce/woocommerce/issues/43395
- [ ] https://github.com/woocommerce/woocommerce/issues/43394
- [ ] https://github.com/woocommerce/woocommerce/issues/43396
- [ ] https://github.com/woocommerce/woocommerce/issues/43311
- [ ] https://github.com/woocommerce/woocommerce/issues/44391
- [ ] https://github.com/woocommerce/woocommerce/issues/45301
- [ ] https://github.com/woocommerce/woocommerce/issues/43397
- [ ] https://github.com/woocommerce/woocommerce/issues/45214
- [ ] https://github.com/woocommerce/woocommerce/issues/45644
- [ ] https://github.com/woocommerce/woocommerce/issues/46156
- [ ] https://github.com/woocommerce/woocommerce/pull/46228
- [ ] https://github.com/woocommerce/woocommerce/issues/47351
```

**Comment by kmanijak** [comment]
Beta label has been removed, closing as done
