### ISSUE TITLE
Create API endpoint to duplicate a certain product

### ISSUE THREAD

**Issue by louwie17** [woothemes/woocommerce#43282]
**Issue Description:**

As part of https://github.com/woocommerce/woocommerce/issues/43062 we will allow users to duplicate a given product and safe it as draft.
This would be best if it was done server side with the option of an endpoint.

This issue is to add a duplicate endpoint to the Woo REST api. 

**Implementation details**

- A new `duplicate` endpoint should be created, which takes a product ID and returns a new duplicate of the product, in draft status

**Acceptance criteria**

```[tasklist]
### Tasks
- [x] Create new endpoint POST `wc/v3/products/<product id>/duplicate` that creates and returns a new draft product copied from the passed in product id.
- [x] Endpoint should support the status ( or potential other product data ) as part of the POST and adhere to that. Status will default to `draft`
- [x] Name should include `(Copy)` at the end
- [x] For variable product we should copy over the variations as well ( the fixed amount, similar as the classic experience, we will have a follow up issue for supporting variations above the limit >100 ).
- [x] Add PHP tests
```

**Comment by octaedro** [comment]
> I have a question related to this point. From this part: _or potential other product data_, I understand that the endpoint is also expected to receive props with product data and update the product after the duplication. Is that correct?

Correct!

> If that's the case, I don't think we should do everything together since these are two separate actions. If we need to duplicate and update the product, I would create a separate endpoint for that. However, I think the best option for the mentioned case is to call two different endpoints.

I don't quite agree, why would we create a separate endpoint for duplicating and updating? Also its much easier from the front-end perspective to just call a single endpoint and have both done.
In order to duplicate currently we already have to modify some parts of the duplicated product anyhow like the SKU and name ( see some of the [legacy update logic](https://github.com/woocommerce/woocommerce/blob/ef015f740f89c35cebf34bc0c39a971be6723b68/plugins/woocommerce/includes/admin/class-wc-admin-duplicate-product.php#L152) ).

The additional data is optional and not required, so it will act like a normal duplicate endpoint unless the additional data is passed in.
