### ISSUE TITLE
Improve the validation process when changing the product type

### ISSUE THREAD

**Issue by mdperez86** [woothemes/woocommerce#43280]
**Prerequisites (mark completed items with an [x]):**
- [ ] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [ ] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

**Description**

When changing the product type by using the `Change product type` selector in the `Basic details` section some validation errors could occurs disabling the user to perform the change. It is a little annoying specially when the required fields are outside of the visible area of the screen. In this case the user does not know the root cause and could be perceived as a bug.
An example is when trying to change from an external product to a simple one, since the `LINK TO THE EXTERNAL PRODUCT` field is required it needs to be filled just like the `NAME` to be able to continue with the change. 

**ACs**

```[tasklist]
### Tasks
- [x] Remove the required validation constraint from the `LINK TO THE EXTERNAL PRODUCT` field
```

**Comment by mdperez86** [comment]
@j111q @pmcpinto @louwie17 We need help to understand the best way to solve this. From design, technical and product point of views.

**Comment by pmcpinto** [comment]
We have this error handling proposal by Jarek: https://github.com/woocommerce/woocommerce/issues/40371

But it requires the side panel, and I'm not 100% sure it could work well with this use case.

> An example is when trying to change from an external product to a simple one, since the LINK TO THE EXTERNAL PRODUCT field is required it needs to be filled just like the NAME to be able to continue with the change.

Is this the only use case? We can simplify and remove the required condition from the external product link field. We don't have it as required field in the classic experience.

**Comment by pmcpinto** [comment]
> Is this the only use case? We can simplify and remove the required condition from the external product link field. We don't have it as required field in the classic experience.

@mdperez86 can you check this? Thanks!

**Comment by mdperez86** [comment]
@pmcpinto 

> Is this the only use case? We can simplify and remove the required condition from the external product link field. We don't have it as required field in the classic experience.

In all product types that the new product experience currently supports I only see two required fields, the product `NAME` and the `LINK TO THE EXTERNAL PRODUCT`. While as a work around we can remove the required validation from the `LINK TO THE EXTERNAL PRODUCT` field, that is not going to solve the real problem because:

1. The `NAME` field is still required and the user is not going to be able to change the product type when the `NAME` field is empty. (In this case the problem is not too bad since the field with the error is visible on the screen, so the user can see the validation error)
2. If a 3rd party plugin registers a new product type/layout template with more validations the problem remains.

If this issue is critical enough I recommend to do your suggestion and implement the real fix as part of the error handling by Jarek https://github.com/woocommerce/woocommerce/issues/40371 or another future issue.

**Comment by pmcpinto** [comment]
@mdperez86  thanks for the clarification.

I think we should remove the required condition for the external product field. The validation error for the name has enough visibility, so I'm not super concerned.

> If a 3rd party plugin registers a new product type/layout template with more validations the problem remains

We can address this once the team is ready to start implementing #40371. And I think @j111q will take a look at the error handling flow proposed by Jarek.
