### ISSUE TITLE
[EPIC] Customize your Store - Pattern Assembler

### ISSUE THREAD

**Issue by nefeline** [woothemes/woocommerce#43623]
Prepare the Customize Your Store (CYS) onboarding flow for general release, ensuring all eligible features are available for use in the core of WooCommerce.

This project can be divided into four macro tasks:

* Update in-app marketplace and transitional pages

* Update the copy and designs to match those the design team provided. Add any metrics if they were not already implemented in the previous phase on WooExpress.

* Explore relying on [the new Font Library](https://github.com/WordPress/gutenberg/issues/54169) (expected to be released on WordPress 6.5) to power the Assembler's fonts feature.

* The conditional removal of any Jetpack dependencies from the Pattern Assembler.
```[tasklist]
### Tasks
- [ ] https://github.com/woocommerce/woocommerce/issues/42865
- [ ] https://github.com/woocommerce/woocommerce/issues/43491
- [ ] https://github.com/woocommerce/woocommerce/issues/43490
- [ ] https://github.com/woocommerce/woocommerce/issues/43485
- [ ] https://github.com/woocommerce/woocommerce/issues/43492
- [ ] https://github.com/woocommerce/woocommerce/issues/43486
- [ ] https://github.com/woocommerce/woocommerce/issues/43482
- [ ] https://github.com/woocommerce/woocommerce/issues/43480
- [ ] https://github.com/woocommerce/woocommerce/issues/43462
- [ ] https://github.com/woocommerce/woocommerce/issues/43459
- [ ] https://github.com/woocommerce/woocommerce/issues/43456
- [ ] https://github.com/woocommerce/woocommerce/issues/43454
- [ ] https://github.com/woocommerce/woocommerce/issues/41924
- [ ] https://github.com/woocommerce/woocommerce/issues/43667
- [ ] https://github.com/woocommerce/woocommerce/issues/43780
- [ ] https://github.com/woocommerce/woocommerce/issues/43856
- [ ] https://github.com/woocommerce/woocommerce/issues/44005
- [ ] https://github.com/woocommerce/woocommerce/issues/44009
- [ ] https://github.com/woocommerce/woocommerce/issues/44010
- [ ] https://github.com/woocommerce/woocommerce/issues/44067
- [ ] https://github.com/woocommerce/woocommerce/issues/44076
- [ ] https://github.com/woocommerce/woocommerce/issues/44187
- [ ] https://github.com/woocommerce/woocommerce/issues/44257
- [ ] https://github.com/woocommerce/woocommerce/issues/44258
- [ ] https://github.com/woocommerce/woocommerce/issues/44259
- [ ] https://github.com/woocommerce/woocommerce/issues/44307
- [ ] https://github.com/woocommerce/woocommerce/issues/44315
- [ ] https://github.com/woocommerce/woocommerce/issues/44385
- [ ] https://github.com/woocommerce/woocommerce/issues/44427
- [ ] https://github.com/woocommerce/woocommerce/issues/44457
- [ ] https://github.com/woocommerce/woocommerce/issues/44543
- [ ] https://github.com/woocommerce/woocommerce/issues/44545
- [ ] https://github.com/woocommerce/woocommerce/issues/44547
- [ ] https://github.com/woocommerce/woocommerce/issues/44552
- [ ] https://github.com/woocommerce/woocommerce/issues/44548
- [ ] https://github.com/woocommerce/woocommerce/issues/44555
- [ ] https://github.com/woocommerce/woocommerce/issues/44576
- [ ] https://github.com/woocommerce/woocommerce/issues/44578
- [ ] https://github.com/woocommerce/woocommerce/issues/44602
- [ ] https://github.com/woocommerce/woocommerce/issues/44609
- [ ] https://github.com/woocommerce/woocommerce/issues/44610
- [ ] https://github.com/woocommerce/woocommerce/issues/44614
- [ ] https://github.com/woocommerce/woocommerce/issues/44685
- [ ] https://github.com/woocommerce/woocommerce/issues/44700
- [ ] https://github.com/woocommerce/woocommerce/issues/44725
- [ ] https://github.com/woocommerce/woocommerce/issues/44726
- [ ] https://github.com/woocommerce/woocommerce/issues/44766
- [ ] https://github.com/woocommerce/woocommerce/issues/44794
- [ ] https://github.com/woocommerce/woocommerce/issues/44887
- [ ] https://github.com/woocommerce/woocommerce/issues/44889
- [ ] https://github.com/woocommerce/woocommerce/issues/45138
- [ ] https://github.com/woocommerce/woocommerce/issues/45215
- [ ] https://github.com/woocommerce/woocommerce/issues/45221
- [ ] https://github.com/woocommerce/woocommerce/issues/45279
- [ ] https://github.com/woocommerce/woocommerce/issues/45307
- [ ] https://github.com/woocommerce/woocommerce/issues/45341
- [ ] https://github.com/woocommerce/woocommerce/issues/45343
- [ ] https://github.com/woocommerce/woocommerce/issues/45344
- [ ] https://github.com/woocommerce/woocommerce/issues/45350
- [ ] https://github.com/woocommerce/woocommerce/issues/45398
- [ ] https://github.com/woocommerce/woocommerce/issues/45420
- [ ] https://github.com/woocommerce/woocommerce/issues/45383
- [ ] https://github.com/woocommerce/woocommerce/issues/45380
- [ ] https://github.com/woocommerce/woocommerce/issues/45379
- [ ] https://github.com/woocommerce/woocommerce/issues/45284
- [ ] https://github.com/woocommerce/woocommerce/issues/45281
- [ ] https://github.com/woocommerce/woocommerce/issues/45104
- [ ] https://github.com/woocommerce/woocommerce/issues/44820
- [ ] https://github.com/woocommerce/woocommerce/issues/44435
- [ ] https://github.com/woocommerce/woocommerce/issues/45418
- [ ] https://github.com/woocommerce/woocommerce/issues/45377
- [ ] https://github.com/woocommerce/woocommerce/issues/45282
- [ ] https://github.com/woocommerce/woocommerce/issues/44916
- [ ] https://github.com/woocommerce/woocommerce/issues/44823
- [ ] https://github.com/woocommerce/woocommerce/issues/45448
- [ ] https://github.com/woocommerce/woocommerce/issues/45475
- [ ] https://github.com/woocommerce/woocommerce/issues/45476
- [ ] https://github.com/woocommerce/woocommerce/issues/45486
- [ ] https://github.com/woocommerce/woocommerce/issues/45539
- [ ] https://github.com/woocommerce/woocommerce/issues/45542
- [ ] https://github.com/woocommerce/woocommerce/issues/45593
- [ ] https://github.com/woocommerce/woocommerce/issues/45784
- [ ] https://github.com/woocommerce/woocommerce/issues/46193
- [ ] https://github.com/woocommerce/woocommerce/issues/46194
```

**Comment by nefeline** [comment]
This project has been released with WooCommerce 8.8, more details available on https://developer.woocommerce.com/2024/03/22/customize-your-store/

Closing out this epic.
