### ISSUE TITLE
Add the collapsible Schedule section

### ISSUE THREAD

**Issue by mdperez86** [woothemes/woocommerce#43706]
**Description**

Use the sidebar/modal to publish product by schedule.
Gutenberg has a similar component for this already called [`PostSchedule`](https://github.com/WordPress/gutenberg/blob/e00bcc1dd0bbb739c294413ce1b562ae3a672119/packages/edit-post/src/components/sidebar/post-schedule/index.js#L13) we should try to re-use or mimic as much of this as possible. It does use an exported component from the `wordpress/editor` package called [`PostSchedule`](https://github.com/WordPress/gutenberg/blob/41a30232f5d9ad57246e9843c40cae4ca62acda4/packages/editor/src/components/post-schedule/index.js#L20)

**Epic**

#40371

Depends on #43704

**Design (temporary link)**

[AkVNGImLgSqCObTQ3idVn7-fi-3359_344908](https://href.li/?https://www.figma.com/file/AkVNGImLgSqCObTQ3idVn7/?node-id=3359-344908)

**ACs**

```[tasklist]
### Tasks
- [x] Create the collapsible Schedule section AkVNGImLgSqCObTQ3idVn7-fi-3359_345477
- [x] The `Add: xxx` section works exactly as in the post/site editor
- [x] When expanded, the user can select the time and date
- [x] If no custom time and date is selected, the section says `Add: Immediately`. If the user adds a custom time and date, it says: `Add: [date] [time]`.
- [x] When the user selects a future time and date, the top button's label changes from `Add` to `Schedule`
```
