### ISSUE TITLE
List validation error messages in the pre-publish modal

### ISSUE THREAD

**Issue by mdperez86** [woothemes/woocommerce#43708]
**Description**

All the validation error messages are listed in the pre-publish modal preventing users from publishing the product and let them see/fix the errors.

**Epic**

#40371

Depends on #43704

**Design (temporary link)**

[AkVNGImLgSqCObTQ3idVn7-fi-3359_344908](https://href.li/?https://www.figma.com/file/AkVNGImLgSqCObTQ3idVn7/?node-id=3359-344908)

**ACs**

```[tasklist]
### Tasks
- [ ] List validation messages for all affected fields the same as they're displayed below them. AkVNGImLgSqCObTQ3idVn7-fi-3359_345808
- [ ] The section title includes the total number of identified issues. If there's just one issue, the title says: `1 issue found`. If there are more, it says: `X issues found`.
- [ ] When the pre-publish modal is open, the `Add` button is disabled until all issues are resolved.
- [ ] When an error is solved, it immediately disappears from the list.
```

**Comment by pmcpinto** [comment]
@j111q After our chat last week about error validation (all Core validation happens inline), I'm not 100% confident that we should treat this part and #43709 as must-haves for the 1st iteration of the pre-publish modal. What do you think?

**Comment by j111q** [comment]
@pmcpinto Yes, agree. Let's keep investigating this and exploring if it is necessary!

**Comment by pmcpinto** [comment]
@mdperez86 are you okay with removing this issue and #43709 from the initial iteration? Let us know if you have questions. Thanks.

**Comment by pmcpinto** [comment]
@mdperez86 @louwie17, to confirm, I'll remove this issue and #43709 from cycle 45 as we don't consider it a must-have for the initial iteration.

**Comment by jamesckemp** [comment]
This version of the product editor is now deprecated
