### ISSUE TITLE
Add `Always show pre-publish checks` checkbox

### ISSUE THREAD

**Issue by mdperez86** [woothemes/woocommerce#43707]
**Description**

The sidebar/modal can be optional when the form does not contains any validation error.

We may want to use the exact same setting that the post/site editor uses for this, see [`isPublishedSidebarEnabled`](https://github.com/WordPress/gutenberg/blob/55fbdd96aa2642dff194cb69ebe02c3669eebae0/packages/editor/src/components/post-publish-panel/index.js#L146).

**Epic**

#40371

Depends on #43704

**Design (temporary link)**

[AkVNGImLgSqCObTQ3idVn7-fi-3359_344908](https://href.li/?https://www.figma.com/file/AkVNGImLgSqCObTQ3idVn7/?node-id=3359-344908)

**ACs**

```[tasklist]
### Tasks
- [x] Add `Always show pre-publish checks` checkbox at the bottom of the sidebar/modal AkVNGImLgSqCObTQ3idVn7-fi-3359_345477
- [x] The `Always show pre-publish checks` disables the pre-publish modal and publishes the product immediately when the user clicks `Publish`
- [x] When the form is invalid if the `Always show pre-publish checks` box was unchecked before, we don't show it at the bottom of the panel (the panel is only shown because of the errors).
```

**Comment by mdperez86** [comment]
@j111q @pmcpinto 

What is the default value of the `Always show pre-publish checks` checkbox? `Checked` or `unchecked`?

**Comment by louwie17** [comment]
> @j111q @pmcpinto
> 
> What is the default value of the `Always show pre-publish checks` checkbox? `Checked` or `unchecked`?

Checked? it appears to be set to `true` by default for the post editor preferences: https://github.com/WordPress/gutenberg/blob/0c3b9ab1f52047b0984dfd5ba50b1096d1ff4cdc/packages/edit-post/src/index.js#L54

**Comment by pmcpinto** [comment]
> Checked? it appears to be set to true by default for the post editor preferences: https://github.com/WordPress/gutenberg/blob/0c3b9ab1f52047b0984dfd5ba50b1096d1ff4cdc/packages/edit-post/src/index.js#L54

Yes. Btw @j111q do you think we should have this check at the bottom of the panel or move it to the top?
