### ISSUE TITLE
Create the sidebar/modal component

### ISSUE THREAD

**Issue by mdperez86** [woothemes/woocommerce#43704]
**Description**

A new sidebar/modal will be shown in the new product editor, to let the user see/fix validation errors and other product settings.
Note a sidebar for this already exists in the post/page/site editor, so we should use a similar approach or the same components if possible.
There are two sidebars in the post/page editor, one that is used to inspect block elements and one that is only used for the pre-publish sidebar. We want the latter.
You can also see the difference yourself when going to the post editor, the block settings sidebar only extends the height of the editor, but the pre-publish sidebar extends the entire height ( try publishing a post for the first time and it will show up ).
See this [PrePublish component](https://github.com/WordPress/gutenberg/blob/62a7316473b74911670fc28fcfe3b927a7fbb808/packages/editor/src/components/post-publish-panel/prepublish.js#L25) that is used in [this `PostPublishPanel` ](https://github.com/WordPress/gutenberg/blob/55fbdd96aa2642dff194cb69ebe02c3669eebae0/packages/editor/src/components/post-publish-panel/index.js#L26)
Which in turn gets used by the `InterfaceSkeleton` which we already are using for the editor.

**Epic**

#40371

Depends on #43703

**Design (temporary link)**

[AkVNGImLgSqCObTQ3idVn7-fi-3359_344908](https://href.li/?https://www.figma.com/file/AkVNGImLgSqCObTQ3idVn7/?node-id=3359-344908)

**ACs**

```[tasklist]
### Tasks
- [x] Create the sidebar/modal and add it to the right side of the product editor AkVNGImLgSqCObTQ3idVn7-fi-3359_345477
- [x] When the user clicks Publish in the top right corner, a panel slides out from the right edge of the screen. It looks and works exactly like the pre-publish modal in the post/site editor.
- [x] Add the `Publish` button to the sidebar to persist the unsaved changes AkVNGImLgSqCObTQ3idVn7-fi-3359_345477
- [x] Add the `Cancel` button to the sidebar to hide/close it AkVNGImLgSqCObTQ3idVn7-fi-3359_345477
- [x] Add the title section of the sidebar AkVNGImLgSqCObTQ3idVn7-fi-3359_345477
```
