### ISSUE TITLE
Add navigation to the validation error message list

### ISSUE THREAD

**Issue by mdperez86** [woothemes/woocommerce#43709]
**Description**

All the validation error messages are listed in the pre-publish modal preventing users from publishing the product and let them see/fix the errors.

**Epic**

#40371

Depends on #43708

**Design (temporary link)**

[AkVNGImLgSqCObTQ3idVn7-fi-3359_344908](https://href.li/?https://www.figma.com/file/AkVNGImLgSqCObTQ3idVn7/?node-id=3359-344908)

**ACs**

```[tasklist]
### Tasks
- [ ] Add arrows at the right of the errors section title AkVNGImLgSqCObTQ3idVn7-fi-3359_345808
- [ ] If there are no more next or previous errors, the arrow button is disabled and changes color to Gutenberg-400.
- [ ] User can click on each message to go between affected fields and solve them one by one.
- [ ] User can use the arrows in the corner to go between affected fields and solve them one by one.
```

**Comment by jamesckemp** [comment]
This version of the product editor is now deprecated
