### ISSUE TITLE
Unskip checkout-related e2e tests

### ISSUE THREAD

**Issue by nielslange** [woothemes/woocommerce#43741]
### Describe the solution you'd like

Currently, we still have the following skipped checkout-related e2e tests:

```[tasklist]
### Tasks
- [x] `/tests/cart/cart-checkout-block-translations.shopper.block_theme.side_effects.spec.ts`
- [x] `/tests/checkout/checkout-block.shopper.block_theme.side_effects.spec.ts`
- [x] `/tests/checkout/order-confirmation.block_theme.side_effects.spec.ts`
- [x] `/tests/templates/cart-template.block_theme.spec.ts`
- [x] `/tests/templates/checkout-template.block_theme.spec.ts`
```

https://github.com/woocommerce/woocommerce/blob/824dc6be5107d7a68d6300bd903cefbf52b88b5a/plugins/woocommerce-blocks/tests/e2e/tests/cart/cart-checkout-block-translations.shopper.block_theme.side_effects.spec.ts#L24

https://github.com/woocommerce/woocommerce/blob/824dc6be5107d7a68d6300bd903cefbf52b88b5a/plugins/woocommerce-blocks/tests/e2e/tests/checkout/checkout-block.shopper.block_theme.side_effects.spec.ts#L177

https://github.com/woocommerce/woocommerce/blob/824dc6be5107d7a68d6300bd903cefbf52b88b5a/plugins/woocommerce-blocks/tests/e2e/tests/checkout/order-confirmation.block_theme.side_effects.spec.ts#L132

https://github.com/woocommerce/woocommerce/blob/824dc6be5107d7a68d6300bd903cefbf52b88b5a/plugins/woocommerce-blocks/tests/e2e/tests/templates/cart-template.block_theme.spec.ts#L32

https://github.com/woocommerce/woocommerce/blob/824dc6be5107d7a68d6300bd903cefbf52b88b5a/plugins/woocommerce-blocks/tests/e2e/tests/templates/checkout-template.block_theme.spec.ts#L32

Due to recent changes, we should be able to unskip these tests. See also p1705419535522349/1705415731.324509-slack-C8X6Q7XQU.

### Describe alternatives you've considered

n/a

### Additional context

n/a
