### ISSUE TITLE
Refinement on Variations tab

### ISSUE THREAD

**Issue by j111q** [woothemes/woocommerce#43808]
**Design**
AkVNGImLgSqCObTQ3idVn7-fi-3301%3A321179

**P2 post**
peCask-Dc-p2

**Acceptance criteria**

```[tasklist]
### Tasks
- [x] Variations tab should be moved to the second tab, after `General`
- [x] When the user has not added any Variations, they will see an empty state with an illustration and three buttons: (Primary) `Add options`,  (Secondary) `Add sizes`, (Secondary) `Add colors`
- [x] When a user clicks on the secondary buttons of Add sizes or Add colors, then those attributes will be automatically populated into the input field.
- [x] If the attribute (Size / Color) has already been added to the store, then it should appear in the dropdown menu below.
- [x] Add an empty state to the variations table when there are no options added yet.
```
