### ISSUE TITLE
[Product Block Editor]: track Linked Products feature events

### ISSUE THREAD

**Issue by retrofox** [woothemes/woocommerce#43801]
**Description**

Collect and implement events to track in the Linked Products feature

**ACs**

```[tasklist]
### Tasks
- [x] Upon click of dropdown: `product_template_selector_open` (props: `supported_templates` ids, `unsupported_templates` ids)
- [x] Upon click of template: `product_template_selector_selected` ( props: `selected_template` ( template id ), `unsupported_template` : ( if unsupported or not ) )
- [x] Track for notice of product changed: `product_template_changed` ( props: `template` ( template id ) )
- [x] `linked_products_choose_related_click` ( props: `field`: `cross-sells` | `up-sells`, same as product value )
- [x] `linked_products_placeholder_dismiss` ( props: `field`: `cross-sells` | `up-sells`, same as product value )
- [x] `linked_products_product_select` ( props: `field`: `cross-sells` | `up-sells`, same as product value )
- [x] `linked_products_product_remove` ( props: `field`: `cross-sells` | `up-sells`, same as product value )
- [x] `linked_products_product_preview_click` ( props: `field`: `cross-sells` | `up-sells`, same as product value )
- [x] `linked_products_product_add` ( props: `field`: `cross-sells` | `up-sells`, same as product value )
```
