### ISSUE TITLE
Review npm dependency versions

### ISSUE THREAD

**Issue by rrennick** [woothemes/woocommerce#44015]
**Issue Description:**

This is an epic to review npm dependency versions after the merge of the blocks repo. Issues were created for each npm dependency that has multiple versions in the monorepo.

In the course of syncing a dependency, it should be updated in Syncpack.
```[tasklist]
### Tasks
- [ ] https://github.com/woocommerce/woocommerce/issues/43980
- [ ] https://github.com/woocommerce/woocommerce/issues/43979
- [ ] https://github.com/woocommerce/woocommerce/issues/43978
- [ ] https://github.com/woocommerce/woocommerce/issues/43977
- [ ] https://github.com/woocommerce/woocommerce/issues/43976
- [ ] https://github.com/woocommerce/woocommerce/issues/43975
- [ ] https://github.com/woocommerce/woocommerce/issues/43974
- [ ] https://github.com/woocommerce/woocommerce/issues/43973
- [ ] https://github.com/woocommerce/woocommerce/issues/43972
- [ ] https://github.com/woocommerce/woocommerce/issues/43971
- [ ] https://github.com/woocommerce/woocommerce/issues/43970
- [ ] https://github.com/woocommerce/woocommerce/issues/43969
- [ ] https://github.com/woocommerce/woocommerce/issues/43968
- [ ] https://github.com/woocommerce/woocommerce/issues/43967
- [ ] https://github.com/woocommerce/woocommerce/issues/43966
- [ ] https://github.com/woocommerce/woocommerce/issues/43965
- [ ] https://github.com/woocommerce/woocommerce/issues/43964
- [ ] https://github.com/woocommerce/woocommerce/issues/43963
- [ ] https://github.com/woocommerce/woocommerce/issues/43962
- [ ] https://github.com/woocommerce/woocommerce/issues/43961
- [ ] https://github.com/woocommerce/woocommerce/issues/43960
- [ ] https://github.com/woocommerce/woocommerce/issues/43959
- [ ] https://github.com/woocommerce/woocommerce/issues/43958
- [ ] https://github.com/woocommerce/woocommerce/issues/43957
- [ ] https://github.com/woocommerce/woocommerce/issues/43956
- [ ] https://github.com/woocommerce/woocommerce/issues/43955
- [ ] https://github.com/woocommerce/woocommerce/issues/43954
- [ ] https://github.com/woocommerce/woocommerce/issues/43953
- [ ] https://github.com/woocommerce/woocommerce/issues/43952
- [ ] https://github.com/woocommerce/woocommerce/issues/43951
- [ ] https://github.com/woocommerce/woocommerce/issues/43950
- [ ] https://github.com/woocommerce/woocommerce/issues/43949
- [ ] https://github.com/woocommerce/woocommerce/issues/43948
- [ ] https://github.com/woocommerce/woocommerce/issues/43947
- [ ] https://github.com/woocommerce/woocommerce/issues/43946
- [ ] https://github.com/woocommerce/woocommerce/issues/43945
- [ ] https://github.com/woocommerce/woocommerce/issues/43944
- [ ] https://github.com/woocommerce/woocommerce/issues/43943
- [ ] https://github.com/woocommerce/woocommerce/issues/43942
- [ ] https://github.com/woocommerce/woocommerce/issues/43941
- [ ] https://github.com/woocommerce/woocommerce/issues/43940
- [ ] https://github.com/woocommerce/woocommerce/issues/43939
- [ ] https://github.com/woocommerce/woocommerce/issues/43938
- [ ] https://github.com/woocommerce/woocommerce/issues/43937
- [ ] https://github.com/woocommerce/woocommerce/issues/43936
- [ ] https://github.com/woocommerce/woocommerce/issues/43935
- [ ] https://github.com/woocommerce/woocommerce/issues/43934
- [ ] https://github.com/woocommerce/woocommerce/issues/43933
- [ ] https://github.com/woocommerce/woocommerce/issues/43932
- [ ] https://github.com/woocommerce/woocommerce/issues/43931
- [ ] https://github.com/woocommerce/woocommerce/issues/43930
- [ ] https://github.com/woocommerce/woocommerce/issues/43929
- [ ] https://github.com/woocommerce/woocommerce/issues/43928
- [ ] https://github.com/woocommerce/woocommerce/issues/43927
- [ ] https://github.com/woocommerce/woocommerce/issues/43926
- [ ] https://github.com/woocommerce/woocommerce/issues/43925
- [ ] https://github.com/woocommerce/woocommerce/issues/43924
- [ ] https://github.com/woocommerce/woocommerce/issues/43923
- [ ] https://github.com/woocommerce/woocommerce/issues/43922
- [ ] https://github.com/woocommerce/woocommerce/issues/43921
- [ ] https://github.com/woocommerce/woocommerce/issues/43920
- [ ] https://github.com/woocommerce/woocommerce/issues/43919
- [ ] https://github.com/woocommerce/woocommerce/issues/43918
- [ ] https://github.com/woocommerce/woocommerce/issues/43917
- [ ] https://github.com/woocommerce/woocommerce/issues/43916
- [ ] https://github.com/woocommerce/woocommerce/issues/43915
- [ ] https://github.com/woocommerce/woocommerce/issues/43914
- [ ] https://github.com/woocommerce/woocommerce/issues/43913
- [ ] https://github.com/woocommerce/woocommerce/issues/43912
- [ ] https://github.com/woocommerce/woocommerce/issues/43911
- [ ] https://github.com/woocommerce/woocommerce/issues/43910
- [ ] https://github.com/woocommerce/woocommerce/issues/43909
- [ ] https://github.com/woocommerce/woocommerce/issues/43908
- [ ] https://github.com/woocommerce/woocommerce/issues/43907
- [ ] https://github.com/woocommerce/woocommerce/issues/43906
- [ ] https://github.com/woocommerce/woocommerce/issues/43905
- [ ] https://github.com/woocommerce/woocommerce/issues/43904
- [ ] https://github.com/woocommerce/woocommerce/issues/43903
- [ ] https://github.com/woocommerce/woocommerce/issues/43902
- [ ] https://github.com/woocommerce/woocommerce/issues/43901
- [ ] https://github.com/woocommerce/woocommerce/issues/43900
- [ ] https://github.com/woocommerce/woocommerce/issues/43899
- [ ] https://github.com/woocommerce/woocommerce/issues/43898
- [ ] https://github.com/woocommerce/woocommerce/issues/43897
- [ ] https://github.com/woocommerce/woocommerce/issues/43896
- [ ] https://github.com/woocommerce/woocommerce/issues/43895
- [ ] https://github.com/woocommerce/woocommerce/issues/43894
- [ ] https://github.com/woocommerce/woocommerce/issues/43893
- [ ] https://github.com/woocommerce/woocommerce/issues/43892
- [ ] https://github.com/woocommerce/woocommerce/issues/43891
- [ ] https://github.com/woocommerce/woocommerce/issues/43890
- [ ] https://github.com/woocommerce/woocommerce/issues/43889
- [ ] https://github.com/woocommerce/woocommerce/issues/43888
- [ ] https://github.com/woocommerce/woocommerce/issues/43887
- [ ] https://github.com/woocommerce/woocommerce/issues/43886
- [ ] https://github.com/woocommerce/woocommerce/issues/43885
- [ ] https://github.com/woocommerce/woocommerce/issues/43884
- [ ] https://github.com/woocommerce/woocommerce/issues/43883
- [ ] https://github.com/woocommerce/woocommerce/issues/43882
- [ ] https://github.com/woocommerce/woocommerce/issues/43881
- [ ] https://github.com/woocommerce/woocommerce/issues/43880
```
