### ISSUE TITLE
Product data is empty not able to edit anything

### ISSUE THREAD

**Issue by sayan-dot** [woothemes/woocommerce#44500]
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Hyy guys today is my first day of working with woo commerce and Wordpress .

I'm trying to add a new product but after filling the product description the product data section is completely empty and allowing me to edit anything in there 
<img width="717" alt="Screenshot 2024-02-09 164742" src="https://github.com/woocommerce/woocommerce/assets/74709250/ece666e5-cebd-459b-9094-87c74e3502c9">

my product data is looking like this I don't know how to fix it I tried deleting all the plugins and changing themes but I'm still facing this issue

### Expected behavior

i want it to let me customize the product type and all the actual behaviour

### Actual behavior

it shows a completely white screen not allowing me to edit anything

### Steps to reproduce

1. host your domain on miles
2. download wordpress and select a theme 
3. go to the wordpress admin panel and install the woocommerce 
4. products 
5. add new products and scroll down to product data 

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): http://nvnverse.com/wp58
Site address (URL): http://nvnverse.com/wp58
WC Version: 8.5.2
REST API Version: ✔ 8.5.2
WC Blocks Version: ✔ 11.8.0-dev
Action Scheduler Version: ✔ 3.7.1
Log Directory Writable: ✔
WP Version: ❌ 6.3.3 - There is a newer version of WordPress available (6.4.3)
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: LiteSpeed
PHP Version: 8.1.24
PHP Post Max Size: 64 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.61.1
OpenSSL/1.1.1k

SUHOSIN Installed: –
MySQL Version: 10.6.15-MariaDB
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.5.2
WC Database Prefix: wppf_
Total Database Size: 9.57MB
Database Data Size: 6.31MB
Database Index Size: 3.26MB
wppf_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wppf_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wppf_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wppf_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wppf_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wppf_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wppf_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wppf_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wppf_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wppf_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wppf_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wppf_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wppf_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wppf_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wppf_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wppf_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wppf_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wppf_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wppf_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wppf_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wppf_gla_attribute_mapping_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wppf_gla_budget_recommendations: Data: 0.19MB + Index: 0.14MB + Engine InnoDB
wppf_gla_merchant_issues: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wppf_gla_shipping_rates: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wppf_gla_shipping_times: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wppf_jetpack_sync_queue: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wppf_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wppf_mailpoet_automations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wppf_mailpoet_automation_runs: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wppf_mailpoet_automation_run_logs: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wppf_mailpoet_automation_run_subjects: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wppf_mailpoet_automation_triggers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wppf_mailpoet_automation_versions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wppf_mailpoet_custom_fields: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wppf_mailpoet_dynamic_segment_filters: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wppf_mailpoet_feature_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wppf_mailpoet_forms: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wppf_mailpoet_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wppf_mailpoet_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wppf_mailpoet_newsletters: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wppf_mailpoet_newsletter_links: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wppf_mailpoet_newsletter_option: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wppf_mailpoet_newsletter_option_fields: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wppf_mailpoet_newsletter_posts: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wppf_mailpoet_newsletter_segment: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wppf_mailpoet_newsletter_templates: Data: 2.52MB + Index: 0.00MB + Engine InnoDB
wppf_mailpoet_scheduled_tasks: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wppf_mailpoet_scheduled_task_subscribers: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wppf_mailpoet_segments: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wppf_mailpoet_sending_queues: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wppf_mailpoet_settings: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wppf_mailpoet_statistics_bounces: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wppf_mailpoet_statistics_clicks: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wppf_mailpoet_statistics_forms: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wppf_mailpoet_statistics_newsletters: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wppf_mailpoet_statistics_opens: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wppf_mailpoet_statistics_unsubscribes: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wppf_mailpoet_statistics_woocommerce_purchases: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wppf_mailpoet_stats_notifications: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wppf_mailpoet_subscribers: Data: 0.02MB + Index: 0.23MB + Engine InnoDB
wppf_mailpoet_subscriber_custom_field: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wppf_mailpoet_subscriber_ips: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wppf_mailpoet_subscriber_segment: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wppf_mailpoet_subscriber_tag: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wppf_mailpoet_tags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wppf_mailpoet_user_agents: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wppf_mailpoet_user_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wppf_options: Data: 1.44MB + Index: 0.06MB + Engine InnoDB
wppf_postmeta: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wppf_posts: Data: 0.22MB + Index: 0.06MB + Engine InnoDB
wppf_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wppf_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wppf_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wppf_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wppf_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wppf_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wppf_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wppf_wc_admin_note_actions: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wppf_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wppf_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wppf_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wppf_wc_orders: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wppf_wc_orders_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wppf_wc_order_addresses: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wppf_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wppf_wc_order_operational_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wppf_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wppf_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wppf_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wppf_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wppf_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wppf_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wppf_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wppf_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wppf_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wppf_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 7
mailpoet_page: 1
nav_menu_item: 9
page: 12
pagelayer-template: 6
post: 6
product: 4

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (7) ###

Google Listings and Ads: by WooCommerce – 2.5.17
Jetpack: by Automattic – 13.1.1
MailPoet: by MailPoet – 4.43.0
PageLayer: by Pagelayer Team – 1.8.2
Pinterest for WooCommerce: by WooCommerce – 1.3.20
PopularFX Website Templates: by Pagelayer Team – 1.2.4
WooCommerce: by Automattic – 8.5.2

### Inactive Plugins (2) ###

Akismet Anti-spam: Spam Protection: by Automattic - Anti-spam Team – 5.3.1
Hello Dolly: by Matt Mullenweg – 1.7.2

### Settings ###

API Enabled: –
Force SSL: –
Currency: INR (₹)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to Woo.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature screen enabled: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: –

### WC Pages ###

Shop base: #32 - /shop/
Cart: #34 - /cart/
Checkout: #36 - /checkout/
My account: #38 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: PopularFX
Version: 1.2.5
Author URL: https://pagelayer.com
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-variation-management
product-virtual-downloadable
product-external-affiliate
product-grouped
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: customize-store
minified-js
new-product-management-experience
product-linked
settings
async-product-editor-category-field

Daily Cron: ❌ Not scheduled
Options: ✔
Notes: 65
Onboarding: completed

### MailPoet ###

Sending Method: PHPMail
Send all site's emails with: Default WordPress sending method
Task Scheduler method: Action Scheduler
Cron ping URL: http://nvnverse.com/wp58?mailpoet_router&endpoint=cron_daemon&action=ping

### Action Scheduler ###

Pending: 9
Oldest: 2024-02-09 13:13:58 +0000
Newest: 2024-02-09 13:16:02 +0000

### Status report information ###

Generated at: 2024-02-09 13:17:37 +00:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.
```[tasklist]
### Tasks
```
