### ISSUE TITLE
Product Collection M1: New UX - Contextual Collections

### ISSUE THREAD

**Issue by kmanijak** [woothemes/woocommerce#45317]
**Background:**

In https://github.com/woocommerce/woocommerce/issues/43037 we delivered the contextual awareness for collections and filters. We have access to the location in Editor and frontend, and pass the necessary data to the query.

Now, the missing part is to consume that data and provide the UX that allows collections to be contextual. That includes:
- Extending Collections definition to specify the required context
- Handling the states of Collection in Editor depends on:
  - if the required context is provided (error or prompt to choose context)
  - if the context allows to display of final results or a preview
- Describing and POCing the problems related to template parts and patterns (synced)

```[tasklist]
### Tasks
- [ ] https://github.com/woocommerce/woocommerce/issues/44874
- [ ] https://github.com/woocommerce/woocommerce/issues/44877
- [ ] https://github.com/woocommerce/woocommerce/issues/44878
- [ ] https://github.com/woocommerce/woocommerce/issues/44879
- [x] Describing the problems related to template parts and synced patterns
- [ ] POC to solve the above
- [ ] https://github.com/woocommerce/woocommerce/issues/50916
```

**Comment by kmanijak** [comment]
Closing as done
