### ISSUE TITLE
Some summaries & sentiment missing from FSOR

### ISSUE THREAD

**Issue by peterfabian** [woothemes/woocommerce#45340]
Some records in FSOR are missing summaries and sentiment. E.g. record `recIeI2sFKfS10ckD` on view `viwGWBNh7dxa43M4J`. In the view `viwGWBNh7dxa43M4J`, I can see 103 records missing the information out of a total of 435 records added in 2024.

```[tasklist]
### Tasks
- [x] Investigate why some records are missing summaries and sentiment
- [x] Add missing summaries and sentiment to records in FSOR
- [ ] Add notification to catch missing summaries and sentiment in the future
```

**Comment by nima-karimi** [comment]
I've created a PR to fix the error handling and job retry mechanism that was failing us here. Because of poor error handling, the job was not being retried, and any API failure would mean those errors were never updated. PR ready for review here: D142178

The other parts of this issue are still pending.

**Comment by nima-karimi** [comment]
The error handling diff (D142178) is now merged and deployed. This should also allow us to catch any instances where summaries are not generated unless we want to add a specific check (periodically or when generating reports) to verify that summary columns are not empty. 

@peterfabian, could you please comment on the other two remaining tasks in this issue? I believe you were working on adding the missing values before your AFK. Do we still have more items to backfill?

**Comment by nima-karimi** [comment]
This is done. We've backfilled the records with missing values up to Oct. 2023 and added proper error handling to catch future instances of this issue (if they happen again).
