### ISSUE TITLE
Integrate Product Editor with Block Binding API

### ISSUE THREAD

**Issue by retrofox** [woothemes/woocommerce#45416]
Integrate the new Block Binding API functionally with the Product Editor in favor of improving the application's extensibility. Since the API is in the middle of a dev-process, we would like to split the epic in two main sections: Core and Product Editor.

# Core

```[tasklist]
- [ ] https://github.com/WordPress/gutenberg/pull/60276
- [ ] https://github.com/WordPress/gutenberg/pull/60296
- [ ] https://github.com/WordPress/gutenberg/pull/60335
- [ ] Block Binding API: expose action to register an external source
```

# Product Editor

```[tasklist]
### First iteration
- [ ] #45421
- [ ] https://github.com/woocommerce/woocommerce/issues/45656
- [ ] https://github.com/woocommerce/woocommerce/issues/45422
- [ ] https://github.com/woocommerce/woocommerce/issues/45622
- [ ] https://github.com/woocommerce/woocommerce/issues/45424
- [ ] https://github.com/woocommerce/woocommerce/issues/45437
- [ ] https://github.com/woocommerce/woocommerce/issues/45431
- [ ] https://github.com/woocommerce/woocommerce/issues/45429
- [ ] https://github.com/woocommerce/woocommerce/issues/45423
```

```[tasklist]
### Follow-up tasks
- [ ] https://github.com/woocommerce/woocommerce/issues/45425
- [ ] https://github.com/woocommerce/woocommerce/issues/45426
- [ ] https://github.com/woocommerce/woocommerce/issues/45427
- [ ] https://github.com/woocommerce/woocommerce/issues/45428
- [ ] https://github.com/woocommerce/woocommerce/issues/45430
- [ ] https://github.com/woocommerce/woocommerce/issues/45432
- [ ] https://github.com/woocommerce/woocommerce/issues/45433
- [ ] [Product Block Editor]: integrate `woocommerce/product-description-field` block
- [ ] https://github.com/woocommerce/woocommerce/issues/45510
```

### Links

* https://github.com/WordPress/gutenberg/issues/53300

**Comment by gigitux** [comment]
Could we close this issue?

**Comment by retrofox** [comment]
yes, closing for now.
