### ISSUE TITLE
Add LLM Labels to FSOR reports

### ISSUE THREAD

**Issue by peterfabian** [woothemes/woocommerce#45572]
Based on the research spike done for https://github.com/woocommerce/woocommerce/issues/44900, it seems that it's easier to cluster based on labels than on summaries. Let's add labels to FSOR records so that we can use them for clustering.

For the tasks below, one can first try this the experimental copy of FSOR, then go to live version.

```[tasklist]
### Tasks
- [x] Add LLM Labels column to FSOR
- [x] Find a good prompt to produce labels. The one I used in testing is below.
- [x] Decide whether the labeling should be done based on the LLM Summary or the original user message.
- [ ] Add LLM Labels to fields filled in via webhook
- [x] Fill in the labels using GPT4
- [ ] When automated labeling (triggered by Airtable webhook) fails, send a message to our Slack channel so that we can fix it (or fill in missing items before running a report?)
```

Prompt for labeling:
```
messages = [
        {
            "role": "system", 
            "content": "You are an expert product manager reviewing user feedback on WooCommerce platform and related extensions."
        },
        {
            "role": "user", 
            "content": f"Tag the feedback to route it to the appropriate teams. Use JSON format and a simple 'tags' array to return a flat list of tags at different levels of abstraction from general to specific. E.g. If a user reports a problem with the Stripe payment gateway, include 'Payment Gateway' and also 'Stripe'. You can also add multiple tags for a single piece of feedback if it covers multiple areas, like 'Performance' and 'Shipping'.\n\n This is the user feedback: '{feedback_item}'"
        },
    ]
```

**Comment by peterfabian** [comment]
Diff ready for review in Phabricator as D142378.

**Comment by nima-karimi** [comment]
D142378 is merged, closing this and marking it as done.
