### ISSUE TITLE
[Epic] Remove `@wordpress/components` from Frontend Use

### ISSUE THREAD

**Issue by samueljseay** [woothemes/woocommerce#45571]
This epic tracks the work needed to remove the outdated `@wordpress/components` package from the cart and checkout pages of the front-end shopper experience.

Tasks TBD.
```[tasklist]
### Tasks
- [ ] https://github.com/woocommerce/woocommerce/issues/45573
- [ ] https://github.com/woocommerce/woocommerce/issues/45574
- [ ] https://github.com/woocommerce/woocommerce/issues/45680
- [ ] https://github.com/woocommerce/woocommerce/pull/45974/
- [ ] https://github.com/woocommerce/woocommerce/issues/46061
- [ ] https://github.com/woocommerce/woocommerce/issues/46062
- [ ] https://github.com/woocommerce/woocommerce/issues/46208
- [ ] https://github.com/woocommerce/woocommerce/issues/44503
- [ ] https://github.com/woocommerce/woocommerce/pull/46219
- [ ] https://github.com/woocommerce/woocommerce/issues/46357
- [ ] https://github.com/woocommerce/woocommerce/issues/47106
```

```[tasklist]
### Post-work tasks (after components are migrated)
- [ ] https://github.com/woocommerce/woocommerce/issues/44653
- [ ] https://github.com/woocommerce/woocommerce/issues/47210
```

**Comment by opr** [comment]
@samueljseay I have added https://github.com/woocommerce/woocommerce/issues/44653 to the task list - I suggest we review this after the work has been done to check if the issue is still valid.

**Comment by opr** [comment]
Since the project is complete, I will close this epic, however the remaining, and follow-up issues are still open:

- https://github.com/woocommerce/woocommerce/issues/44653
- https://github.com/woocommerce/woocommerce/issues/47210
- https://github.com/woocommerce/woocommerce/issues/46357
- https://github.com/woocommerce/woocommerce/issues/47757
