### ISSUE TITLE
[EPIC] Product Editor: Description editing improvements

### ISSUE THREAD

**Issue by mattsherman** [woothemes/woocommerce#45676]
```[tasklist]
### Tasks
- [ ] https://github.com/woocommerce/woocommerce/issues/45660
- [ ] https://github.com/woocommerce/woocommerce/issues/45662
- [ ] https://github.com/woocommerce/woocommerce/issues/45663
- [ ] https://github.com/woocommerce/woocommerce/issues/45664
- [ ] https://github.com/woocommerce/woocommerce/issues/45740
- [ ] https://github.com/woocommerce/woocommerce/issues/45741
- [ ] https://github.com/woocommerce/woocommerce/issues/47123
- [ ] https://github.com/woocommerce/woocommerce/issues/47188
- [ ] https://github.com/woocommerce/woocommerce/issues/47508
```
