### ISSUE TITLE
[Epic] Optimize the shopper experience 

### ISSUE THREAD

**Issue by ralucaStan** [woothemes/woocommerce#45708]
Optimize the shopper experience 
```[tasklist]
### Quick wins
- [ ] https://github.com/woocommerce/woocommerce/issues/44835
- [ ] https://github.com/woocommerce/woocommerce/issues/44837
- [ ] https://github.com/woocommerce/woocommerce/issues/44839
- [ ] https://github.com/woocommerce/woocommerce/issues/47509
- [ ] https://github.com/woocommerce/woocommerce/issues/48433
```
