### ISSUE TITLE
[EPIC] Migrating WooCommerce Patterns to the PTK and updating the Intro page

### ISSUE THREAD

**Issue by nefeline** [woothemes/woocommerce#45834]
## Migrating WooCommerce Patterns to the PTK

The primary goal of this project is to migrate all WooCommerce patterns to a shared library, the Patterns Toolkit, and abstract the AI feature, ensuring it is decoupled from the core of WooCommerce. With this migration, we can rely on the dedicated API to fetch WooCommerce patterns and other curated patterns for usage within our plugin. An additional positive outcome of this project is that the size of the WooCommerce plugin will be significantly reduced, considering all images required for patterns will be migrated to this dedicated API.

## Updated Intro Page

This iteration aims to tailor the CYS experience for existing WooCommerce users or new WooCommerce users who already have a site or have already chosen/imported a theme.

```[tasklist]
### Tasks
- [ ] https://github.com/woocommerce/woocommerce/issues/45835
- [ ] https://github.com/woocommerce/woocommerce/issues/47396
- [ ] https://github.com/woocommerce/woocommerce/issues/47403
- [ ] https://github.com/woocommerce/woocommerce/issues/47395
- [ ] https://github.com/woocommerce/woocommerce/issues/47401
- [ ] https://github.com/woocommerce/woocommerce/issues/47399
- [ ] https://github.com/woocommerce/woocommerce/issues/47402
- [ ] https://github.com/woocommerce/woocommerce/issues/47408
- [ ] https://github.com/woocommerce/woocommerce/issues/47409
- [ ] https://github.com/woocommerce/woocommerce/issues/46837
- [ ] https://github.com/woocommerce/woocommerce/issues/46865
- [ ] https://github.com/woocommerce/woocommerce/issues/47014
- [ ] https://github.com/woocommerce/woocommerce/issues/47012
- [ ] https://github.com/woocommerce/woocommerce/pull/47392
- [ ] https://github.com/woocommerce/woocommerce/issues/48179
- [ ] https://github.com/woocommerce/woocommerce/issues/48181
- [ ] https://github.com/woocommerce/woocommerce/issues/48521
- [ ] https://github.com/woocommerce/woocommerce/issues/48601
- [ ] https://github.com/woocommerce/woocommerce/issues/48603
- [ ] https://github.com/woocommerce/woocommerce/issues/48605
- [ ] https://github.com/woocommerce/woocommerce/issues/48947
- [ ] https://github.com/woocommerce/woocommerce/issues/48793
- [ ] https://github.com/woocommerce/woocommerce/issues/49110
```

**Comment by gigitux** [comment]
This project will be shipped with WooCommerce 9.2! Thanks for your effort, folks! 🚀
