### ISSUE TITLE
Spike: What ways can we increase the product editor performance

### ISSUE THREAD

**Issue by louwie17** [woothemes/woocommerce#46015]
**Prerequisites (mark completed items with an [x]):**
- [x] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [x] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

**Issue Description:**

This issue is a spike to research and come up with a list of changes we can make to increase the product editor performance.
Performance has been one of the main concerns recently with the new product editor.

This spike should be limited to three days and come up with a list of problems and potential solutions.

Some areas to consider:
- First contentful paint
- First to interaction
- Total blocking time
- Number of scripts and requests going out, do all of them need to get loaded or run? Could blocks be combined into a single enqueue?
- React profiler ( check interactions across the form or during tab switching, or on save )

**Acceptance criteria**

- [ ] Create follow up issues for the performance issues found

```[tasklist]
### Tasks
- [ ] https://github.com/woocommerce/woocommerce/issues/46442
- [ ] https://github.com/woocommerce/woocommerce/issues/46443
- [ ] https://github.com/woocommerce/woocommerce/issues/46444
- [ ] https://github.com/woocommerce/woocommerce/issues/46445
- [ ] https://github.com/woocommerce/woocommerce/issues/46446
- [ ] https://github.com/woocommerce/woocommerce/issues/47291
```
