### ISSUE TITLE
[EPIC] Product Editor: Description editor extensibility

### ISSUE THREAD

**Issue by mattsherman** [woothemes/woocommerce#46025]
## Description

Extensibility points will be added to the description editor in the new product editor.

```[tasklist]
### Tasks
- [x] Refactor description editor modal to use interface skeleton, so that block editor interface elements such the `PluginSidebar` can be used
- [x] Introduce a new `PluginArea` scope for the description editor modal to allow extensions to load code in its context
- [ ] https://github.com/woocommerce/woocommerce/issues/42878
- [ ] https://github.com/woocommerce/woocommerce/issues/42880
- [ ] Support persistent annotations (see discussion: https://github.com/woocommerce/woocommerce/discussions/42761)
- [ ] https://github.com/woocommerce/woocommerce/issues/47197
- [ ] https://github.com/woocommerce/woocommerce/issues/47200
- [ ] https://github.com/woocommerce/woocommerce/issues/47198
- [ ] https://github.com/woocommerce/woocommerce/issues/47152
- [ ] Product Editor: Modal block editor sidebar header button visual differences
```

**Comment by mattsherman** [comment]
Current WIP PR exploring use of `ComplementaryArea`...

https://github.com/woocommerce/woocommerce/pull/46597
