### ISSUE TITLE
[Epic] Product editor performance fixes and general enhancements - Cycle 46

### ISSUE THREAD

**Issue by louwie17** [woothemes/woocommerce#46032]
This issue encapsulates the product editor performance fixes and general enhancements for Cycle 46.
Some issues may get added to this depending on the outcome of #46015
Ordered by priority.

```[tasklist]
### Tasks
- [ ] https://github.com/woocommerce/woocommerce/issues/46015
- [ ] https://github.com/woocommerce/woocommerce/issues/45294
- [ ] https://github.com/woocommerce/woocommerce/issues/45295 
- [ ] https://github.com/woocommerce/woocommerce/issues/43282
- [ ] https://github.com/woocommerce/woocommerce/issues/43062
- [ ] https://github.com/woocommerce/woocommerce/issues/41816
```

**Note:**
Issue #45294 and #45295 were created in replacement of #35851, #38231, #38229, as these issues should be fixed when making use of the GB components.
