### ISSUE TITLE
Order Attribution in Analytics Epic.

### ISSUE THREAD

**Issue by budzanowski** [woothemes/woocommerce#46054]
Epic issue for Order Attribution in Analytics.

The following are the work to be done for Orders Analytics and should be shipped out incrementally. Integration branch for API and UI can be created when it makes sense to do so. 

```[tasklist]
### Orders
- [ ] https://github.com/woocommerce/woocommerce/issues/46379
- [ ] https://github.com/woocommerce/woocommerce/issues/46383
- [ ] https://github.com/woocommerce/woocommerce/issues/46415
- [ ] https://github.com/woocommerce/woocommerce/issues/46390
```

The following Revenue Analytics would use the work done above.

```[tasklist]
### Revenue
- [ ] https://github.com/woocommerce/woocommerce/issues/46392
```

Co-DRI: @ibndawood and @ecgan

**Comment by ecgan** [comment]
I have edited the issue description with a list of tasks for Orders Analytics and Revenue Analytics.

**Comment by ecgan** [comment]
I have added `status: on hold` label to this epic issue.
