### ISSUE TITLE
Epic: Consolidate testing workflows

### ISSUE THREAD

**Issue by adimoldovan** [woothemes/woocommerce#46108]
This is an epic tracking the work on consolidating the testing workflows in CI.

```[tasklist]
### Tasks
- [ ] https://github.com/woocommerce/woocommerce/issues/41489
- [ ] https://github.com/woocommerce/woocommerce/issues/45097
- [ ] https://github.com/woocommerce/woocommerce/issues/44773
- [ ] https://github.com/woocommerce/woocommerce/issues/46180
- [ ] https://github.com/woocommerce/woocommerce/issues/46181
- [ ] https://github.com/woocommerce/woocommerce/issues/46924
- [ ] https://github.com/woocommerce/woocommerce/issues/46925
- [ ] https://github.com/woocommerce/woocommerce/issues/47223
- [ ] https://github.com/woocommerce/woocommerce/issues/47267
- [ ] https://github.com/woocommerce/woocommerce/issues/47531
- [ ] https://github.com/woocommerce/woocommerce/issues/47532
- [ ] https://github.com/woocommerce/woocommerce/issues/47533
- [ ] https://github.com/woocommerce/woocommerce/issues/48366
```

**Comment by adimoldovan** [comment]
Closing as done.
