### ISSUE TITLE
Product Filters Block Final Stretch

### ISSUE THREAD

**Issue by thealexandrelara** [woothemes/woocommerce#46142]
The goal of this project is to implement a new design to the Product Filters block, including new features and improving the user experience. 

### Final stretch
Refer to the sub-issues below.

### Future cycles
- [ ] https://github.com/woocommerce/woocommerce/issues/51855
- [x] https://github.com/woocommerce/woocommerce/issues/51640
- [ ] https://github.com/woocommerce/woocommerce/issues/51864
- [x] https://github.com/woocommerce/woocommerce/issues/43493

### i6 - Restructure
- [x] https://github.com/woocommerce/woocommerce/issues/52853
- [x] https://github.com/woocommerce/woocommerce/issues/54257
- [x] https://github.com/woocommerce/woocommerce/issues/53902
- [x] https://github.com/woocommerce/woocommerce/issues/52885
- [x] https://github.com/woocommerce/woocommerce/issues/52854
- [x] https://github.com/woocommerce/woocommerce/issues/52794
- [x] https://github.com/woocommerce/woocommerce/issues/52775
- [x] https://github.com/woocommerce/woocommerce/issues/52884
- [x] https://github.com/woocommerce/woocommerce/issues/54943
- [x] https://github.com/woocommerce/woocommerce/issues/54944
- [x] https://github.com/woocommerce/woocommerce/issues/52442

### i5 - Finishing touches
- [x] https://github.com/woocommerce/woocommerce/issues/51780
- [x] https://github.com/woocommerce/woocommerce/issues/51636
- [x] https://github.com/woocommerce/woocommerce/issues/51622
- [x] https://github.com/woocommerce/woocommerce/issues/51638
- [x] https://github.com/woocommerce/woocommerce/issues/51639
- [x] https://github.com/woocommerce/woocommerce/issues/51641
- [x] https://github.com/woocommerce/woocommerce/issues/51859
- [x] https://github.com/woocommerce/woocommerce/issues/51789
- [x] https://github.com/woocommerce/woocommerce/issues/51821
- [x] https://github.com/woocommerce/woocommerce/issues/51787
- [x] https://github.com/woocommerce/woocommerce/issues/51781
- [x] https://github.com/woocommerce/woocommerce/issues/51868

### i4 – Overlay, Display Styles, and Interactivity API
- [x] https://github.com/woocommerce/woocommerce/issues/49933
- [x] https://github.com/woocommerce/woocommerce/issues/49977
- [x] https://github.com/woocommerce/woocommerce/issues/49976
- [x] https://github.com/woocommerce/woocommerce/issues/50273
- [x] https://github.com/woocommerce/woocommerce/issues/50866
- [x] https://github.com/woocommerce/woocommerce/issues/50867
- [x] https://github.com/woocommerce/woocommerce/issues/49975
- [x] https://github.com/woocommerce/woocommerce/issues/50871
- [x] https://github.com/woocommerce/woocommerce/issues/50868
- [x] https://github.com/woocommerce/woocommerce/issues/49931
- [x] https://github.com/woocommerce/woocommerce/issues/49693
- [x] https://github.com/woocommerce/woocommerce/issues/46981
- [x] https://github.com/woocommerce/woocommerce/issues/50150

### i3: Product Filters template part and Overlay template part
In the previous cycle, we had planned to implement the Product Filters as a synced pattern; however, after some discussion and investigation, we concluded that it wouldn't be possible to implement the synced pattern at its current state. For this cycle, we will be implementing the Product Filters as a template part and continue the work on the Overlay template part by focusing on the frontend side and integrating it with the editor. We will also be addressing some issues raised on the last cycle.
- [x] https://github.com/woocommerce/woocommerce/issues/43493
- [x] https://github.com/woocommerce/woocommerce/issues/49933
- [x] https://github.com/woocommerce/woocommerce/issues/49977
- [x] https://github.com/woocommerce/woocommerce/issues/49976
- [x] https://github.com/woocommerce/woocommerce/issues/49975
- [x] https://github.com/woocommerce/woocommerce/issues/49693
- [x] https://github.com/woocommerce/woocommerce/issues/49690
- [x] https://github.com/woocommerce/woocommerce/issues/49974
- [x] https://github.com/woocommerce/woocommerce/issues/49978
- [x] https://github.com/woocommerce/woocommerce/issues/48641
- [x] https://github.com/woocommerce/woocommerce/issues/49979
- [x] https://github.com/woocommerce/woocommerce/issues/49980
- [x] https://github.com/woocommerce/woocommerce/issues/49998
- [x] https://github.com/woocommerce/woocommerce/issues/49578
- [x] https://github.com/woocommerce/woocommerce/issues/47038
- [x] https://github.com/woocommerce/woocommerce/issues/49500
- [x] https://github.com/woocommerce/woocommerce/issues/47039
- [x] https://github.com/woocommerce/woocommerce/issues/48990
- [x] https://github.com/woocommerce/woocommerce/issues/49503
- [x] https://github.com/woocommerce/woocommerce/issues/49577

### i2: Synced Pattern and Overlay Template Part
In this cycle, we will be adding the Product Filters wrapper block to a Synced Pattern and working on the Overlay template part for the block.
- [x] https://github.com/woocommerce/woocommerce/issues/48018
- [x] https://github.com/woocommerce/woocommerce/issues/47039
- [x] https://github.com/woocommerce/woocommerce/issues/47911
- [x] https://github.com/woocommerce/woocommerce/issues/46986
- [x] https://github.com/woocommerce/woocommerce/issues/47037
- [x] https://github.com/woocommerce/woocommerce/issues/48019
- [x] https://github.com/woocommerce/woocommerce/issues/48022
- [x] https://github.com/woocommerce/woocommerce/issues/47913
- [x] https://github.com/woocommerce/woocommerce/issues/47975
- [x] https://github.com/woocommerce/woocommerce/issues/47977
- [x] https://github.com/woocommerce/woocommerce/issues/48637
- [x] https://github.com/woocommerce/woocommerce/issues/48025

### i1: Wrapper and Clear button blocks
This initial cycle focuses on implementing the wrapper block and the clear button for the Product Filters block.
- [x] https://github.com/woocommerce/woocommerce/issues/46981
- [x] https://github.com/woocommerce/woocommerce/issues/47525
- [x] https://github.com/woocommerce/woocommerce/issues/46296
- [x] https://github.com/woocommerce/woocommerce/issues/46984
- [x] https://github.com/woocommerce/woocommerce/issues/46293
- [x] https://github.com/woocommerce/woocommerce/issues/46295
- [x] https://github.com/woocommerce/woocommerce/issues/46297
- [x] https://github.com/woocommerce/woocommerce/issues/46298
- [x] https://github.com/woocommerce/woocommerce/issues/46299
