### ISSUE TITLE
[Epic] Graduate Additional Fields

### ISSUE THREAD

**Issue by ralucaStan** [woothemes/woocommerce#46385]
```[tasklist]
### Tasks
- [ ] https://github.com/woocommerce/woocommerce/issues/45841
- [ ] https://github.com/woocommerce/woocommerce/issues/42025
- [ ] https://github.com/woocommerce/woocommerce/issues/42774
- [ ] https://github.com/woocommerce/woocommerce/issues/42138
- [ ] https://github.com/woocommerce/woocommerce/pull/47137
```

**Comment by senadir** [comment]
Fields are already graduated and visibility parser moved to its own project.
