### ISSUE TITLE
Spike - Improve Time to Interactive (TTI)

### ISSUE THREAD

**Issue by mdperez86** [woothemes/woocommerce#46443]
**Prerequisites (mark completed items with an [x]):**
- [ ] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [ ] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

**Issue Description:**

The Time to Interactive (TTI) metric is currently suboptimal due to specific issues that are causing delays in interactivity. This metric is crucial as it reflects the time at which a page is fully interactive. Below are the details of the issues and the proposed actions to resolve them.

### Bad request
- URL - /wp-json/wc/v3/products/-1
- Duration - 674.815ms
- Issue https://github.com/woocommerce/woocommerce/issues/45401

**Problem**: This endpoint is being called with an invalid product ID (-1), which likely results in unnecessary processing and delay.
**Proposed Fix**: Ensure that calls to this endpoint are made with valid product IDs or remove the call.

### Long running task
- Expensive function call 
  - https://github.com/woocommerce/woocommerce/blob/trunk/packages/js/components/src/experimental-select-tree-control/select-tree-menu.tsx#L48
  - https://github.com/woocommerce/woocommerce/blob/trunk/packages/js/components/src/experimental-select-tree-control/select-tree-menu.tsx#L54

```[tasklist]
### Tasks
- [ ] https://github.com/woocommerce/woocommerce/issues/45401
```

**Comment by nathanss** [comment]
Related: https://github.com/woocommerce/woocommerce/issues/45401
