### ISSUE TITLE
Spike - Decrease number of scripts, styles, and requests going out

### ISSUE THREAD

**Issue by mdperez86** [woothemes/woocommerce#46445]
**Prerequisites (mark completed items with an [x]):**
- [ ] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [ ] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

**Issue Description:**

### Scripts

![image](https://github.com/woocommerce/woocommerce/assets/13334210/c7367ca9-603f-4942-b158-80e92ad02341)
![image](https://github.com/woocommerce/woocommerce/assets/13334210/44e35620-58f6-4ee7-a5d9-fa12e36cc9d4)
![image](https://github.com/woocommerce/woocommerce/assets/13334210/6e6536f7-037c-4ec4-8b0b-58f4309e32c6)

- This report indicates that more than half of all downloaded scripts are unused by the current page. 
- A lot of block specific scripts are downloaded even when none of them are used. 
- Blocks that do not belong to the block editor itself are also downloaded.
- Issue https://github.com/woocommerce/woocommerce/issues/46502

### Styles

![image](https://github.com/woocommerce/woocommerce/assets/13334210/d147cd73-c799-4304-8229-b1421539de14)

- 2.1 MB of css content downloaded
- 92 css files requested

![image](https://github.com/woocommerce/woocommerce/assets/13334210/253770c8-daf7-4a6e-909b-dedd5202e549)

- 73 of 92 are block css files. Only 21 are blocks that belong to the product editor.
- Almost all block css files have the same repeated code, in some cases this represents more of the 90% of the css file.
- Issue https://github.com/woocommerce/woocommerce/issues/46501

```css
:root {
    --wp-admin-theme-color: #007cba;
    --wp-admin-theme-color--rgb: 0,124,186;
    --wp-admin-theme-color-darker-10: #006ba1;
    --wp-admin-theme-color-darker-10--rgb: 0,107,161;
    --wp-admin-theme-color-darker-20: #005a87;
    --wp-admin-theme-color-darker-20--rgb: 0,90,135;
    --wp-admin-border-width-focus: 2px
}

@media(-webkit-min-device-pixel-ratio: 2),(min-resolution:192dpi) {
    :root {
        --wp-admin-border-width-focus:1.5px
    }
}

body.admin-color-light {
    --wp-admin-theme-color: #0085ba;
    --wp-admin-theme-color--rgb: 0,133,186;
    --wp-admin-theme-color-darker-10: #0073a1;
    --wp-admin-theme-color-darker-10--rgb: 0,115,161;
    --wp-admin-theme-color-darker-20: #006187;
    --wp-admin-theme-color-darker-20--rgb: 0,97,135;
    --wp-admin-border-width-focus: 2px
}

@media(-webkit-min-device-pixel-ratio: 2),(min-resolution:192dpi) {
    body.admin-color-light {
        --wp-admin-border-width-focus:1.5px
    }
}

body.admin-color-modern {
    --wp-admin-theme-color: #3858e9;
    --wp-admin-theme-color--rgb: 56,88,233;
    --wp-admin-theme-color-darker-10: #2145e6;
    --wp-admin-theme-color-darker-10--rgb: 33,69,230;
    --wp-admin-theme-color-darker-20: #183ad6;
    --wp-admin-theme-color-darker-20--rgb: 24,58,214;
    --wp-admin-border-width-focus: 2px
}

@media(-webkit-min-device-pixel-ratio: 2),(min-resolution:192dpi) {
    body.admin-color-modern {
        --wp-admin-border-width-focus:1.5px
    }
}

body.admin-color-blue {
    --wp-admin-theme-color: #096484;
    --wp-admin-theme-color--rgb: 9,100,132;
    --wp-admin-theme-color-darker-10: #07526c;
    --wp-admin-theme-color-darker-10--rgb: 7,82,108;
    --wp-admin-theme-color-darker-20: #064054;
    --wp-admin-theme-color-darker-20--rgb: 6,64,84;
    --wp-admin-border-width-focus: 2px
}

@media(-webkit-min-device-pixel-ratio: 2),(min-resolution:192dpi) {
    body.admin-color-blue {
        --wp-admin-border-width-focus:1.5px
    }
}

body.admin-color-coffee {
    --wp-admin-theme-color: #46403c;
    --wp-admin-theme-color--rgb: 70,64,60;
    --wp-admin-theme-color-darker-10: #383330;
    --wp-admin-theme-color-darker-10--rgb: 56,51,48;
    --wp-admin-theme-color-darker-20: #2b2724;
    --wp-admin-theme-color-darker-20--rgb: 43,39,36;
    --wp-admin-border-width-focus: 2px
}

@media(-webkit-min-device-pixel-ratio: 2),(min-resolution:192dpi) {
    body.admin-color-coffee {
        --wp-admin-border-width-focus:1.5px
    }
}

body.admin-color-ectoplasm {
    --wp-admin-theme-color: #523f6d;
    --wp-admin-theme-color--rgb: 82,63,109;
    --wp-admin-theme-color-darker-10: #46365d;
    --wp-admin-theme-color-darker-10--rgb: 70,54,93;
    --wp-admin-theme-color-darker-20: #3a2c4d;
    --wp-admin-theme-color-darker-20--rgb: 58,44,77;
    --wp-admin-border-width-focus: 2px
}

@media(-webkit-min-device-pixel-ratio: 2),(min-resolution:192dpi) {
    body.admin-color-ectoplasm {
        --wp-admin-border-width-focus:1.5px
    }
}

body.admin-color-midnight {
    --wp-admin-theme-color: #e14d43;
    --wp-admin-theme-color--rgb: 225,77,67;
    --wp-admin-theme-color-darker-10: #dd382d;
    --wp-admin-theme-color-darker-10--rgb: 221,56,45;
    --wp-admin-theme-color-darker-20: #d02c21;
    --wp-admin-theme-color-darker-20--rgb: 208,44,33;
    --wp-admin-border-width-focus: 2px
}

@media(-webkit-min-device-pixel-ratio: 2),(min-resolution:192dpi) {
    body.admin-color-midnight {
        --wp-admin-border-width-focus:1.5px
    }
}

body.admin-color-ocean {
    --wp-admin-theme-color: #627c83;
    --wp-admin-theme-color--rgb: 98,124,131;
    --wp-admin-theme-color-darker-10: #576e74;
    --wp-admin-theme-color-darker-10--rgb: 87,110,116;
    --wp-admin-theme-color-darker-20: #4c6066;
    --wp-admin-theme-color-darker-20--rgb: 76,96,102;
    --wp-admin-border-width-focus: 2px
}

@media(-webkit-min-device-pixel-ratio: 2),(min-resolution:192dpi) {
    body.admin-color-ocean {
        --wp-admin-border-width-focus:1.5px
    }
}

body.admin-color-sunrise {
    --wp-admin-theme-color: #dd823b;
    --wp-admin-theme-color--rgb: 221,130,59;
    --wp-admin-theme-color-darker-10: #d97426;
    --wp-admin-theme-color-darker-10--rgb: 217,116,38;
    --wp-admin-theme-color-darker-20: #c36922;
    --wp-admin-theme-color-darker-20--rgb: 195,105,34;
    --wp-admin-border-width-focus: 2px
}

@media(-webkit-min-device-pixel-ratio: 2),(min-resolution:192dpi) {
    body.admin-color-sunrise {
        --wp-admin-border-width-focus:1.5px
    }
}
```

```[tasklist]
### Tasks
- [ ] https://github.com/woocommerce/woocommerce/issues/46502
- [ ] https://github.com/woocommerce/woocommerce/issues/46501
```

**Comment by nathanss** [comment]
We originally estimated only the part about handling the repeated CSS code
