### ISSUE TITLE
Spike: Improve First Contentful Paint

### ISSUE THREAD

**Issue by mdperez86** [woothemes/woocommerce#46442]
**Prerequisites (mark completed items with an [x]):**
- [ ] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [ ] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

**Issue Description:**

The product form currently exhibits slow load times, impacting user experience by delaying the First Contentful Paint (FCP). This metric is crucial as it directly influences user perception of the site's responsiveness.

#### Implement Lazy Loading - Spike https://github.com/woocommerce/woocommerce/issues/46492

- Components Targeted for Lazy Loading - Issue https://github.com/woocommerce/woocommerce/issues/46493
  - `ProductMVPFeedbackModalContainer`: This modal container is not immediately necessary on page load and can be loaded asynchronously to reduce initial load time.
  - `BlockEditorTourWrapper`: Similar to the ProductMVPFeedbackModalContainer, this component can be deferred a few seconds.
  - PoC [here](https://github.com/woocommerce/woocommerce/pull/46399).

#### Optimize Large Contentful Paint Elements

- `Summary` field: Identified as one of the largest contentful paint elements, optimizing this field can significantly enhance rendering speed. Issue https://github.com/woocommerce/woocommerce/issues/46491

<img width="663" alt="summary-Screenshot 2024-04-09 at 11 53 57 AM" src="https://github.com/woocommerce/woocommerce/assets/1314156/cda1cca1-2113-4729-a12c-6c0b1dac4bea">

Review and optimize the underlying code for the Summary field.
Implement more efficient CSS and JavaScript, ensuring that heavy computations or styles that block rendering are minimized or eliminated.

```[tasklist]
### Tasks
- [ ] https://github.com/woocommerce/woocommerce/issues/46493
- [ ] https://github.com/woocommerce/woocommerce/issues/46491
- [ ] https://github.com/woocommerce/woocommerce/issues/46492
```

**Comment by octaedro** [comment]
Hi @mdperez86,
I added some test results and a few suggestions to improve the FCP.

**Comment by nathanss** [comment]
The estimation added is just for the `Implement Lazy Loading` part.

**Comment by octaedro** [comment]
### Aditional information
**Lighthouse tests by environment**

- **Production**

<img width="756" alt="prod" src="https://github.com/woocommerce/woocommerce/assets/1314156/56cbc090-4925-4c82-b3a8-d56eeb8e0d52">

```
FCP -> 2.0 seconds
Speed Index -> 4.2 seconds
TTI (Time to interactive) -> 5.43 seconds
```

- **Mobile**

<img width="754" alt="Screenshot 2024-04-09 at 1 10 26 PM" src="https://github.com/woocommerce/woocommerce/assets/1314156/6b4311f9-1794-47da-82cd-271f9b43b438">

```
FCP -> 4.8 seconds
Speed Index -> 15.6s
```

- **Development**

<img width="764" alt="dev-Screenshot 2024-04-09 at 11 12 44 AM" src="https://github.com/woocommerce/woocommerce/assets/1314156/2708c82c-1ffa-4fcc-b0e1-3ec0a7915a73">

```
FCP -> 4.6 seconds
Speed Index -> 7.9 seconds
TTI (Time to interactive) -> 1.72 seconds
```

**Comment by samueljseay** [comment]
@octaedro Can I recommend you use the save to HTML feature of lighthouse reports?

For example when it gives you results for FCP and LCP it includes server latency in that number which can vary depending on if it's local instance or a server somewhere else so screenshotting is not too helpful. Furthermore the HTML report gives all the details of where you should focus improvements which should be more actionable :)
