### ISSUE TITLE
Product Collection: POC how to expose `registerProductCollection`

### ISSUE THREAD

**Issue by kmanijak** [woothemes/woocommerce#46534]
**Background:**
Product Collection is supposed to allow for registering custom collections. To do that some sort of `registerProductCollection` function has to be exposed to 3PD.

```[tasklist]
### Tasks
- [ ] Kickoff discussion about the possible ways of exposing the function to get users' feedback
- [ ] POC some options
- [ ] Once POC'd and verified create an issue about preparing production-ready the solution
```

**Comment by kmanijak** [comment]
This has been done in scope of another issue. Closing as duplicate.
