### ISSUE TITLE
Epic - [Custom fields] Let the created custom field names be usable in other products

### ISSUE THREAD

**Issue by mdperez86** [woothemes/woocommerce#46541]
**Prerequisites (mark completed items with an [x]):**
- [ ] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [ ] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

**Epic**
#44169

**Issue Description:**
Due to the absence of a rest API that manages custom fields in the new experience is not posible yet to show the already created custom field names across different products. This means that the user is not going to see the previous created ones so they have to remember the names they used before.

**ACs**

```[tasklist]
### Tasks
- [ ] https://github.com/woocommerce/woocommerce/issues/46918
- [ ] https://github.com/woocommerce/woocommerce/issues/46919
- [ ] https://github.com/woocommerce/woocommerce/issues/46920
- [ ] https://github.com/woocommerce/woocommerce/issues/46921
- [ ] https://github.com/woocommerce/woocommerce/issues/46612
```
