### ISSUE TITLE
[CFT Custom fields] Fix copy and link

### ISSUE THREAD

**Issue by mdperez86** [woothemes/woocommerce#46540]
**Prerequisites (mark completed items with an [x]):**
- [ ] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [ ] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

**Issue Description:**
Epic #44169

**ACs**

```[tasklist]
### Tasks
- [ ] <s>The copy should be updated “Add custom field” rather than “Show custom fields”</s>
- [ ] <s>Change the toggle by a checkbox like "Downloads"</s>
- [x] The link in the helper text should be replaced with this one: [https://woocommerce.com/document/custom-product-fields/](https://href.li/?https://woocommerce.com/document/custom-product-fields/)
- [x] Add tracking events
- [ ] https://github.com/woocommerce/woocommerce/issues/46606
```

**Tracking events**

- [x] The custom fields toggle
- [x] Add new button
- [x] Add button (inside the modal). Number and name of custom fields as properties
- [x] Edit and delete buttons

**Comment by pmcpinto** [comment]
I think we should start by tracking:
- The custom fields toggle
- Add new button
- Add button (inside the modal). Number and name of custom fields as properties
- Edit and delete buttons
Thanks
