### ISSUE TITLE
strtolower() E_DEPRECATED in includes/class-wc-tracker.pclass-wc-tracker.phphp:816

### ISSUE THREAD

**Issue by mondalaci** [woothemes/woocommerce#46560]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

From time to time, the following PHP warning gets thrown:

```
E_DEPRECATED: strtolower(): Passing null to parameter #1 ($string) of type string is deprecated
(/var/www/ultimatehackingkeyboard.com/wordpress/wp-content/plugins/woocommerce/includes/class-wc-tracker.php:816)

strtolower(/var/www/ultimatehackingkeyboard.com/wordpress/wp-content/plugins/woocommerce/includes/class-wc-tracker.php:816)

WC_Tracker::get_orders_origins(/var/www/ultimatehackingkeyboard.com/wordpress/wp-content/plugins/woocommerce/includes/class-wc-tracker.php:440)

WC_Tracker::get_orders(/var/www/ultimatehackingkeyboard.com/wordpress/wp-content/plugins/woocommerce/includes/class-wc-tracker.php:170)

WC_Tracker::get_tracking_data(/var/www/ultimatehackingkeyboard.com/wordpress/wp-content/plugins/woocommerce/includes/class-wc-tracker.php:75)

WC_Tracker::send_tracking_data(/var/www/ultimatehackingkeyboard.com/wordpress/wp-includes/class-wp-hook.php:324)

WP_Hook::apply_filters(/var/www/ultimatehackingkeyboard.com/wordpress/wp-includes/class-wp-hook.php:348)

WP_Hook::do_action(/var/www/ultimatehackingkeyboard.com/wordpress/wp-includes/plugin.php:565)

do_action_ref_array(/var/www/ultimatehackingkeyboard.com/wordpress/wp-cron.php:191)
```

### Expected behavior

This warning should not be thrown.

### Actual behavior

I use Rollbar to log PHP errors on our site, and this warning gets thrown from time to time.

### Steps to reproduce

This issue happens occasionally. I can't explicitly trigger it.

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://ultimatehackingkeyboard.com/wordpress
Site address (URL): https://ultimatehackingkeyboard.com
WC Version: 8.7.0
REST API Version: ✔ 8.7.0
Action Scheduler Version: ✔ 3.7.2
Log Directory Writable: ✔
WP Version: 6.5.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.24.0
PHP Version: 8.2.10-2ubuntu1
PHP Post Max Size: 8 MB
PHP Time Limit: 0
PHP Max Input Vars: 1000
cURL Version: 8.2.1
OpenSSL/3.0.10

SUHOSIN Installed: –
MySQL Version: 8.0.36-0ubuntu0.23.10.1
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.7.0
WC Database Prefix: wp_
Total Database Size: 687.28MB
Database Data Size: 401.66MB
Database Index Size: 285.62MB
wp_woocommerce_sessions: Data: 2.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_order_items: Data: 4.50MB + Index: 2.52MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 147.16MB + Index: 46.05MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 11.02MB + Index: 8.78MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 5.02MB + Index: 3.03MB + Engine InnoDB
wp_aelia_dismissed_messages: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_aelia_exchange_rates_history: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_commentmeta: Data: 1.52MB + Index: 0.34MB + Engine InnoDB
wp_comments: Data: 17.55MB + Index: 15.09MB + Engine InnoDB
wp_contact_form_log: Data: 3.52MB + Index: 0.00MB + Engine InnoDB
wp_dhl_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_e_events: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_e_notes: Data: 0.02MB + Index: 0.17MB + Engine InnoDB
wp_e_notes_users_relations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_e_submissions: Data: 0.02MB + Index: 0.23MB + Engine InnoDB
wp_e_submissions_actions_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_e_submissions_values: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_failed_jobs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_fusion_form_entries: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_fusion_form_fields: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_fusion_form_submissions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_fusion_forms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_iconic_was_fees: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_jckpc_inventory: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_knowledgebase_auto: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_knowledgebase_log: Data: 2.52MB + Index: 1.52MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 14.48MB + Index: 0.30MB + Engine InnoDB
wp_postmeta: Data: 32.55MB + Index: 6.03MB + Engine InnoDB
wp_posts: Data: 32.55MB + Index: 7.06MB + Engine InnoDB
wp_queue: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_shortpixel_folders: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_shortpixel_meta: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_shortpixel_postmeta: Data: 4.52MB + Index: 4.22MB + Engine InnoDB
wp_shortpixel_queue: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_term_relationships: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.25MB + Index: 0.31MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 37.58MB + Index: 45.16MB + Engine InnoDB
wp_users: Data: 2.52MB + Index: 1.55MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.08MB + Index: 0.02MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.09MB + Index: 0.00MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 1.50MB + Index: 0.77MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_addresses: Data: 4.52MB + Index: 7.06MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_operational_data: Data: 3.52MB + Index: 1.91MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 9.52MB + Index: 9.47MB + Engine InnoDB
wp_wc_order_stats: Data: 4.38MB + Index: 3.44MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.47MB + Index: 0.28MB + Engine InnoDB
wp_wc_orders: Data: 5.52MB + Index: 9.53MB + Engine InnoDB
wp_wc_orders_meta: Data: 41.58MB + Index: 109.58MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_saferpaycw_customer_contexts: Data: 0.16MB + Index: 0.08MB + Engine InnoDB
wp_woocommerce_saferpaycw_documents: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_saferpaycw_ecc: Data: 0.36MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_saferpaycw_schema_version: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_saferpaycw_storage: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_saferpaycw_transactions: Data: 9.52MB + Index: 0.00MB + Engine InnoDB
wp_wpmailsmtp_attachment_files: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wpmailsmtp_debug_events: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpmailsmtp_email_attachments: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wpmailsmtp_emails_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wpmailsmtp_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

attachment: 1293
custom_css: 1
cwginstocknotifier: 59
e-landing-page: 1
elementor_library: 5
mc4wp-form: 4
nav_menu_item: 6
oembed_cache: 4
page: 219
post: 175
product: 53
product_variation: 9
revision: 4380
shop_coupon: 1277
shop_order_placehold: 18688
stc: 2
vpc-config: 1
wcct_countdown: 1
wp_global_styles: 1
wpcode: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (24) ###

Elementor Pro: by Elementor.com – 3.20.3
Elementor: by Elementor.com – 3.20.4
Avada Builder: by ThemeFusion – 3.11.7
Avada Core: by ThemeFusion – 5.11.7
WooCommerce Attribute Swatches by Iconic: by Iconic  – 1.17.3
WooCommerce Product Configurator by Iconic: by Iconic – 1.21.2
Integration for Szamlazz.hu & WooCommerce: by Viszt Péter – 5.9
mame Saferpay for WooCommerce: by mame webdesign hüttig – 1.7.2
Rollbar: by Rollbar – 2.7.1
ShortPixel Image Optimizer: by ShortPixel - Convert WebP/AVIF & Optimize Images – 5.5.5
Aelia Foundation Classes for WooCommerce: by Aelia – 2.4.25.240317
Aelia Currency Switcher for WooCommerce: by Aelia – 5.1.4.240307
WooCommerce EU VAT Number: by WooCommerce – 2.9.2
WooCommerce Nested Category Layout: by SkyVerge – 1.20.1
Sequential Order Numbers for WooCommerce: by SkyVerge – 1.10.1
Aelia Tax Display by Country for WooCommerce: by Aelia – 1.20.12.240307
WooCommerce: by Automattic – 8.7.0
WordSnippets: by László Monda – 1.0.0
WP Fastest Cache Premium: by Emre Vona – 1.7.0
WP Fastest Cache: by Emre Vona – 1.2.5
WP Mail SMTP Pro: by WP Mail SMTP – 4.0.2
UGL DHL Shipping: by UGL – 1.0.0
UGL Knowledgebase: by UGL – 1.0.0
WPS Hide Login: by WPServeur
NicolasKulka
wpformation – 1.9.13.2

### Settings ###

API Enabled: –
Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to Woo.com: ✔
Enforce Approved Product Download Directories: –
HPOS feature screen enabled: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: –

### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 days
Level threshold: –
Log directory size: 40 MB

### WC Pages ###

Shop base: #4622 - /shop
Cart: #4623 - /cart
Checkout: #4624 - /checkout
My account: #4625 - /my-account
Terms and conditions: #5610 - /terms-of-service

### Theme ###

Name: Avada-UHK
Version: 1.0.0
Author URL: https://theme-fusion.com
Child Theme: ✔
Parent Theme Name: Avada
Parent Theme Version: 7.11.7
Parent Theme Author URL: https://themeforest.net/user/ThemeFusion
WooCommerce Support: ✔

### Templates ###

Overrides: Avada/woocommerce/cart/cart.php
Avada/woocommerce/checkout/form-pay.php
Avada/woocommerce/checkout/review-order.php
avada-uhk/woocommerce/emails/customer-invoice.php
Avada/woocommerce/single-product/short-description.php
Avada/woocommerce/single-product/tabs/additional-information.php
Avada/woocommerce/single-product/tabs/description.php

### Számlázz.hu ###

PRO version: ✔
Path: /var/www/ultimatehackingkeyboard.com/wordpress/wp-content/uploads/wc_szamlazz
IPN URL: https://ultimatehackingkeyboard.com/?wc_szamlazz_ipn_url=9c2528199f4c0913de58c68d96b
Payment methods: Array
(
    [paypal] => Array
        (
            [deadline] => 
            [complete] => 1
            [proform] => 
            [deposit] => 1
            [name] => 
            [auto_disabled] => 
        )

    [mame_sp_creditcard] => Array
        (
            [deadline] => 
            [complete] => 1
            [proform] => 
            [deposit] => 1
            [name] => 
            [auto_disabled] => 
        )

    [cardinity] => Array
        (
            [deadline] => 
            [complete] => 1
            [proform] => 
            [deposit] => 1
            [name] => 
            [auto_disabled] => 
        )

    [sb_test] => Array
        (
            [deadline] => 
            [complete] => 1
            [proform] => 
            [deposit] => 1
            [name] => 
            [auto_disabled] => 
        )

)

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-variation-management
product-virtual-downloadable
product-external-affiliate
product-grouped
product-linked
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: customize-store
minified-js
new-product-management-experience
product-pre-publish-modal
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2024-04-14 21:32:00 +02:00
Options: ✔
Notes: 129
Onboarding: completed

### Action Scheduler ###

Complete: 4,169
Oldest: 2024-03-14 09:46:37 +0100
Newest: 2024-04-14 07:48:19 +0200

Failed: 10,792
Oldest: 2019-05-28 19:17:32 +0200
Newest: 2024-04-14 10:42:24 +0200

Pending: 12
Oldest: 2024-04-14 10:47:24 +0200
Newest: 2024-04-20 04:14:55 +0200

### Status report information ###

Generated at: 2024-04-14 10:45:55 +02:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**Comment by jorgeatorres** [comment]
Fixed in #54353.
