### ISSUE TITLE
[Blocks] Migrate Jest/Puppeteer tests to Playwright

### ISSUE THREAD

**Issue by gigitux** [woothemes/woocommerce#46579]
With https://github.com/woocommerce/woocommerce/pull/45148, we migrate the env to node 20. Unfortunately, the old E2E tests infrastructure doesn't work with Node 20. This issue is dedicated to migrating the E2E tests to Playwright.

```[tasklist]
### Tasks
- [ ] https://github.com/woocommerce/woocommerce/pull/46576
- [ ] https://github.com/woocommerce/woocommerce/pull/46580
- [ ] https://github.com/woocommerce/woocommerce/pull/46583
- [ ] https://github.com/woocommerce/woocommerce/pull/46591
- [ ] #46594
- [ ] https://github.com/woocommerce/woocommerce/pull/46644
- [ ] https://github.com/woocommerce/woocommerce/pull/46671
- [ ] https://github.com/woocommerce/woocommerce/pull/46672
```
