### ISSUE TITLE
[Enhancement]: Add link to error snackbar pointing to the Tab/Section where the error originates

### ISSUE THREAD

**Issue by octaedro** [woothemes/woocommerce#46768]
The error snackbar will contain a link that points to the tab and section where the error is generated. After clicking this link, the user will be directed to the tab and the specific section containing the field with the error.

To accomplish that and in order to avoid huge PRs, the work here will be split in this way:

- [x] Add context to errors - #49242
- [x] Add link into the error snackbar - #49246
- [x] Add reference to number control-  #49357
- [x] Add tests to hooks created for the error snackbar #49576

There are a few things that are not covered by these changes:

- Error handling when an error comes from the server (like `invalid sku`).
- It would be good to improve how we handle the clientId param and the parent recognition.

```[tasklist]
### ACs
- [x] Add link to the snackbar pointing tab/section where the error originates
```
