### ISSUE TITLE
[Epic] Pre-publish modal validation

### ISSUE THREAD

**Issue by louwie17** [woothemes/woocommerce#46788]
Most of the pre publish panel has been implemented as part of https://github.com/woocommerce/woocommerce/issues/40371. At the time the error handling/validation was out of scope. This epic will contain this implementation.

**Design (temporary link)**
AkVNGImLgSqCObTQ3idVn7-fi-3359_344908

<img width="877" alt="image" src="https://github.com/woocommerce/woocommerce/assets/79307566/b033fa19-e938-491d-aeb9-174c3b1c79fa">

**Acceptance criteria**

- [ ] Error handling
   - [ ] The section title includes the total number of identified issues. If there's just one issue, the title says: `1 issue found`. If there are more, it says: `X issues found`.
   - [ ] When the pre-publish modal is open, the `Add` button is disabled until all issues are resolved.
   - [ ] We list validation messages for all affected fields the same as they're displayed below them.
   - [ ] User can click on each message or use the arrows in the corner to go between affected fields and solve them one by one.
   - [ ] If there are no more next or previous errors, the arrow button is disabled and changes color to Gutenberg-400.
   - [ ] When an error is solved, it immediately disappears from the list.
   - [ ] If the` Always show pre-publish checks` box was unchecked before, we don't show it at the bottom of the panel (the panel is only shown because of the errors).

```[tasklist]
### Tasks
- [ ] https://github.com/woocommerce/woocommerce/issues/43708
- [ ] https://github.com/woocommerce/woocommerce/issues/43709
```

**Comment by jamesckemp** [comment]
This version of the product editor is now deprecated
