### ISSUE TITLE
[Epic] Product editor dropdown updates and enhancements - Cycle 47

### ISSUE THREAD

**Issue by louwie17** [woothemes/woocommerce#46783]
This issue encapsulates the product editor performance fixes and general enhancements for Cycle 46.
Some issues may get added to this depending on the outcome of #46015
Ordered by priority.

```[tasklist]
### Product ID Spike Tasks
- [ ] https://github.com/woocommerce/woocommerce/issues/41816
```
```[tasklist]
### Select Control Tasks
- [ ] https://github.com/woocommerce/woocommerce/issues/41816
- [ ] https://github.com/woocommerce/woocommerce/issues/45294
- [ ] https://github.com/woocommerce/woocommerce/issues/45295 
- [ ] https://github.com/woocommerce/woocommerce/issues/38218
- [ ] https://github.com/woocommerce/woocommerce/issues/38232
- [ ] https://github.com/woocommerce/woocommerce/issues/38227
```

**Note:**
Issue #45294 and #45295 were created in replacement of #35851, #38231, #38229, and #38227 as these issues should be fixed when making use of the GB components.
