### ISSUE TITLE
CYS - Full Composability

### ISSUE THREAD

**Issue by gigitux** [woothemes/woocommerce#47323]
This is a tracking issue for the Full Composability feature for the Customize Your Store Project. This project will provide the users the flexibility to design their own homepage by adding, removing, shuffling, and rearranging patterns:

![image](https://github.com/woocommerce/woocommerce/assets/4463174/27dc70ea-239b-480b-8ece-cdbb3883e0f3)
*this image is a mockup - not a real implementation*

```[tasklist]
### Tasks - WIP
- [ ] https://github.com/woocommerce/woocommerce/issues/47325
- [ ] https://github.com/woocommerce/woocommerce/issues/47326
- [ ] https://github.com/woocommerce/woocommerce/issues/47327
- [ ] https://github.com/woocommerce/woocommerce/issues/47328
- [ ] https://github.com/woocommerce/woocommerce/issues/47371
- [ ] https://github.com/woocommerce/woocommerce/issues/47453
- [ ] https://github.com/woocommerce/woocommerce/issues/47454
- [ ] https://github.com/woocommerce/woocommerce/issues/47455
- [ ] https://github.com/woocommerce/woocommerce/issues/47456
- [ ] https://github.com/woocommerce/woocommerce/issues/47751
```

**Comment by nefeline** [comment]
Closing this one out in favor of https://github.com/woocommerce/woocommerce/issues/47459
