### ISSUE TITLE
[EPIC] Full Composability

### ISSUE THREAD

**Issue by nefeline** [woothemes/woocommerce#47459]
**Issue Description:**

This project aims to introduce full composability to the Customize Your Store Assembler, which will provide users with the flexibility to design their own homepage by adding, removing, shuffling, and rearranging patterns.

This initiative is directly tied and dependent on https://github.com/woocommerce/woocommerce/issues/45834 : both features are expected to be released together.
```[tasklist]
### Features
- [ ] https://github.com/woocommerce/woocommerce/issues/47461
- [ ] https://github.com/woocommerce/woocommerce/issues/47462
- [ ] https://github.com/woocommerce/woocommerce/issues/47463
- [ ] https://github.com/woocommerce/woocommerce/issues/47464
- [ ] https://github.com/woocommerce/woocommerce/issues/47465
- [ ] https://github.com/woocommerce/woocommerce/issues/47326
- [ ] https://github.com/woocommerce/woocommerce/issues/47327
- [ ] https://github.com/woocommerce/woocommerce/issues/47325
- [ ] https://github.com/woocommerce/woocommerce/issues/47371
- [ ] https://github.com/woocommerce/woocommerce/issues/47453
- [ ] https://github.com/woocommerce/woocommerce/issues/47454
- [ ] https://github.com/woocommerce/woocommerce/issues/47455
- [ ] https://github.com/woocommerce/woocommerce/issues/47456
- [ ] https://github.com/woocommerce/woocommerce/issues/47521
- [ ] https://github.com/woocommerce/woocommerce/issues/47545
- [ ] https://github.com/woocommerce/woocommerce/issues/47570
- [ ] https://github.com/woocommerce/woocommerce/issues/47577
- [ ] https://github.com/woocommerce/woocommerce/issues/47751
- [ ] https://github.com/woocommerce/woocommerce/issues/47752
- [ ] https://github.com/woocommerce/woocommerce/issues/47855
- [ ] https://github.com/woocommerce/woocommerce/issues/48182
- [ ] https://github.com/woocommerce/woocommerce/issues/48251
- [ ] https://github.com/woocommerce/woocommerce/issues/48252
- [ ] https://github.com/woocommerce/woocommerce/issues/48308
- [ ] https://github.com/woocommerce/woocommerce/issues/48381
- [ ] https://github.com/woocommerce/woocommerce/issues/48426
- [ ] https://github.com/woocommerce/woocommerce/issues/48438
- [ ] https://github.com/woocommerce/woocommerce/issues/48551
- [ ] https://github.com/woocommerce/woocommerce/issues/48663
- [ ] https://github.com/woocommerce/woocommerce/issues/48950
- [ ] https://github.com/woocommerce/woocommerce/issues/49197
```

```[tasklist]
### Bugs
- [ ] https://github.com/woocommerce/woocommerce/issues/48683
- [ ] https://github.com/woocommerce/woocommerce/issues/48680
- [ ] https://github.com/woocommerce/woocommerce/issues/49024
- [ ] https://github.com/woocommerce/woocommerce/issues/48678
- [ ] https://github.com/woocommerce/woocommerce/issues/48669
- [ ] https://github.com/woocommerce/woocommerce/issues/48682
- [ ] https://github.com/woocommerce/woocommerce/issues/48711
- [ ] https://github.com/woocommerce/woocommerce/issues/48713
- [ ] https://github.com/woocommerce/woocommerce/issues/48728
- [ ] https://github.com/woocommerce/woocommerce/issues/48783
- [ ] https://github.com/woocommerce/woocommerce/issues/48784
- [ ] https://github.com/woocommerce/woocommerce/issues/48786
- [ ] https://github.com/woocommerce/woocommerce/issues/48787
- [ ] https://github.com/woocommerce/woocommerce/issues/48888
- [ ] https://github.com/woocommerce/woocommerce/issues/49128
```

```[tasklist]
### Next iteration
- [ ] https://github.com/woocommerce/woocommerce/issues/48439
```

**Comment by gigitux** [comment]
This project will be shipped with WooCommerce 9.2! Thanks for your effort, folks! 🚀
