### ISSUE TITLE
[Epic] Product editor enhancements - Cycle 48

### ISSUE THREAD

**Issue by louwie17** [woothemes/woocommerce#47571]
This issue encapsulates the product editor enhancements for Cycle 48.
Ordered by priority within each section.

```[tasklist]
### Must haves ( also listed in the lists below )
- [ ] https://github.com/woocommerce/woocommerce/issues/40351
- [ ] https://github.com/woocommerce/woocommerce/issues/45641
- [ ] https://github.com/woocommerce/woocommerce/issues/45740
- [ ] https://github.com/woocommerce/woocommerce/issues/47146
- [ ] https://github.com/woocommerce/woocommerce/issues/47251
- [ ] https://github.com/woocommerce/woocommerce/issues/48116
```

```[tasklist]
### Variations
- [ ] https://github.com/woocommerce/woocommerce/issues/40351
- [ ] https://github.com/woocommerce/woocommerce/issues/45641
- [ ] https://github.com/woocommerce/woocommerce/issues/48116
```

```[tasklist]
### Description
- [ ] https://github.com/woocommerce/woocommerce/issues/45740
- [ ] https://github.com/woocommerce/woocommerce/issues/47197
- [ ] https://github.com/woocommerce/woocommerce/issues/45664
- [ ] https://github.com/woocommerce/woocommerce/issues/47152
- [ ] https://github.com/woocommerce/woocommerce/issues/47188
- [ ] https://github.com/woocommerce/woocommerce/issues/47200
```

```[tasklist]
### Misc
- [ ] https://github.com/woocommerce/woocommerce/issues/47146
- [ ] https://github.com/woocommerce/woocommerce/issues/45883
- [ ] https://github.com/woocommerce/woocommerce/issues/46342
- [ ] https://github.com/woocommerce/woocommerce/issues/47293
- [ ] https://github.com/woocommerce/woocommerce/issues/45920
- [ ] https://github.com/woocommerce/woocommerce/issues/45925
- [ ] https://github.com/woocommerce/woocommerce/issues/40958
- [ ] https://github.com/woocommerce/woocommerce/issues/36773
- [ ] https://github.com/woocommerce/woocommerce/issues/38054
- [ ] https://github.com/woocommerce/woocommerce/issues/32837
- [ ] https://github.com/woocommerce/woocommerce/issues/47788
- [ ] https://github.com/woocommerce/woocommerce/issues/47804
- [ ] https://github.com/woocommerce/woocommerce/pull/48114
- [ ] https://github.com/woocommerce/woocommerce/issues/48393
- [ ] https://github.com/woocommerce/woocommerce/issues/48398
- [ ] https://github.com/woocommerce/woocommerce/issues/48290
- [ ] https://github.com/woocommerce/woocommerce/issues/48094
```

```[tasklist]
### Custom fields
- [ ] https://github.com/woocommerce/woocommerce/issues/46541
- [ ] https://github.com/woocommerce/woocommerce/issues/46612
```

```[tasklist]
### Tracks
- [ ] https://github.com/woocommerce/woocommerce/issues/47107
- [ ] https://github.com/woocommerce/woocommerce/issues/47108
```

**Comment by pmcpinto** [comment]
I think the top-5 priorities should be:

https://github.com/woocommerce/woocommerce/issues/40351
https://github.com/woocommerce/woocommerce/issues/45641
https://github.com/woocommerce/woocommerce/issues/45740
https://github.com/woocommerce/woocommerce/issues/35851
https://github.com/woocommerce/woocommerce/issues/47146

**Comment by mdperez86** [comment]
Select Control specific issues are going to be covered as part of https://github.com/woocommerce/woocommerce/issues/49040

**Comment by louwie17** [comment]
Done.
