### ISSUE TITLE
`[Epic]` Product Form Template system (PFT)

### ISSUE THREAD

**Issue by retrofox** [woothemes/woocommerce#47906]
```[tasklist]
### MVP Tasks
- [ ] https://github.com/woocommerce/woocommerce/issues/48134
- [ ] https://github.com/woocommerce/woocommerce/issues/47907
- [ ] https://github.com/woocommerce/woocommerce/issues/47998
- [ ] https://github.com/woocommerce/woocommerce/issues/48203
- [ ] https://github.com/woocommerce/woocommerce/issues/47997
- [ ] https://github.com/woocommerce/woocommerce/issues/47999
- [ ] https://github.com/woocommerce/woocommerce/issues/48000
- [ ] https://github.com/woocommerce/woocommerce/pull/48265
- [ ] https://github.com/woocommerce/woocommerce/issues/48266
- [ ] https://github.com/woocommerce/woocommerce/issues/48174
- [ ] https://github.com/woocommerce/woocommerce/issues/48236
- [ ] https://github.com/woocommerce/woocommerce/issues/48278
- [ ] https://github.com/woocommerce/woocommerce/issues/48001
- [ ] Deprecate template registry in favor of product_form post type querying and insertion.
- [ ] This can either be done by a combination of custom block editor and/or removing block tools. OR…
- [ ] Rendering a tree of React elements based on the View components as demonstrated in the POC PR.
- [ ] Depending on the approach taken above, the blocks may need to be refactored (in a very minor way) to have both Edit and View renders.
- [ ] https://github.com/woocommerce/woocommerce/issues/48334
```

### Relevante links

* [GitHub dashboard](https://github.com/orgs/woocommerce/projects/60/views/77)

* https://github.com/woocommerce/woocommerce/pull/45969
* https://github.com/woocommerce/woocommerce/pull/46135
* https://github.com/woocommerce/woocommerce/pull/46348

**Comment by gigitux** [comment]
Hey @retrofox! Do you think that we can close this issue?

**Comment by retrofox** [comment]
Yes. After a talk with dev folks, we decided to hold on with this approach for now.
