### ISSUE TITLE
Fix visual inconsistencies with the Checkout Block from WooCommerce 9.0

### ISSUE THREAD

**Issue by ralucaStan** [woothemes/woocommerce#47991]
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

The Subs area need visual updates in order to be aligned with the new Checkout Block layout

### Expected behavior

```[tasklist]
### Tasks
- [ ] https://github.com/woocommerce/woocommerce/issues/47900
- [ ] Rename "Shipping" to "Delivery".
- [ ] Remove `via` in the shipping line item.
- [ ] Include shipping address in shipping line item? (debatable).
- [ ] Show included taxes in the total (debatable).
- [ ] Separate discount from subtotal.
- [ ] Don't show taxes if they're 0.
- [ ] Show shipping as free if it's 0.
- [ ] Align how taxes are shown when there are multiple taxes.
```

### Screenshots

Those are screenshots that shows how our summary items are (top) and how subscription summary items are (bottom):

<img width="377" alt="Screenshot 2024-05-28 at 5 48 06 PM" src="https://github.com/woocommerce/woocommerce/assets/6165348/28705e8a-1dc6-45fd-a800-716d9b2880cf">
<img width="389" alt="Screenshot 2024-05-28 at 5 47 21 PM" src="https://github.com/woocommerce/woocommerce/assets/6165348/58753ba0-7082-4177-8388-f00fea0e7815">
<img width="381" alt="Screenshot 2024-05-28 at 5 46 34 PM" src="https://github.com/woocommerce/woocommerce/assets/6165348/2d018161-c26d-4042-9d19-23e0a6613b19">
<img width="368" alt="Screenshot 2024-05-28 at 5 46 16 PM" src="https://github.com/woocommerce/woocommerce/assets/6165348/f0cd52df-5043-452f-89bd-0f73e46d96ae">
<img width="371" alt="Screenshot 2024-05-28 at 5 45 45 PM" src="https://github.com/woocommerce/woocommerce/assets/6165348/8d9196ae-1104-4930-ad1e-dc61ea57b207">

### Steps to reproduce

-

### WordPress Environment

n/a

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by pmcpinto** [comment]
@PanosSynetos, will your team implement these changes? Just to confirm if it makes sense to keep the team Rubik label. cc @opr

**Comment by PanosSynetos** [comment]
Hey @pmcpinto - This is not for SomewhereWarm to work on. Our work on Subscriptions is very specific to new features that we're implementing. I added the issue to our board so I can track it, sorry if this was misleading

**Comment by opr** [comment]
@pmcpinto the team to ask about this is maybe @woocommerce/quark I think they own Woo Subscriptions - Rubik _can_ do it though if Quark doesn't have much availability.
