### ISSUE TITLE
Move the order attribution data into separate table and ensure this table is ingested by Jetpack Sync

### ISSUE THREAD

**Issue by ibndawood** [woothemes/woocommerce#48034]
**Issue Description:**

The order attribution data is currently stored as order metadata. We need to move this data to a separate table to run complex queries for analytics purposes. The new table should also be ingested by Jetpack Sync.

```[tasklist]
### Tasks
- [ ] Define and create a new table for storing order attribution data. 
- [ ] The order create action should store attribution data to this new table.
- [ ] Migrate existing order attribution data to this newly created table.
- [ ] Jetpack sync integration
```

**Comment by ibndawood** [comment]
This issue is no longer valid as the business requirements have changed.
