### ISSUE TITLE
Epic: Remove jQuery from WooCommerce

### ISSUE THREAD

**Issue by samueljseay** [woothemes/woocommerce#48517]
**Issue Description:**

This epic is a place to collect issues related to removing jQuery from front-end WooCommerce. There are quite a few places where it's still present. 

The idea is to get a summarized view of the work necessary to remove it so teams can focus on it in a cooldown or external contributors can know what needs to be done if they wish to help out.

```[tasklist]
### Tasks
- [ ] https://github.com/woocommerce/woocommerce/issues/36604
- [ ] https://github.com/woocommerce/woocommerce/issues/36251
- [ ] Replace jQuery usage on woocommerce.js with plain JS (or remove outdated code)
```

**Comment by LenVan** [comment]
Hi all,

Just wanted to add a quick confirmation from our side — we’re using a FSE theme with entirely React-based blocks, no jQuery involved at all. Still, WooCommerce enqueues `woocommerce-js` on the front end, which brings along `jquery`, `jquery-migrate`, and `jquery-blockui`.

Are there any plans to rewrite this small script (woocommerce-js) in vanilla JS to remove the jQuery dependency? It would be great to avoid loading unnecessary libraries in modern themes.

Thanks!

**Comment by ayoubkhan558** [comment]
Many developers have abandoned using jQuery, now its time for Woocommerce to stop using it

**Comment by miikkamakela-into** [comment]
<img width="500" height="676" alt="Image" src="https://github.com/user-attachments/assets/94c6f53b-ec81-4f24-8b21-61ce3da0944e" />

**Comment by ayoubkhan558** [comment]
ANY UPDATE?

**Comment by kkoteen** [comment]
Hey folks - We’re closing this as not planned for now. The expected performance gains are relatively small, while the risk of introducing breaking changes is high.
