### ISSUE TITLE
[Epic] Checkout Account Creation Improvements

### ISSUE THREAD

**Issue by mikejolley** [woothemes/woocommerce#48608]
This list is not complete and will be expanded as designs are finalised.

```[tasklist]
### Settings UI changes
- [ ] https://github.com/woocommerce/woocommerce/issues/48533
- [ ] https://github.com/woocommerce/woocommerce/issues/49184
```

```[tasklist]
### Create account ~~block~~ fields
- [ ] https://github.com/woocommerce/woocommerce/issues/48723
- [ ] https://github.com/woocommerce/woocommerce/issues/48628
```

```[tasklist]
### Checkout flow
- [ ] https://github.com/woocommerce/woocommerce/issues/42529
```

Related issues:

- https://github.com/woocommerce/woocommerce/issues/42430

Documentation updates:

- [ ] https://woocommerce.com/document/configuring-woocommerce-settings/accounts-and-privacy/

**Comment by mikejolley** [comment]
I'm not sure I have access to edit docs so I've put in a request.

The development tasks for this project have been merged so closing this epic!
