### ISSUE TITLE
[Enhancement]: "Create Account" Block on checkout

### ISSUE THREAD

**Issue by mikejolley** [woothemes/woocommerce#48724]
### Describe the solution you'd like

We are creating a "create account" block on the checkout to improve the checkout flow. 

```[tasklist]
### Tasks
- [ ] Create new block type "Create Account" (name TBD)
- [ ] Make block forced so its inserted on all existing and new checkouts
- [ ] Locked block type—cannot be removed
- [ ] Preview in editor to match guest checkout design, unchecked
- [ ] Frontend appearance depends on chosen global settings. See design variations below.
```

### Account required - Send password setup link on

Block does not render.

### Account required - Send password setup link off

![Screenshot 2024-06-21 at 14 11 20](https://github.com/woocommerce/woocommerce/assets/90977/8f033cb5-0e18-4b43-a91d-6509f9fd800d)

### Guest checkout - Send password setup link on

![Screenshot 2024-06-21 at 14 13 51](https://github.com/woocommerce/woocommerce/assets/90977/e841c18d-d276-4060-9a29-c63f1f028461)

### Account required - Send password setup link off

![Screenshot 2024-06-21 at 14 13 30](https://github.com/woocommerce/woocommerce/assets/90977/8e540bd9-20ec-4dc2-86f6-2b23a9d045e4)
```[tasklist]
### Tasks
```

**Comment by brnhrst** [comment]
First of all, great that this issue is being addressed!

But do I get it right that there will be no option for the user to assign an individual user name?

**Comment by mikejolley** [comment]
@brnhrst Not not in this iteration, and it doesn't currently exist on block checkout. There will be a discussion posted about it.

**Comment by brnhrst** [comment]
Thanks for the clarification! This is currently the main reason keeping us from switching to Block Checkout. I’ll keep an eye on the discussion.

**Comment by mikejolley** [comment]
@brnhrst Whats the main blocker with auto-generated username? Can you summarise so I can pass it on? Thanks

**Comment by brnhrst** [comment]
@mikejolley Sure, I’d be happy to. We sell digital content such as video courses and software, which we make available for download in our customers’ accounts or as online streams when they are logged in. So creating an user account is required for our customers.

In addition, we are trying to build a community and offer our users opportunities to discuss and exchange ideas with each other, give us public feedback, etc. We use other Wordpress plugins for this, which also use the Wordpress user data, so that this workflow has worked very well so far with the functionality of the classic checkout. Users prefer not to use their email addresses or real names here; instead, they like to choose a username. 

And since most new users create their account when they make their first purchase with us, it's very important for us that the checkout (and of course the WooCommerce frontend login/registration forms) can provide this functionality.

**Comment by pmcpinto** [comment]
Hey Michael, thanks for your feedback.

> Users prefer not to use their email addresses or real names here; instead, they like to choose a username.
> And since most new users create their account when they make their first purchase with us, it's very important for us that the checkout (and of course the WooCommerce frontend login/registration forms) can provide this functionality.

Do you have any insights on why your customers dislike using their email address or real name as the username?

**Comment by brnhrst** [comment]
I think the main reason is that the content of our users, e.g. forum posts, is publicly accessible on our website for everyone and is scanned by search engines. Accordingly, users do not want their e-mail address or full name to be published. At the same time, however, a community does not function completely anonymously without any means of identifying each other and it is certainly standard practice worldwide to use nicknames in online communities.

It may be that our user base, which is almost exclusively European and primarily German, is a little less liberal with personal data on the Internet, but I don't think that's the decisive factor.

For a pure store, this function is of course rather unimportant and if you see WooCommerce as a pure e-commerce system, I would probably leave this function out. But the fact that WooCommerce as a Wordpress plugin can be so easily connected with other content and great plugins and that it has such a simple interface with the Wordpress user data to connect several tools and the users and their data, purchases etc. is certainly a strong argument for many people to use WooCommerce at all.

**Comment by mikejolley** [comment]
I am closing this—we're opting to keep everything alongside the create account toggle for this iteration. See https://github.com/woocommerce/woocommerce/issues/48723
