### ISSUE TITLE
[Epic] Addressing tech debt React 18 and Blocks API V3

### ISSUE THREAD

**Issue by ralucaStan** [woothemes/woocommerce#48789]
We accumulated some tech debt in our monorepo, causing WooCommerce plugins to emit console warnings or degrade the editor experience. 

```[tasklist]
### Tasks
- [ ] https://github.com/woocommerce/woocommerce/issues/48796
- [ ] https://github.com/woocommerce/woocommerce/issues/48797
- [ ] https://github.com/woocommerce/woocommerce/issues/48801
- [ ] https://github.com/woocommerce/woocommerce/issues/48716
- [ ] https://github.com/woocommerce/woocommerce/issues/46879
- [ ] https://github.com/woocommerce/woocommerce/pull/51037
```

**Comment by ralucaStan** [comment]
Closing this issue as we managed to remove all the instances of ReactDOM.render and updated our blocks to Blocks API V3. WooCommerce 9.3 will be the first version released with this change.

A big thank you to all the people working to make this happen.
