### ISSUE TITLE
[Epic] Improve the Express Checkout Area

### ISSUE THREAD

**Issue by alexflorisca** [woothemes/woocommerce#48807]
This is a list of tasks for the Express Checkout Area. It follows on from the [Synchronising styles of Express Checkout Buttons](https://github.com/woocommerce/woocommerce/discussions/48055#top) discussion and the [POC: Pass style properties to Express Checkout buttons](https://github.com/woocommerce/woocommerce/pull/47899#top) PR

**Edit: This Project has spilled into Cycle 5 because of a few unknowns. The work completed in Cycle 4:**

```[tasklist]
### Cycle 4
- [ ] https://github.com/woocommerce/woocommerce/issues/48809
- [ ] https://github.com/woocommerce/woocommerce/issues/48810
- [ ] https://github.com/woocommerce/woocommerce/issues/49093
- [ ] https://github.com/woocommerce/woocommerce/issues/47175
- [x] Create PR in [Square](https://github.com/woocommerce/woocommerce-square/pull/175)
- [x] Create RFC for the border-radius spike and gather feedback
- [x] Add borderRadius as an attribute to the express checkout block
- [x] Adjust button sizes and rounded corners in editor preview
```

Deliverables for Cycle 5

```[tasklist]
### Cycle 5
- [x] Missing tests for express payment methods
- [x] Sync Cart & Checkout express area settings
- [x] Merge https://github.com/woocommerce/woocommerce/pull/47899/commits
- [x] Finish [PR in Stripe](https://github.com/woocommerce/woocommerce-gateway-stripe/pull/3164)
- [x] Finish [PR in WooPayments](https://github.com/Automattic/woocommerce-payments/pull/8888)
- [x] Finish [PR in PayPal](https://github.com/woocommerce/woocommerce-paypal-payments/pull/2354)
- [x] ~Create PR in AmazonPay~ - Asked them to do it
- [x] Update documentation
- [ ] Test the integration with all payment extension PRs
- [x] Spike: Rendering preview buttons in the editor
```

These are extra improvements to the editor that have gone through a quite a lot of discussion. Nikki and i synced on these and made some decisions about how to proceed with some of these, so I'm listing them here for completeness. Some of these may make it out in Cycle 5, although it's doubtfull all of them will.

```[tasklist]
### Editor Improvements
- [ ] https://github.com/woocommerce/woocommerce/issues/50839
- [x] ~Add a preview button only when there is a registered EPM, but it's not active for the merchant~ Descoped, this would need to be done after rendering the payment buttons in the editor
- [x] ~Group payment methods from the same extension together in the editor~ Descoped, created issue: https://github.com/woocommerce/woocommerce/issues/50691
- [x] Center the Express Checkout text and change grid gap to 14px between buttons
```

**Comment by ralucaStan** [comment]
@alexflorisca let's close this epic issue. Feel free to include some useful links to people revisiting this ticket.

**Comment by alexflorisca** [comment]
Sure. 
This is the Project Thread: pfwcF5-yy-p2. 
This is the follow up Project to render the buttons inside the editor: pfwcF5-WG-p2
