### ISSUE TITLE
Shipping fee calculations bug

### ISSUE THREAD

**Issue by annapazii9** [woothemes/woocommerce#49473]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Hello,

The formula for shipping calculations is:
 Z + [fee percent="X" min_fee=”Y”]

In the case where X < Y the result supposed to be Z + Y but I got a result Z + X
![Capture d'écran 2024-07-12 155414](https://github.com/user-attachments/assets/7f6ac86c-5aa1-47c6-937e-705eba8f7766)

### Expected behavior

For the formula:  
5 + [fee percent="15" min_fee=”4”]
Expected behavior
total 19,35 € TTC -> 16,13 € HT

15% from 16,13 = 2.42

2.4 < 4   =>  5 + 4 = 9

### Actual behavior

For the formula:  
5 + [fee percent="15" min_fee=”4”]
Actual behavior
total 19,35 € TTC -> 16,13 € HT

15% from 16,13 = 2.42

2.4 < 4   =>  5 + 2.4 = 7.42

### Steps to reproduce

![Capture d'écran 2024-07-12 155414](https://github.com/user-attachments/assets/c9462883-3ea0-445f-9695-737501375436)

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): http://favoridecor.fr
Site address (URL): http://favoridecor.fr
WC Version: 9.1.1
Legacy REST API Package Version: ✔ 1.0.4
Action Scheduler Version: ✔ 3.8.0
Log Directory Writable: ✔
WP Version: 6.5.5
WP Multisite: –
WP Memory Limit: 768 Mo
WP Debug Mode: –
WP Cron: ✔
Language: fr_FR
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.4.33
PHP Post Max Size: 256 Mo
PHP Time Limit: 120
PHP Max Input Vars: 3000
cURL Version: 8.2.1
OpenSSL/3.1.1

SUHOSIN Installed: –
MySQL Version: 8.0.36-28
Max Upload Size: 256 Mo
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 9.0.2
WC Database Prefix: thz_
Taille totale de la base de données: 52.00MB
Taille de la base de données: 40.13MB
Taille de l’index: 11.87MB
thz_woocommerce_sessions: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
thz_woocommerce_api_keys: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
thz_woocommerce_attribute_taxonomies: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
thz_woocommerce_downloadable_product_permissions: Données : 0.02MB + Index : 0.06MB + Moteur InnoDB
thz_woocommerce_order_items: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
thz_woocommerce_order_itemmeta: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
thz_woocommerce_tax_rates: Données : 0.02MB + Index : 0.06MB + Moteur InnoDB
thz_woocommerce_tax_rate_locations: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
thz_woocommerce_shipping_zones: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
thz_woocommerce_shipping_zone_locations: Données : 0.02MB + Index : 0.05MB + Moteur InnoDB
thz_woocommerce_shipping_zone_methods: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
thz_woocommerce_payment_tokens: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
thz_woocommerce_payment_tokenmeta: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
thz_woocommerce_log: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
thz_actionscheduler_actions: Données : 5.02MB + Index : 3.16MB + Moteur InnoDB
thz_actionscheduler_claims: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
thz_actionscheduler_groups: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
thz_actionscheduler_logs: Données : 1.41MB + Index : 0.52MB + Moteur InnoDB
thz_aioseo_cache: Données : 0.14MB + Index : 0.03MB + Moteur InnoDB
thz_aioseo_crawl_cleanup_blocked_args: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
thz_aioseo_crawl_cleanup_logs: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
thz_aioseo_notifications: Données : 0.09MB + Index : 0.06MB + Moteur InnoDB
thz_aioseo_posts: Données : 0.30MB + Index : 0.02MB + Moteur InnoDB
thz_commentmeta: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
thz_comments: Données : 0.02MB + Index : 0.09MB + Moteur InnoDB
thz_e_events: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
thz_gla_attribute_mapping_rules: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
thz_gla_budget_recommendations: Données : 0.19MB + Index : 0.14MB + Moteur InnoDB
thz_gla_merchant_issues: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
thz_gla_shipping_rates: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
thz_gla_shipping_times: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
thz_icl_background_task: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
thz_icl_content_status: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
thz_icl_core_status: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
thz_icl_flags: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
thz_icl_languages: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
thz_icl_languages_translations: Données : 0.20MB + Index : 0.17MB + Moteur InnoDB
thz_icl_locale_map: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
thz_icl_message_status: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
thz_icl_mo_files_domains: Données : 0.05MB + Index : 0.02MB + Moteur InnoDB
thz_icl_node: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
thz_icl_reminders: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
thz_icl_string_batches: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
thz_icl_string_packages: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
thz_icl_string_positions: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
thz_icl_string_status: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
thz_icl_string_translations: Données : 0.06MB + Index : 0.03MB + Moteur InnoDB
thz_icl_strings: Données : 1.52MB + Index : 0.67MB + Moteur InnoDB
thz_icl_translate: Données : 1.52MB + Index : 0.02MB + Moteur InnoDB
thz_icl_translate_job: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
thz_icl_translation_batches: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
thz_icl_translation_downloads: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
thz_icl_translation_status: Données : 0.08MB + Index : 0.02MB + Moteur InnoDB
thz_icl_translations: Données : 0.13MB + Index : 0.30MB + Moteur InnoDB
thz_jetpack_sync_queue: Données : 0.02MB + Index : 0.06MB + Moteur InnoDB
thz_links: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
thz_mailpoet_automation_run_logs: Données : 0.02MB + Index : 0.06MB + Moteur InnoDB
thz_mailpoet_automation_run_subjects: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
thz_mailpoet_automation_runs: Données : 0.02MB + Index : 0.08MB + Moteur InnoDB
thz_mailpoet_automation_triggers: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
thz_mailpoet_automation_versions: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
thz_mailpoet_automations: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
thz_mailpoet_custom_fields: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
thz_mailpoet_dynamic_segment_filters: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
thz_mailpoet_feature_flags: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
thz_mailpoet_forms: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
thz_mailpoet_log: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
thz_mailpoet_migrations: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
thz_mailpoet_newsletter_links: Données : 0.02MB + Index : 0.05MB + Moteur InnoDB
thz_mailpoet_newsletter_option: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
thz_mailpoet_newsletter_option_fields: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
thz_mailpoet_newsletter_posts: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
thz_mailpoet_newsletter_segment: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
thz_mailpoet_newsletter_templates: Données : 4.06MB + Index : 0.00MB + Moteur InnoDB
thz_mailpoet_newsletters: Données : 0.02MB + Index : 0.05MB + Moteur InnoDB
thz_mailpoet_scheduled_task_subscribers: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
thz_mailpoet_scheduled_tasks: Données : 0.34MB + Index : 0.20MB + Moteur InnoDB
thz_mailpoet_segments: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
thz_mailpoet_sending_queues: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
thz_mailpoet_settings: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
thz_mailpoet_statistics_bounces: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
thz_mailpoet_statistics_clicks: Données : 0.02MB + Index : 0.05MB + Moteur InnoDB
thz_mailpoet_statistics_forms: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
thz_mailpoet_statistics_newsletters: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
thz_mailpoet_statistics_opens: Données : 0.02MB + Index : 0.08MB + Moteur InnoDB
thz_mailpoet_statistics_unsubscribes: Données : 0.02MB + Index : 0.05MB + Moteur InnoDB
thz_mailpoet_statistics_woocommerce_purchases: Données : 0.02MB + Index : 0.08MB + Moteur InnoDB
thz_mailpoet_stats_notifications: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
thz_mailpoet_subscriber_custom_field: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
thz_mailpoet_subscriber_ips: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
thz_mailpoet_subscriber_segment: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
thz_mailpoet_subscriber_tag: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
thz_mailpoet_subscribers: Données : 0.02MB + Index : 0.23MB + Moteur InnoDB
thz_mailpoet_tags: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
thz_mailpoet_user_agents: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
thz_mailpoet_user_flags: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
thz_options: Données : 8.11MB + Index : 0.19MB + Moteur InnoDB
thz_postmeta: Données : 3.38MB + Index : 0.67MB + Moteur InnoDB
thz_posts: Données : 7.34MB + Index : 0.30MB + Moteur InnoDB
thz_revslider_css: Données : 0.13MB + Index : 0.02MB + Moteur InnoDB
thz_revslider_css_bkp: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
thz_revslider_layer_animations: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
thz_revslider_layer_animations_bkp: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
thz_revslider_navigations: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
thz_revslider_navigations_bkp: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
thz_revslider_sliders: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
thz_revslider_sliders_bkp: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
thz_revslider_slides: Données : 0.31MB + Index : 0.02MB + Moteur InnoDB
thz_revslider_slides_bkp: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
thz_revslider_static_slides: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
thz_revslider_static_slides_bkp: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
thz_sgs_log_events: Données : 0.08MB + Index : 0.02MB + Moteur InnoDB
thz_sgs_log_visitors: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
thz_term_relationships: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
thz_term_taxonomy: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
thz_termmeta: Données : 0.05MB + Index : 0.03MB + Moteur InnoDB
thz_terms: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
thz_trp_dictionary_fr_fr_en_us: Données : 0.22MB + Index : 0.27MB + Moteur InnoDB
thz_trp_gettext_en_us: Données : 0.28MB + Index : 0.34MB + Moteur InnoDB
thz_trp_gettext_fr_fr: Données : 1.52MB + Index : 0.61MB + Moteur InnoDB
thz_trp_gettext_original_meta: Données : 0.02MB + Index : 0.05MB + Moteur InnoDB
thz_trp_gettext_original_strings: Données : 0.47MB + Index : 0.30MB + Moteur InnoDB
thz_trp_original_meta: Données : 0.08MB + Index : 0.13MB + Moteur InnoDB
thz_trp_original_strings: Données : 0.17MB + Index : 0.16MB + Moteur InnoDB
thz_usermeta: Données : 0.13MB + Index : 0.03MB + Moteur InnoDB
thz_users: Données : 0.02MB + Index : 0.05MB + Moteur InnoDB
thz_wc_admin_note_actions: Données : 0.06MB + Index : 0.02MB + Moteur InnoDB
thz_wc_admin_notes: Données : 0.06MB + Index : 0.00MB + Moteur InnoDB
thz_wc_category_lookup: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
thz_wc_customer_lookup: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
thz_wc_download_log: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
thz_wc_order_addresses: Données : 0.02MB + Index : 0.06MB + Moteur InnoDB
thz_wc_order_coupon_lookup: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
thz_wc_order_operational_data: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
thz_wc_order_product_lookup: Données : 0.02MB + Index : 0.06MB + Moteur InnoDB
thz_wc_order_stats: Données : 0.02MB + Index : 0.05MB + Moteur InnoDB
thz_wc_order_tax_lookup: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
thz_wc_orders: Données : 0.02MB + Index : 0.11MB + Moteur InnoDB
thz_wc_orders_meta: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
thz_wc_product_attributes_lookup: Données : 0.05MB + Index : 0.02MB + Moteur InnoDB
thz_wc_product_download_directories: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
thz_wc_product_meta_lookup: Données : 0.02MB + Index : 0.09MB + Moteur InnoDB
thz_wc_rate_limits: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
thz_wc_reserved_stock: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
thz_wc_tax_rate_classes: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
thz_wc_webhooks: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
thz_woodmart_wishlist_products: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
thz_woodmart_wishlists: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
thz_wpforms_logs: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
thz_wpforms_payment_meta: Données : 0.02MB + Index : 0.05MB + Moteur InnoDB
thz_wpforms_payments: Données : 0.02MB + Index : 0.14MB + Moteur InnoDB
thz_wpforms_tasks_meta: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
thz_wpgmza: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
thz_wpgmza_admin_notices: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
thz_wpgmza_circles: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
thz_wpgmza_image_overlays: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
thz_wpgmza_maps: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
thz_wpgmza_point_labels: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
thz_wpgmza_polygon: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
thz_wpgmza_polylines: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
thz_wpgmza_rectangles: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB

### Post Type Counts ###

attachment: 1659
cms_block: 31
customize_changeset: 1
elementor_library: 1
flamingo_contact: 13
flamingo_inbound: 10
language_switcher: 4
mailpoet_page: 1
mc4wp-form: 1
nav_menu_item: 93
oembed_cache: 6
page: 29
portfolio: 9
post: 9
product: 103
product_variation: 156
revision: 332
woodmart_layout: 2
woodmart_sidebar: 1
woodmart_size_guide: 1
woodmart_slide: 9
wp_global_styles: 1
wp_navigation: 1
wp_template: 3
wpcf7_contact_form: 4

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (32) ###

WPML Multilingual CMS: par OnTheGoSystems – 4.6.11
All in One SEO Pack: par L’équipe All in One SEO – 4.6.6
Contact Form 7 Multilingual: par OnTheGoSystems – 1.2.2
Contact Form 7: par Takayuki Miyoshi – 5.9.6
Flamingo: par Takayuki Miyoshi – 2.5
MonsterInsights - Google Analytics pour WordPress: par MonsterInsights – 8.28.0
Google Listings and Ads: par WooCommerce – 2.7.6
Jetpack: par Automattic – 13.6
Éditeur de page: par Michael M - WPBakery.com – 7.4
HubSpot All-In-One Marketing - Formulaires, fenêtres surgissantes, discussion en direct: par HubSpot – 11.1.22
MC4WP : Mailchimp pour WordPress: par ibericode – 4.9.13
MailPoet: par MailPoet – 4.55.0
OptinMonster: par OptinMonster Popup Builder Team – 2.16.4
Pinterest pour WooCommerce: par WooCommerce – 1.3.24
Slider Revolution: par ThemePunch – 6.6.20
Safe SVG: par 10up – 2.2.5
Speed Optimizer: par SiteGround – 7.6.2
Security Optimizer: par SiteGround – 1.5.0
WooCommerce Legacy REST API: par WooCommerce – 1.0.4
WooCommerce Multilingual & Multicurrency: par OnTheGoSystems – 5.3.6
WooPayments: par Woocommerce – 7.9.1
WooCommerce PayPal Payments: par WooCommerce – 2.8.1
WooCommerce Shipping & Tax: par WooCommerce – 2.6.1
WooCommerce: par Automattic – 9.1.1
Woodmart Core: par  – 1.0.42
SiteGround Central: par SiteGround – 3.0.2
WP Go Maps (anciennement WP Google Maps): par WP Go Maps (anciennement WP Google Maps) – 9.0.40
WPForms Lite: par WPForms – 1.8.9.6
MailChimp for WordPress Multilingual: par OnTheGoSystems – 0.0.3
WPML String Translation: par OnTheGoSystems – 3.2.12
WPML to Polylang: par WP SYNTEX – 0.6
WPForms Multilingual: par OnTheGoSystems – 0.3.6

### Inactive Plugins (5) ###

Elementor: par Elementor.com – 3.22.3
Envira Gallery Lite: par Envira Gallery Team – 1.8.13
Extra product options For WooCommerce | Custom Product Addons and Fields: par ThemeHigh – 3.2.7
OTGS Installer: par OnTheGoSystems – 3.1.3
TranslatePress - Multilingual: par Cozmoslabs
Razvan Mocanu
Madalin Ungureanu
Cristophor Hurduban – 2.8.1

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: EUR (€)
Currency Position: right_space
Thousand Separator: 
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 jours
Level threshold: –
Log directory size: 4 Ko

### WC Pages ###

Base de la boutique: #1249 - /produits/
Panier: #6 - /cart/ -  Contient le code court [woocommerce_cart]
Commander: #7 - /checkout/ -  Contient le code court [woocommerce_checkout]
Mon compte: #8 - /mon-compte/
Conditions générales de vente et d’utilisation: ❌ Page non définie

### Theme ###

Name: Woodmart
Version: 7.5.1 (une mise à jour de la version 7.5.2 est disponible)
Author URL: http://themeforest.net/user/xtemos
Child Theme: ❌ – Si vous modifiez WooCommerce sur un thème parent que vous n‘avez pas construit personnellement
nous vous recommandons d‘utiliser un thème enfant. Voir : Comment créer un thème enfant

WooCommerce Support: ✔

### Templates ###

Overrides: woodmart/woocommerce/archive-product.php
woodmart/woocommerce/cart/cart-item-data.php
woodmart/woocommerce/cart/cart.php
woodmart/woocommerce/cart/cross-sells.php
woodmart/woocommerce/cart/mini-cart.php
woodmart/woocommerce/checkout/form-checkout.php
woodmart/woocommerce/checkout/thankyou.php
woodmart/woocommerce/content-product-cat.php
woodmart/woocommerce/content-product.php
woodmart/woocommerce/content-single-product.php
woodmart/woocommerce/content-widget-product.php
woodmart/woocommerce/global/breadcrumb.php
woodmart/woocommerce/global/form-login.php
woodmart/woocommerce/global/quantity-input.php
woodmart/woocommerce/loop/add-to-cart.php version 3.3.0 est obsolète. La version du noyau est 9.0.0
woodmart/woocommerce/loop/loop-end.php
woodmart/woocommerce/loop/loop-start.php
woodmart/woocommerce/loop/no-products-found.php
woodmart/woocommerce/loop/orderby.php
woodmart/woocommerce/loop/pagination.php
woodmart/woocommerce/loop/sale-flash.php
woodmart/woocommerce/myaccount/form-login.php
woodmart/woocommerce/product-searchform.php
woodmart/woocommerce/single-product/add-to-cart/grouped.php
woodmart/woocommerce/single-product/add-to-cart/variable.php
woodmart/woocommerce/single-product/meta.php
woodmart/woocommerce/single-product/product-attributes.php
woodmart/woocommerce/single-product/product-image.php version 7.8.0 est obsolète. La version du noyau est 9.0.0
woodmart/woocommerce/single-product/product-thumbnails.php
woodmart/woocommerce/single-product/rating.php
woodmart/woocommerce/single-product/related.php
woodmart/woocommerce/single-product/sale-flash.php
woodmart/woocommerce/single-product/tabs/description.php
woodmart/woocommerce/single-product/tabs/tabs.php
woodmart/woocommerce/single-product/title.php
woodmart/woocommerce/single-product/up-sells.php
woodmart/woocommerce/single-product-reviews.php
woodmart/woocommerce/single-product.php

Outdated Templates: ❌
					
					
						Apprenez comment mettre à jour

### WooPayments ###

Version: 7.9.1
Connected to WPCOM: Oui
WPCOM Blog ID: 224921178
Account ID: acct_1O3FkrCAOVY9f7nt
Payment Gateway: Activé
Test Mode: Désactivé
Enabled APMs: card
WooPay: Non éligible
Apple Pay / Google Pay: Activé (checkout)
Fraud Protection Level: basic
Multi-currency: Activé
Auth and Capture: Activé
Documents: Activé
Logging: Désactivé

### MailPoet ###

Sending Method: PHPMail
Send all site's emails with: Méthode d’envoi par défaut de WordPress
Task Scheduler method: Action Scheduler
Cron ping URL: https://favoridecor.fr?mailpoet_router&endpoint=cron_daemon&action=ping

### WooCommerce PayPal Payments ###

Onboarded: ✔
Shop country code: FR
WooCommerce currency supported: ✔
Advanced Card Processing available in country: ✔
Pay Later messaging available in country: ✔
Webhook status: –
PayPal Vault enabled: –
ACDC Vault enabled: –
Logging enabled: –
Reference Transactions: ✔
Used PayPal Checkout plugin: –
Subscriptions Mode: Disabled

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-custom-fields
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page
launch-your-store

Disabled Features: experimental-blocks
minified-js
pattern-toolkit-full-composability
product-pre-publish-modal
printful
settings
async-product-editor-category-field
product-editor-template-system

Daily Cron: ✔ Next scheduled: 2024-07-13 09:23:00 +00:00
Options: ✔
Notes: 102
Onboarding: completed

### Action Scheduler ###

Canceled: 1
Oldest: 2024-06-19 01:00:07 +0000
Newest: 2024-06-19 01:00:07 +0000

Complete: 2 915
Oldest: 2024-06-11 15:17:56 +0000
Newest: 2024-07-12 14:02:07 +0000

Failed: 4
Oldest: 2023-10-09 10:27:10 +0000
Newest: 2024-04-12 09:25:08 +0000

Pending: 10
Oldest: 2024-07-12 14:02:36 +0000
Newest: 2024-07-16 16:40:04 +0000

### Status report information ###

Generated at: 2024-07-12 14:02:09 +00:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.
```[tasklist]
### Tasks
```

**Comment by rrennick** [comment]
@annapazii9 Thanks for creating the issue. Could you provide the steps to reproduce this issue in a development install? Those steps need to create the issue with only WooCommerce active and using a default theme.

**Comment by annapazii9** [comment]
Search the product MD008 -> add 1 to the cart -> look at delivery fee

**Comment by rrennick** [comment]
@annapazii9 We need to be able to reproduce this issue in a development install. The instructions you provided look like they are intended to show the issue on your site.
