### ISSUE TITLE
[Epic] Upgrade `woocommerce-blocks` to React 19

### ISSUE THREAD

**Issue by nielslange** [woothemes/woocommerce#49533]
### Describe the solution you'd like

On April 25, 2024, [React 19 RC](https://react.dev/blog/2024/04/25/react-19) was released. This epic contains various issues to upgrade `woocommerce-blocks` from React 18 to React 19.

```[tasklist]
### Removed deprecated React APIs
- [ ] https://github.com/woocommerce/woocommerce/issues/49534
- [x]  [Removed: Legacy Context using `contextTypes` and `getChildContext`](https://react.dev/blog/2024/04/25/react-19-upgrade-guide#removed-removing-legacy-context) → This change does not apply to `woocommerce-blocks`.
- [x] [Removed: string refs](https://react.dev/blog/2024/04/25/react-19-upgrade-guide#removed-string-refs) → This change does not apply to `woocommerce-blocks`.
- [x] [Removed: Module pattern factories](https://react.dev/blog/2024/04/25/react-19-upgrade-guide#removed-module-pattern-factories) → This change does not apply to `woocommerce-blocks`.
- [x] [Removed: `React.createFactory`](https://react.dev/blog/2024/04/25/react-19-upgrade-guide#removed-createfactory) → This change does not apply to `woocommerce-blocks`.
- [x] [Removed: `react-test-renderer/shallow`](https://react.dev/blog/2024/04/25/react-19-upgrade-guide#removed-react-test-renderer-shallow) → This change does not apply to `woocommerce-blocks`.
``` 

```[tasklist]
### Removed deprecated React DOM APIs
- [x] [Removed: `react-dom/test-utils`](https://react.dev/blog/2024/04/25/react-19-upgrade-guide#removed-react-dom-test-utils) → This change does not apply to `woocommerce-blocks`.
- [ ] #48796
- [ ] https://github.com/woocommerce/woocommerce/issues/49536
- [ ] #48801
- [ ] https://github.com/woocommerce/woocommerce/issues/49538
``` 

```[tasklist]
### New deprecations
- [ ] https://github.com/woocommerce/woocommerce/issues/49539
- [ ] https://github.com/woocommerce/woocommerce/issues/49540
```
