### ISSUE TITLE
Epic: Reduce Pre-Merge CI Checks Duration

### ISSUE THREAD

**Issue by adimoldovan** [woothemes/woocommerce#49542]
### CI checks frequency: focused on reducing the number of jobs or their frequency
- [ ] https://github.com/woocommerce/woocommerce/issues/46375

### CI checks duration: focus on reducing the time is takes for workflows/jobs to run
- [ ] https://github.com/woocommerce/woocommerce/issues/48932
- [ ] https://github.com/woocommerce/woocommerce/issues/49543
- [x] https://github.com/woocommerce/woocommerce/issues/49544
- [x] https://github.com/woocommerce/woocommerce/issues/49545
- [ ] https://github.com/woocommerce/woocommerce/issues/49549
- [ ] https://github.com/woocommerce/woocommerce/issues/49550
- [ ] https://github.com/woocommerce/woocommerce/issues/49546
- [x] https://github.com/woocommerce/woocommerce/issues/49547
- [ ] https://github.com/woocommerce/woocommerce/issues/50623

### Package Deprecation Tasks: focus on removing deprecated packages
- [ ] https://github.com/woocommerce/woocommerce/issues/40116
- [x] https://github.com/woocommerce/woocommerce/issues/40117
- [ ] https://github.com/woocommerce/woocommerce/issues/40118
- [ ] https://github.com/woocommerce/woocommerce/issues/40119

### Test audit: focus on test auditing and removing/updating tests duplicating coverage
- [ ] https://github.com/woocommerce/woocommerce/issues/50964
- [ ] https://github.com/woocommerce/woocommerce/issues/48935

**Comment by kalessil** [comment]
Closing this epic, but keeping the remaining few issues open: the associated project was closed with decent improvements in CI performance.
