### ISSUE TITLE
woocommerce_shop_order_search_fields and HPOS meta fields

### ISSUE THREAD

**Issue by seldimi** [woothemes/woocommerce#49667]
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When HPOS is not activated, you can add capability to search a custom order meta field (in wp_postmeta), with filter woocommerce_shop_order_search_fields, which is used in search_orders (class-wc-order-data-store-ctp.php)
What it does, is adding the custom field names and it allows you to search in wp_postmeta

When HPOS is activated, and compatibility/sync is not active, the order meta fields are saved in wc_orders_meta table only, so the above function never queries it. It only checks order_items, postmeta and customers meta. It doesn't check any new HPOS tables

### Expected behavior

The search_orders function should also search for wc_orders_meta as well.

### Actual behavior

It currently ignores the wc_orders_meta fields and the new tables from searching.

### Steps to reproduce

1. Add a custom field via CRUD in an WC_ORDER when HPOS enabled.
2. Add functionality to search the custom fields via woocommerce_shop_order_search_fields
3. Search for it. Nothing will be found.
4. Activate the compatibility mode, or sync orders/order_meta or activate legacy order tables.
5. Try and search again, it will be there

### WordPress Environment

Latest WordPress/WooCommerce

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by coreymckrill** [comment]
@seldimi With HPOS there is a different filter hook that you can use to add custom meta fields to the search query:
https://github.com/woocommerce/woocommerce/blob/8fb09532044eca1464682e4395ec63c7c021697f/plugins/woocommerce/src/Internal/DataStores/Orders/OrdersTableSearchQuery.php#L348-L361
