### ISSUE TITLE
WPC Product Bundles messes up my datalayer/GTM tracking value and product quantity

### ISSUE THREAD

**Issue by Houss4w** [woothemes/woocommerce#49720]
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Hello everyone,

We have implemented the WPC Product Bundles on one store and it’s messing up my datalayer value datalayer/GTM value and product number on the cart and checkout page.

See the exemple below : **126,70€** in total on the page

but

My datalayer checker is returning **251,7** in ecommerce.value. I think it’s because it counts multiple time some of the product, and I am having this issue only with the WPC Product Bundles plugin.

### Expected behavior

It is only supposed to get the total amount of value of the cart

### Actual behavior

It counts product multiple times and doesn't get the right value

### Steps to reproduce

See the following pic
![Mon panier - MOONSTONE](https://github.com/user-attachments/assets/10d82095-8897-4776-b1f3-0e359b41e254)
and then this one : 
<img width="520" alt="image" src="https://github.com/user-attachments/assets/4f394372-747b-400e-ac3e-6dac6c418cc5">

### WordPress Environment

<details><summary>System Status Report</summary>

```
### WordPress Environment ###

WordPress address (URL): [Redacted]
Site address (URL): [Redacted]
WC Version: 9.1.2
Legacy REST API Package Version: L’extension Legacy REST API n’est pas installée sur ce site.
Action Scheduler Version: ✔ 3.7.4
Log Directory Writable: ✔
WP Version: ❌ 6.5.5 - Une nouvelle version de WordPress est disponible (6.6)
WP Multisite: –
WP Memory Limit: 640 Mo
WP Debug Mode: –
WP Cron: ✔
Language: fr_FR
External object cache: ✔

### Server Environment ###

Server Info: LiteSpeed
PHP Version: 8.0.30
PHP Post Max Size: 135 Mo
PHP Time Limit: 60
PHP Max Input Vars: 10000
cURL Version: 7.87.0
OpenSSL/1.1.1d

SUHOSIN Installed: –
MySQL Version: 10.3.34-MariaDB-cll-lve
Max Upload Size: 128 Mo
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

[REDACTED]

### Post Type Counts ###

attachment: 1335
customize_changeset: 9
elementor_font: 2
elementor_library: 33
jet-form-builder: 1
jet-smart-filters: 5
nav_menu_item: 10
oembed_cache: 2
page: 30
post: 23
product: 147
product_variation: 680
revision: 47
shop_coupon: 31
shop_order: 889
shop_order_refund: 5
wfacp_checkout: 1
wffn_ty: 1
wfob_bump: 44
wfocu_funnel: 21
wfocu_offer: 21
wp_global_styles: 1
wpcode: 74

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (48) ###

Astra Pro: par Brainstorm Force – 4.7.2
Better Search Replace: par WP Engine – 1.4.7
Bulk Edit Products, Prices & Attributes for Woocommerce: par ELEXtensions – 2.0.1
FunnelKit Cart for WooCommerce: par FunnelKit – 1.7.1
Axepta Online BNP Paribas: par Quadra Informatique – 2.2.3
Cookie banner plugin for WordPress – Cookiebot CMP by Usercentrics: par Usercentrics A/S – 4.3.9
Elementor Pro: par Elementor.com – 3.23.0
GTM4WP - A Google Tag Manager (GTM) plugin for WordPress: par Thomas Geiger – 1.20.2
EAN for WooCommerce: par WPFactory – 4.9.7
Elementor: par Elementor.com – 3.23.1
FunnelKit Funnel Builder Pro: par FunnelKit – 3.4.3
FunnelKit Funnel Builder: par FunnelKit – 3.4.5
Goaffpro Affiliate Marketing: par Goaffpro – 2.7.9
Google Listings and Ads: par WooCommerce – 2.7.6
WPCode Lite: par WPCode – 2.2.0
JetElements For Elementor: par Crocoblock – 2.6.18
JetEngine: par Crocoblock – 3.5.1
JetSmartFilters - Astra compatibility: par Crocoblock – 1.0.0
JetSmartFilters: par Crocoblock – 3.5.2
JetWooBuilder For Elementor: par Crocoblock – 2.1.13
Judge.me Product Reviews for WooCommerce: par Judge.me – 1.3.22
Kadence WooCommerce Email Designer: par Kadence WP – 1.5.13
Klaviyo: par Klaviyo
Inc. – 3.3.5

Media Library Helper by Codexin: par Codexin Technologies – 1.3.0
Metorik Helper: par Metorik – 1.7.2
Mondial Relay - InPost - WordPress: par Rodolphe Cazemajou-Tournié – 5.2
Obfuscation Lien par Cyril Jouault: par Cyril Jouault – 1.0
Payplug pour WooCommerce: par Payplug – 2.8.0
Redirection: par John Godley – 5.4.2
Tidio Chat: par Tidio LLC – 6.0.20
Chronopost & Mondial relay pour WooCommerce - WCMultiShipping: par Mondial Relay WooCommerce - WCMultiShipping – 2.4.6
Suivi avancé des envois pour WooCommerce: par zorem – 3.6.8
Friendly User Agent for WooCommerce: par Blaze Concepts – 1.3.0
WPC Product Bundles for WooCommerce: par WPClever – 8.0.9
Additional Variation Images Gallery for WooCommerce: par Emran Ahmed – 1.3.22
PDF Invoices & Packing Slips for WooCommerce: par WP Overnight – 3.8.5
WooCommerce: par Automattic – 9.1.2
Yoast SEO: par L’équipe Yoast – 23.0
WP All Export Pro: par Soflyy – 1.8.9
WP All Import Pro: par Soflyy – 4.8.6-beta-1.8
WP Mail SMTP: par WP Mail SMTP – 4.1.0
WP Rocket: par WP Media – 3.16.2.1
WP All Export - WooCommerce Export Add-On Pro: par Soflyy – 1.0.9
WP All Import - WooCommerce Import Add-On Pro: par Soflyy – 4.0.1-beta-1.9
WPvivid Plugins Pro: par wpvivid.com – 2.2.25
WPvivid Backup Plugin: par Équipe WPvivid – 0.9.103
WPvivid Imgoptim Free: par WPvivid Team – 0.9.22
Smart Coupons for WooCommerce Pro: par WebToffee – 2.0.9

### Inactive Plugins (0) ###


### Dropin Plugins () ###

advanced-cache.php: advanced-cache.php
object-cache.php: object-cache.php

### Must Use Plugins (1) ###

closte-requirements.php: par  –

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: right
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)
woosb (woosb)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 jours
Level threshold: –
Log directory size: 31 Mo

### WC Pages ###

Base de la boutique: #6 - /boutique-diatomite-pierre-absorbante/
Panier: #7 - /panier/ -  Contient le code court [woocommerce_cart]
Commander: #8 - /checkout/ -  Contient le code court [woocommerce_checkout]
Mon compte: #9 - /my-account/
Conditions générales de vente et d’utilisation: ❌ Page non définie

### Theme ###

Name: Astra
Version: 4.7.3
Author URL: https://wpastra.com/about/?utm_source=theme_preview&utm_medium=author_link&utm_campaign=astra_theme
Child Theme: ❌ – Si vous modifiez WooCommerce sur un thème parent que vous n‘avez pas construit personnellement
nous vous recommandons d‘utiliser un thème enfant. Voir : Comment créer un thème enfant

WooCommerce Support: ✔

### Templates ###

Overrides: /home/64402d12c1ac1878f8431037/public_html/wp-content/plugins/woo-variation-gallery/templates/product-images.php version 7.8.0 est obsolète. La version du noyau est 9.0.0
/home/64402d12c1ac1878f8431037/public_html/wp-content/plugins/woo-variation-gallery/templates/product-thumbnails.php

Outdated Templates: ❌
					
					
						Apprenez comment mettre à jour

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-custom-fields
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page
launch-your-store

Disabled Features: experimental-blocks
minified-js
pattern-toolkit-full-composability
product-pre-publish-modal
printful
settings
async-product-editor-category-field
product-editor-template-system

Daily Cron: ✔ Next scheduled: 2024-07-20 08:26:37 +00:00
Options: ✔
Notes: 85
Onboarding: skipped

### Action Scheduler ###

Terminé: 13 687
Oldest: 2024-06-18 14:16:04 +0000
Newest: 2024-07-19 13:58:10 +0000

Échoué: 4 754
Oldest: 2023-06-27 09:51:38 +0000
Newest: 2024-07-19 11:36:51 +0000

En attente: 6
Oldest: 2024-07-19 13:59:10 +0000
Newest: 2024-07-23 19:41:53 +0000


### Status report information ###

Generated at: 2024-07-19 13:59:02 +00:00
```
</details>

### Isolating the problem

- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.
```[tasklist]
### Tasks
```
