### ISSUE TITLE
Establish react roots for new payment settings

### ISSUE THREAD

**Issue by adrianduffell** [woothemes/woocommerce#49923]
## Project Overview

The payment settings will be re-developed with React-based views to provide a better onboarding and management experience. As a pre-requisite to this effort, this project establishes react views in the classic settings screen for payments.

The video below mocks up a future state where settings are modernized. This is a small step towards this -- by moving the payments settings components out of PHP / jQuery and into React, we allow these settings to be forward-compatible with a future modernized design.

https://github.com/user-attachments/assets/cfbeb1d5-b709-4fbb-8272-7481d0e00dc9

```[tasklist]
### Tasks
- [ ] https://github.com/woocommerce/woocommerce/issues/49926
- [ ] https://github.com/woocommerce/woocommerce/issues/49927
- [ ] https://github.com/woocommerce/woocommerce/issues/49928
- [ ] https://github.com/woocommerce/woocommerce/issues/49930
- [x] Provide handover documentation to Moltres
```
