### ISSUE TITLE
Meta data cache doesn't get flushed when `update_post_meta` updates the object's meta

### ISSUE THREAD

**Issue by jimjasson** [woothemes/woocommerce#50207]
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Run the following snippet:

```
>  $object = new WC_Product();
= WC_Product {#12414}

>  $object->save();
= 4492

> // Verify that cache isn't set
> wp_cache_get( $object->get_meta_cache_key(), 'products' )
= false

> // set the cache
> $object->get_meta_data()
= []

> // Verify that cache is set
> wp_cache_get( $object->get_meta_cache_key(), 'products' )
= []

> update_post_meta( 4492, 'some_key', 'some_value' )
= 615079

> // verify that cache isn't updated
> wp_cache_get( $object->get_meta_cache_key(), 'products' )
= []

> // re read product, it will read the stale cache
> $p = wc_get_product( 4492 )
= WC_Product_Simple {#12480}

> // check the stale cache
> wp_cache_get( $p->get_meta_cache_key(), 'products' )
= []

> $p->get_meta_data()
= []

> $p->get_meta('some_key', true)
= ""
```

cc @vedanshujain who suggested that: "[that intermediate cache](https://github.com/woocommerce/woocommerce/blob/a73c6e554659dc9da85bc0f9bc4cac569cb9df1e/plugins/woocommerce/includes/abstracts/abstract-wc-data.php#L638-L643) shouldn't be there, since there's already wp cache that we can use".

### Expected behavior

The `update_post_meta` doesn't flush the product meta cache.

### Actual behavior

The `update_post_meta` should flush the product meta cache.

### Steps to reproduce

See description

### WordPress Environment

Fresh WordPress install with the latest WooCommerce version active.

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.
