### ISSUE TITLE
Incorrect Net Sales in Analytics Product Reports

### ISSUE THREAD

**Issue by ianlin** [woothemes/woocommerce#50480]
This epic issue covers all the problems related to inconsistent net sales in analytics.

The issue originally started with [#32837](<https://github.com/woocommerce/woocommerce/issues/32837>), and @octaedro later addressed it by creating a post (pcQJnU-2J6-p2) discussing the problem. He then created the following related issues on GitHub:

* [WOOPLUG-4547](https://linear.app/a8c/issue/WOOPLUG-4547/inconsistent-behavior-of-net-sales-in-analytics-for-partial-refunds)
* [WOOPLUG-4548](https://linear.app/a8c/issue/WOOPLUG-4548/inconsistent-behavior-of-net-sales-in-analytics-for-full-refunds)
* [WOOPLUG-2353](https://linear.app/a8c/issue/WOOPLUG-2353/inconsistent-behavior-of-net-sales-in-analytics-for-partial-order)

He has already completed the first PR ([#48768](<https://github.com/woocommerce/woocommerce/issues/48768>)) that addressed [WOOPLUG-4547](https://linear.app/a8c/issue/WOOPLUG-4547/inconsistent-behavior-of-net-sales-in-analytics-for-partial-refunds). However, since the analytics responsibilities have been handed over to @woocommerce/automata, we need to follow up on the remaining issues and aim to resolve them as quickly as we can.

A shared branch, [fix/32837-48761-48775-48954-inconsistent-behavior-of-net-sales-in-analytics](<https://github.com/woocommerce/woocommerce/tree/fix/32837-48761-48775-48954-inconsistent-behavior-of-net-sales-in-analytics>), has been created. This will serve as a feature branch, meaning all subsequent PRs should be merged into this branch first, allowing us to release all the fixes together.

### Issues

- [X] [WOOPLUG-4547](https://linear.app/a8c/issue/WOOPLUG-4547/inconsistent-behavior-of-net-sales-in-analytics-for-partial-refunds)
  - [#48768](<https://github.com/woocommerce/woocommerce/issues/48768>)
- [X] [WOOPLUG-4548](https://linear.app/a8c/issue/WOOPLUG-4548/inconsistent-behavior-of-net-sales-in-analytics-for-full-refunds)
  - [#51262](<https://github.com/woocommerce/woocommerce/issues/51262>)
- [ ] [WOOPLUG-2353](https://linear.app/a8c/issue/WOOPLUG-2353/inconsistent-behavior-of-net-sales-in-analytics-for-partial-order)

**Comment by ianlin** [comment]
Most of the issues were resolved in this PR #53019 and it will be included in WC 9.9.0.

The only remaining issue regarding incorrect net sales in product reports is #48954.
