### ISSUE TITLE
Delayed account creation: Create "account creation" block

### ISSUE THREAD

**Issue by mikejolley** [woothemes/woocommerce#50632]
Create the account creation block. This should have a feature branch until complete.

Requirements:

- Placement of the feature in Order confirmation— after initial order details
- Editable heading and bullet points
- Styles inherited from global settings
- Default settings:
     - Order email will be the account email
     - Shopper will set up a password
     - Minimum 8 character password (or adjust strengths in existing component)

As well as creating the block and making it functional on the frontend there will be additional tasks for the editor UX and default content.

This block will require API support in order to create accounts (see https://github.com/woocommerce/woocommerce/issues/48580) unless we opt to go with a basic form POST instead. TBD

Figma flows:
xsRWL4dMRYrTsMrLbXIuoA-fi-57_543

![image](https://github.com/user-attachments/assets/7f80abee-063b-4d77-bce5-1b6f1f0f61de)

p2: pdFofs-1U1-p2

```[tasklist]
### Tasks
- [x] Create block
- [x] Editor settings: Background and text colors
- [x] Insert block into default order confirmation page template
- [x] Make create account button functional
- [x] Show confirmation after registration
```
