### ISSUE TITLE
Add lint rule to prevent incorrect usage of prime marks

### ISSUE THREAD

**Issue by adrianduffell** [woothemes/woocommerce#50780]
**Prerequisites (mark completed items with an [x]):**
- [ ] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [ ] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

**Issue Description:**

Over 90 JS files contain known incorrect usage of prime marks. For example `Let's get you started` should be `Let’s get you started`.

To prevent further instances, add a lint rule to prevent prime marks such as `'` and `"`, when apostrophes `’` and quotation marks `“ ”` should be used instead. These can be detected inside strings in `__()`.

```[tasklist]
### Tasks
- [ ] Apply jscodeshift codemod to `./packages/js` to convert prime marks to apostrophes
- [ ] Develop and apply jscodeshift codemod to `./packages/js` and `./plugins/woocommerce-admin` to convert `"` to quotation marks
- [ ] Develop and apply codemod to convert prime marks in PHP files to apostrophes
- [ ] Develop and apply codemod to convert `"` to quotation marks in PHP files
- [ ] Develop eslint rules for erroring on " and ' in js files
- [ ] Develop phpcs rules for erroring on " and ' in php files
- [ ] Apply jscodeshift codemod to the rest of `./plugins/woocommerce-admin` for non Ghidorah owned files (I excluded them from #50776)
```

**Comment by rjchow** [comment]
The codemod I used for https://github.com/woocommerce/woocommerce/pull/50776 is as follows:

```js
module.exports = function(fileInfo, api) {
  const j = api.jscodeshift.withParser('ts');
  const source = j(fileInfo.source);

  // Find all string literals and replace straight apostrophes with curly ones
  source.find(j.Literal, {
    value: v => typeof v === 'string' && v.includes("'")
  }).forEach(path => {
    const original = path.node.value;
    const replaced = original.replace(/'/g, '’');
    path.node.value = replaced;
  });

  return source.toSource();
};


```

Run this by installing jscodeshift
`npm i -g jscodeshift`
Then saving this script to a file, and running `npx npx jscodeshift -t replace-straight-apostrophe.js ./client/**/*.ts`

Note that you'll need to modify the command for .ts, .js, jsx, and .tsx. You'll also need to modify the script `withParser`
