### ISSUE TITLE
[e2e tests] Review e2e tests and remove any redundant or non relevant checks

### ISSUE THREAD

**Issue by adimoldovan** [woothemes/woocommerce#50964]
Some of the e2e tests are either redundant or are not relevant to be included in a WooCommerce regression suite.

Find these tests and remove them.

This list will be updated with new tests as soon as they meet the criteria:

```[tasklist]
### Tasks
- [x] basic-setup.spec.js > can enable tax rates and calculations
- [x] basic-setup.spec.js > can configure permalink settings
- [x] setup-onboarding.spec.js > can make sure WooCommerce is activated
- [x] update-woocommerce.spec.js
```

**Comment by adimoldovan** [comment]
`basic-setup.spec.js > can enable tax rates and calculations` is also checked in `settings-tax.spec.js > can enable tax calculation`

**Comment by adimoldovan** [comment]
`basic-setup.spec.js > can configure permalink settings` not a WooCommerce critical flow

**Comment by adimoldovan** [comment]
`setup-onboarding.spec.js > can make sure WooCommerce is activated` It only checks the plugin is active in the plugins page. This is an implicit checks, any other test would fail if the plugins would not be active.

**Comment by adimoldovan** [comment]
> `setup-onboarding.spec.js > can make sure WooCommerce is activated` It only checks the plugin is active in the plugins page. This is an implicit checks, any other test would fail if the plugins would not be active.

Addressed in https://github.com/woocommerce/woocommerce/pull/51706

**Comment by adimoldovan** [comment]
> `basic-setup.spec.js > can enable tax rates and calculations` is also checked in `settings-tax.spec.js > can enable tax calculation`

Addressed in https://github.com/woocommerce/woocommerce/pull/51707

**Comment by adimoldovan** [comment]
> `basic-setup.spec.js > can configure permalink settings` not a WooCommerce critical flow

Addressed in https://github.com/woocommerce/woocommerce/pull/51707

**Comment by adimoldovan** [comment]
> update-woocommerce.spec.js

Addressed with https://github.com/woocommerce/woocommerce/pull/52493

**Comment by adimoldovan** [comment]
This is done.
