### ISSUE TITLE
Run the daily-checks against the nightly package

### ISSUE THREAD

**Issue by adimoldovan** [woothemes/woocommerce#51027]
More context: pf59Ax-1Pg-p2#comment-1532

Current state:
- the daily-checks are triggered on a schedule, via the `tests-daily-run.yml` workflow, that triggers `ci.yml` with the 'daily-checks' event. `ci.yml` then runs the configured checks as classic checks, running the build command and mapping the plugin dir in wp-env.
- the release-checks are triggered whenever a release is published or updated. `ci.yml` the configured checks but skips the build step, downloads the release package and includes it in the plugins list in wp-env config to be installed.

Proposed state:
Switch the daily-checks to use the nightly release instead, which is updated every night.

### Tasks
- [ ] Consolidate both the the release-checks and the nightly-checks in a single workflow, that should trigger ci.yml with similar parameters.
- [ ] Have the nightly-checks run on a schedule every night, after the nightly build is created.
- [ ] Remove `tests-daily-run.yml`.

**Comment by adimoldovan** [comment]
Update: no progress on this in the last 2 weeks, still keeping it as high prio.

**Comment by juliaamosova** [comment]
@adimoldovan is AFK this week and next week so there will be no progress on this issue until the week of Oct 28th at least.

**Comment by adimoldovan** [comment]
Update: no progress on this in the last 2 weeks because of AFK, still keeping it as high prio.

**Comment by lanej0** [comment]
Leaving as high priority in the sweep, but no updates due to end of year AFK.

**Comment by juliaamosova** [comment]
Leaving this one as a high priority and assigned to @adimoldovan.

**Comment by adimoldovan** [comment]
Reviewed the issue, keeping as high prio.
