### ISSUE TITLE
[EPIC] Render express payment buttons in the editor

### ISSUE THREAD

**Issue by alexflorisca** [woothemes/woocommerce#51034]
This is a tracking issue for all the tasks related to rendering the express payment buttons in the editor

```[tasklist]
### Tasks
- [ ] https://github.com/woocommerce/woocommerce/issues/42353
- [ ] Render from the `content` prop in the editor
- [ ] Deprecate the `edit` prop
- [ ] Address UX for when there are no payment buttons visible
- [ ] Analyse performance impact
```

**Comment by alexflorisca** [comment]
This project ended up taking a different route, instead encouraging third party payment plugins to render the buttons in the editor. The main challenge here was that some buttons rely on third party scripts which are not enqueued in the editor. This would break existing plugins if we were to force rendering of the `contend` prop in the editor. More details on this project thread (pfwcF5-WG-p2)
