### ISSUE TITLE
[Epic] Mini Cart: Refactor the Mini Cart blocks to use Interactivity API

### ISSUE THREAD

**Issue by samueljseay** [woothemes/woocommerce#51079]
This is an epic to track the work needed to migrate the existing Mini Cart block to use the WordPress Interactivity API.

```[tasklist]
### Tasks
- [ ] [Migrate top level block to Interactivity API](https://github.com/woocommerce/woocommerce/issues/51078)
- [ ] Migrate the Mini Cart Drawer to Interactivity API
- [ ] Use the Interactivity API directives to render the Mini Cart inner blocks (still as React components)
```

**Comment by rpldom** [comment]
I found a bug with counter in new mini-cart and classic theme.
https://github.com/woocommerce/woocommerce/issues/60819

**Comment by SantosGuillamot** [comment]
Closing this issue because the minicart powered by the interactivity API is already finished and currently under an experimental setting. Feedback about it is being gathered in this discussion: https://github.com/woocommerce/woocommerce/discussions/59850
