### ISSUE TITLE
Order Attribution Install & Connect

### ISSUE THREAD

**Issue by ianlin** [woothemes/woocommerce#51567]
Project: pfKYZu-1rB-p2

This epic issue serves as a container, grouping together several sub-issues for tracking and managing the progress of various tasks related to adding banners to encourage merchants to install a separate plugin.

A shared branch `feature/51567-order-attribution-install-and-connect` has been created and this will serve as a feature branch, meaning all subsequent PRs should be merged into this branch first, allowing us to test and release everything together.

This feature is aimed for inclusion in the WooCommerce 9.5 release (feature freeze on 21 October).

```[tasklist]
###
- [x] Add a banner in core analytics’ overview page. (mZgTgnHhRdyff3Gy5HIwcB-fi-2132_57151) - #51672
- [x] Add a banner in core analytics’ overview page when the previous banner is dismissed. (mZgTgnHhRdyff3Gy5HIwcB-fi-2132_57323) - #51908
- [x] Add a banner in WooCommerce -> Extensions -> Discover our favourites. (mZgTgnHhRdyff3Gy5HIwcB-fi-2516_89657) - #52282
- [ ] Add a banner in WooCommerce Activity feed. (mZgTgnHhRdyff3Gy5HIwcB-fi-2132_57485)
- [ ] Add a banner in WooCommerce order editor’s order attribution metabox. (mZgTgnHhRdyff3Gy5HIwcB-fi-2149_75634)
- [x] Click the CTAs on all the banners will go to the product page. (mZgTgnHhRdyff3Gy5HIwcB-fi-2132_57939)
- [x] Enable the banners for the % of merchants - #52532
```
