### ISSUE TITLE
[Epic] WooCommerce Blocks Storybook bugs

### ISSUE THREAD

**Issue by opr** [woothemes/woocommerce#51785]
In the WooCommerce blocks Storybook instance there are some issues that I found while testing:

- [x] `CheckboxControl` - can’t click to toggle the checkbox
- [ ] `RemovableChip` - can't remove the chip when pressing the `x`
- [ ] `RadioControlAccordion` and `RadioControl` - styling seems to be missing or just needs extra padding (See image 1)
- [ ] `TextInput` - comes with an error by default (not sure if intended, but would be good to investigate)
- [ ] `ValidatedTextInput` - can’t get error state to show, the “With error” variation also doesn’t work
- [ ] `Title` - changing heading level doesn’t affect heading size
- [ ] `CountryInput` - docs page goes off the screen (See image 2). Also label seems incorrect, should be "Select a country".
- [ ] `QuantitySelector` - the `editable` prop should be on by default. Also add a new variation so we have two versions:  editable/not editable

#### Image 1
<img src="https://github.com/user-attachments/assets/c4e25ec3-dfdf-4dc1-bcf6-0b75ab72d6d4" width="500" />

#### Image 2
![image](https://github.com/user-attachments/assets/45c8ba1c-181b-48b7-ba7e-96fec47450da)

**Comment by amitraj2203** [comment]
Hi @opr,

I tested the issue locally, and some of the bugs are no longer reproducible. So they may have already been fixed. The ones I couldn’t reproduce are:

- `CheckboxControl` - Was able to click to toggle the checkbox
- `RadioControlAccordion` and `RadioControl` - Styling seems fine just that the padding top and bottom should be similar on both
- `CountryInput` - The docs page looks fine but label still seems incorrect

https://github.com/user-attachments/assets/a5d76782-126e-4c99-8013-b763bb9f96b6

The rest of the issues are still reproducible, and I’d like to work on fixing those. Could you please assign this issue to me?
Let me know if I’m missing anything.

Thanks!

**Comment by opr** [comment]
@amitraj2203 thanks, I assigned it to you! `CheckboxControl` looks good now.

`RadioControlAccordion` and `RadioControl` yes the left and right spacing looks OK, but when clicking into one of them the subsequent content looks off too, maybe this could be improved, perhaps it should be lined up with the rest of the controls?

<img width="522" alt="Image" src="https://github.com/user-attachments/assets/651fe159-1a69-44ba-a9da-929c05240a73" />

`CountryInput` yes the docs page looks OK now, but the label should be updated.

Thanks again, let me know if you need help with any of this 🙇🏼

**Comment by amitraj2203** [comment]
Hi @opr,

I've raised a [PR](https://github.com/woocommerce/woocommerce/pull/58053) for this. Could you please review it when you get a chance?

Thanks!
