### ISSUE TITLE
Order tracked with Meta Ad but not being shown on orders on Woo

### ISSUE THREAD

**Issue by khannaavik** [woothemes/woocommerce#51943]
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Order tracked with Meta Ad but not being shown on orders on Woo

### Expected behavior

order to be seen upon woo orders

### Actual behavior

Order tracked with Meta Ad but not being shown on orders on Woo

### Steps to reproduce

Order tracked with Meta Ad but not being shown on orders on Woo

### WordPress Environment

Order tracked with Meta Ad but not being shown on orders on Woo

### Isolating the problem

- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**Comment by lanej0** [comment]
Hi @khannaavik 

We're going to need a little more information in order to be able to help you out with this issue.  Can you give us some details about the steps you take to produce this issue?  Can you provide us with some information about your environment?
