### ISSUE TITLE
[Epic] Updating all React 17.0.2 dependencies to React 18.3.x

### ISSUE THREAD

**Issue by ralucaStan** [woothemes/woocommerce#52189]
>

```[tasklist]
### Dependencies
- [x] @woocommerce/onboarding -[ package.json](https://github.com/woocommerce/woocommerce/blob/8b35b0785c761bda0b90188ade462c83af5b3643/packages/js/onboarding/package.json#L69)
- [x] plugins/woocommerce-admin -[ package.json](https://github.com/woocommerce/woocommerce/blob/8b35b0785c761bda0b90188ade462c83af5b3643/plugins/woocommerce-admin/package.json#L93)
```

```[tasklist]
### Peer/dev dependencies
- [x] @woocommerce/ai -[ package.json](https://github.com/woocommerce/woocommerce/tree/8b35b0785c761bda0b90188ade462c83af5b3643/packages/js/ai)
- [x] @woocommerce/product-editor -[ package.json](https://github.com/woocommerce/woocommerce/blob/8b35b0785c761bda0b90188ade462c83af5b3643/packages/js/product-editor/package.json)
- [x] @woocommerce/plugin-woocommerce-beta-tester -[ package.json](https://github.com/woocommerce/woocommerce/blob/8b35b0785c761bda0b90188ade462c83af5b3643/plugins/woocommerce-beta-tester/package.json#L54)
- [x] @woocommerce/components -[ package.json](https://github.com/woocommerce/woocommerce/blob/8b35b0785c761bda0b90188ade462c83af5b3643/packages/js/components/package.json#L126)
- [x] @woocommerce/experimental -[ package.json](https://github.com/woocommerce/woocommerce/blob/8b35b0785c761bda0b90188ade462c83af5b3643/packages/js/experimental/package.json#L89)
- [x] @wordpress/notices -[ package.json](https://github.com/woocommerce/woocommerce/blob/8b35b0785c761bda0b90188ade462c83af5b3643/packages/js/notices/package.json#L62)
- [x] @woocommerce/customer-effort-score -[ package.json](https://github.com/woocommerce/woocommerce/blob/8b35b0785c761bda0b90188ade462c83af5b3643/packages/js/customer-effort-score/package.json#L104)
- [x] @woocommerce/block-templates -[ package.json](https://github.com/woocommerce/woocommerce/blob/8b35b0785c761bda0b90188ade462c83af5b3643/packages/js/block-templates/package.json#L81)
- [x] @woocommerce/data -[ package.json](https://github.com/woocommerce/woocommerce/tree/8b35b0785c761bda0b90188ade462c83af5b3643/packages/js/data)
- [x] packages/js/admin-layout -[ package.json](https://github.com/woocommerce/woocommerce/blob/8b35b0785c761bda0b90188ade462c83af5b3643/packages/js/admin-layout/package.json#L71)
- [x] @woocommerce/settings-editor - [package.json](https://github.com/woocommerce/woocommerce/blob/trunk/packages/js/settings-editor/package.json#L140)
```

```[tasklist]
### Cleanup work
- [x] Revert [Monorepo: relax webpack TypeScript errors (turn into warnings) ](https://github.com/woocommerce/woocommerce/pull/51993)
- [ ] https://github.com/woocommerce/woocommerce/issues/53562
- [x] Fix type errors in @woocommerce/admin-library
- [ ] https://github.com/woocommerce/woocommerce/issues/55399
- [ ] https://github.com/woocommerce/woocommerce/issues/55398
- [ ] https://github.com/woocommerce/woocommerce/issues/53939
- [ ] https://github.com/woocommerce/woocommerce/issues/53943
- [ ] https://github.com/woocommerce/woocommerce/issues/53944
```

```[tasklist]
### Checkout TS warnings triggered by the update of `@wordpress/data`
- [ ] #54331
- [ ] #54376
- [ ] https://github.com/woocommerce/woocommerce/issues/54425
- [ ] https://github.com/woocommerce/woocommerce/issues/54426
- [ ] https://github.com/woocommerce/woocommerce/issues/54427
- [ ] https://github.com/woocommerce/woocommerce/issues/54428

**Comment by kalessil** [comment]
@ralucaStan: following up on this epic, there is one more package for `Peer/dev dependencies`:
- `@woocommerce/settings-editor` - [package.json](https://github.com/woocommerce/woocommerce/blob/trunk/packages/js/settings-editor/package.json#L140)

**Comment by ralucaStan** [comment]
For better visibility, I collected the follow-up work in https://github.com/woocommerce/woocommerce/issues/56437;

**Comment by ralucaStan** [comment]
Closing as all subtasks have now been closed
