### ISSUE TITLE
Make Store API suitable to build headless stores

### ISSUE THREAD

**Issue by senadir** [woothemes/woocommerce#53325]
The goal of this issue is to track the main issues that needs to be done to have Store API work as a headless solution, ideally outside the box.

```[tasklist]
### Tasks
- [ ] Support Checkout links from Store API responses.
- [ ] Bring Cart Token session handler to be on par with cookie one.
- [ ] Built-in multi origin CORS permission
```

**Comment by pierorocca** [comment]
>   ideally outside the box.

Did you mean "out of the box", meaning "off the shelf"?

I am really interested in embedded commerce use cases including embeddable checkout links. We POC'd this for WooPay a while back and ideally it could be done at the core level with an ability to alter the link to direct the link to an alternative checkout like WooPay.

Could you point me to your vision for this enhancement @senadir?

**Comment by samrat-biswas-git** [comment]
It looks like this might be covered by the following work: https://github.com/woocommerce/woocommerce/pull/54287. I've linked your issue to it so you can follow the progress there.

Where it's at: Link issue #53325 to draft PR #54287 and let the owning team confirm whether that PR is the canonical tracker for the remaining headless gaps.

**Comment by pierorocca** [comment]
I'm looking at checkout more holistically and how we could support headless while at the same time have it support and be compatible with 3P extensions. The Store API already supports headless but it the result is a stripped down basic checkout.
