### ISSUE TITLE
Blueprint MVP Epic

### ISSUE THREAD

**Issue by moon0326** [woothemes/woocommerce#53673]
Figma: [Y5pUYSJPsGEud1vknUZhi8-fi-3814_18301](https://href.li/?https://www.figma.com/file/Y5pUYSJPsGEud1vknUZhi8/?node-id=3814-18301)

### Tasks
- [ ] https://github.com/woocommerce/woocommerce/issues/53675
- [ ] https://github.com/woocommerce/woocommerce/issues/53678
- [ ] https://github.com/woocommerce/woocommerce/issues/53803
- [ ] https://github.com/woocommerce/woocommerce/issues/53679
- [ ] https://github.com/woocommerce/woocommerce/issues/53680
- [ ] https://github.com/woocommerce/woocommerce/issues/53972
- [ ] https://github.com/woocommerce/woocommerce/issues/53975
- [ ] https://github.com/woocommerce/woocommerce/issues/54013
- [ ] https://github.com/woocommerce/woocommerce/issues/54219
- [ ] https://github.com/woocommerce/woocommerce/issues/55202
- [ ] https://github.com/woocommerce/woocommerce/issues/54222
- [ ] https://github.com/woocommerce/woocommerce/issues/54221
- [ ] https://github.com/woocommerce/woocommerce/issues/50563
- [x] https://github.com/woocommerce/woocommerce/issues/55201
- [ ] https://github.com/woocommerce/woocommerce/issues/53984
- [ ] https://github.com/woocommerce/woocommerce/issues/55155
- [ ] https://github.com/woocommerce/woocommerce/issues/54014
- [x] Blueprint: Remove experimental zip option
- [ ] https://github.com/woocommerce/woocommerce/issues/54012
- [ ] https://github.com/woocommerce/woocommerce/issues/54496
- [ ] https://github.com/woocommerce/woocommerce/issues/55114
- [ ] https://github.com/woocommerce/woocommerce/issues/55117
- [ ] https://github.com/woocommerce/woocommerce/issues/55532
- [ ] https://github.com/woocommerce/woocommerce/issues/55533
- [ ] https://github.com/woocommerce/woocommerce/issues/55846

**Comment by moon0326** [comment]
@adrianduffell  For "Blueprint: Remove non-active themes from list", should we also remove non-active plugins as well?
