### ISSUE TITLE
FAQ backlog for common checkout block integration questions

### ISSUE THREAD

**Issue by ralucaStan** [woothemes/woocommerce#53832]
## Description of the Document Requested

We're looking to document FAQ from people integrating with the checkout blocks. 
This ticket should collect common questions & answers as the team receives them from internal/external developers.
Answers should include links to documentation, or code snippets

## Why is this Document Important?

By offering FAQs we address the most common requests and are prepared to answer future inquiries. 
We also con identify parts of the documentation that aren't clear and can be improved.
We can also collect integration gaps in the product.

```[tasklist]
### Tasks
- [x] Example of how to add fees after a JS action (using `extensionCartUpdate`)
- [x] How to refresh Checkout - `cartExtensionUpdate` or in rare cases, share example of how to force refetch cart data with data stores
- [ ] Update FAQ to mention realtime persisted checkout fields and how normal hooks can be used to modify the cart
- [ ] How do I render something in Checkout
- [ ] How do I conditionally hide fields (once JS Schema work is done)
- [ ] Perform additional validation on the order before completing checkout
```

**Comment by pierorocca** [comment]
Hi @ralucaStan, I'm closing this issue. Key "how to" instructions are best addressed in the core dev docs in the appropriate topic area. 

Troubleshooting / common pitfalls is the one exception that could warrant its own section.
