### ISSUE TITLE
Improve and Unify settings API classes

### ISSUE THREAD

**Issue by mikejolley** [woothemes/woocommerce#6361]
- [ ] Unify the settings APIs used in gateways, shipping and settings screens.
- [ ] Ensure old settings API is bw compatible where naming differs
- [ ] Use same 'output' functions for form fields
- [ ] Support 'sections' under all settings tabs if setup #6560
- [ ] Ensure 'range' type works or is supported in core #7722
- [ ] Refactor/streamline Emails, Shipping, Gateways loading and settings section key generation #6779 - look into using method IDs instead of classnames
- [ ] Required flag for settings #6083
- [ ] Move woocommerce_register_shipping_method() from includes/class-wc-shipping.php #7370
- [ ] Support for option attributes #8024

**Comment by davetgreen** [comment]
At the time of writing adding settings is completely broken when using woocommerce_get_settings_checkout filter, but fares a little better when using the _tax variant: Everything works for _tax with the exception of saving the option data.

**Comment by mikejolley** [comment]
On-hold for https://make.wordpress.org/core/2015/05/27/metadata-api-project-reborn-the-new-fields-api-project/ which is coming in a future core release.

**Comment by mikejolley** [comment]
Added to trello meanwhile https://trello.com/c/Yh1NXyvc/83-settings-api-refactor-awaiting-core-feature
